zer0-os/zOS

- src/components/invite-dialog/container.test.tsx
- src/components/invite-dialog/container.tsx
- src/components/invite-dialog/index.test.tsx
- src/components/invite-dialog/index.tsx
- src/components/invite-dialog/styles.scss
- src/store/create-invitation/index.ts
- src/store/create-invitation/saga.test.ts
- src/store/create-invitation/saga.ts
- removes `maxInvitesPerUser` / `maxUses`.
- no longer require a max value for invites.
NOTE:: I notice the designs still contain the remaining count of invites displayed on the invite dialog. Are we sure we no longer require an invite count?
After deletions:
> refactor: remove max invites per user

- package-lock.json
- package.json
chore: bump version (`1.24.0`) -> (`1.25.0`)
> chore: bump version (`1.24.0`) -> (`1.25.0`)

- src/components/chat-view-container/chat-view.tsx
- src/components/chat-view-container/styles.scss
Converts the css `animation` property to a transition when fading in the message container. This is to allow background blur to work on all the child elements
> Remove the animation attribute on the conversation container

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/types.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
- adds room to favorites (matrix)
- publishes room tag event updates
- handles room favorite updates (saga)
- adds and handles action for favoriting room
- to be able to mark rooms (conversations) as favorites for an enhanced user experience
- alternatively, you could call the `addRoomToFavorites` and check the tag event is logged and the event content tags contains the `m.favorite` tag.
ADD Favorite Demo (once wired up) with rough three dot menu
https://github.com/zer0-os/zOS/assets/39112648/0d8cd48b-1e5d-4bb8-880c-bcd3393737b8
> feat: implement adding favorite room tags

- src/components/secure-backup/styles.scss
> Update Backup Flow to have "highlight blue text" instead of "Success Green"

- src/components/messenger/list/conversation-item/conversation-item.scss
- src/components/messenger/list/conversation-item/index.tsx
- src/components/messenger/list/conversation-item/more-menu/index.test.tsx
- src/components/messenger/list/conversation-item/more-menu/index.tsx
- src/components/messenger/list/conversation-item/more-menu/styles.scss
- uses right click to open the more menu dropdown items
- removes the three dot menu trigger for the dropdown (in favor of right click)
- new requirement request
- run branch and right click on conversation items to click either 'favorite' or 'unfavorite' menu items
https://github.com/zer0-os/zOS/assets/39112648/5d88579d-edbb-4c87-bda6-ef5a7de77cb5
> feat: use a right-click interaction to add & remove conversations from favourites

- package-lock.json
- package.json
chore: bump version (`1.28.0`) -> (`1.29.0`)
> chore: bump version (`1.28.0`) -> (`1.29.0`)

- src/lib/chat/matrix/utils.test.ts
- src/lib/chat/matrix/utils.ts
- enhances the message content parsing to ensure proper handling of URLs and text, preserving intended formatting.
-  improve the user experience by ensuring message content is displayed as intended.
- run UI and reply to a message that contains text and a url. you could also test replying to messages with a mix of content and should see the expected format.
Before
After
> refactor(parse-plain-body): improve parsing of quoted lines

- src/components/messenger/list/conversation-item/index.tsx
- feature flags favorites right click / hides dropdown menu when right clicking conversation item.
- feature not released.
> refactor: feature flag favorites right click

- package-lock.json
- package.json
chore: bump version (`1.29.0`) -> (`1.30.0`)
> chore: bump version (`1.29.0`) -> (`1.30.0`)

- src/components/messenger/list/conversation-list-panel/index.tsx
Figma design uses `favourites`: 
but this should instead be consistent with other uses of `favorites` (american spelling):
> refactor(favorites-empty-state): update to american spelling for favorites

- src/components/content-highlighter/styles.scss
- viewing mentions redesign as shown below in screenshots.
- When composing a message, mention a user and send the message. When the message is displayed in the chat view check the mentions in the body of the message (compare with figma/below screenshot).
Before
After
> feat(content-highlighter): viewing mentions redesign updates

- src/components/app-bar/index.tsx
- src/components/app-bar/styles.scss
- src/lib/feature-flags.ts
Removes the app bar feature flag as it has been enabled in production for nearly a week now
> Remove enableAppBar feature flag

- src/components/message-input/index.test.tsx
- src/components/message-input/index.tsx
- src/components/message-input/mentions/index.tsx
- extracts mentions functionality from message input into a standalone mentions component.
- updates the message input test to reflect changes - basically just replacing mentions input import with mentions component import.
- tidy up the message input file to make working on mentions in follow up tasks far easier.
- run ui and manually test mentions as usual.
> refactor(message-input): extract mentions functionality into a standalone mentions component

- package-lock.json
- package.json
- chore: bump version (`1.30.0`) -> (`1.31.0`)
> chore: bump version (`1.30.0`) -> (`1.31.0`)

- src/components/message-input/mentions/index.tsx
- src/components/message-input/mentions/styles.scss
- updates suggestions list styles and applies highlight filter to suggestion search results.
- align with figma designs
- run UI and manually test mentions.
Before:
After:
> feat(mentions): redesign suggestions list and apply highlight filter

- src/components/message-input/mentions/styles.scss
-  adds truncation and ellipsis to suggestions display handle
- minor style changes
- as per design / improved ui
> feat(mentions): add truncation and ellipsis to suggestions display handle

- src/components/message-input/mentions/index.tsx
- ensures the highlight filter is applied to subsequent mentions
- the highlight filter was applied to only the first mention suggestion list 
> fix(mentions): highlight filter on subsequent mention suggestions

- src/components/message-input/mentions/styles.scss
- fixes the highlight background sync on selected/composed mentions
- improve ui / fix issue
> fix(mentions): highlighted mention background sync

- src/lib/chat/index.ts
- src/store/authentication/api.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- src/store/chat/bus.ts
- src/store/chat/index.ts
- src/store/chat/saga.ts
- src/store/chat/types.ts
- src/store/page-load/saga.test.ts
- src/store/page-load/saga.ts
- src/store/registration/saga.ts
Removes the old chatAccessToken from state
This state was previously used for Sendbird connections but we now don't use it for anything.
Login/Register/etc and verify that there are no errors and you can message as usual
> Remove references to old Sendbird chat access token

- src/store/channels-list/saga.ts
- src/store/chat/index.ts
- src/store/chat/saga.ts
- src/store/chat/types.ts
Fixes the bug where the "initial conversation" with the person who invited me, does not render display name, ZID, and avatar (until page refresh).
The **issue** which i found is: We're creating the `welcomeConversation`, which calls `matrix-client's createConversation`. BUT, the chatConnection bus, is NOT activated. (i.e **the chatBus is not emitting real time events**, since it is not connected/initialized). When you create a conversation in matrix, it will create an empty room first, and then invite other people. Now we had created the room and saved that in our state during `createConversation`. But as soon as we get the next matrix event (`RoomMember.Joined` related to the invitee), we don't end up "emitting" it, as the `chatBus` wasn't connected, so, we don't end up processing it and …
> [Fix] the initial conversation with my inviter does not render display name/ ZID /avatar until page refresh

- package-lock.json
- package.json
- chore: bump version (`1.31.0`) -> (`1.32.0`)
> chore: bump version (`1.31.0`) -> (`1.32.0`)

- src/store/channels-list/api.ts
- src/store/messages/api.ts
- src/store/messages/saga.send.test.ts
- src/store/messages/uploadable.test.ts
- src/store/messages/uploadable.ts
We no longer get chat information from zero-api. This removes some of the helpers that were referencing zero-api endpoints.
> Remove references to the api endpoint chatChannels as we no longer need them

- src/components/secure-backup/styles.scss
-  icon and text alignment improvements
- ui improvements (see below screenshots)
Before:
After:
> feat(secure-backup): icon and text alignment improvements

- src/components/messenger/list/create-conversation-panel/create-conversation-panel.scss
- src/components/messenger/list/create-conversation-panel/index.test.tsx
- src/components/messenger/list/create-conversation-panel/index.tsx
- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
- src/store/create-conversation/index.ts
- src/store/create-conversation/saga.test.ts
- src/store/create-conversation/saga.ts
- removes `StartGroupChat` stage.
- renaming to reflect changes to create conversation flow.
- `CreateConversationPanel` updates to handle both creating one on one conversation and starts a group conversation.
- updates tests to reflect changes to flow/sagas.
- as per figma designs - removes use of the `StartGroupPanel` and the start group chat stage
- run the UI and test the updated flow.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/08abef89-9e6a-4136-a3ec-75d082fea974
> refactor(messenger-list): update and enhance create conversation flow

- package-lock.json
- package.json
chore: bump version (`1.33.0`) -> (`1.34.0`)
> chore: bump version (`1.33.0`) -> (`1.34.0`)

- src/components/messenger/list/conversation-item/index.test.tsx
- src/components/messenger/list/conversation-item/index.tsx
- removes tooltip from conversation item
- as requested from leadership.
- there is no need for tooltips when we already have status with avatars, names at top of conversations etc.
- run ui and hover over conversation item.
> feat: remove tooltip from conversation item

- package-lock.json
- package.json
- chore: bump version (`1.34.0`) -> (`1.35.0`)
> chore: bump version (`1.34.0`) -> (`1.35.0`)

- src/components/messenger/autocomplete-members/index.test.tsx
- src/components/messenger/autocomplete-members/index.tsx
- implements an onSearchChange callback to manage the search active state within the autocomplete component, ensuring the UI responds correctly to user search interactions.
- to improve the user experience by providing immediate visual feedback when a search is being performed and to support better state management within the component.
> feat(autocomplete-member): implement onSearchChange callback for search state updates

- package-lock.json
- package.json
- chore: bump version (`1.35.0`) -> (`1.36.0`)
> chore: bump version (`1.35.0`) -> (`1.36.0`)

- package-lock.json
- package.json
- chore: bump version (`1.36.0`) -> (`1.37.0`)
> chore: bump version (`1.36.0`) -> (`1.37.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- fixes issue where room name and avatar are not updated in the conversation item (conversation list) when the current user creates a group conversation.
- the `addChannel` function appeared to be overriding the group name due to the event not being registered. this change ensures that the name and avatar are fetched at the appropriate time.
- run the ui and create a group conversation > check the name and avatar get updated.
> fix: fetching of room name and avatar when creating a group

- package-lock.json
- package.json
- chore: bump version (`1.38.0`) -> (`1.39.0`)
> chore: bump version (`1.38.0`) -> (`1.39.0`)

- src/components/messenger/autocomplete-members/index.tsx
- src/components/messenger/list/create-conversation-panel/index.tsx
- implements focus back to search input once a member has been selected.
- improved ux.
- run ui, search users, select member and check input is focussed.
https://github.com/zer0-os/zOS/assets/39112648/c986dcba-c86c-4b5a-897d-ce521c09f427
> feat(create-conversation-panel): implement focus to input once member is selected

- src/components/messenger/list/create-conversation-panel/index.tsx
- src/components/messenger/list/selected-user-tag/index.tsx
- implements focus back to search input once a member has been removed.
- improved ux.
- run ui, search users, select member, remove member and check input is focussed.
https://github.com/zer0-os/zOS/assets/39112648/9c946feb-7628-47a4-8efa-c72156a6fc48
> feat(create-conversation-panel): implement focus to input once selected member is removed

- src/components/messenger/list/add-members-panel/index.tsx
- implements focus to input when selecting or removing members on the add members panel.
- improved UX
- go through the add member flow and add/remove members - check focus of input.
https://github.com/zer0-os/zOS/assets/39112648/63a76e36-a7c8-4e2e-849d-3df2d6ba0616
> feat(add-members-panel): implement focus to input when selecting or removing members

- package-lock.json
- package.json
- chore: bump version (`1.40.0`) -> (`1.41.0`)
> chore: bump version (`1.40.0`) -> (`1.41.0`)

- src/components/messenger/list/index.test.tsx
- src/store/authentication/types.ts
Removes some fields that are no longer used in the app
Because these fields are being removed from the api side and they're meaningless now.
> Remove unused user fields

- src/components/edit-profile/container.test.tsx
- src/components/edit-profile/container.tsx
- src/components/edit-profile/index.test.tsx
- src/components/edit-profile/index.tsx
- src/lib/feature-flags.ts
- src/store/edit-profile/api.ts
- src/store/edit-profile/index.ts
- src/store/edit-profile/saga.ts
Removes the internal functionality to join/leave the global network
We are removing the network concept completely from the api side so these are no longer valid
> Remove internal global network management functionality

- src/authentication/confirm-password-reset/index.tsx
- src/authentication/create-account-details/index.tsx
- src/authentication/create-email-account/index.tsx
- src/authentication/create-wallet-account/index.tsx
- src/authentication/email-login/index.tsx
- src/authentication/request-password-reset/index.tsx
- src/authentication/validate-invite/index.tsx
- src/authentication/web3-login/index.tsx
- src/components/group-management/remove-member-dialog/index.tsx
- src/components/messenger/list/edit-conversation-panel/index.tsx
- src/components/secure-backup/restore-backup/index.tsx
- src/components/secure-backup/verify-key-phrase/index.tsx
- applies `isFilled` flag to alert component where required.
- filled background has been made optional in zui and set to false by default, as a result, the `isFilled` flag should be added to uses of `Alert` where the design still requires a filled background. 
- run the UI and check the alert backgrounds.
> feat(alerts): apply isFilled flag to component where required

- package-lock.json
- package.json
- chore: bump version (`1.41.0`) -> (`1.42.0`)
> chore: bump version (`1.41.0`) -> (`1.42.0`)

- package-lock.json
- package.json
- chore: bump version (`1.42.0`) -> (`1.43.0`)
> chore: bump version (`1.42.0`) -> (`1.43.0`)

- package-lock.json
- package.json
-chore: bump version (1.43.0) -> (1.44.0)
> chore: bump version (`1.43.0`) -> (`1.44.0`)

- package-lock.json
- package.json
chore: bump version (`1.44.0`) -> (`1.45.0`)
> chore: bump version (`1.44.0`) -> (`1.45.0`)

- package-lock.json
- package.json
- chore: bump version (`1.45.0`) -> (`1.46.0`)
> chore: bump version (`1.45.0`) -> (`1.46.0`)

- package-lock.json
- package.json
- chore: bump version (`1.46.0`) -> (`1.47.0`)
> chore: bump version (`1.46.0`) -> (`1.47.0`)

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/platform-apps/channels/messages-menu/index.tsx
- right click on menssage box 
- refactory renderMenssage()
https://github.com/zer0-os/zOS/assets/57037080/30ba4897-0792-4458-a7c9-596c31066380
1. How will this affect security? noops
1. How will this affect performance? noops
1. Does this change any APIs? noops
> feat(messages): enable right click

- src/components/electron-titlebar/index.tsx
- src/components/electron-titlebar/styles.scss
- src/index.tsx
- introduces a transparent, draggable titlebar to the Electron application, enabling window movement without a visible interface disruption.
- to reposition the Electron window using a dedicated draggable region that aligns with macOS traffic light controls.
- this will need to be tested in the electron environment.
- in terms of ensuring no breaking changes, run tests and ui as usual. 
The titlebar is transparent but for demo purposes I have filled it red here.
> feat(electron-titlebar): implement css draggale titlebar region for electron window app

- package-lock.json
- package.json
- chore: bump version (`1.49.0`) -> (`1.50.0`)
> chore: bump version (`1.49.0`) -> (`1.50.0`)

- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/chat/conversation-header/styles.scss
- replaces existing elements that render conversation icon with the Avatar component.
- consistency of using Avatars when profile/group images are required.
- run UI and check conversation header for Avatar component.
> refactor(conversation-header): replace and add the avatar component to the conversation header

- package-lock.json
- package.json
- chore: bump version (`1.50.0`) -> (`1.51.0`)
> chore: bump version (`1.50.0`) -> (`1.51.0`)

- src/lib/feature-flags.ts
Enables users to register via emails (by default).
> Enable email registration by default

- src/Main.tsx
- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/chat/conversation-header/styles.scss
- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- src/components/messenger/list/utils/utils.tsx
- src/components/messenger/secondary-sidekick-content/index.tsx
- src/components/messenger/secondary-sidekick-content/view-members-panel/index.test.tsx
- src/components/messenger/secondary-sidekick-content/view-members-panel/index.tsx
- src/components/messenger/secondary-sidekick-content/view-members-panel/styles.scss
- src/components/sidekick/index.test.tsx
- src/components/sidekick/index.tsx
- src/components/sidekick/styles.scss
- src/store/group-management/index.ts
- src/store/group-management/saga.test.ts
- src/store/group-management/saga.ts
- src/store/group-management/selectors.ts
- This PR introduces the Right Sidekick and functionality to open this and few the new `ViewMembersPanel`.
- Lays the foundations to move group management into the right side kick.
- run the UI > open a group conversation > click group icon in conversation header > check panel slides gracefully in and out of view.
https://github.com/zer0-os/zOS/assets/39112648/a7bd2e2d-4e82-4e6a-941e-b19b595df569
> feat: add right side kick panel, sub components, and wire up actions/state

- package-lock.json
- package.json
- chore: bump version (`1.52.1`) -> (`1.53.0`)
> chore: bump version (`1.52.1`) -> (`1.53.0`)

- src/components/messenger/chat/conversation-header/index.tsx
- Simply flips button positions in conversation header.
> refactor(conversation-header): flip header group-management buttons

- src/components/sidekick/styles.scss
- secondary sidekick width and padding modifications
- leadership request 
- run ui / tests as usual
> refactor(sidekick): secondary sidekick width and padding modifications

- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- enables users to open view members panel on all conversations.
- run ui and check view members panel can be opened on each conversation
> feat(view-members): enable view members for all conversations

- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/index.test.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/view-members-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- replaces otherMembers.length with isOneOnOne for condition within group management.
- using otherMembers.length > 1 doesn't necessarily mean the conversation is a one on one conversation as groups could go from i.e. 3 members to 2 members.
> fix: use isOneOnOne to determine conversation type in group management

- src/store/channels/saga.ts
- closes right sidekick when opening a different conversations.
- prevents panels being open when they shouldn't be.
- run ui and switch conversations whilst the right side kick is open
> feat(sidekick): close right sidekick when opening a different conversation

- package-lock.json
- package.json
chore: bump version (`1.53.0`) -> (`1.54.0`)
> chore: bump version (`1.53.0`) -> (`1.54.0`)

- package-lock.json
- package.json
chore: bump version (`1.54.0`) -> (`1.55.0`)
> chore: bump version (`1.54.0`) -> (`1.55.0`)

- src/components/chat-view-container/chat-view-container.test.tsx
- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/chat-view.test.tsx
- src/components/chat-view-container/chat-view.tsx
- src/components/inverted-scroll/index.test.tsx
- src/components/inverted-scroll/index.tsx
- src/components/inverted-scroll/styles.scss
- hides scrollbar when sidekick is open.
- per request.
- runs tests as usual.
- run the UI > check scrollbar on the right side > open sidekick > check for scrollbar.
https://github.com/zer0-os/zOS/assets/39112648/753697ab-0758-4620-ae75-d698216ba870
> feat(inverted-scroll): hide scrollbar when secondary sidekick is open

- src/store/channels/saga.ts
- keeps sidekick open and resets conversation management when switching conversations (opening a different conversation).
- per request.
- run UI and follow the demo below.
https://github.com/zer0-os/zOS/assets/39112648/9b6b6bb1-dcb9-4ce5-ad6c-8a7075a37f29
> refactor(channels-saga): keep sidekick panel open when switching conversations

- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/edit-conversation-panel/styles.scss
- removes label and adds placeholder text to group name input
- per design.
- run ui and open edit group panel.
> refactor(edit-group-panel): remove label and add placeholder text to group name input

- package-lock.json
- package.json
- chore: bump version (`1.56.0`) -> (`1.57.0`)
> chore: bump version (`1.56.0`) -> (`1.57.0`)

- src/components/settings-menu/index.tsx
- sets current users Avatar status to active.
- Always display online status for current user. 
- run ui and check current users Avatar in header as below. 
> refactor(user-header): hard code current users presence status in header

- src/components/messenger/group-management/container.tsx
- src/components/messenger/list/index.tsx
- src/components/settings-menu/index.tsx
- hardcode current user status to active where we display users avatar (citizen list item).
- if the user is online, we can just set the status to active. there is currently an existing bug where we are not fetching the current users online status therefore it is undefined. This is essentially a quick fix for now.
- run the ui and check your users online status on the avatars where displayed.
> refactor(current-user-presence): hardcode and set current user online status to active

- package-lock.json
- package.json
- chore: bump version (`1.57.0`) -> (`1.58.0`)
> chore: bump version (`1.57.0`) -> (`1.58.0`)

- src/components/citizen-list-item/index.test.tsx
- src/components/citizen-list-item/index.tsx
- src/components/citizen-list-item/styles.scss
- handle member click in the citizen list item component.
- handle member key down.
- this allows us to add an action/event when clicking the citizen list item, the follow ups to this will create or open a conversation with the selected member.
https://github.com/zer0-os/zOS/assets/39112648/d37a1449-bf3c-4840-b3b1-7e908f54001a
> feat(citizen-list-item): handle member click / key down

- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.tsx
- wires up clickable members to process opening existing conversation or creating conversation on the Group Details and Edit Group panels of the right sidekick.
- run the UI and attempt to click members when in the group management flow on the right side kick.
https://github.com/zer0-os/zOS/assets/39112648/abaa69d7-5172-4a29-ad6c-c5c159fbcf7f
> feat(group-details/edit-group panels): wire up clickable members to process opening existing conversation or creating conversation

- package-lock.json
- package.json
- chore: bump version (`1.58.0`) -> (`1.59.0`)
> chore: bump version (`1.58.0`) -> (`1.59.0`)

- src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
- src/components/messenger/list/conversation-list-panel/index.tsx
- fixes tab badge issues (screenshot). Only display tab badge on unselected tab.
- fixes broken fade in of favorites preview.
- improve ui.
- run ui and tag favorite conversations / untag favorites > check preview and tab badge
Before fix:
https://github.com/zer0-os/zOS/assets/39112648/e870faed-2e9b-420b-bb01-f7c7a0a83571
After fix:
https://github.com/zer0-os/zOS/assets/39112648/816d0dc7-7e53-4d60-9874-3a23175eeef7
> fix(tab-badge/favorites-preview): fade in preview and tab badge display

- package-lock.json
- package.json
- chore: bump version (`1.59.0`) -> (`1.60.0`)
> chore: bump version (`1.59.0`) -> (`1.60.0`)

- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.test.tsx
- adds tests to group management panels using onMemberSelect event to ensure it is published
- add test coverage
> refactor(group-management): add test coverage for onMemberSelect events

- src/components/citizen-list-item/index.test.tsx
- src/components/citizen-list-item/index.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.tsx
- src/components/messenger/group-management/view-members-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- renaming of prop
- updates tests where necessary due to change
- improved naming within the context of the citizen list item
> refactor(citizen-list-item): rename onMemberSelect to onSelect

- src/store/edit-profile/index.ts
- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- adds open and close user profile actions / state
- to continue work on updating the edit profile panel (redesign)
- run tests as usual - no UI implemented yet.
> feat(user-profile): add open and close user profile actions / state

- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- ensures the users profile panel is closed on logout / termination.
- so when the user logs back in the user profile doesn't remain open.
- run ui > open profile > logout > log back in.
> feat(authentication): close user profile on terminate

- package-lock.json
- package.json
- chore: bump version (`1.61.0`) -> (`1.62.0`)
> chore: bump version (`1.61.0`) -> (`1.62.0`)

- src/components/message-input/container.tsx
- src/components/message-input/index.test.tsx
- src/components/message-input/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/messages/saga.send.test.ts
- src/store/messages/saga.ts
- src/store/utils.ts
Implements the following logic:
- As soon as you start typing in the <MessageInput/> component, we start publishing a "typing" event (which we'll later process on the client side)
- the above is built into a race saga condition, as we need to publish "stopped typing" when: 
- it has been 5s & the user hasn't typed anymore
- the users "sends" a message in chat
- the user changes the room (opens another conversation). in this case we should publish stop typing event for the previous room.
- users logs out of the app
- We also store `currentUserLastTypingEventPublishedAt` in redux for each `Channel`, to ensure we only send the next typing event AFTER the timeout (which is 5s). Since the API is rate-limited.
Doc reference: [https://spec.matrix.org/v1.10/client-server-api/#typing-notifications] …
> Send typing events to matrix homeserver  when user starts typing

- src/components/message-input/giphy/styles.scss
- src/components/message-input/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/store/messages/uploadable.test.ts
- src/store/messages/uploadable.ts
- implements uploading image urls to handle sending gifs
- to enable sending gifs
- run the UI > open gif container by clicking the icon > select gif and send
https://github.com/zer0-os/zOS/assets/39112648/35f74d8e-5094-424b-8b4f-71d70be2d45f
> feat(giphy): implement uploading image urls to handle sending gifs

- package-lock.json
- package.json
- chore: bump version (`1.62.0`) -> (`1.63.0`)
> chore: bump version (`1.62.0`) -> (`1.63.0`)

- src/components/messenger/list/group-details-panel/index.test.tsx
- src/components/messenger/list/group-details-panel/index.tsx
- prevents user creating group without a name set.
- disables the submit button if there is no name entered.
-as requested.
- run ui > create group > try submitting.
https://github.com/zer0-os/zOS/assets/39112648/257f900f-f5cb-4b06-b25c-fb0e0fdf28e0
> feat(group-details): prevent create group if no name is set - disable submit button

- package-lock.json
- package.json
- chore: bump version (`1.63.0`) -> (`1.64.0`)
> chore: bump version (`1.63.0`) -> (`1.64.0`)

- package-lock.json
- package.json
- chore: bump version (`1.64.0`) -> (`1.65.0`)
> chore: bump version (`1.64.0`) -> (`1.65.0`)

- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- src/components/messenger/chat/styles.scss
- src/components/messenger/lib/utils.test.ts
- src/components/messenger/lib/utils.tsx
- src/components/messenger/list/conversation-item/conversation-item.scss
- src/components/messenger/list/conversation-item/index.test.tsx
- src/components/messenger/list/conversation-item/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
In chat:
(single user typing)
(two users typing)
(more than two users typing)
In conversation list panel:
> Render `typing indicators` in the UI 

- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
Previously editing a message got broken on local (and logged an error on prod). This was due to the fact that the typing events were * not * going through while edit. 
Reason: The `channelId` is an optional parameter to the `<MessageInput>` component, & while editing a message, it was not being sent (which i had missed). Fixed now.
> Send typing events correctly when you're editing a message

- src/components/messenger/list/group-details-panel/index.tsx
- updates the autofocus for the name input on the group details panel.
- updates the placeholder text for the name input on the group details panel.
- run UI and run through the group details flow.
https://github.com/zer0-os/zOS/assets/39112648/33099339-dd1f-4f84-9075-caee46990aee
> refactor(group-details): update placeholder text and add autofocus to name input

- package-lock.json
- package.json
- chore: bump version (`1.66.2`) -> (`1.67.0`)
> chore: bump version (`1.66.2`) -> (`1.67.0`)

- src/store/messages/utils.ts
- uses the correct image url when creating optimistic message object.
- before these changes, the url being used for the optimistic message was the preview_gif url which causes flickering of image sizes as shown in the before and after below. By using the same image url here as what we use when uploading the image, the size and quality will remain consistent for better UI/UX.
Before:
https://github.com/zer0-os/zOS/assets/39112648/e3ebc99e-646e-4807-b89d-2f5dff5415ee
After:
https://github.com/zer0-os/zOS/assets/39112648/154b52da-f069-44fe-ad8b-256e45fb0919
> fix(gifs): use correct giphy image url when creating optimistic message object

- src/components/messenger/chat/styles.scss
Adds a `display: none` on empty & reduces padding
> Small tweaks to the typing indicator UI

- package-lock.json
- package.json
- chore: bump version (`1.67.0`) -> (`1.68.0`)
> chore: bump version (`1.67.0`) -> (`1.68.0`)

- src/Main.tsx
- src/components/dialog-manager/container.test.tsx
- src/components/dialog-manager/container.tsx
- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
- adds dialog manager container
- moves secure backup dialog from messenger/list component level to the dialog manager
- adds test coverage
- tidy up the managing of dialogs to ensure expected functionality and more than one dialog rendering
- you can open the secure backup dialog via the usual flow.
> feat(dialog-manager): add and handle secure backup dialog in manager

- package-lock.json
- package.json
- chore: bump version (`1.68.0`) -> (`1.69.0`)
> chore: bump version (`1.68.0`) -> (`1.69.0`)

- src/lib/chat/matrix-client.ts
- src/lib/chat/types.ts
We need to add a new feature: `Add Moderators`. 
Currently we have minimum `invite, kick` level set to 100 for all users. This means that only the room creator/admin (which has a `power_level` of 100) can invite and kick users. 
We need to bring this down to `50` for existing groups, so that the admins of that groups can set users as moderators (with a `power_level` of `50`), and they can `invite`/`kick` users. Additionally, admins will be able to add/remove moderators.
> Add a function to lower minimum `invite` & `kick` levels for existing groups during initial load

- src/components/dialog-manager/container.test.tsx
- src/components/dialog-manager/container.tsx
- add rewards dialog to the manager
- ensures rewards dialog can render from a higher level by calling saga actions.
> feat(dialog-manager): add rewards dialog

- package-lock.json
- package.json
- chore: bump version (`1.69.1`) -> (`1.70.0`)
> chore: bump version (`1.69.1`) -> (`1.70.0`)

- package-lock.json
- package.json
- chore: bump version (`1.70.0`) -> (1.71.0`)
> chore: bump version (`1.70.0`) -> (1.71.0`)

- src/store/messages/saga.send.test.ts
- src/store/messages/saga.ts
- src/store/messages/saga.uploadFileMessage.test.ts
https://github.com/zer0-os/zOS/assets/33264364/8914e9ce-5a10-4580-a1bf-f0dc471c9af3
> [Fix] When sending an image message, the text and image position jump around for a split second

- src/authentication/validate-invite/index.tsx
- src/authentication/validate-invite/styles.scss
- removes header and subtitle from `/get-access` page components.
- copy changes to placeholder.
- adds focus on input, on page load.
- run UI > visit `/get-access` route.
> feat(get-access-page): redesign and auto focus to input on render

- src/components/citizen-list-item/index.test.tsx
- src/components/citizen-list-item/index.tsx
- src/components/citizen-list-item/styles.scss
- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/index.test.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/member-management-menu/container.test.tsx
- src/components/messenger/group-management/member-management-menu/container.tsx
- src/components/messenger/group-management/member-management-menu/index.test.tsx
- src/components/messenger/group-management/member-management-menu/index.tsx
- src/components/messenger/group-management/member-management-menu/styles.scss
Updates the members list in the **edit group panel** to use `3 dot` menu instead of the `x` icon. This is to allow more options to manage the members of the group. The admin can now either
a) Remove a member from the group
b) Set/Remove a member as a "moderator" from the group
Part b) is currently in implementation.
Before:
https://github.com/zer0-os/zOS/assets/33264364/abf855ce-2578-4919-ab17-ca3473beb6a7
After:
https://github.com/zer0-os/zOS/assets/33264364/36578d9c-5b24-44dc-b87a-a650b2bd6751
> Update `Edit Group` Flow: Show 3 dot menu instead of `x` icon to remove member

- src/components/message/index.tsx
- src/platform-apps/channels/messages-menu/index.test.tsx
- src/platform-apps/channels/messages-menu/index.tsx
Note:: This PR simply fixes the bug. I will be refactoring this so the dialog is handled in the dialog manager, in a follow up PR.
- fixes the rendering of the delete message confirmation modal when right clicking a message bubble and selecting the delete option.
- fix bug.
- run UI, send a message, and then right click message bubble, select delete, check modal is rendered. 
https://github.com/zer0-os/zOS/assets/39112648/29053a73-3cb4-44a7-9883-860d736f92ff
> fix(message-menu): rendering of delete message modal when right clicking and selecting delete option

- src/authentication/create-account-method/styles.scss
- src/authentication/create-email-account/index.tsx
- src/authentication/create-email-account/styles.scss
- src/authentication/create-wallet-account/index.tsx
- src/authentication/create-wallet-account/styles.scss
- src/authentication/email-login/styles.scss
- redesigns the create account options - web3 and email
- run ui and visit the create account page. you will need an invite code to pass through acces.
https://github.com/zer0-os/zOS/assets/39112648/3529e0ae-e9d7-47c5-a3f3-2c448e8ca452
> feat(create-account): redesign create account options

- package-lock.json
- package.json
- chore: bump version (`1.71.1`) -> (`1.72.0`)
> chore: bump version (`1.71.1`) -> (`1.72.0`)

- package-lock.json
- package.json
- src/index.tsx
- src/lib/desktop.ts
- src/utils.ts
Enables the ToDesktop SDK and creates a `desktopInit` function to run setup for the desktop app.
The updates should have no effect on the web app.
> Integrate ToDesktop SDK

- package-lock.json
- package.json
- chore: bump version (`1.72.0`) -> (`1.73.0`)
> chore: bump version (`1.72.0`) -> (`1.73.0`)

- package-lock.json
- package.json
- chore: bump version (`1.73.0`) -> (`1.74.0`)
> chore: bump version (`1.73.0`) -> (`1.74.0`)

- src/components/message/index.tsx
- ensures browser context menu can be opened when highlighting text.
- accessibility.
- run the UI, send a message, highlight text, and right click for browser context menu.
https://github.com/zer0-os/zOS/assets/39112648/9600eac1-1e28-4afe-b6f8-a62721ac86ca
> fix(message): browser context menu on when highlighting text

- package-lock.json
- package.json
- chore: bump version (`1.74.0`) -> (`1.75.0`)
> chore: bump version (`1.74.0`) -> (`1.75.0`)

- src/components/group-management/member-management-dialog/container.test.tsx
- src/components/group-management/member-management-dialog/container.tsx
- src/components/group-management/member-management-dialog/index.test.tsx
- src/components/group-management/member-management-dialog/index.tsx
- src/components/messenger/group-management/container.test.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/index.test.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/member-management-menu/index.tsx
- src/components/messenger/group-management/member-management-menu/styles.scss
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/feature-flags.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/utils.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
- src/store/group-management/index.ts
- src/store/group-management/saga.test.ts
- src/store/group-management/saga.ts
This PR covers the following updates:
- adds a new feature flag (`allowModeratorActions`)
- updates the `channel` state to add `moderatorIds` (this will store the channel's moderator id's). Also updated `matrix-client` to parse the `matrixIds` -> `zeroUserIds` (since the raw id's which we receive from matrix, for mods, are matrixIds)
- updates `matrix-client` (& sagas) to add core logic for setting a new moderator. It also publishes a real-time event (`publishRoomMemberPowerLevelChanged`), which we receive in the `saga`, and update the channel state accordingly.
- updated `MemberManagementDialog` to reflect UI for setting a member as moderator.
https://github.com/zer0-os/zOS/assets/33264364/5f3e30d0-6150-4dba-a092-d3137b493e69
> Implement core logic for `setting a new moderator` (by admin) [Feature flagged]

- package-lock.json
- package.json
- chore: bump version (`1.75.0`) -> (`1.76.0`)
> chore: bump version (`1.75.0`) -> (`1.76.0`)

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- makes read receipts private!
- these should be private by default
> refactor(matrix-client): make read receipts private

- package-lock.json
- package.json
-  chore: bump version (`1.76.0`) -> (`1.77.0`)
> chore: bump version (`1.76.0`) -> (`1.77.0`)

- src/components/group-management/member-management-dialog/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.tsx
- src/components/messenger/group-management/view-members-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- src/components/messenger/list/utils/utils.test.ts
- src/components/messenger/list/utils/utils.tsx
Renders '`Mod`' tag for users who are moderators of the group (`view-members-panel`, `group-info-panel`, `edit-group-panel`)
`Members Panel`
`Group Info Panel`
`Edit Group Panel`
> Render Users with 'Mod' tags, for users who are moderators of group in various panels

- src/lib/feature-flags.ts
- adds enableReadReceiptPreferences to feature flags
- to feature flag user read receipt preferences
> feat(feature-flags): add enableReadReceiptPreferences

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/types.ts
- src/lib/feature-flags.ts
- src/store/channels/index.ts
- src/store/channels/saga.ts
Note: UI updates in follow up.
- Implements user-configurable read receipt preferences with a default to private if feature flagged, default to public if not, and includes a feature flag for enabling this functionality 
- test coverage
- To give users control over their read receipt visibility, enhancing privacy and user experience.
- this is not yet wired up so you can not test manually in the UI without code changes to do so.
> feat(matrix-client): matrix set receipt preferences and get receipt preferences when reading a room

- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- src/components/messenger/group-management/container.test.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/member-management-menu/container.test.tsx
- src/components/messenger/group-management/member-management-menu/container.tsx
- src/components/messenger/group-management/member-management-menu/index.test.tsx
- src/components/messenger/group-management/member-management-menu/index.tsx
Allows group moderator access to `Edit Group` panel. In the `Edit group` Panel, 
- an `admin` has FULL access (edit group image, name, add/remove members, make/remove moderators)
- a `moderator` has LIMITED access :: it can only 
-  a) add members to group
- b) remove members from group (only those who aren't `admins` or `mods`)
This is the view from a moderator (as current user):
https://github.com/zer0-os/zOS/assets/33264364/7a2e1d68-0be4-4635-8619-55964154fcf0
This is the view from an admin (as current user):
https://github.com/zer0-os/zOS/assets/33264364/be48ee7e-998e-43f5-ad50-f8e057b125fb
> Allow Group Moderator access to `Edit Group` Panel & can `Remove Members` (**only**)

- src/components/group-management/member-management-dialog/container.tsx
- src/components/group-management/member-management-dialog/styles.scss
> Increase `{ width, line-height }` of text in Member Management Dialog

- src/lib/chat/matrix-client.ts
Earlier, if a user is a `Moderator`, and he is removed from the group, then if he would rejoin he would still remain a moderator. This should not happen.
So before we kick a user out, now we first lower it's `power_level` down to `0` first, and then kick him out.
This is how the admin messages are now:
> Reset a user's `power_level` before `kicking` him out

- src/components/group-management/member-management-dialog/styles.scss
- src/lib/chat/matrix/chat-message.test.ts
- src/lib/chat/matrix/chat-message.ts
- src/lib/chat/matrix/utils.ts
Sometimes the admin messages were not displaying in the UI, after you set/remove a user as a moderator. This was because, sometimes instead of "0" `power_level`, we would just get an "empty"/"undefined" field for the `power_level` in the event content. For eg.
Before
```js
{
"admin": <100>
"user-1": <50> // mod
}
```
Now, if we remove this user as mod, then we sometimes get ::
```js
{
"admin": <100>
// this is empty
}
```
In normal cases we should get something like:
```js
{
"admin": <100>
"user-1": <0> // normal user now
}
```
This PR handles the above case. 
Before (notice one admin message is missing):
After:
> [FIX] Sometimes the admin messages do not display when you set/remove a `Mod`

- src/lib/chat/matrix-client.ts
Executes `lowerMinimumInviteAndKickLevels` before setting a user as `Mod` in a room. This is just to "make sure" that all groups have the correct permissions set, for a `Mod` to perform `{ invite, kick }` actions. 
For example, if a room is created via android/iOS, and we don't have the right `power_levels` set for a room in that case, then this should handle it (since we're explicitly correcting the room's power_levels as soon as we set a moderator).
> Trigger `lowerMinimumInviteAndKickLevels` before setting a user as `Moderator`

- src/components/message-input/mentions/index.test.tsx
- src/components/message-input/mentions/index.tsx
- src/components/message/index.tsx
https://linear.app/zero-tech/issue/ZOS-95/when-editing-a-message-if-your-browser-supports-spellcheck-you-should
- Prevents `contextmenu` from triggering when the user is hovering editable text (in this case, the `textarea` which appears after you hit `Edit`on a message)
N/a
https://github.com/zer0-os/zOS/assets/12437916/57d7a854-049f-4f76-83e1-95045d8d9fe5
> feat(message): prevent custom context menu on textarea

- package-lock.json
- package.json
- chore: bump version (`1.79.0`) -> (`1.80.0`)
> chore: bump version (`1.79.0`) -> (`1.80.0`)

- src/_glass.scss
- removes border gradient from glass styles.
- run UI and check borders for sidekick, emoji panel etc
> feat: remove border gradient from glass style

- package-lock.json
- package.json
- chore: bump version (`1.80.0`) -> (`1.81.0`)
> chore: bump version (`1.80.0`) -> (`1.81.0`)

- package-lock.json
- package.json
- chore: bump version (`1.81.0`) -> (`1.82.0`)
> chore: bump version (`1.81.0`) -> (`1.82.0`)

- src/components/message/edit-message-actions/edit-message-actions.test.tsx
- src/components/message/edit-message-actions/edit-message-actions.tsx
- src/components/message/edit-message-actions/styles.scss
- src/components/message/styles.scss
https://linear.app/zero-tech/issue/ZOS-26/edit-message-design
- Replaces `❌` and `✔️` icons in `EditMessageActions` with `Cancel` and `Send`
- When editing, editing bubble width now matches max message width
N/a
1. Send a message, preferably a long one so you can test max input width
2. Open Edit Message dialog (right click on message, or hit triple dot menu beside message, and click "Edit)
- Edit message buttons should be `Cancel` and `Send`, rather than `❌` and `✔️`
- Input should match max message width
> feat: edit message design changes

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/chat/bus.ts
- src/store/messages/saga.ts
- tracks and publishes real time read receipts (currently feature flagged).
- to update the UI in real time for read receipts (as per demo below).
- run ui and follow the demo below.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/564d7d2f-d340-4195-90e4-15f7018b99a4
> feat(read-receipts): track and publish live receipts

- src/components/messenger/message-info/container.tsx
- src/components/messenger/message-info/index.tsx
- src/components/messenger/message-info/overview-panel/index.test.tsx
- src/components/messenger/message-info/overview-panel/index.tsx
- src/components/messenger/message-info/overview-panel/styles.scss
- adds message info container, index and overview panel.
- in order to display read receipts in message info panel.
- this will not be wired up to the UI yet.
> feat(message-info): add container and component

- package-lock.json
- package.json
- chore: bump version (`1.84.0`) -> (`1.85.0`)
> chore: bump version (`1.84.0`) -> (`1.85.0`)

- src/components/messenger/list/styles.scss
- adds a custom opaque footer button colour (invite button on conversation list panel).
- as requested for improved ux.
- run ui and check button as per demo below.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/f5016885-61c6-4151-b4ec-f1b84c4170d0
> feat(messenger-list): add custom opaque footer button color

- package-lock.json
- package.json
- chore: bump version (`1.85.0`) -> (`1.86.0`)
> chore: bump version (`1.85.0`) -> (`1.86.0`)

- package-lock.json
- package.json
- chore: bump version (`1.86.0`) -> (`1.87.0`)
> chore: bump version (`1.86.0`) -> (`1.87.0`)

- package-lock.json
- package.json
- chore: bump version (`1.87.0`) -> (`1.88.0`)
> chore: bump version (`1.87.0`) -> (`1.88.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- updates argument type for the setReadReceiptFunction
- Removes flag. We would normally just flip this, it is safe to remove here.
- leads the way to handle setting of receipts in an improved way (follow up PRs).
- run tests as usual. this wasn't wired up yet.
> refactor(matrix-client): update set read receipt function argument type and remove flag

- package-lock.json
- package.json
- chore: bump version (`1.88.0`) -> (`1.89.0`)
> chore: bump version (`1.88.0`) -> (`1.89.0`)

- src/components/messenger/message-info/overview-panel/index.tsx
- adds content highlighter to message content to message info overview panel
- render mentions correctly
- run ui and send a message with a mention. open message info and check message content.
> feat(message-info-overview-panel): add highlighter for mentions in message content

- package-lock.json
- package.json
- chore: bump version (`1.89.0`) -> (`1.90.0`)
> chore: bump version (`1.89.0`) -> (`1.90.0`)

- src/components/message/index.tsx
- enables view message info for all members
- open any message menu and check message info is an option on the message menu and opens as expected
> refactor(info-option): enable view message info for all members

- src/lib/chat/index.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- src/store/user-profile/index.ts
- src/store/user-profile/saga.test.ts
- src/store/user-profile/saga.ts
- ensures read receipts preferences are fetched to persist choice after refresh or logout.
- to ensure read receipts preferences are working as expected.
- run the ui and choose a read receipt preference > refresh page and check setting is the same.
> fix(read-receipts): ensure read receipts persist on refresh or logout/login

- package-lock.json
- package.json
- chore: bump version (`1.90.0`) -> (`1.91.0`)
> chore: bump version (`1.90.0`) -> (`1.91.0`)

- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.tsx
- src/components/message/styles.scss
- src/components/messenger/message-info/container.tsx
- src/store/message-info/index.ts
- src/store/message-info/saga.test.ts
- src/store/message-info/saga.ts
- src/store/messages/saga.ts
- feat(chat-view): implements message bubble read receipts
- read receipts on message bubbles to show if a conversation is fully read.
- run the UI and check for the read receipts on message bubbles.
> feat(chat-view): implement message bubble read receipts

- package-lock.json
- package.json
- chore: bump version (`1.91.0`) -> (`1.92.0`)
> chore: bump version (`1.91.0`) -> (`1.92.0`)

- package-lock.json
- package.json
- chore: bump version (`1.92.0`) -> (`1.93.0`)
> chore: bump version (`1.92.0`) -> (`1.93.0`)

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- private read receipts by default
- as requested (privacy conerns)
- create account > complete registration/login flow > check read receipts setting in user profile (and test read receipts with another test user)
> refactor(matrix-client): private read receipts by default

- src/lib/browser/index.ts
Clicking notification popup on desktop app will now open / maximize the desktop window.
See [ELT-16]
> fix(ELT-16): notification onclick show window

- package-lock.json
- package.json
- chore: bump version (`1.93.0`) -> (`1.94.0`)
> chore: bump version (`1.93.0`) -> (`1.94.0`)

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
Handles edited messages and read receipts : 
- sends read receipt for non-edited event
- sends read receipt for original event if latest event is an edit
- sends read receipt for latest event if original event is not found
- previously editing a message was causing issues with the read receipts. these changes fix that.
- run the ui and test real time and non real time read receipt events for edited messages and non edited messages.
> feat(matrix-client): add functionally to process and handle read receipts for edited messages

- package-lock.json
- package.json
- chore: bump version (`1.94.0`) -> (`1.95.0`)
> chore: bump version (`1.94.0`) -> (`1.95.0`)

- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/components/message/styles.scss
- src/components/messenger/message-info/container.tsx
- src/store/messages/saga.ts
- adds functionality for real-time/non-real time delivered receipts and updates ui to have three icons for sent, delivered and read states.
- as per request.
- run the UI > send a message > check receipt state.
https://github.com/zer0-os/zOS/assets/39112648/0a9493c7-ca5a-4912-941c-6c1b7ce260bb
> feat(delivered-receipts): add functionality for real-time/non-real time delivered receipts and ui

- package-lock.json
- package.json
- chore: bump version (`1.95.0`) -> (`1.96.0`)
> chore: bump version (`1.95.0`) -> (`1.96.0`)

- package-lock.json
- package.json
- chore: bump version (`1.96.0`) -> (`1.97.0`)
> chore: bump version (`1.96.0`) -> (`1.97.0`)

- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/components/message/styles.scss
- src/components/messenger/message-info/container.tsx
- src/store/messages/saga.ts
- adds functionality for real-time/non-real time delivered receipts and updates ui to have three icons for sent, delivered and read states.
- as per request.
- run the UI > send a message > check receipt state.
https://github.com/zer0-os/zOS/assets/39112648/0a9493c7-ca5a-4912-941c-6c1b7ce260bb
> feat(delivered-receipts): implement delivered receipts functionality and ui

- package-lock.json
- package.json
- chore: bump version (`1.97.0`) -> (`1.98.0`)
> chore: bump version (`1.97.0`) -> (`1.98.0`)

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/platform-apps/channels/messages-menu/index.test.tsx
- src/platform-apps/channels/messages-menu/index.tsx
- allows editing text when sent with a media message
- to be able to edit text messages that are sent with media (images).
- run the UI > send a media message and text > open message menu > select `Edit` > edit message and click send.
https://github.com/zer0-os/zOS/assets/39112648/ff4d9580-4655-471a-8461-149ef8261f11
> feat(messages): allow editing text when sent with a media message

- package-lock.json
- package.json
- chore: bump version (`1.98.0`) -> (`1.99.0`)
> chore: bump version (`1.98.0`) -> (`1.99.0`)

- src/components/message/index.tsx
- src/components/message/styles.scss
- replaces IconCheckDouble with two IconChecks.
- updates styles.
- IconCheckDouble appears to be causing issues (especially on the vite build) due to some exporting issues in ZUI. As a result, as a work around, we can just use two check icons to give the impression of a double tick icon for delivered and read receipts. This fixes the issues, and also fixes issues when running tests.
- run UI and check read receipt icons.
> fix(icons): remove icon check double and replaces with two icon check icons

- src/components/messenger/user-profile/settings-panel/styles.scss
- fixes icon position in settings > read receipts checkbox.
- positioning (before and after below)
Before:
After:
> fix(settings): checkbox icon position

- src/components/messenger/user-profile/account-management-panel/container.test.tsx
- src/components/messenger/user-profile/account-management-panel/container.tsx
- src/components/messenger/user-profile/account-management-panel/index.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- src/components/wallet-list-item/index.test.tsx
- src/components/wallet-list-item/index.tsx
- src/components/wallet-list-item/styles.scss
(wallet and no email)
(email but no wallet): in this case we have disabled "add new wallet" button for now, since it will be added in future.
> Add `Manage Accounts` section

- package-lock.json
- package.json
- chore: bump version (`1.99.0`) -> (`2.0.0`)
> chore: bump version (`1.99.0`) -> (`2.0.0`)

- src/index.tsx
- src/restricted.scss
- src/restricted.tsx
- src/utils.ts
Note :: this is a first attempt / approach at implementing a restricted page. I will be deploying this to development to test, but this does not necessarily mean we will keep these additions, i.e. if there is a better way to handle restricting mobile devices.
- adds and renders restriction page on mobile devices
- as per request
- prevent users using the app via web browser on mobile
- once deployed to development, using a mobile visit the dev url and check the restricted page is rendered.
> feat(mobile-restriction): add and render restriction page on mobile devices

- src/index.tsx
- src/store/page-load/saga.test.ts
- src/store/page-load/saga.ts
- applies mobile restriction logic to page load saga
- adds restricted route
- handling this logic in the page load saga prevents unexpected issues when rendering routes i.e. flickering when page load completes
- once merged this can be tested on development via mobile device.
> feat(page-load-saga): apply mobile restriction logic to page load saga

- src/store/page-load/saga.test.ts
- src/store/page-load/saga.ts
Note :: Further refactoring required. We should move the android download functionality to the restricted component for the restricted route now that we would prevent the user from reaching the login route.
- set load to complete if restricted route is reached due to device being mobile.
- this removes test with regards to showing android download links. 
- prevents the route changing to login when page load is complete on a mobile device.
> fix(page-load-saga): ensure restricted route persists and does not switch to login route on load complete

- src/restricted.scss
- src/restricted.tsx
- add store link elements to restricted page
- so users can navigate to the correct store if they land on the restricted route page
> feat(restricted-route): add store link elements to restricted page

- package-lock.json
- package.json
- chore: bump version (`2.0.0`) -> (`1.100.0`)
NOTE :: As requested we are going back down a major version to 1.100.0
> chore: bump version (`2.0.0`) -> (`1.100.0`)

- src/components/message/parent-message/styles.scss
- src/components/reply-card/styles.scss
- Ensures that media images in the reply card maintain their aspect ratio and fit within the container without stretching.
- To improve the visual presentation of media images in reply cards and prevent them from appearing distorted.
- run ui and reply to image messages
Before:
After:
> fix(reply-card-and-parent-message): maintain aspect ratio for media images in reply card

- package-lock.json
- package.json
- chore: bump version (`1.100.0`) -> (`1.101.0`)
> chore: bump version (`1.100.0`) -> (`1.101.0`)

- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/utils.test.ts
- src/components/chat-view-container/utils.ts
- src/store/messages/index.ts
- src/store/messages/utils.matrix.test.ts
- src/store/messages/utils.matrix.ts
- moves message linking and mapping logic to container level from message saga and utils
- fix issue with fetching message data
- run the UI and ensure message edit, replies, images etc render as expected.
https://github.com/zer0-os/zOS/assets/39112648/0434241e-a117-414b-beeb-2436805899dd
> feat(chat-view-container): move message linking and mapping logic to container level

- package-lock.json
- package.json
- chore: bump version (`1.101.0`) -> (`1.102.0`)
> chore: bump version (`1.101.0`) -> (`1.102.0`)

- .github/workflows/development.yml
Currently `main` is broken due to this
> Update `workflows/development.yml` workflow to install with `--legacy-peer-deps`

- src/authentication/validate-invite/index.test.tsx
- src/authentication/validate-invite/index.tsx
If you had copied the invite code with a "space" at end, the GET ACCESS call would fail even if the code is correct (sc below).
Fixed now, as we're trimming the input.
> `trim` the invite code on the input during registration

- src/lib/feature-flags.ts
Flips the feature flag to enable rewards on production.
> Enable rewards 

- package-lock.json
- package.json
- src/components/edit-profile/index.tsx
- src/components/inverted-scroll/index.tsx
- src/components/message-input/index.tsx
- src/components/message/edit-message-actions/edit-message-actions.tsx
- src/components/messenger/autocomplete-members/index.tsx
- src/components/modal/index.tsx
- src/components/tooltip-popup/tooltip-popup.tsx
- src/components/web3-connect/index.tsx
- src/index.tsx
- src/lib/web3/web3-react.tsx
- src/messenger-main.tsx
- src/setupTests.ts
- React 17 -> React 18. `react`, `react-dom`, and typings, all upgraded.
- Used [the new `root.render` function](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#:~:text=//%20Before,(%3CApp%20tab%3D%22home%22%20/%3E)%3B) at app root.
- Upgraded `testing-library/react` to work with React 18. All of our RTL tests are working as expected.
- Installed and configured an [Enzyme React 18 adapter](https://www.npmjs.com/package/@cfaester/enzyme-adapter-react-18) (`@cfaester/enzyme-adapter-react-18`). All of our Enzyme tests are working as expected.
- Removed `@wojtekmaj/enzyme-adapter-react-17`.
- Upgraded `react-router-dom` to `5.3.2`, [which supports React 18 `StrictMode`](https://github.com/remix-run/react-router/releases/tag/v5.3.2).
- Upgraded `react-redux` to `7.2.8`, [which …
> chore: upgrade to React 18

- src/store/channels-list/api.ts
API PR: [https://github.com/zer0-os/zos-api/pull/22](https://github.com/zer0-os/zos-api/pull/22)
Currently for a very group, which has a lot of matrixIds, the GET request from the browser was failing due to "URI too long" issue. Since this is converted to post now, we can send large data via `req.body` instead of `query.params`
> Use `POST` instead of `GET` to fetch ZERO user's info using their matrixIds via `/matrix/users/zero`

- index.html
- src/invite.tsx
- src/pages/login/login-container.tsx
- on android download uses, replace store path with latest app store path.
- direct users to latest app, not the outdated one.
> feat(android-smart-popup): replace store path

- package-lock.json
- package.json
- chore: bump version (`1.106.0`) -> (`1.107.0`)
> chore: bump version (`1.106.0`) -> (`1.107.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/lib/chat/matrix/types.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
Note :: tests will be converted to vite tests in follow up.
- implements adding and removing custom mute conversation tags 
- gets is room muted tags for rooms
- to be able to mute room notifications
> feat(matrix-client): implement and handle adding / removing custom mute conversation tags

- src/components/messenger/list/conversation-item/conversation-item.scss
- src/components/messenger/list/conversation-item/index.tsx
- fixes the muted icon position
- ensure muted icons align in the conversation list
- run UI and check muted icons in conversation list items as per below.
Truncated
> feat(conversation-list-item): fixed muted icon position

- package-lock.json
- package.json
- chore: bump version (`1.109.0`) -> (`1.110.0`)
> chore: bump version (`1.109.0`) -> (`1.110.0`)

- src/store/channels-list/saga.ts
It seems like "user presence" i.e online/offline status is causing heavy load on the server, which is causing performance issues. to test it, we're disabling it on development and production.
This PR mutes (for **now**), the `fetchUserPresence` call during initial load
> mute `fetchUserPresence` call during initial load

- src/components/citizen-list-item/index.test.tsx
- src/components/citizen-list-item/index.tsx
- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/list/conversation-item/index.test.tsx
- src/components/messenger/list/conversation-item/index.tsx
- remove user status from avatars
- presence has been disabled, therefore hiding user status`
> feat(avatars): remove user status from avatars

- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- re-adds subtitle to display users primary zid or wallet address
- to display users wallet/primaryzid
- run ui and check subtitle in conversation header
> refactor(conversation-header): re-add subtitle to display users primary zid or wallet address

- package-lock.json
- package.json
- chore: bump version (`1.114.0`) -> (`1.115.0`)
> chore: bump version (`1.114.0`) -> (`1.115.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/chat/bus.ts
- src/store/messages/saga.ts
- process real time read receipts only for active conversations
- to reduce the need to process of read receipts in conversations that are not open to optimise performance
> refactor(messages-saga): process real time read receipts only for active conversations

- package-lock.json
- package.json
- chore: bump version (`1.115.0`) -> (`1.116.0`)
> chore: bump version (`1.115.0`) -> (`1.116.0`)

- src/store/messages/saga.ts
-  increases batch interval when receiving new messages
- increase the "batch processing" from 0.5s to 2s for improved performance (as requested).
> refactor(messages-saga): increase batch interval when receiving new messages

- package-lock.json
- package.json
- chore: bump version (`1.116.0`) - (`1.117.0`)
> chore: bump version (`1.116.0`) - (`1.117.0`)

- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
Note :: the code has simply been commented out here for testing purposes on production. this will either be reverted or improved in a follow up.
- temporarily disables message bubble read receipts processing
- check performance in production with this removed
> refactor(chat-view): temporarily disable message bubble read receipts processing

- package-lock.json
- package.json
- chore: bump version (`1.117.0`) -> (`1.118.0`)
> chore: bump version (`1.117.0`) -> (`1.118.0`)

- package-lock.json
- package.json
- chore: bump version (`1.119.0`) -> (`1.120.0`)
> chore: bump version (`1.119.0`) -> (`1.120.0`)

- package-lock.json
- package.json
- chore: bump version (`1.120.0`) -> (`1.121.0`)
> chore: bump version (`1.120.0`) -> (`1.121.0`)

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- This refactor consolidates the fetching of room tags for favorites and muted status into a single function to optimize initial load times.
- This change reduces the number of network requests during the initial loading of conversations, significantly improving performance for users with many conversations.
- run UI and check initial load time.
> refactor(matrix-client): room tag fetching to optimize initial load time by consolidating network requests

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- Optimizes room tags fetching by making concurrent network requests to improve performance.
- To reduce the overall loading time and enhance the user experience by fetching data more efficiently.
- run the UI and test initial loading time of app - check network dev tools tab, and you can enable timer logs feature flag to check timings.
> refactor(matrix-client, channels-list-saga): optimize room tags fetching by parallelizing network requests

- src/store/channels-list/saga.ts
- moves time end for fetching conversations
- accurate timer logs
> refactor(timer-logs): move time end for fetching conversations

- src/components/messenger/chat/conversation-header/index.test.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/chat/conversation-header/styles.scss
-  remove tooltip and re-align elements from conversation header
- no longer required
> refactor(conversation-header): remove tooltip and re-align elements

- package-lock.json
- package.json
- chore: bump version (`1.124.0`) -> (`1.125.0`)
> chore: bump version (`1.124.0`) -> (`1.125.0`)

- src/store/messages/saga.ts
- reduces the batch interval for new messages received back down to 0.5s
- the existing interval was set to 2s making loading specific conversations slower
> refactor(messages/saga): change batch interval back to 0.5s due to making loading specific conversations slower

- package-lock.json
- package.json
- chore: bump version (`1.125.0`) -> (`1.126.0`)
> chore: bump version (`1.125.0`) -> (`1.126.0`)

- src/components/chat-view-container/chat-view-container.test.tsx
- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/chat-view.test.tsx
- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/components/message/styles.scss
- src/lib/chat/matrix/chat-message.ts
- src/lib/chat/matrix/media.ts
- src/store/messages/index.ts
- src/store/messages/saga.ts
Note :: the UI for the placeholder is a basic implementation for now. This will be improved in follow ups.
- The implementation and refactoring for downloading and decrypting images when conversation is active.
-  Prevent download/decrypt happening on initial load for every conversation. 
- Run test as usual.
- Run UI and check images media rendering for active conversations. 
> feat: download and decrypt images only when conversation is active

- src/lib/chat/matrix-client.ts
Reduces the messages we're fetching for each channel from 100 to 50.
> Reduce `getMessagesByChannelId` limit from 100 to 50

- package-lock.json
- package.json
- chore: bump version (`1.127.0`) -> (`1.128.0`)
> chore: bump version (`1.127.0`) -> (`1.128.0`)

- package-lock.json
- package.json
- chore: bump version (`1.128.0`) -> (`1.129.0`)
> chore: bump version (`1.128.0`) -> (`1.129.0`)

- package-lock.json
- package.json
- chore: bump version (`1.129.0`) -> (`1.130.0`)
> chore: bump version (`1.129.0`) -> (`1.130.0`)

- src/components/messenger/user-profile/overview-panel/index.tsx
- src/components/messenger/user-profile/overview-panel/styles.scss
- adds scrollbar container to overview panel (user-profile)
- run the UI > decrease screensize when on user profile overview panel > hover over panel and check scrol.
https://github.com/user-attachments/assets/fba6838c-0797-4b4d-8723-8eb08f34ffac
> feat(user-profile/overview-panel): add scrollbar container to panel

- src/components/messenger/user-profile/downloads-panel/index.tsx
- src/components/messenger/user-profile/downloads-panel/styles.scss
- adds scrollbar container to downloads panel (user-profile)
- run the UI > decrease screensize when on user profile downloads panel > hover over panel and check scroll.
https://github.com/user-attachments/assets/f61104b6-36c8-4d8f-a418-b9e3ad40c6c5
> feat(user-profile/downloads-panel): add scrollbar container to panel

- src/components/messenger/user-profile/settings-panel/index.tsx
- src/components/messenger/user-profile/settings-panel/styles.scss
- adds scrollbar container to settings panel (user-profile)
- run the UI > decrease screensize when on user profile settings panel > hover over panel and check scroll.
https://github.com/user-attachments/assets/a90c0f8c-ca17-4620-bfeb-f6b05d026b38
> feat(user-profile/settings-panel): add scrollbar container to panel

- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- adds scrollbar container to account management panel (user-profile)
- run the UI > decrease screensize when on user profile account management panel > hover over panel and check scroll.
https://github.com/user-attachments/assets/2a3fd47b-3578-4a6c-9b43-398e699440d7
> feat(user-profile/account-management-panel): add scrollbar container to panel

- src/components/edit-profile/index.tsx
- src/components/edit-profile/styles.scss
- adds scrollbar container to edit profile panel (user-profile)
- run the UI > decrease screensize when on user profile edit profile panel > hover over panel and check scroll.
https://github.com/user-attachments/assets/8202a329-6eda-4b03-be47-2850c3ec62d4
> feat(user-profile/edit-profile): add scrollbar container to panel

- package-lock.json
- package.json
- chore: bump version (`1.130.0`) -> (`1.131.0`)
> chore: bump version (`1.130.0`) -> (`1.131.0`)

- package-lock.json
- package.json
- chore: bump version (`1.131.0`) -> (`1.132.0`)
> chore: bump version (`1.131.0`) -> (`1.132.0`)

- src/components/messenger/list/conversation-item/index.test.tsx
- src/components/messenger/list/conversation-item/index.tsx
- src/components/messenger/list/conversation-item/more-menu/index.test.tsx
- src/components/messenger/list/conversation-item/more-menu/index.tsx
- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/types.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
- replaces specific favorites functions/calls with label management functions/calls to handle favorite room tagging
- now that we have label management in place we can consolidate the handling of room tagging.
- run the ui and test favorite room tagging is working as expected.
https://github.com/user-attachments/assets/5f3321b0-fbc4-40c6-9508-0488d49415b9
> refactor(favorites): use channel label management to handle favorite room tagging

- package-lock.json
- package.json
- chore: bump version (`1.132.0`) -> (`1.133.0`)
> chore: bump version (`1.132.0`) -> (`1.133.0`)

- src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
- src/components/messenger/list/conversation-list-panel/index.tsx
- applies horizontal scroll to tab list
- re-orders list items
- removes some padding
- as requested
- improved ui/ux
- run ui and test scroll on tab list
https://github.com/user-attachments/assets/c8e3ae46-4c2c-46e2-8520-e0530193b527
> feat(conversation-list/tab-list): apply horizontal scroll to tab list

- src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
-  updates scss of tab badge to always render even if tab is active
- minor style change to prevent jolting - add border bottom
- design requested
- run UI > click on a tab that has unread count, and check unread count is still displayed
> refactor(conversation-list/labels): always render unread count

- src/components/messenger/list/conversation-item/more-menu/index.test.tsx
- src/components/messenger/list/conversation-item/more-menu/index.tsx
- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- This PR adds support for archiving conversations in the conversation list and ensures archived conversations are handled correctly by removing their other labels and adjusting unread counts.
- To provide users with the ability to archive conversations, ensuring that archived conversations do not appear in other lists or affect unread counts, improving organization and usability.
- run ui and follow demo below.
https://github.com/user-attachments/assets/06adff0d-7c0c-4540-aa4e-fc28947b4046
> feat(conversation-list/labels): add archive label and handle archived conversations

- package-lock.json
- package.json
- chore: bump version (`1.133.0`) -> (`1.134.0`)
> chore: bump version (`1.133.0`) -> (`1.134.0`)

- package-lock.json
- package.json
- chore: bump version (`1.134.0`) -> (`1.135.0`)
> chore: bump version (`1.134.0`) -> (`1.135.0`)

- package-lock.json
- package.json
-chore: bump version (`1.135.0`) -> (`1.136.0`)
> chore: bump version (`1.135.0`) -> (`1.136.0`)

- src/App.tsx
- src/App.vitest.tsx
- src/Main.test.tsx
- src/Main.tsx
- src/apps/app-router.tsx
- src/apps/app-router.vitest.tsx
- src/components/app-bar/index.tsx
- src/index.tsx
- src/lib/feature-flags.ts
- src/messenger-main.test.tsx
- src/messenger-main.tsx
- Creates a top-level `App` component, which houses all "global UI" (providers, app bar), and renders the `AppSwitcher`.
- Creates an `AppRouter`, which is basically just a `Router` which renders different apps to a container based on `Route`.
- Moves all "global UI" from `Main` to `App`.
- Adds a feature flag (`enableExplorer`) for testing the app switcher.
So we can add arbitrary "sub apps" to zOS, as per the initial vision of the product.
- These changes should deliver 0 perceivable difference to the user. So, all flows should work exactly the same as before.
- Run `FEATURE_FLAGS.enableExplorer = true` in your browser console, and click the `Explorer` option in the app bar. Note: you will have to hit `Back` in your browser to go back to Messenger
---
Please note:
- I used function …
> feat: app switcher

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/message-info/saga.test.ts
- src/store/message-info/saga.ts
- src/store/messages/saga.ts
- removes functionality for read receipts.
- ensures when a user opens the 'message info' panel, that read receipts are not processed
> refactor(read-receipts): remove calls for read receipts

- package-lock.json
- package.json
- chore: bump version (`1.136.0`) -> (`1.137.0`)
> chore: bump version (`1.136.0`) -> (`1.137.0`)

- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- renders favorites (star icon) first in tab list even if list is empty
- prevent the movement of elements i.e. updating the existing functionality where Favorites star icon and All tab switched places based on length of conversations in list.
- run ui and check tab list order.
> refactor(conversation-list-panel): render favorites (star icon) first in tab list even if list is empty

- src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
- adjusts the height of the unread count tag badge
- run ui and check unread count tag badge (as per below)
BEFORE
AFTER
> refactor: adjust the height of the unread count tag badge

- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
- prevents browser notifications if a room is tagged as archived
- there should not be notifications for archived rooms 
- run ui, archive room and send a message to that room. A browser notification should not be sent.
> feat(browser-notifications): do not send browser notifications when room is archived

- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- removes archived conversations from search results
- archived conversations should not appear when searching existing conversations
- run the ui and follow the steps outlined in demo below.
https://github.com/user-attachments/assets/d97693ab-5fd0-4c04-8ae1-1bec502af415
> feat(conversation-list-panel): filter archived conversations from search

- package-lock.json
- package.json
- chore: bump version (`1.137.0`) -> (`1.138.0`)
> chore: bump version (`1.137.0`) -> (`1.138.0`)

- package-lock.json
- package.json
- chore: bump version (`1.138.0`) -> (`1.139.0`)
> chore: bump version (`1.138.0`) -> (`1.139.0`)

- src/components/content-highlighter/index.tsx
- This change resolves a React error by moving the key prop out of the props spread in the ContentHighlighter component.
- We are making this change to prevent potential issues caused by improper handling of the key prop.
> fix: move key prop out of props spread to resolve react error

- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
- src/store/channels-list/saga.ts
- src/store/chat/index.ts
- src/store/chat/types.ts
- Sets the initial selected tab to "Favorites" if there are non-archived favorite conversations, otherwise defaults to "All".
- To ensure that the default view prioritizes favorite conversations while excluding archived ones.
- run UI > favorite a conversation > refresh > check tabs.
DEMO
https://github.com/user-attachments/assets/c242855c-380a-4f43-9e1e-5ec1d7e893e3
> feat: handle selected label on load

- package-lock.json
- package.json
- chore: bump version (`1.140.0`) -> (`1.141.0`)
> chore: bump version (`1.140.0`) -> (`1.141.0`)

- src/components/message/index.tsx
- src/store/messages/api.ts
- src/store/messages/saga.send.test.ts
- src/store/messages/saga.ts
- adds error handling for link preview
- resolve error thrown when there is a bad preview url
- run ui and enter a bad url
> fix: error handling for link preview

- package-lock.json
- package.json
- chore: bump version (`1.141.0) -> (`1.142.0`)
> chore: bump version (`1.141.0) -> (`1.142.0`)

- src/apps/app-router.tsx
- src/apps/app-router.vitest.tsx
- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- src/apps/messenger/index.tsx
- src/apps/messenger/messenger-main.test.tsx
- src/apps/messenger/messenger-main.tsx
This is a very minor change.
- Clears up the `src` directory.
- Is consistent with putting all apps in `apps/` - this lets us keep all app entry-points in the same place.
> refactor: move Messenger files to `apps/messenger/`

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.createChannel.test.ts
- src/store/channels-list/saga.ts
- src/store/create-conversation/index.ts
- src/store/create-conversation/saga.test.ts
- src/store/create-conversation/saga.ts
This PR introduces the functionality to create unencrypted "Social Channels" within the platform, alongside the existing encrypted group conversations. It updates the client and server logic to support the creation, management, and user invitation for these channels. Additionally, it extends the existing Redux saga workflows to handle the creation of both encrypted conversations and unencrypted channels, including relevant tests to ensure the new functionality works as expected.
We are making this change to enhance the platform's flexibility by allowing users to create Social Channels that are better suited for larger communities and public interactions. Unlike private encrypted conversations, these channels are unencrypted, making them more efficient and scalable for broader audiences.
- …
> feat: add support for creating unencrypted channels

- src/store/create-conversation/saga.test.ts
- src/store/create-conversation/saga.ts
-  allows group creation with the same members.
- removes logic from the relevant saga function.
- to allow users to create a new unencrypted group but bypass/override our previous rule of only being able to create a new group if one does not exist with the same members
- try creating a new group with same users as another group
> refactor: allow group creation with the same members

- package-lock.json
- package.json
- chore: bump version (`1.143.0`) -> (`1.144.0`)
> chore: bump version (`1.143.0`) -> (`1.144.0`)

- package-lock.json
- package.json
- chore: bump version (`1.144.0`) -> (`1.145.0`)
> chore: bump version (`1.144.0`) -> (`1.145.0`)

- src/components/edit-profile/styles.scss
- src/components/messenger/list/group-details-panel/group-type-menu/index.tsx
- src/components/messenger/list/group-details-panel/group-type-menu/styles.scss
- src/components/messenger/user-profile/settings-panel/index.tsx
- src/components/messenger/user-profile/settings-panel/styles.scss
- add width to select input dropdown menu to align with width of the select input
> feat: add menu class names to handle and improve select input dropdown menu width sizes

- src/components/messenger/feed/index.test.tsx
- src/components/messenger/feed/index.tsx
- src/components/messenger/feed/styles.scss
- adds a messenger feed container
- Feed will be part of the new Channels feature
- the ui for this is not yet wired up.
> feat: add basic messenger feed container

- src/apps/messenger/Main.tsx
- src/components/messenger/feed/index.tsx
- renders messenger feed container when current channel is a social channel
- requirement for Channels feature.
- the messenger feed container, that will container the post input component and post component, should render when the current channel is a social channel.
- run ui > enableChannels feature flag > create social channel group > check UI contains element with text 'Messenger Feed'
> feat: render messenger feed container when current channel is a social channel (featureFlagged)

- package-lock.json
- package.json
- chore: bump version (`1.146.0`) -> (`1.147.0`)
> chore: bump version (`1.146.0`) -> (`1.147.0`)

- src/lib/chat/matrix-client.ts
- rename method - publishChannelTypeChange -> publishGroupTypeChange
- improve naming
> refactor: rename publish channel type change to publish group type change for consistency

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/media.ts
- This update bypasses the encryption process for file uploads in non-encrypted rooms, optimizing performance and ensuring correct file handling.
- We are making this change to prevent unnecessary encryption in non-encrypted rooms, improving the efficiency of file uploads and maintaining consistent behavior across different room types.
- run ui and send images in non encrypted rooms then refresh
> fix(matrix-client/messages-saga): bypass encrypting files during upload if non encrypted room

- package-lock.json
- package.json
- chore: bump version (`1.147.0`) -> (`1.148.0`)
> chore: bump version (`1.147.0`) -> (`1.148.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/lib/chat/matrix/types.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/messages/index.ts
- src/store/messages/utils.ts
- src/store/posts/index.ts
- src/store/posts/saga.test.ts
- src/store/posts/saga.ts
- src/store/posts/utils.ts
- src/store/reducer.ts
- src/store/saga.ts
- adds posts store saga, reducer and actions (sendPost, fetchPosts)
- adds test coverage
- separation of posts and messages
- this saga is not yet wired up
> feat(posts-saga): add posts store saga and actions

- src/components/messenger/feed/components/post/styles.module.scss
> fix: post width

- src/components/messenger/feed/feed-view-container/feed-view-container.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view-container.tsx
- src/components/messenger/feed/feed-view-container/feed-view.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view.tsx
- src/components/messenger/feed/feed-view-container/styles.scss
- src/components/messenger/feed/index.test.tsx
- src/components/messenger/feed/index.tsx
- src/components/messenger/feed/styles.scss
This refactor separates the MessengerFeed functionality by introducing a new FeedViewContainer, ensuring that component lifecycle methods like componentDidMount and componentDidUpdate are triggered only when necessary. This helps in improving performance and maintaining cleaner code structure.
The change is made to address performance issues and prevent unnecessary API calls triggered by the componentDidMount and componentDidUpdate methods. By moving the feed-specific logic to a dedicated container, we ensure that these methods are only called when the feed-related data needs to be fetched or updated, resulting in a more efficient and maintainable codebase.
- run ui > switch conversations and check network tab for messages request
1. …
> refactor(messenger-feed-container): add separate feed view container resolving unnecessary componentdidmount/didupdate triggers

- src/components/messenger/chat/index.tsx
- src/components/messenger/feed/feed-view-container/feed-view.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view.tsx
This PR refactors the FeedView component to conditionally render the Waypoint based on the content height relative to the viewport. Additionally, it updates the tests to cover this new behavior, ensuring that the Waypoint only triggers when the user scrolls and the content exceeds the viewport height.
The change addresses an issue where the Waypoint was being triggered immediately when there were only a few posts, causing unnecessary data fetching. By rendering the Waypoint only when needed, we improve performance and ensure that additional posts are fetched only when the user scrolls down to view more content.
> feat(feed-view): implement and test conditional waypoint rendering based on content height in feedview component

- src/components/messenger/feed/feed-view-container/feed-view-container.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view-container.tsx
This update prevents unnecessary post fetching in the FeedViewContainer when switching conversations if posts have already been loaded. It also enhances the component and its tests to ensure that data is only fetched when needed, improving performance and reducing redundant network requests.
We made this change to optimize performance by reducing unnecessary data fetching. This ensures that when users switch between conversations, previously loaded posts aren't fetched again, leading to a more efficient and faster user experience. Additionally, enhancing the tests ensures the reliability and correctness of the implemented logic.
> refactor(feed-view-container): prevent post fetches if posts have loaded when switching conversations, and enhance tests

- src/components/chat-view-container/chat-view.tsx
- improves the positioning of the chat skeleton when loading messages in a room
- improved UI/UX
BEFORE
AFTER
> refactor(chat-view): improve chat skeleton positioning when loading messages

- src/store/messages/saga.ts
- updates current user map with logic to include display sub handle (zid or wallet)
- map users subhandle to use in ui
> feat(local-users-map): update current user map with logic to include display sub handle (zid or wallet)

- src/components/messenger/feed/components/posts/index.tsx
- applies post sender display sub handle data to author prop/attribute to display zid or wallet address
- as per design requirement
- run ui > open social channel > check displaySubHandle (if one exists for user) as per screenshot below
> feat(posts): apply post sender display sub handle data to author prop/attribute to display zid or wallet address

- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- src/lib/chat/matrix-client.ts
- handles group management when conversation is a social channel, i.e. canEdit, canView, canAddMembers.
- updates required so group management is enabled for social channels.
- create a social channel and test group management controls.
> feat(group-management): update / handle group management for token gated social channels

- src/apps/messenger/Main.module.scss
- src/apps/messenger/Main.tsx
- src/components/messenger/chat/conversation-header/container.test.tsx
- src/components/messenger/chat/conversation-header/container.tsx
- src/components/messenger/chat/conversation-header/index.tsx
- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- src/components/messenger/chat/styles.scss
Header now spans the full length of the Messenger container
> feat: move conversation header higher up the DOM tree

- src/components/messenger/feed/index.tsx
- separation of chat and feed loading state when submitting messages and posts
- when submitting a chat message in a social channel, the 'post' loading state would also be triggered. This is bad UI/UX therefore we are ensuring we only check message send status specifically for post messages when sending a post.
- run UI > open/create social channel > send a chat message and check that the create a post submitting status is not rendered.
> fix(feed/chat): separation of chat and feed loading state when submitting messages and posts

- src/components/messenger/feed/components/post/index.tsx
- src/components/messenger/feed/components/post/styles.module.scss
- handles formatting of long body text to improve layout ui in Posts.
- sets post body text styles - white space and word break.
- to improve the UI for posts with long body text
- run UI > open/create social channel > create posts with long body text > check width of containers.
> feat(posts): handle formatting of long body text to improve layout ui

- src/components/messenger/feed/styles.scss
- aligns bottom of feed container with other sidekicks and chat containers 
- improved UI
- run UI > open/create social channel > check bottom alignment of containers 
> feat: align bottom of feed container with sidekicks and chat containers

- src/components/messenger/chat/index.tsx
- src/components/messenger/chat/styles.scss
- removes message input footer gradient and align container bottom
- improve ui
- run UI > check message input is aligned at the bottom with other containers
> refactor(messenger-chat-container): remove message input footer gradient and align container bottom

- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- disables edit group name if token gated chat
- improve ui
- run ui > create/open token gated chat > try editing group name
> feat(edit-conversation-panel): disable edit group name if token gated chat

- src/components/messenger/list/group-details-panel/group-type-dialog/index.tsx
- updates social channel group type text content
- removes (coming soon) because social channels are ready for release
> feat(group-type-dialog): update social channel group type text content

- src/components/messenger/feed/styles.scss
- remove min-width to allow space for right sidekick
> fix(messenger-feed): remove min-width to allow space for right sidekick

- package-lock.json
- package.json
- chore: bump version (`1.155.0`) -> (`1.156.0`)
> chore: bump version (`1.155.0`) -> (`1.156.0`)

- src/components/messenger/user-profile/account-management-panel/container.test.tsx
- src/components/messenger/user-profile/account-management-panel/container.tsx
- src/components/messenger/user-profile/account-management-panel/index.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- src/lib/feature-flags.ts
- src/lib/web3/rainbowkit/connect.tsx
- src/lib/web3/rainbowkit/connect.vitest.tsx
- src/store/web3/index.ts
Adds UI for supporting "Add Wallet", if a user has signed in via an email account. This is currently feature flagged under `enableAddWallets` key.
- User can click on `+ Add Wallet` button to link a new wallet
- If metamask is already connected, then just directly show the Modal (sc)
- otherwise, user is prompted to connect their wallet first, and then the modal is shown
- this also fixes some of the global state management using rainbowKit/connect. we weren't storing the `walletAddress`, and the `connectedId` correctly in our redux state before.
(Add wallets button)
(if wallet is already connected)
(if not, connect wallet first)
Follow ups
- Saga logic
- backend integration
> Support ability to Add a wallet to an email account (UI)

- src/components/messenger/user-profile/account-management-panel/container.test.tsx
- src/store/account-management/index.ts
- src/store/account-management/saga.test.ts
- src/store/account-management/saga.ts
Cleans up some code which is not needed anymore at the saga level.
> clean up saga logic for `WalletSelectModal`

- src/components/messenger/list/group-details-panel/group-type-dialog/index.tsx
- src/components/messenger/list/group-details-panel/group-type-menu/index.test.tsx
- src/components/messenger/list/group-details-panel/group-type-menu/index.tsx
- src/components/messenger/list/group-details-panel/index.tsx
- removes ability to create social group channel
- we are/will be restricting users from creating a social channel based on token gated access control rules for these types of groups.
> refactor(create-group-flow): remove ability to create social channel group

- package-lock.json
- package.json
- chore: bump version (`1.156.0`) -> (`1.157.0`)
> chore: bump version (`1.156.0`) -> (`1.157.0`)

- src/store/account-management/api.ts
- src/store/account-management/saga.test.ts
- src/store/account-management/saga.ts
If you add a new wallet, and your wallet has some zid's, then the backend now will set that user's "default zid", and return that in the response. This PR updates the saga logic to update the local redux state with that `ZID`. 
If none is present in the API response, then primary ZID is derived from the wallet address (eg. `0x64af...63fe`)
> Update user's primaryZID after adding new wallet

- src/components/messenger/user-profile/settings-panel/index.tsx
- src/components/messenger/user-profile/settings-panel/utils.test.ts
- src/components/messenger/user-profile/settings-panel/utils.ts
- src/main.scss
- src/store/background/index.ts
- src/utils.ts
- Add new Lights Out (Static) default background. Add option to Settings background dropdown menu on user profile settings panel. Add logic for selection and adjust existing logic to continue to handle static green particle background (but no longer as default).
- redesign task
- run UI > check default is lights out background > check settings panel to change background
https://github.com/user-attachments/assets/e3318707-0aca-43dc-9005-6db22b1975ac
> feat(redesign-background): add and wire up default lights out background and selection

- src/components/messenger/list/user-header/index.tsx
-  replace collapse/expand icons for user header
> refactor(user-header): replace collapse/expand icons

- src/components/messenger/feed/index.tsx
- src/components/messenger/feed/styles.scss
- fixes width when message loading for scrollbar hack
- UI error - quick fix for scrollbar hack until further improvements
> fix(posts-header): fix width when message loading for scrollbar hack

- package-lock.json
- package.json
- chore: bump version (`1.158.0`) -> (`1.159.0`)
> chore: bump version (`1.158.0`) -> (`1.159.0`)

- src/components/messenger/feed/components/post/index.tsx
- This fixes unnecessary image reloads and reduces redundant network requests by memoizing media rendering functions.
- To improve performance by preventing images from reloading on every render, reducing network overhead and enhancing user experience.
> fix(messenger-feed): resolve unnecessary image reloads by memoizing functions in media rendering

- src/components/messenger/feed/feed-view-container/feed-view.tsx
- src/components/messenger/feed/feed-view-container/styles.scss
- This ensures the Waypoint is properly visible and triggers the fetchMore function to load more posts in the feed view.
- The Waypoint was not triggering as expected due to insufficient DOM presence, causing posts to not load as the user scrolled to the bottom of the feed.
- check feed UI renders more posts when scrolling to bottom of fetched posts
> fix(messenger-feed): re-position and fix waypoint for visibility and trigger loading more posts in feed view

- src/main.scss
-  removes empty side space for 2560 x 1600 resolution
- as requested (n3o)
> feat(app-main): remove empty side space for 2560 x 1600 resolution

- package-lock.json
- package.json
- chore: bump version (`1.161.0`) -> (`1.162.0`)
> chore: bump version (`1.161.0`) -> (`1.162.0`)

- src/components/messenger/feed/styles.scss
- removes messenger feed right and left padding
- correct container spacing as per designs
> refactor(messenger-feed): remove inline padding

- src/components/messenger/feed/styles.scss
-  removes top stroke from messenger feed conversation header
> refactor(feed-header): remove top stroke

- src/apps/messenger/Main.module.scss
- src/components/messenger/feed/styles.scss
- adds media query to adjust max-width of messenger feed for 2560x1440 screen resolution
> feat(messenger-feed): add media query to adjust max-width of messenger feed for 2560x1440 screen resolution

- src/apps/messenger/Main.module.scss
- src/components/messenger/chat/styles.scss
- src/components/messenger/feed/styles.scss
- src/main.scss
- removes min height on media queries
- not required as causes issues by setting a min height, we don't need to be concerned with height
> refactor(media-queries): remove min height on media queries

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/types.ts
- src/store/rewards/api.ts
- src/store/rewards/index.ts
- src/store/rewards/saga.test.ts
- src/store/rewards/saga.ts
- This adds functionality to handle MEOW token 'transfers' between users, including API integration and state management in the frontend.
- We are implementing the ability for users to transfer MEOW tokens as part of the app's reward and interaction system.
- Note:: this is not yet wired up to UI
> feat(rewards): add meow transfer functionality with error handling and state management updates

- src/components/messenger/feed/components/post/index.tsx
- correctly disables the 'MEOW' action if users balance is not sufficient. 
- fix.
> fix(post-component): correctly disable ability to meow if the users balance is less than required amount

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/storage/idb.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- src/store/registration/api.ts
- src/store/registration/saga.test.ts
- src/store/registration/saga.ts
- src/store/test/store.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
Our cloudinary was recently disabled, so new image uploads (profile images, group icons) are failing now. This PR starts to shift image uploads of ZERO from cloudinary/s3 to our own homeserver. 
This PR handles profile Images during these 2 flows
- when a user edits their profile
- when a user registers for the first time (and uploads their profile image)
For the 2nd point, it had to be handled using indexed-db (which we're using as an image cache), because during the time of registration, the matrix client is not initialized and we cannot upload the image to the homeserver at that point of time. So, we're caching the image first, and when the user logs in, we then use the `matrixClient` to upload the image to the homeserver and then call ZERO-API (`editUserProfile`) to update the …
> Upload Profile Images to the (synapse) homeserver instead of cloudinary

- src/store/users/saga.test.ts
- src/store/users/saga.ts
When you search for users in the search bar, it fetches the users from the API which has the profileImage urls for each user. But since profileImages are uploaded to the homeserver now, those urls will be "authenticated". So we need to download them using the matrixClient.accessToken and then display those in the UI (after local downlaod)
> Display profile Images (avatar) for users displaying during global search

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
After a user edits their profile image, we update our API database with the updated profile image. This PR adds support to "also" update the matrixClient's profile :: `avatar_url`.
> Update matrix API `avatar_url` after editing a user profile (or during registration)

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.ts
- src/store/group-management/saga.test.ts
- src/store/group-management/saga.ts
When you're creating or editing the group profile picture, it uploads it to cloudinary. This PR migrates that upload method from cloudinary to the homeserver itself (since we've recently disabled our cloudinary account).
> Upload groupIcons to the homeserver instead of cloudinary

- src/lib/chat/matrix-client.ts
This adds a type check to ensure fileUrl is a string before proceeding with the download logic.
To prevent runtime errors when fileUrl is not a string and to handle unexpected input gracefully.
> fix(matrix-client): add type check for fileUrl in downloadFile method

- src/components/messenger/feed/feed-view-container/feed-view.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view.tsx
- src/components/messenger/feed/feed-view-container/styles.scss
- ensures fetch more posts is called by removing waypoint conditional height check restriction
- fix empty social channels where posts are not being fetched, potentially caused due to waypoint not working as expected, this attempts to fix the issue.
- run ui > open social channel > check posts are fetched and rendered if expected
> fix(feed-view-container): ensure fetch more posts is called by removing waypoint conditional height check restriction

- src/components/messenger/feed/feed-view-container/feed-view.test.tsx
- src/components/messenger/feed/feed-view-container/feed-view.tsx
- src/components/messenger/feed/feed-view-container/styles.scss
- when triggering fetching more posts, add loading state condition and render loading spinner
- improve ui / ux by indicating loading of fetching more posts
- run ui and load more posts on social channels
> feat(feed-view): handle loading state and add loading spinner to indicate more posts loading when triggering fetchMore on posts

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/media.ts
This PR handles the final piece of image migrations from cloudinary to our homeserver. We now upload the image messages to our homeserver, directly instead of uploading them to s3. 
We also ensure backwards compatibility, since the old messages (which were uploaded to s3), should also be visible.
> Upload image messages to the homeserver instead of s3

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/media.ts
When uploading new files (profileImage/groupIcon/image message), we're now uploading the `mxc://..` url directly now. This is because the Rust SDK (which the mobile app is using), is uploading image messages directly with the mxc urls.
> Upload `mxc://` urls instead of http via `matrixClient.uploadFile`

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
For compatibility with the rust SDK, which mobile is using
> add `{  h, w }` fields while uploading file

- src/apps/messenger/Main.tsx
- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- src/store/group-management/saga.ts
- opens secondary side kick by default if social channel
- as requested
- run ui and test by hitting social channel conversation id in url
> feat(group-management/chat-sagas): open secondary side kick by default if social channel

- src/lib/chat/matrix/chat-message.ts
- sends browser notifications when event is post event
- add notification for posts
> feat(posts/message-saga): send browser notifications when event is post event

- package-lock.json
- package.json
- chore: bump version (`1.169.0`) -> (`1.170.0`)
> chore: bump version (`1.169.0`) -> (`1.170.0`)

- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
After a user edits their profile Image, we save it in the API database. AND, we also call matrixClient to update the avatar_url in the user directory. This PR skips the latter for now.
This is because the `matrixEditProfile` call is spurring up a lot of events (like membership update, joins etc), which is causing the web client to process all these events. Which is impacting performance.
> do not edit matrix avatar_url during edit profile

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/feature-flags.ts
Reverts the change effectively to upload image messages to matrix. If you do want to send messages to matrix, use `postImageMessagesToMatrix` feature flag.
> add featureFlag (`postImageMessagesToMatrix`) to post image messages to matrix

- package-lock.json
- package.json
- chore: bump version (`1.172.0`) -> (`1.173.0`)
> chore: bump version (`1.172.0`) -> (`1.173.0`)

- src/store/channels-list/saga.ts
Stops the parsing of profile images if it is a cloudinary url (since we have removed that service). This is to prevent GET errors like this in the console:
> mute cloudinary urls

- src/store/messages/index.ts
- src/store/messages/saga.ts
- This change adds a downloadStatus to the media object to prevent repeated decryption attempts during re-renders.
- We are making this change to improve performance and avoid unnecessary processing by ensuring that failed or already processed media files are not re-attempted for decryption.
- run UI and check redux state - ensure that loadAttachmentDetails is not run on re-render
> feat(messages): add download status state to media object to prevent repeated decryption attempts on re-renders

- package-lock.json
- package.json
- chore: bump version (`1.174.0`) -> (`1.175.0`)
> chore: bump version (`1.174.0`) -> (`1.175.0`)

- package-lock.json
- package.json
- chore: bump version (`1.175.0`) -> (`1.176.0`)
> chore: bump version (`1.175.0`) -> (`1.176.0`)

- src/components/chat-view-container/chat-view.tsx
- src/lib/chat/chat-message.test.ts
- src/lib/chat/chat-message.ts
- handles reaction events sent from mobile device
- web does not currently handle the same reaction events as mobile. as a result this causes some undefined admin messages and preview on web, therefore these changes are made to handle these i.e. filter out the reaction message and add a basic preview message.
> feat(messenger-chat/conversation-previews): handle reaction events sent from mobile device

- package-lock.json
- package.json
- chore: bump version (`1.176.0`) -> (`1.177.0`)
> chore: bump version (`1.176.0`) -> (`1.177.0`)

- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/chat-view.tsx
- fixes issue so we correctly filter out reaction admin messages from chat
- we do not want to see admin messages in the messenger chat stating that a reaction has been made by a user, this should only render in the conversation list preview.
> fix(chat-view-container): correctly filter out reaction admin messages from chat

- package-lock.json
- package.json
- chore: bump version (`1.177.0`) -> (`1.178.0`)
> chore: bump version (`1.177.0`) -> (`1.178.0`)

- src/lib/chat/matrix-client.ts
- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
`spawns` the "edit profile" for the matrix user directory, when the user edits their profile image. We spawn it since it triggers a number of membership update events, which can be process in the bg.
> call matrix API to update profile `avatar_url` after edit profile

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/messages/saga.ts
- updates media (payload) handling for unencrypted rooms by ensuring Matrix URLs are processed and skipping unnecessary file decryption for non-encrypted media.
- payload update to work when receiving and sending to mobile devices, as a result some updates here required to handle the changes.
- run UI and send images in encrypted/non-encrypted rooms.
> feat(media): update media handling for unencrypted rooms

- src/components/messenger/feed/components/post/index.tsx
- updates media (payload) handling for unencrypted social channels by ensuring Matrix URLs are processed and skipping unnecessary file decryption for non-encrypted media.
- payload update
- run UI and send images in social channels
> feat(messenger-feed): update media handling on posts for unencrypted rooms

- src/lib/chat/matrix/chat-message.ts
This update ensures that the file name from image messages is not incorrectly displayed as the message content by filtering it out and setting the content to an empty string for image message types.
This change prevents unnecessary file names from being rendered as message text in the UI, ensuring that the message content is reserved for actual text and keeping the display cleaner.
- run UI > Check images received, they should not display file name in message body
> refactor(mapMatrixMessage): filter out file names from image messages and set message content to an empty string for image types

- package-lock.json
- package.json
- chore: bump version (`1.179.0`) -> (`1.180.0`)
> chore: bump version (`1.179.0`) -> (`1.180.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- src/store/channels-list/utils.ts
- src/store/users/saga.ts
Currently the new iOS app uploads `{ user_name, profileInfo }` to matrix, instead of the ZERO-API. So, the profile Image is not coming in from the API (always). 
This PR handles the case if we have a profile avatar_url from the matrix-client itself, and not just the ZERO-API.
> Parse `avatar_url` if it is stored in matrix user_directory (and not zero-api)

- src/lib/feature-flags.ts
- flips enable meows feature flag
- to enable the meowing feature for social channels
> refactor(feature-flags): flip enable meows feature flag

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
This update ensures that MessengerFeed and MessengerChat components are only rendered when a conversation is not in the process of being joined. It also simplifies the component's logic by reducing redundant checks and improving readability.
We are making this change to prevent inconsistent UI states by ensuring that users do not see the chat or feed components while a conversation is still being joined. The simplification also improves code maintainability and readability, reducing the risk of errors.
> fix(messenger-chat-container/main): only render messenger chat container when the conversation is valid and not joining (active)

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- src/store/chat/api.ts
Adds generic error handling to the joinRoom function to ensure that all errors, including server errors (e.g., 500), are handled gracefully by returning a consistent response.
To prevent the join room process from hanging when an unexpected error occurs, providing a better user experience and more reliable state management.
> fix(joining-conversation): add generic error handling to joinRoom to prevent hanging state on unexpected errors

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- src/lib/chat/matrix-client.ts
- src/store/chat/api.ts
Prevents rooms with a social channel type from being incorrectly mapped as one-on-one conversations, ensuring they are recognized as group conversations with appropriate group management features and correct room state.
To avoid incorrect UI behavior that occurs when social channels are treated as one-on-ones, which disrupts group management functionality such as adding/removing members and managing group settings.
> fix(matrix-client/tgc): prevent social channels from being mapped as one-on-ones to ensure proper room state

- src/lib/chat/chat-message.test.ts
- src/lib/chat/chat-message.ts
- add default fallback if event is not mapped to a message
- improves UI - fixes blank message preview
> feat(message-preview): add default fallback if event is not mapped to a message

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/types.ts
- src/store/edit-profile/saga.test.ts
- src/store/edit-profile/saga.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
Mobile is using matrix's user directory to show the displayname and avatar url, instead of the ZERO API. Earlier we had the user hash, instead of the display name in the matrix user profile, this PR updates that, for a new user created, or an existing one.
> Creating a new user, or editing an existing profile should update matrix user `displayname` as well (in user directory)

- src/components/messenger/group-management/container.test.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
Previously, profile avatars were not showing up during "global user search". This was because, for existing users, we have locally downloaded and saved the blob url, but the API was returning the mxc:// url, this PR updates the logic to map the `profileImage`/`image` key to local blob url, before displaying the search results in the frontend
> [Fix] Profile avatars not showing up during global user search

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
Previously we were downloading each image one by one while mapping all users in ZERO (conversations + messages). This PR updates this to download images in a batches of "15" each time (batch size limit is placed to avoid too much memory/bandwidth consumption)
> Batch download images during initial load

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
Downloads the thumbnails (in batches of 20 each), instead of the actual image to improve performance
> Download `thumbnails` of profile images during initial load

- package-lock.json
- package.json
- chore: bump version (`1.188.0`) -> (`1.189.0`)
> chore: bump version (`1.188.0`) -> (`1.189.0`)

- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
To improve initial load performance, we're now downloading and rendering profile avatars after initial load is complete (and user sees the conversations on the UI)
> Download profile avatar after initial load

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- removes 'click to download' functionality for media in active conversation
- ensures media is auto downloaded (calls loadAttachmentDetails) when conversation is active
- improve UI/UX as click to download adds additional clicks for user, unnecessarily.
> feat(media-messages): auto load attachement details when conversation is active

- src/store/channels-list/saga.ts
This change modifies how secondary conversation data (like member profile images and tags) is updated. Instead of overriding the entire conversation state, it selectively updates relevant parts of the data to prevent overriding previously loaded information. This helps maintain a more stable and consistent UI.
We're making this change to address UI flickering and inconsistencies caused by redundant updates that override previously fetched conversation data. By batching updates more efficiently, we ensure smoother rendering and reduce performance issues related to unnecessary state changes.
- run ui and check conversation state isn't overriding on load
Please note - …
> refactor(channels-list-saga): Optimize conversation secondary data state updates by batching secondary data loading to prevent UI flickering

- src/components/messenger/list/index.tsx
- src/lib/chat/matrix-client.ts
- unblocks join events 
- this also filters admin message previews
- issues with join events being skipped causing events to be missed
> fix(matrix-client/messenger-list): unblock member join events

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/chat/bus.ts
- src/store/messages/index.ts
- implements ability for sending and receiving emoji reaction events (matrix-client).
- to enable reactions on messages.
- Note :: this is not yet wired up to UI.
> feat(matrix-client): implement send emoji message reaction and get message emoji reactions

- src/lib/chat/matrix-client.ts
> up thumbnail resolution from `32 x 32` to `96 x 96` 

- src/store/messages/saga.fetch.test.ts
- src/store/messages/saga.receiveNewMessage.test.ts
- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
This change enhances the mapMessagesAndPreview function to include emoji reactions for each message. Specifically, it fetches reactions associated with messages in a channel and adds them to the corresponding message data, allowing reactions to be displayed properly.
We made this change to fix an issue where reactions were not being displayed on messages. By mapping and including reactions within the mapMessagesAndPreview function, messages now display their respective reactions, providing users with better interactivity and visibility of engagement in the chat.
- run ui > add reactions to a message > refresh and ensure reactions persist
> fix(map-reactions/message-saga): improve mapping of reactions to messages in by handling in mapMessagesAndPreview

- src/components/message/styles.scss
- removes blur from message bubble backgrounds and applies solid colour background to owners message bubble.
- faint lines were appearing on windows for the owners message bubble background. These changes fix those.
> fix(message): fix colour issue on owners message bubble background on windows

- src/store/users/saga.test.ts
- src/store/users/saga.ts
Fixes the bug where the matrix user displayname was not being updated to the "actual name". This was happening in the case if the user doesn't upload a profile image upon registration.
> Fix issue where displayname is not updated (via matrix sdk) upon registration

- package-lock.json
- package.json
- chore: bump version (`1.199.0`) -> (`1.200.0`)
> chore: bump version (`1.199.0`) -> (`1.200.0`)

- src/components/messenger/feed/index.test.tsx
- src/components/messenger/feed/index.tsx
- fixes inability to leave a social channel by implementing leave group dialog modal and functionality
- to be able to leave a social channel
- run UI and attempt to leave a social channel via the group management options
> fix(messenger-feed): fix and implement leave group dialog to leave a social channel

- src/components/notifications-feed/index.tsx
- src/lib/chat/matrix/chat-message.ts
- src/store/notifications/saga.ts
- fixes error when attempting to extract mentions from message content
- uses optional chaining
- prevent unwanted error
> fix(chat-message): update extractMentionsFromBody with optional chaining for matches to prevent unwanted error

- src/components/notifications-feed/notification-item/utils.test.ts
- src/components/notifications-feed/notification-item/utils.ts
- src/lib/chat/matrix/chat-message.ts
- removes outdated meow reaction system notifications
- meows and posts are no longer handled via the matrix events system therefore they need to be re-wired for notifications app.
> refactor(notifications-feed): remove outdated meow reaction system notifications

- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- processes notifications related to current user only
- to only display notification relevant to the current user, not all users
-  run UI, enable notifications app and check notification items
> refactor(matrix-client): process notifications related to current user only

- src/store/posts/saga.ts
- If `primaryZid` was `undefined`, it would throw `Cannot read properties of null (reading 'split')`, which is not helpful for the user.
> fix: `undefined` `primaryZid` handling

- src/components/messenger/feed/components/post-input/container.tsx
- src/components/messenger/feed/components/post-input/index.test.tsx
- src/components/messenger/feed/components/post-input/index.tsx
- src/store/login/saga.ts
If the user does not have a wallet connected to the UI, render a `Connect Wallet` button.
> feat: connect wallet button when posting

- src/components/messenger/feed/components/post-input/index.tsx
Removes ability to add files to social channel posts. This is not supported in the backend yet.
> fix: disable dropzone files

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/notifications/index.ts
- src/store/notifications/saga.test.ts
- src/store/notifications/saga.ts
This commit refactors the fetchNotifications saga to optimize the performance of notification fetching operations. It ensures that the saga correctly handles the mostRecentTimestamp to avoid unnecessary calls and improves error handling by ensuring that errors during the fetching process are properly caught and dispatched. Additionally, it combines existing notifications with new ones while removing duplicates, ensuring that the state is updated efficiently.
We are making this change to enhance the performance and reliability of the notification fetching process. By optimizing how notifications are retrieved and processed, we reduce unnecessary operations, which can lead to improved responsiveness in the application. Furthermore, better error handling ensures that users receive …
> refactor(fetch-and-get-notifications): optimize notification fetching and processing

- package-lock.json
- package.json
- chore: bump version (`1.206.0`) -> (`1.207.0`)
> chore: bump version (`1.206.0`) -> (`1.207.0`)

- src/components/notifications-feed/index.test.tsx
- src/components/notifications-feed/index.tsx
- src/components/notifications-feed/notification-item/index.tsx
- src/components/notifications-feed/notification-item/styles.module.scss
- src/components/notifications-feed/styles.module.scss
- src/components/reaction-menu/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/lib/feature-flags.ts
- src/store/notifications/index.ts
- src/store/notifications/saga.test.ts
- src/store/notifications/saga.ts
- tracks read and unread notifications
- to highlight to a user which notifications are yet to be considered as read or unread
- run ui, enable feature flag for notifications read status, check notifications.
> feat(notification-app): implement notification read/unread tracking system

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/platform-apps/channels/messages-menu/index.test.tsx
- src/platform-apps/channels/messages-menu/index.tsx
- src/store/messages/index.ts
What does this do?
Adds the ability to download media files (images, videos, etc.) directly from the message context menu in chat conversations.
Why are we making this change?
To improve user experience by providing an easy and intuitive way for users to save media content shared in conversations without having to open the media in a new tab or use browser-specific methods.
Run UI and right click image message to test
> feat(message-menu): add download functionality to message menu

- package-lock.json
- package.json
- chore: bump version (`1.210.0`) -> (`1.211.0`)
> chore: bump version (`1.210.0`) -> (`1.211.0`)

- src/components/messenger/feed/components/post/actions/meow/meow-action.module.scss
- Removes logic which disables `pointer-events` when user has already MEOW'd a post.
Note: this requires [API changes](https://github.com/zer0-os/zos-api/pull/130) to be merged.
> feat: allow click when already voted

- package-lock.json
- package.json
- Bumps minor version `1.211.0` -> `1.212.0`
> chore: bump minor `1.211.0` -> `1.212.0`

- package-lock.json
- package.json
- chore: bump version (`1.213.0`) -> (`1.214.0`)
> chore: bump version (`1.213.0`) -> (`1.214.0`)

- package-lock.json
- package.json
- chore: bump version (`1.214.0`) -> (`1.215.0`)
> chore: bump version (`1.214.0`) -> (`1.215.0`)

- package-lock.json
- package.json
- chore: bump version (`1.215.0`) -> (`1.216.0`)
> chore: bump version (`1.215.0`) -> (`1.216.0`)

- src/lib/feature-flags.ts
- Defaults `enableLoadMore` feature flag to `true`
> chore: `enableLoadMore` default to `true`

- package-lock.json
- package.json
- Bumps version from `1.216.0` to `1.217.0`
> chore: bump minor `1.216.0` -> `1.217.0`

- src/App.tsx
- src/components/app-bar/container.tsx
- src/components/app-bar/container.vitest.tsx
- src/components/app-bar/index.tsx
- src/components/app-bar/index.vitest.tsx
- src/components/app-bar/styles.scss
- src/components/notifications-feed/index.test.tsx
- src/components/notifications-feed/index.tsx
- src/components/notifications-feed/notification-item/index.tsx
- src/components/notifications-feed/notification-item/styles.module.scss
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- uses room unread count to process notifications
- refactors notification items and feed to align with unread count functionality
- better performance and simpler solution for notifications app
> feat(notifications): use room unread count to process notifications

- package-lock.json
- package.json
- chore: bump version (`1.217.0`) -> (`1.218.0`)
> chore: bump version (`1.217.0`) -> (`1.218.0`)

- package-lock.json
- package.json
- chore: bump version (`1.218.0`) -> (`1.219.0`)
> chore: bump version (`1.218.0`) -> (`1.219.0`)

- package-lock.json
- package.json
- chore: bump version (`1.219.0`) -> (`1.220.0`)
> chore: bump version (`1.219.0`) -> (`1.220.0`)

- src/store/posts/saga.ts
- removes receiveChannel from reset function
- to prevent interference with message state when opening conversations. this was causing messages to be removed from local state and then refetched, which had a significant impact on performance. refetching is not required.
> fix(posts-saga): remove receiveChannel from reset function to prevent interference with message state

- package-lock.json
- package.json
- chore: bump version (`1.221.0`) -> (`1.222.0`)
> chore: bump version (`1.221.0`) -> (`1.222.0`)

- src/store/channels/saga.ts
- src/store/posts/saga.ts
- implements start polling function and adds conditions to stop polling when polling channel is no longer active
- performance optimisations
- run UI and check polling starts/stops if social channel is active
> refactor(posts-saga): implement start polling function and conditions to stop polling when polling channel is no longer active

- src/components/chat-view-container/chat-view.tsx
- src/components/lightbox/index.tsx
- src/components/lightbox/styles.module.scss
-  improves z-index stacking and add stop propagation
- reports from users that they are unable to interact with the toolbar items in the lightbox and therefore unable to close, copy or download.
> refactor(lightbox): improve z-index stacking and add stop propagation

- package-lock.json
- package.json
- chore: bump version (`1.223.0`) -> (`1.224.0`)
> chore: bump version (`1.223.0`) -> (`1.224.0`)

- package-lock.json
- package.json
- chore: bump version (`1.225.0`) -> (`1.226.0`)
> chore: bump version (`1.225.0`) -> (`1.226.0`)

- src/components/chat-view-container/styles.scss
- adjusts the position of the waypoint entry in the chat view
- to begin fetching messages earlier when backwards scrolling through message history.
- attempt to make the scroll experience smoother
- run ui and backwards scroll
> refactor(chat-view-waypoint): adjust position of waypoint for earlier message fetching when scrolling

- src/components/message-input/index.test.tsx
- src/components/message-input/index.tsx
- src/components/message/index.tsx
- src/components/message/parent-message/index.test.tsx
- src/components/message/parent-message/index.tsx
- src/components/message/styles.scss
- src/components/reply-card/reply-card.test.tsx
- src/components/reply-card/reply-card.tsx
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.test.ts
- src/lib/chat/matrix/chat-message.ts
- Adds support for uploading and displaying video messages in chat.
- To provide a better user experience introducing functionality to share video content similar to how we handle images.
- run UI and send video file.
> feat(media-video): add send and receive video message support

- package-lock.json
- package.json
- chore: bump version (`1.227.0`) -> (`1.228.0`)
> chore: bump version (`1.227.0`) -> (`1.228.0`)

- package-lock.json
- package.json
- chore: bump version (`1.228.0`) -> (`1.229.0`)
> chore: bump version (`1.228.0`) -> (`1.229.0`)

- src/components/notifications-feed/index.test.tsx
- src/components/notifications-feed/index.tsx
- src/components/notifications-feed/styles.module.scss
- adds tabs and filter notifications
- to be able to switch between All, Highlights, Muted notifications
- run ui and check notifications app
> feat(notifications-app): add tabs and filter notifications

- package-lock.json
- package.json
- chore: bump version (`1.229.0`) -> (`1.230.0`)
> chore: bump version (`1.229.0`) -> (`1.230.0`)

- package-lock.json
- package.json
- chore: bump version (`1.230.0`) -> (`1.231.0`)
> chore: bump version (`1.230.0`) -> (`1.231.0`)

- package-lock.json
- package.json
- chore: bump version (`1.231.0`) -> (`1.232.0`)
> chore: bump version (`1.231.0`) -> (`1.232.0`)

- src/apps/app-router.tsx
- src/components/messenger/feed/components/comment-input/index.tsx
- src/components/messenger/feed/components/comment-input/styles.module.scss
- src/components/messenger/feed/components/comment-input/useCommentInput.ts
- src/components/messenger/feed/components/main-feed/index.tsx
- src/components/messenger/feed/components/main-feed/useMainFeed.ts
- src/components/messenger/feed/components/post-input/container.tsx
- src/components/messenger/feed/components/post-input/index.tsx
- src/components/messenger/feed/components/post/actions/reply/reply-action.module.scss
- src/components/messenger/feed/components/post/actions/reply/reply-action.tsx
- src/components/messenger/feed/components/post/actions/reply/useReplyAction.ts
- src/components/messenger/feed/components/post/index.tsx
- src/components/messenger/feed/components/post/styles.module.scss
- src/components/messenger/feed/components/posts/index.tsx
- src/components/messenger/feed/index.test.tsx
- src/components/messenger/feed/index.tsx
- src/components/messenger/feed/lib/useMeowPost.ts
- src/components/messenger/feed/post-view-container/back-button/index.tsx
- src/components/messenger/feed/post-view-container/back-button/styles.module.scss
- src/components/messenger/feed/post-view-container/index.tsx
- src/components/messenger/feed/post-view-container/reply-list/index.tsx
- src/components/messenger/feed/post-view-container/reply-list/styles.module.scss
- src/components/messenger/feed/post-view-container/reply-list/useReplyList.ts
- src/components/messenger/feed/post-view-container/styles.module.scss
- src/components/messenger/feed/post-view-container/usePostView.ts
- src/lib/feature-flags.ts
- src/lib/web3/rainbowkit/provider.tsx
- src/store/posts/index.ts
- src/store/posts/saga.ts
- src/store/posts/utils.ts
- Adds the ability to comment on posts.
> feat: comment on posts

- package-lock.json
- package.json
- chore: bump version (`1.232.0`) -> (`1.233.0`)
> chore: bump version (`1.232.0`) -> (`1.233.0`)

- src/lib/feature-flags.ts
- Sets `enableComments` feature flag to `true`.
- It doesn't remove the feature flag in case we need to disable comments at some point in the near future.
> chore: `enableComments` flag default to `true`

- package-lock.json
- package.json
- Bumps minor version `1.233.0` -> `1.234.0`
> chore: bump version (`1.233.0` -> `1.234.0`)

- src/components/reaction-menu/index.tsx
Adds debug logging to track the reaction click flow and ensures click events don't bubble up to parent elements by using stopPropagation() in the reaction menu click handlers.
To diagnose why reaction clicks sometimes fail to register (requiring page refresh) by tracking the execution flow through console logs, while preventing potential event bubbling issues that could cause clicks to be intercepted by parent elements before reaching their intended handlers.
- run ui and use reactions
> refactor(reactions): add stop propagation and error logs to reaction selection

- package-lock.json
- package.json
- chore: bump version (`1.234.0`) -> (`1.235.0`)
> chore: bump version (`1.234.0`) -> (`1.235.0`)

- src/components/app-bar/index.tsx
- src/components/messenger/list/index.tsx
- src/lib/chat/chat-message.test.ts
- src/lib/chat/chat-message.ts
- removes prefix for one on one conversations
- run UI and check conversation item of one on one conversations
> refactor(conversation-item): remove prefix for one on one conversations

- package-lock.json
- package.json
- chore: bump version (`1.235.0`) -> (`1.236.0`)
> chore: bump version (`1.235.0`) -> (`1.236.0`)

- src/components/account-locked-dialog/container.test.tsx
- src/components/account-locked-dialog/container.tsx
- src/components/account-locked-dialog/index.test.tsx
- src/components/account-locked-dialog/index.tsx
- adds account locked dialog (container and component)
- To display modal dialog indicating to the user their account is locked when the account locked matrix error is thrown on login/initialization
- this container and component is not yet wired up to the ui (dialog manager), this will come in a follow up PR
> feat(dialogs): add account locked dialog

- src/components/attachment-preview-modal/index.test.tsx
- src/components/attachment-preview-modal/index.tsx
- src/components/attachment-preview-modal/styles.scss
- adds attachment preview modal component
- to render previews for certain file types
- this is not yet wired up to the UI but you can see the screenshot below of the component.
No Preview Available due to type:
Preview Available:
> feat(attachment-preview-modal): add attachment preview modal component

- src/components/message-input/index.test.tsx
- src/components/message-input/index.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/store/messages/uploadable.test.ts
- src/store/messages/uploadable.ts
- src/store/messages/utils.ts
- send/receive pdf files and display preview
- to be able to display preview and download pdf files (from messages).
- run UI and send a pdf file as a message
> feat(upload-file): add send and receive pdf file message support

- package-lock.json
- package.json
- chore: bump version (`1.237.0`) -> (`1.238.0`)
> chore: bump version (`1.237.0`) -> (`1.238.0`)

- package-lock.json
- package.json
- chore: bump version (`1.238.0`) -> (`1.239.0`)
> chore: bump version (`1.238.0`) -> (`1.239.0`)

- src/components/chat-view-container/chat-view.tsx
- src/components/message/index.test.tsx
- src/components/message/index.tsx
- We're modifying the Message component's renderMedia method to only trigger media downloads after messages have been successfully fetched. This is done by adding a check for messagesFetchStatus === MessagesFetchState.SUCCESS before calling loadAttachmentDetails.
- Currently, media attachments are being downloaded twice due to the interaction between message fetching and media loading. The first download occurs during initial render, and a second download is triggered when messages are re-fetched. This causes unnecessary network requests and potential performance issues. By waiting for messages to be fully fetched before initiating media downloads, we eliminate the redundant downloads while maintaining all functionality.
- run UI and render conversations with media …
> fix(media): prevent duplicate media downloads by checking message fetch status

- package-lock.json
- package.json
- chore: bump version (`1.239.0`) -> (`1.240.0`)
> chore: bump version (`1.239.0`) -> (`1.240.0`)

- src/components/message-input/emoji-picker/styles.scss
- src/components/message/index.tsx
- src/components/reaction-menu/index.tsx
- src/components/reaction-menu/styles.scss
- removes the common reaction tray
- immediately opens the emoji picker instead
- reported issues with the common reaction tray
- run UI and select the heart icon trigger when hovering over a menu to open the emoji picker
> refactor: replace reaction tray and directly open the emoji picker 

- package-lock.json
- package.json
- chore: bump version (`1.240.0`) -> (`1.241.0`)
> chore: bump version (`1.240.0`) -> (`1.241.0`)

- src/components/app-bar/styles.scss
- src/components/messenger/list/conversation-item/conversation-item.scss
- src/components/notifications-feed/notification-item/styles.module.scss
- update highlight colors
- run ui and check colours as shown below
> refactor(unread-highlights): update highlight color

- src/components/message/styles.scss
- src/components/reaction-menu/styles.scss
- increases reaction menu emoji picker z-index
- anchor component relative to menu item
- fix issue where users are reporting emojis can't be selected
- run ui as usual and test reactions
> refactor: increase reaction menu emoji picker z-index and anchor component relative to menu item

- package-lock.json
- package.json
- chore: bump version (`1.244.0`) -> (`1.245.0`)
> chore: bump version (`1.244.0`) -> (`1.245.0`)

- package-lock.json
- package.json
- chore: bump version (`1.245.0`) -> (`1.246.0`)
> chore: bump version (`1.245.0`) -> (`1.246.0`)

- package-lock.json
- package.json
- chore: bump version (`1.246.0`) -> (`1.247.0`)
> chore: bump version (`1.246.0`) -> (`1.247.0`)

- package-lock.json
- package.json
- chore: bump version (`1.247.0`) -> (`1.248.0`)
> chore: bump version (`1.247.0`) -> (`1.248.0`)

- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/index.test.tsx
- src/components/messenger/group-management/index.tsx
- prevent name editing for social channels instead of 0:// prefix check
> refactor: prevent name editing for social channels instead of 0:// prefix check

- package-lock.json
- package.json
- chore: bump version (`1.248.0`) -> (`1.249.0`)
> chore: bump version (`1.248.0`) -> (`1.249.0`)

- package-lock.json
- package.json
- chore: bump version (`1.249.0`) -> (`1.250.0`)
> chore: bump version (`1.249.0`) -> (`1.250.0`)

- src/components/messenger/user-profile/container.tsx
- src/components/messenger/user-profile/index.test.tsx
- src/components/messenger/user-profile/index.tsx
- src/components/messenger/user-profile/linked-accounts-panel/container.test.tsx
- src/components/messenger/user-profile/linked-accounts-panel/container.tsx
- src/components/messenger/user-profile/linked-accounts-panel/index.test.tsx
- src/components/messenger/user-profile/linked-accounts-panel/index.tsx
- src/components/messenger/user-profile/linked-accounts-panel/styles.scss
- src/components/messenger/user-profile/overview-panel/index.test.tsx
- src/components/messenger/user-profile/overview-panel/index.tsx
- src/config.ts
- src/lib/feature-flags.ts
- src/store/user-profile/index.ts
- src/store/user-profile/saga.test.ts
- src/store/user-profile/saga.ts
- adds linked accounts panel 
- adds telegram bridge setup (create conversation with telegram bot user)
- to be able to link telegram accounts (bridging)
- this is currently under featureFlag - enableLinkedAccounts
> feat(user-profile): add linked accounts panel and telegram bridge setup

- package-lock.json
- package.json
- chore: bump version (`1.251.0`) -> (`1.252.0`)
> chore: bump version (`1.251.0`) -> (`1.252.0`)

- src/lib/last-conversation.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- src/store/channels/saga.ts
The implementation adds localStorage persistence to remember and restore the last active conversation when navigating between apps, while maintaining existing conversation management behaviors for user actions like leaving rooms or logging out.
Improve UX
> feat: restore last active conversation when returning to messenger

- package-lock.json
- package.json
- chore: bump version (`1.256.0`) -> (`1.257.0`)
> chore: bump version (`1.256.0`) -> (`1.257.0`)

- package-lock.json
- package.json
- chore: bump version (`1.257.0`) -> (`1.258.0`)
> chore: bump version (`1.257.0`) -> (`1.258.0`)

- package-lock.json
- package.json
- chore: bump version (`1.258.0`) -> (`1.259.0`)
> chore: bump version (`1.258.0`) -> (`1.259.0`)

- .env.example
- package-lock.json
- package.json
- src/apps/messenger/Main.test.tsx
- src/apps/messenger/messenger-main.test.tsx
- src/components/messenger/user-profile/account-management-panel/container.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- src/components/messenger/user-profile/index.test.tsx
- src/components/sidekick/index.test.tsx
- src/config.ts
- src/lib/feature-flags.ts
- src/lib/web3/thirdweb/client.ts
- src/store/reducer.ts
- src/store/saga.ts
- src/store/thirdweb/account-manager.ts
- src/store/thirdweb/api.ts
- src/store/thirdweb/index.ts
- src/store/thirdweb/saga.ts
This PR adds support for Account Abstraction Wallets (aka thirdweb wallets). This is currently feature flagged under `enableAccountAbstraction` flag. If enabled, when the user reloads (or logs in), 
- a new AA wallet will be created, and saved in the backend
Now, when the next time user reloads or logsIn, that same AA wallet will be fetched/initialized.
> [Account Abstraction] Thirdweb Wallet initialization

- package-lock.json
- package.json
- chore: bump version (`1.268.0`) -> (`1.269.0`)
> chore: bump version (`1.268.0`) -> (`1.269.0`)

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- adds room id to alias (zid) conversion using matrix get room local aliases
- to be able to get the alias (zid) of the room from id 
> feat(matrix-client): add room id to alias (zid) conversion using matrix get room local aliases

- src/components/messenger/conversation-actions/container.test.tsx
- src/components/messenger/conversation-actions/container.tsx
- disables group management actions for social channels
- prevent users being added, leaving or edited on social channels (if the user was somehow able to render the conversation in messenger app, which in a follow up should not be possible).
> feat(messenger/conversation-actions): disable group management actions for social channels

- src/apps/feed/components/feed-chat/index.tsx
- src/components/messenger/lib/utils.tsx
- add replies, remove replies, typing indicators and prevent empty message sending in the Feed Chat
> feat(feed-chat): add replies and typing indicators

- package-lock.json
- package.json
- chore: bump version (`1.274.0`) -> (`1.275.0`)
> chore: bump version (`1.274.0`) -> (`1.275.0`)

- src/App.tsx
- src/apps/feed/components/feed-chat/index.tsx
- src/components/app-bar/container.tsx
- src/components/app-bar/container.vitest.tsx
- src/store/channels/saga.ts
- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- Moves App Bar notification count state to App Bar (prevents re-rendering the whole app).
- Adds `isFeedApp` to "mark as read" conditional in Matrix client.
- Calls "mark as read" whenever a chat is validated (i.e. when it's opened).
> fix: unable to mark channel chat notifications as read

- package-lock.json
- package.json
- chore: bump version (`1.275.0` -> (`1.276.0`)
> chore: bump version (`1.275.0` -> (`1.276.0`)

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- only shows joining dialog when joining new conversations
- only show joining dialog is active conversation is not valid
- incorrectly displaying joining dialog
> fix: only show joining dialog when joining new conversations and conversation is not yet valid

- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- Added path checking in performValidateActiveConversation saga to detect if we're in messenger app, and if so, redirect to last active conversation when attempting to open a social channel.
- To prevent social channels from being opened in messenger app since they should only be viewed in the feed app, while maintaining a smooth user experience by showing their last active messenger conversation instead.
- run ui and test
> fix: redirect to last active conversation when social channel opened in messenger

- package-lock.json
- package.json
- chore: bump version (`1.279.0`) -> (`1.280.0`)
> chore: bump version (`1.279.0`) -> (`1.280.0`)

- src/apps/feed/components/feed-chat/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/types.ts
- src/store/messages/saga.send.test.ts
- src/store/messages/saga.ts
Updates the `sendMessage` logic to also include the channel type (if it is a social channel or not). If yes, then we pass on this info to `recordMessageSent` fn, which calls the respective API to record that event.
This is done so that in the rewards calculation, we can filter out the users who have sent messages in social channels.
> Trigger `recordMessageSent` with `type == 'social'` in a social (token gated) channel

- src/components/sidekick/variants/members-sidekick.module.scss
- src/components/sidekick/variants/members-sidekick.tsx
- fixes scroll on secondary sidekick panels
- bug reported
- run ui and test scroll on secondary sidekick panels
> fix(members-sidekick): fix scroll on secondary sidekick panels

- src/components/messenger/list/create-conversation-panel/create-conversation-panel.scss
- src/components/messenger/list/create-conversation-panel/index.tsx
-  fix scrollable container on for the searched members on the create conversation panel
- UX improvements (bug fix)
- run UI and check searched members in create conversation panel are scrollable
> fix(create-conversation-panel): fix scrollable container

- package-lock.json
- package.json
- chore: bump version (`1.282.0`) -> (`1.283.0`)
> chore: bump version (`1.282.0`) -> (`1.283.0`)

- src/lib/chat/matrix-client.ts
- push empty rule actions array when muting
- fixes getting correct muted rooms on initial load and real time tracking 
> fix(matrix-client): push empty rule actions array when muting

- src/components/notifications-feed/index.test.tsx
- src/components/notifications-feed/index.tsx
- src/components/notifications-feed/index.vitest.tsx
- removes muted tab from notifications app
- muted rooms no longer have tracking for unread notifications so the muted tab is no longer required
> refactor(notifications-app): remove muted tab from notifications app

- src/apps/feed/components/sidekick/index.tsx
- src/apps/feed/components/sidekick/lib/selectors.ts
- src/apps/feed/components/sidekick/lib/useSidekick.ts
- src/apps/feed/components/sidekick/styles.module.scss
- src/components/app-bar/container.tsx
- src/components/messenger/conversation-actions/container.tsx
- src/components/messenger/list/conversation-item/index.test.tsx
- src/components/messenger/list/conversation-item/index.tsx
- src/components/notifications-feed/index.test.tsx
- src/components/notifications-feed/index.tsx
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/channels/index.ts
- src/store/channels/saga.test.ts
- src/store/channels/saga.ts
- src/store/chat/bus.ts
- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
> Revert "feat: rebuild muting/unmuting room functionality using matrix push rules"

- src/apps/feed/components/sidekick/index.tsx
- src/apps/feed/components/sidekick/styles.module.scss
- display unread count on muted zids in the channel zid list
- display unread count and mute icon on unread channel zid list 
> feat(channel-zid-list): display unread count on muted zids in the channel zid list

- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- Implements a task cancellation mechanism in the conversation validation process to prevent race conditions when users navigate between conversations quickly.
- To fix a bug where the active conversation ID could be incorrectly set when a user navigates away from a conversation before validation completes, causing UI inconsistencies between the URL and displayed conversation.
- run UI and navigate between channels and messenger app to test correct room content is rendered
> fix(chat-saga/chat-state): handle race condition in conversation validation by cancelling previous tasks

- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- Adding a path consistency check in the conversation validation process to ensure the active conversation ID is only updated if the user hasn't navigated away.
- To fix a bug where rapidly navigating between conversations could cause UI inconsistencies between the URL and displayed conversation content.
- run ui and navigate between channel and messenger apps
> fix(chat-saga/redux-state): handle race condition in conversation validation by checking URL path before setting active conversation

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
- We're eliminating network requests for room tags by accessing the data directly from Room objects already in memory.
- To significantly improve initial load performance by removing unnecessary network requests and making room tags immediately available during conversation loading.
- run the UI, monitor initial load of the app
> refactor(matrix-client): optimize room tags fetching by using in-memory data instead of network requests

- README.md
Updating the readme to include some missing info and to correct some outdated info.
To make onboarding to the repo a bit smoother
> Updating the readme for smoother onboarding to the repo

- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- spawns marking conversations as read when validating conversations
- improve performance of app by running read receipts in background
> refactor(chat-saga): create detached task for marking conversations as read when performing validation

- src/apps/feed/components/sidekick/lib/selectors.ts
- src/components/app-bar/container.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/list/index.tsx
- src/components/messenger/user-profile/linked-accounts-panel/container.tsx
- src/components/notifications-feed/index.tsx
- src/store/channels-list/selectors.ts
> Revert "refactor(components): implement memoized selectors for denormalized conversations"

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
We are modifying the rendering logic of the MembersSidekick component to ensure it is only rendered when the isSecondarySidekickOpen flag is true.
This change is being made to improve the application's performance by reducing unnecessary DOM elements and memory usage when the MembersSidekick is not visible.
- run ui and check element tab in dev tools doesn't show the secondary sidekick container
> refactor(messenger-main): reduce unnecessary DOM elements by conditionally rendering MembersSidekick to improve performance

- src/lib/storage/clear-idb.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- run additional index db storage clearance
- to ensure index db storage is cleared when terminating (log out)
> feat(terminate): run additional index db storage clearance

- src/lib/chat/session-storage.ts
- src/store/authentication/saga.ts
- src/store/rewards/saga.ts
- clears remaining user/session specific storage
- ensures storage is cleared to prevent log out / log in issues between different users on the same device.
> refactor(clear-storage): clear remaining user/session specific storage

- src/components/chat-view-container/chat-view.tsx
- Pre-computing message ownership checks in the renderMessageGroup method to avoid redundant calculations during render.
- To improve rendering performance by reducing redundant function calls when displaying messages, especially in conversations with many messages.
> refactor(chat-view): optimize message rendering by pre-computing ownership checks

- src/index.tsx
- src/pages/error/error-component.tsx
- src/pages/error/error-container.tsx
- src/pages/error/error.scss
- src/pages/error/index.ts
- src/pages/index.ts
- src/store/authentication/api.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- src/store/page-load/saga.test.ts
- src/store/page-load/saga.ts
Adds error page.
Sends the user to the error page if there is a failure getting the current user that isn't a 401
Currently if there is an error fetching the user, we show the user as logged out. There are times where this can be inaccurate and cause users to log back in when they just need to retry.
Go to the site incognito and make sure you end up on the login page (401 for getting current user)
Block current user request in network tab then refresh, you should end up on error page.
> Add error page and and re-direct user fetch errors

- src/components/waypoint/index.test.tsx
- src/components/waypoint/index.tsx
- We're creating a custom Waypoint component that wraps the react-waypoint library to defer callback execution to the next animation frame.
- To improve scrolling performance by preventing layout thrashing and UI jank when waypoint callbacks trigger state updates or data fetching operations during scroll events.
- note this is not yet wired up / replacing existing way point imports from react-waypoint
> feat(waypoint-wrapper): add waypoint component that wraps react-waypoint with requestAnimationFrame

- src/apps/feed/components/feed-view-container/feed-view.test.tsx
- src/apps/feed/components/feed-view-container/feed-view.tsx
- src/apps/feed/components/feed/index.tsx
- src/apps/feed/components/post-view-container/reply-list/index.tsx
- src/components/chat-view-container/chat-view.test.tsx
- src/components/chat-view-container/chat-view.tsx
- replaces existing react waypoint imports for the custom waypoint wrapper imports
- to use the new custom waypoint wrapper with requestAnimationFrame
- run ui and test scroll / waypoints
> refactor(waypoints): replace existing waypoint imports with custom waypoint wrapper imports that use requestAnimationFrame

- src/apps/feed/components/post-input/index.tsx
- src/components/autocomplete-dropdown/index.tsx
- src/components/inverted-scroll/index.tsx
- src/components/message/index.tsx
- We're wrapping DOM manipulation operations in requestAnimationFrame calls to defer them to the browser's next paint cycle.
- To improve UI responsiveness and scrolling performance by preventing layout thrashing and ensuring DOM operations happen at optimal times in the rendering pipeline.
- run ui as usual and interact
> refactor: optimize DOM operations with requestAnimationFrame for smoother UI performance

- src/components/app-bar/index.tsx
- src/components/app-bar/index.vitest.tsx
- We're replacing direct DOM manipulation and forced reflow with requestAnimationFrame in the AppBar component's unhoverContainer method.
- To improve UI performance by eliminating forced synchronous layout operations and allowing the browser to optimize rendering, resulting in smoother animations and reduced jank.
- hover over the app bar and test out ui
> refactor(app-bar): optimize hover behavior with requestAnimationFrame to eliminate forced synchronous layout operations

- src/apps/feed/components/sidekick/index.tsx
- src/apps/feed/index.tsx
- src/lib/last-feed.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- restores last active feed (channel) when returning to channels app
- improved ux/desired functionality
- run the UI, navigate to channels app, select a channel, navigate to another app, return to channels app and check active channel
> feat(channel-app): restore last active feed (channel) when returning to channels app

- src/apps/feed/components/feed-chat/container.tsx
- We're making this change to ensure users can only access chat functionality for ZIDs they own, improving security and preventing unauthorized access to chat features.
- We're adding a conditional check in the FeedChat component that verifies if the current ZID is in the user's list of owned ZIDs before rendering the chat interface.
- run ui and test scenario
> feat(feed-chat): only render FeedChat for ZIDs owned by the user

- src/components/app-bar/container.tsx
- src/components/app-bar/index.tsx
- src/components/app-bar/index.vitest.tsx
- src/lib/last-conversation.ts
- We're updating the AppBar component to handle cases where no last active conversation ID is available by redirecting to the root path instead of an invalid URL.
- To prevent users from being directed to an invalid URL like /conversation/null when no last conversation exists, ensuring a better user experience by leveraging the app's existing fallback logic.
> fix(app-bar): messenger link to handle missing conversation id

- src/store/chat/saga.ts
- We're adding a debounce effect to the ValidateFeedChat action to prevent multiple validation calls when navigating to the feed app.
- To improve performance by preventing unnecessary duplicate API calls that occur when components mount or update in quick succession.
> refactor(chat-saga): add debounce to feed chat validation to prevent duplicate API calls

- craco.config.js
- src/lib/feature-flags.ts
- src/lib/feature-flags/development.ts
- src/lib/feature-flags/flags.ts
- src/lib/feature-flags/production.ts
This adds a few new features to the feature flag system and makes it a bit easier to maintain.
- Flags can now be controlled separately in development vs production
- Flags can be locked, preventing tampering in the console
- Flags can be restricted to individual users
- Flags with this restriction are considered locked
- Flags can be reset to their defaults with `FEATURES_FLAGS.reset()`
This should allow us more control over rolling out new features.
For instance, we can enable something that only the team can test out internally for a while before going to staging, and then production.
Locking flag
```
{ enableFeedChat: { defaultValue: true, locked: true } }
```
Enabled for specific users
```
{ enableFeedChat: { defaultValue: true, allowedUserIds: ['12345'] } }
```
I kept all of the …
> feat: Add new functionality to feature flag system

- src/lib/chat/matrix-client.test.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/media.ts
- src/lib/storage/clear-idb.ts
- src/lib/storage/media-cache/browser-cache.ts
- src/lib/storage/media-cache/idb.ts
- src/lib/storage/media-cache/index.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
- src/store/messages/saga.ts
- src/store/registration/saga.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
- Puts the downloaded images to a cache (browser cache API + indexedDB), for faster retrieval later.
- When the user reloads, it will fetch it from cache first, and if found, it will be returned. This should help in better reload times.
- Also added a `cleanUp` function to run a clearance script every 2 hours, this will refresh the cache i.e get rid of older entries which haven't been accessed since the last "2 days".
> Add caching to images

- src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
- src/components/messenger/list/conversation-list-panel/index.test.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- Adding infinite scroll pagination to the conversation list panel to improve performance by loading conversations in batches.
- To reduce DOM rendering and improve UI performance when dealing with large numbers of conversations.
- run UI and scroll inside the conversation list panel > check elements tab in the dev tools to confirm 20 conversation list items on initial load & then when loading more
> feat(conversation-list-panel): add infinite scroll pagination to conversation list for improved performance

- src/components/layout/panel/styles.module.scss
- Replacing the non-standard writing-mode: sideways-lr with standard CSS properties (writing-mode: vertical-lr and transform: rotate(180deg)).
- To fix an invalid property value error in Electron and ensure consistent rendering across all browsers and platforms.
- run ui and check position of panel header when collapsed 
Solution:
> fix(panel-layout): replace sideways-lr with vertical-lr and transform for better cross-browser compatibility

- src/apps/app-router.module.css
- src/apps/app-router.tsx
The sidekick breaks if it's unmounted due to how the content portal works.
We'll now hide it instead of unmount it when it's not relevant.
A more permanent fix could be to use a ref instead of a query selector, but that'd be a minor refactor
Currently broken when switching to zApp and back to an app that has the sidekick
Go to explorer, then back to chat. Sidekick should render properly
> Fix: Fixes the sidekick breaking if it is unmounted.

- src/lib/feature-flags/production.ts
Fixes the user ids to be correct. I was getting them from the wrong location before
> Fix user ids for aura feature flag

- src/lib/feature-flags/production.ts
Fix an incorrect user id for aura flag
> Fix: Incorrect user id for feature flag

- src/lib/chat/matrix-client.ts
One of the reasons we're getting lots of 503's could be due to sync timing out on the homeserver (attached sc)
Heroku by default has a 30s timeout which returns as 503. This is the same as our sync timeout. Basically, before the sync times out, i think heroku is timing out the request (`code=H12` on logs) and returning 503.
This PR reduces our matrix timeout from 30s to 25s to avoid this.
> Reduce matrix `/sync` timeout from `30s` to `25s`

- src/components/messenger/group-management/view-members-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- src/components/messenger/group-management/view-members-panel/styles.scss
- Adding infinite scroll pagination to the ViewMembersPanel to improve performance by loading members in batches.
- To reduce DOM rendering and improve UI performance when dealing with large groups that have many members.
- run UI and open members panel > you can check the element tab in dev tools to see that up to 20 members are initially rendered in DOM before scrolling and entering waypoint
> feat(view-members-panel): add infinite scroll pagination to member list for improved performance

- src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
- src/components/messenger/group-management/edit-conversation-panel/index.tsx
- src/components/messenger/group-management/edit-conversation-panel/styles.scss
- Adding infinite scroll pagination to the EditConversationPanel to improve performance by loading members in batches.
- To reduce DOM rendering and improve UI performance when editing groups with many members.
- run UI > navigate to the edit conversation panel and check elements tab for number of members and scroll to check waypoint on enter is triggered to load more members
> feat(edit-conversation-panel): add infinite scroll pagination to edit conversation panel for improved performance

- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.tsx
- src/components/messenger/group-management/view-group-information-panel/styles.scss
- Adding infinite scroll pagination to the ViewGroupInformationPanel to improve performance by loading members in batches.
- To reduce DOM rendering and improve UI performance when viewing group information with many members.
- run UI > navigate to view group info panel and check element tab on dev tools for number of members before and after scrolling & triggering load more members via waypoint component
> feat(view-group-information-panel): add infinite scroll pagination to group information panel for improved performance

- src/components/messenger/list/user-search-results/index.test.tsx
- src/components/messenger/list/user-search-results/index.tsx
- src/components/messenger/list/user-search-results/user-search-results.scss
- Adding infinite scroll pagination to the UserSearchResults component to improve performance by loading search results in batches.
- To reduce DOM rendering and improve UI responsiveness when searching for users with common patterns that return many results
- run UI > search results and check elements tab on dev tools to ensure only PAGE_LIMIT amount of search results are in visible in DOM
> feat(user-search-results): add infinite scroll pagination to user search results for improved performance

- src/components/messenger/autocomplete-members/index.test.tsx
- src/components/messenger/autocomplete-members/index.tsx
- src/components/messenger/autocomplete-members/styles.scss
- Adding infinite scroll pagination to the AutocompleteMembers component to load search results in batches of 20 instead of all at once.
- To improve performance and reduce DOM rendering when searching for users with common patterns that might return many results, providing a consistent user experience with other list components in the application.
- run UI and navigate to Add Members Panels / Create Conversation Panel > open dev tools Element tab and check only 20 results are in the DOM prior to scrolling and triggering waypoint get more results
> feat(autocomplete-members): add infinite scroll pagination to autocomplete members for add members and create conversation panels

- src/components/messenger/user-profile/overview-panel/rewards-item/styles.scss
- src/components/messenger/user-profile/overview-panel/styles.scss
- saves space on the overview panel 
- removes need for user to scroll to see all profile options
- run UI > navigate to user profile (top left avatar) > check no need to scroll to see all options
> refactor(user-profile/overview-panel): save space on panels to remove need to scroll

- src/apps/app-router.tsx
- We're conditionally rendering the sidekick space placeholder only when the active ZApp is not fullscreen.
- To ensure fullscreen ZApps can utilize the entire screen width without unnecessary spacing on large displays (2561px and above).
- run ui > navigate to fullscreen zapps (aura) > check element tab doesn't contain sidekickSpace element
> feat(app-router): remove temporary sidekick space rendering for fullscreen zapps

- src/apps/iframe/index.tsx
- src/apps/iframe/index.vitest.tsx
- src/apps/iframe/styles.scss
- We're adding responsive styling for fullscreen iframes that displays them in a contained, centered view on large screens (2561px+) while maintaining full-screen behavior on smaller displays.
- To improve the user experience on large displays by presenting fullscreen ZApps in a more visually appealing, contained format rather than stretching them across the entire screen.
- Note :: not yet wired up to fullscreen zapps - check commit history for follow ups
> feat(iframe): implement responsive fullscreen iframe styling for large displays

- src/apps/external-app/index.tsx
- src/apps/external-app/index.vitest.tsx
- We're adding support for the fullscreen feature in external apps by passing the isFullscreen prop to the IFrame component based on the app's manifest.
- To allow external apps to specify a fullscreen mode that changes the layout and appearance of the app within zOS, providing a better user experience for apps that need more screen real estate.
- run UI and check fullscreen styles are applied to fullscreen zapps using iframe
> feat(external-app): add support for iframe fullscreen feature in external apps

- src/components/messenger/group-management/container.tsx
- Adding debounce to the user search functionality in the group management component to prevent multiple API calls when typing search terms.
- To improve performance by reducing unnecessary network requests when users are typing search queries in the group management interface.
> feat(group-management): debounce user search in group management to reduce api calls

- src/components/messenger/group-management/container.tsx
- src/components/messenger/list/index.tsx
- increases debounce time for user search
- reduce number of api calls
- run UI > search users > check network tab (dev tools) for number of search network requests. This should not fire every character value change. Only once in 800ms.
> refactor(messenger-list/group-management): increase debounce time for user search

- src/store/chat/index.ts
- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- src/store/chat/types.ts
- adds loading progress tracking logic for connection syncing
- to be able to track loading progress of connection
> feat(store/chat/saga): add loading progress tracking logic for connection syncing

- src/components/background-image/index.tsx
Fix react warning calling out that this method was renamed in React v17
> Fix background image deprecated method

- src/components/loading-screen/index.tsx
- src/components/loading-screen/utils.ts
- We're adding a utility function that provides different loading messages based on the current progress percentage of the Matrix connection process.
- To give users more detailed feedback about what's hap
- run ui and refresh to see the loading screen
> feat(loading-screen): add dynamic loading messages to improve user feedback during matrix connection process

- src/store/index.ts
Disabling devtools in production. Shouldn't have a large impact, but every bit helps.
Also, if someone does have the extension it could make a difference as we use it redux quite heavily
> Disable redux dev tools in production

- src/App.tsx
- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- src/components/loading-screen/styles.scss
- src/components/loading-screen/utils.ts
- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- move loading screen to messenger main
- improve ux
> refactor(loading-screen): move loading screen to messenger main

- src/apps/app-router.tsx
- src/components/app-bar/index.tsx
Fixes the sidekick breaking after using a zApp.
It's element is referenced in a portal so it needs to stay in the dom.
Also changing the app icon order to put the zApps at the bottom of the list
> Fix Sidekick un-rendering after visiting zApp

- src/components/messenger/user-profile/settings-panel/index.tsx
- typo in background option name
> fix(settings-panel): typo in background option name

- src/components/chat-view-container/chat-view.tsx
Fixes the message ordering (and duplicate media) in the light box
> Fix lightbox message order

- src/lib/chat/matrix-client.ts
- src/store/matrix/saga.ts
- We're enhancing error logging during the backup restoration process.
- To address issues where users' valid backup keys are being rejected and to gather more diagnostic information about restoration failures.
> refactor(matrix-client/matrix-saga): improved error logging for backup key restoration

- src/apps/messenger/Main.test.tsx
- src/apps/messenger/Main.tsx
- src/components/loading-screen/index.tsx
- src/components/loading-screen/styles.scss
- src/components/messenger/chat/index.test.tsx
- src/components/messenger/chat/index.tsx
- loading screen should only render on initial load when on messenger app
- improve ux 
- run ui and refresh page on messenger app
- when running ui, switch conversation with new messages and check loading screen does not render
> fix(loading-screen/messenger-app): loading screen should only render on initial load and not when switching to conversations that have unread messages

- src/components/chat-view-container/styles.scss
We're fixing the chat view container's opacity transition to ensure content appears smoothly after rendering instead of abruptly.
- The current implementation causes content to appear suddenly which creates a jarring user experience, whereas a smooth transition provides a more polished feel when navigating between conversations.
- run UI and switch conversations in messenger app
> fix(chat-view): improve chat view rendering with proper opacity transition

- src/lib/hooks/README.md
- src/lib/hooks/useMatrixMedia.ts
- src/store/messages/index.ts
- Adds a new useMatrixMedia hook and its documentation to provide a unified, type-safe way to handle both encrypted and non-encrypted Matrix media with built-in caching.
- To replace the old loadAttachmentDetails approach with a more maintainable solution that provides better type safety, caching, and a consistent way to handle media across the application.
- note this is not yet wired up or being used - this will be done in a follow up PR
> feat(hooks): add useMatrixMedia hook and documentation

- .npmrc
- package.json
- src/lib/api/rest.ts
- src/store/authentication/api.ts
I previously removed the zos-component-library from the repo but forgot to remove the .npmrc that was causing us to need github access tokens. That's been cleaned up.
This adds special auth handling for vercel preview environments. It adds the token to memory and uses it for header based authentication when the `VERCEL_ENV` var is set to `preview`. The reason we need this is because we're using cookie based authentication and cookies won't be set on domains outside our main domain
> Add auth handling for Vercel Preview urls

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/matrix/index.ts
- src/store/matrix/saga.test.ts
- src/store/matrix/saga.ts
- Adding progress tracking functionality to the secure backup restoration process by implementing a progress callback in the Matrix client and handling it in our saga.
- To provide users with real-time feedback during the secure backup restoration process, improving the user experience by showing the current stage and progress of the operation.
- Note - this is not yet wired up - these changes only add the matrix progressCallback and the necessary changes re updating the restore progress state 
> feat(matrix-client/matrix-saga) add matrix progress callback tracking for secure backup restoration

- src/components/secure-backup/verify-key-phrase/index.test.tsx
- src/components/secure-backup/verify-key-phrase/index.tsx
- replaces zui input component with zui password input component
- hide/display password entered 
- use correct input type
> refactor(verify-key-phrase): replace zui input component with zui password input component

- src/store/chat/saga.test.ts
- src/store/chat/saga.ts
- switching from call to spawn for conversation read status
- to improve UI responsiveness by making the operation non-blocking
- run UI > switch conversations with unread messages > check UI doesn't show 'blank' container for conversations
> refactor(chat-saga): switch to non-blocking spawn for conversation read status to improve UI responsiveness

- src/components/message/index.tsx
- We're restructuring the JSX in the Message component to keep the MessageMedia component mounted consistently regardless of edit state.
-  To prevent media from disappearing and reappearing when toggling edit mode, which creates a jarring user experience.
- run UI > edit message with media > check for re-rendering
> fix(components/message): media re-rendering flicker when editing messages

- src/components/chat-view-container/utils.test.ts
- src/components/chat-view-container/utils.ts
- Adding logic to set message content to "Message hidden" when isHidden is true in the processMessages function
- To ensure encrypted messages that can't be decrypted show a consistent "Message hidden" message in the chat view instead of showing Matrix errors
- run UI and check chat view when opening a conversation with encrypted messages for correct message hidden message
Before
After
> fix(chat-view): prevent matrix encrypted message and display "Message hidden" for encrypted messages in chat view

- src/components/messenger/list/index.test.tsx
- src/components/messenger/list/index.tsx
- Adding logic to set message content to "Message hidden" when isHidden is true in the addLastMessageMeta function
- To ensure encrypted messages that can't be decrypted show a consistent "Message hidden" message in the messenger list instead of showing Matrix errors
- run UI and check encrypted conversations message preview in the conversation list
Before: 
After:
> fix(messenger-list): prevent matrix encrypted message and display "Message hidden" for encrypted messages in messenger list

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/store/users/saga.test.ts
- src/store/users/saga.ts
For some users we're having this sort of data in synapse database:
This PR adds an additional check for users so that their ZERO profile info (displayname, avatar) gets synced with their matrix profile state. (so that the displayname here is actually their name, not a uuid).
Also added a Sentry log where i think the bug is occurring.
> Add `verifyMatrixProfileIsSynced` 

- src/store/matrix/saga.test.ts
- src/store/matrix/saga.ts
- We're updating the logic in receiveBackupData to consider a backup as restored if it either has trusted status or matches the decryption key.
- To ensure backup restoration works correctly in cases where we can decrypt messages even if the trust state isn't fully established, while maintaining security through the trusted status check.
- run UI and run the restore secure backup flow
> fix(matrix-saga): update backup restoration check to consider both trust and decryption key matches

- package-lock.json
- package.json
- chore: bump zui version (`1.24.0`) -> (`1.25.0`)
> chore: bump zui version (`1.24.0`) -> (`1.25.0`)

- src/components/messenger/lib/utils.test.ts
- src/components/messenger/lib/utils.tsx
- We're adding proper regex character escaping to the highlightFilter function 
- To prevent the app from crashing when users type @ after special characters like question marks, which was causing an invalid regex pattern error.
- run UI and enter characters in message input/user search 
> fix(message/user-search): regex escaping in highlightFilter to prevent app crash when typing special characters

- src/components/edit-profile/index.tsx
- We're changing the value prop of the SelectInput component to use an empty string as fallback when primaryZID is null.
- We're making these changes to resolve a React warning about null values being passed to input components.
- run UI > open profile > edit profile > check console for errors when no zid selected
> fix(edit-profile): null value warning in EditProfile SelectInput component

- src/components/app-bar/index.tsx
- src/components/app-bar/index.vitest.tsx
- adding a Link component around the IconLogoZero to make it navigate to the home page when clicked.
- To provide a standard UX pattern where clicking the logo returns users to the home page.
- run UI and click zero app logo in app bar > check navigates to Home app 
> feat(app-bar): add clickable home app navigation to zero app logo in app bar

- src/lib/chat/matrix/chat-message.ts
When joining a channel you have no `previousContent`, so it's always going to display an avatar change message.
Now checking for `previousContent` as well
> Fix avatar change message when joining a channel

- src/components/app-bar/current-user/index.vitest.tsx
- src/components/app-bar/current-user/lib/useCurrentUserDetails.ts
- We're modifying the user profile click handler to toggle between opening and closing the profile instead of always opening it.
- To improve user experience by allowing users to close the profile with the same button they used to open it.
- run UI > click user profile avatar to open, click again to close
> feat(app-bar/current-user): add toggle behavior to user profile button

- src/components/message/menu/messageMenu.tsx
- src/components/message/menu/messageMenu.vitest.tsx
- We're modifying the canReply logic in the MessageMenu component to disable replies for GIF messages by checking the mimetype.
- To maintain consistency with the mobile app's limitations where GIF messages cannot be replied to due to Matrix Rust SDK compatibility issues.
- run UI and check that reply option is not available on gif messages
> refactor(message-menu): disable reply functionality for GIF messages

- src/components/message/index.tsx
- We're modifying the renderMenu function in the Message component to hide the reaction button for GIF messages.
- To maintain consistency with the iOS app where reactions are disabled for GIF messages due to Matrix Rust SDK compatibility issues.
- check reactions are disabled on gif messages
> refactor(components/message): disable reactions for GIF messages

- src/store/messages/utils.ts
- We're modifying the createOptimisticMessageObject function to set the mimetype to 'image/gif' for GIPHY messages during optimistic message creation.
- To ensure that reaction and reply options are disabled immediately when a GIPHY message is sent, rather than only after a page refresh, by correctly identifying GIPHY messages from the moment they appear in the UI.
> refactor(create-optimistic-message-object): set correct mimetype for GIPHY messages in optimistic message creation

- src/apps/feed/components/show-more-button/index.tsx
- src/apps/feed/components/show-more-button/index.vitest.tsx
- src/apps/feed/components/show-more-button/styles.module.scss
- Adding a new ShowMoreButton component that handles the expansion of truncated posts, along with its styles and tests.
- To improve feed readability by collapsing long posts (>280 characters or >3 line breaks) with a "Show more" button, similar to Twitter's implementation.
- this component is not yet wired up in the UI
> feat(feed/components/show-more-button): add ShowMoreButton component for truncating long posts in feed

- src/apps/feed/lib/analyzePostContent.ts
- src/apps/feed/lib/analyzePostContent.vitest.ts
Extracting post truncation logic into a dedicated utility function with comprehensive test coverage to handle character count, line breaks, and content analysis.
To improve code maintainability and reusability by centralizing post truncation logic in one place, making it easier to test and modify truncation rules across all feed views.
Note :: this is not yet wired up to be used in UI
> feat(feed/lib): add analyzePostContent utility for consistent post truncation logic

- src/apps/feed/components/post-view-container/index.tsx
- src/apps/feed/components/post/index.tsx
- src/apps/feed/components/post/styles.module.scss
- src/apps/feed/components/show-more-button/styles.module.scss
- Adding proper text truncation with ellipsis, smooth transitions, and a "Show more" button to posts that exceed 280 characters or 3 line breaks.
- To improve feed readability and user experience by collapsing long posts while maintaining easy access to their full content, similar to Twitter's implementation.
- run UI > render posts and check long post content is truncated with show more button displayed
> feat(components/post): add text truncation with ellipsis and smooth expansion for long posts (based on analyze post content logic)

- src/lib/hooks/useScrollPosition.ts
- src/lib/hooks/useScrollPosition.vitest.ts
- We're adding a new useScrollPosition hook to restore scroll position when navigating back from post view to feed.
- We're making these changes to improve user experience by maintaining scroll position context when viewing and returning from posts.
- note this is not yet wired up to the UI
> feat(lib/hooks): add useScrollPosition hook

- src/apps/feed/components/post/index.tsx
- We're adding a data-post-id attribute to the Post component wrapper div.
- We're making these changes to enable scroll position restoration by allowing the hook to find the clicked post element in the DOM.
> feat(components/post): add data-post-id attribute to Post wrapper component for scroll restoration

- src/apps/feed/index.tsx
- We're adding the useScrollPosition hook to the FeedApp component to handle scroll position restoration.
- We're making these changes to enable scroll position restoration when navigating to and from posts in the feed view.
- run Ui, navigate to feed app, scroll down to a post, click post to expand, and the click back. Check post clicked is in view
> feat(feed): add scroll position restoration to feed app

- src/apps/home/index.tsx
- We're adding the useScrollPosition hook to the HomeApp component to handle scroll position restoration.
- We're making these changes to enable scroll position restoration when navigating to and from posts in the home view.
- run UI > navigate to home app > scroll down to a post and click > click back button > check post is in view
> feat(home): add scroll position restoration to home app

- src/components/logout-confirmation-modal/index.tsx
- We're adding a close method to the LogoutConfirmationModal component that calls onClose without passing event data.
- To prevent non-serializable event data from reaching Redux actions, which improves performance and follows Redux best practices.
- run UI > open logout dialog > click close icon or secondary button > check console and check performance
> fix(logout-confirmation-modal): prevent non-serializable event data in logout modal close action

- src/components/logout-confirmation-modal/index.tsx
- We're adding a logout method to the LogoutConfirmationModal component that calls onLogout without passing event data.
- To prevent non-serializable event data from reaching Redux actions, which improves performance and follows Redux best practices.
- run UI > open logout dialog > click logout > check console and performance
> fix(logout-confirmation-modal): prevent non-serializable event data in logout modal logout action

- src/apps/feed/components/post/lib/usePostRoute.ts
- src/apps/feed/components/post/lib/usePostRoute.vitest.tsx
- src/apps/profile/index.tsx
- src/apps/profile/index.vitest.tsx
We're modifying the profile app to handle post viewing within the profile context instead of redirecting to the feed app.
To provide a more focused and contextual post viewing experience within user profiles
- run UI > go to profile > click post
> feat(profile): enable post viewing within profile context

- src/apps/profile/index.tsx
- src/apps/profile/index.vitest.tsx
- We're adding the useScrollPosition hook to the ProfileApp component to handle scroll position restoration.
- We're making these changes to enable scroll position restoration when navigating to and from posts in the profile view.
- run UI > navigate to profile app > scroll down to a post and click > click back button > check post is in view
> feat(profile-app): add scroll position restoration to profile app

- src/apps/feed/components/post/link-preview/index.tsx
- src/apps/feed/components/post/link-preview/styles.module.scss
- src/apps/feed/components/post/link-preview/utils.ts
Adding two new files (index.tsx and styles.module.scss) that create a link preview component with YouTube support.
To enhance user experience by allowing inline preview and playback of links shared in posts.
> feat(post-link-preview): add post link preview component with youtube support

- src/apps/feed/components/post/index.tsx
Adding link detection and rendering of the PostLinkPreview component within the post's text content.
To enable automatic link preview functionality for any YouTube links shared within posts.
run UI and post a youtube link
> feat(feed): wire up link preview component in posts

- src/components/message/index.test.tsx
- src/components/message/index.tsx
- src/lib/chat/matrix/chat-message.ts
- src/lib/hooks/useLinkPreview.ts
- src/store/messages/index.ts
- src/store/messages/saga.receiveNewMessage.test.ts
- src/store/messages/saga.send.test.ts
- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
- src/store/messages/utils.ts
Removes Redux/Saga from being responsible for link previews. This data is only used when rendering messages so it's unnecessary to ensure it's loaded and stored in redux. Instead, react query will handle caching that data and only fetching it when we need to render a preview.
This is a necessary prerequisite to making some message optimizations in Redux since it's locking down message processing to being a saga specific task due to managing the previews.
> Remove link previews from redux

- src/lib/chat/chat.vitest.ts
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/chat-message.ts
- src/store/channels-list/saga.ts
- src/store/channels-list/utils.ts
- src/store/messages/index.ts
- src/store/messages/saga.ts
- src/store/messages/utils.matrix.ts
- src/store/posts/index.ts
Removes Matrix from being responsible for setting the Sender field on messages.
This is now managed in redux/saga since that's where the source of truth is for user information.
I'll be doing another follow up task eventually to make this field normalized so that it points to the actual user object in redux rather than manually updating the objects. When denormalizing a message, the sender data should just be populated automatically
Sender data was inconsistent with the source of user information
> Move the responsibility of setting senders to redux/saga from matrix

- src/components/edit-profile/index.test.tsx
- src/components/edit-profile/index.tsx
- src/components/messenger/user-profile/overview-panel/index.test.tsx
- src/components/messenger/user-profile/overview-panel/index.tsx
- src/test/utils.ts
Fixes the profile images in the user panels (overview and edit profile)
I missed these 2 profile images when doing the profile image refactor.
Since we're using the useMatrixImage hook, I converted them to function components as well
> Fix profile images in panels (overview/edit profile)

- package-lock.json
- package.json
- patches/matrix-js-sdk+37.4.0.patch
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix-client.vitest.ts
- src/lib/chat/slidingSync.ts
- src/store/channels-list/utils.ts
Adds a patch to matrix-js-sdk to fix notification counts in encrypted rooms.
I'll be opening an issue with the sdk to talk about how we can fix this in there instead of handling it as a patch, but for now 
Unread notification counts have had some odd issues with sliding sync.
1. Sliding sync doesn't have accurate counts for encrypted rooms. I've removed relying on this data.
2. Read receipts weren't properly updating unread counts. I've added a patch to matrix-js-sdk to fix this.
> Fix notification counts in encrypted rooms

- src/store/channels-list/utils.ts
- src/store/messages/saga.ts
If a message is decrypting, it could be included twice in encrypted conversations when using the initial sync response.
Adding a check to prevent that.
Also cleaning up a call to get users from redux to use the new matrix ids hook.
> Fix: Small fixes with Sliding Sync

- src/store/channels-list/utils.ts
Adds the user's display sub-handle to the user object when fetching them from the API
Open members panel and you should see sub handlers for all users
> Fix: Adds user display sub-handle to user object from API

- src/lib/chat/matrix/event-type-handlers/roomMessage.ts
- src/store/channels-list/saga.test.ts
- src/store/channels-list/saga.ts
Refactors the other room member sagas to be batched and debounced.
If a large channel was syncing, we would trigger a redux action with every member join event which was flooding the store with updates. Now they're debounced and instead of using the payload of the event, we just update with the data from the room itself so that we don't have to rely on the event payloads. This should keep things much simpler and more optimized
Background events were spamming the redux store when syncing channels. Since we have a lot of components that re-render unnecessarily, this was causing some UI jank.
> Fix: Refactor other room member sagas

- src/lib/chat/matrix/matrix-adapter.ts
The unread count is not accurate while the sliding sync is running, so we'll rely on regular matrix events for this information
Fixes an issue where sometimes channels will load in with 1 unread count, even though they are fully read
> Removing unread count while sync is incomplete

- src/lib/chat/matrix-client.ts
Fixes the current user's optimistic messages not being replaced with the actual event data.
For context, when switching to Sliding Sync it seems like Matrix no longer sends a handful of events related to current user's new messages. This was causing us to not update the message properly.
The only event we get is a room timeline event, so I've added some extra logic there to handle these updates
> Fix user optimistic messages not being updated with event data

- src/apps/feed/components/post/actions/feed/styles.module.scss
- src/apps/feed/components/post/styles.module.scss
We're adding max-width constraints and overflow handling to both post containers and ZID displays in feed actions, because long ZIDs and post content were causing undesirable horizontal scrolling that broke the layout and user experience.
Run tests as usual.
Run UI and check posts where the content, such as zids, are long to check there is no overflow/horizontal scroll.
> fix(components/post): prevent horizontal overflow in posts and truncate long zids with ellipsis

- src/apps/feed/components/feed/index.tsx
- src/apps/feed/components/post-input/index.tsx
- src/apps/feed/components/post-input/menu/index.tsx
- src/apps/feed/components/post-input/menu/styles.scss
- src/apps/feed/components/post-media/index.tsx
- src/apps/feed/components/post-media/styles.module.scss
- src/apps/feed/components/post-media/utils.ts
- src/apps/feed/components/post-view-container/index.tsx
- src/apps/feed/components/post-view-container/reply-list/index.tsx
- src/apps/feed/components/post/index.tsx
- src/apps/feed/components/posts/index.tsx
- src/apps/feed/lib/usePostMedia.ts
- src/apps/feed/lib/useSubmitPost.ts
- src/components/dialog-manager/container.test.tsx
- src/components/dialog-manager/container.tsx
- src/components/lightbox/index.tsx
- src/lib/feature-flags.ts
- src/lib/feature-flags/development.ts
- src/lib/feature-flags/flags.ts
- src/lib/feature-flags/production.ts
- src/store/dialogs/index.ts
- src/store/posts/media-api.ts
- src/store/posts/saga.ts
- src/store/posts/utils.ts
- implements and wires up ability to post image media
- ensures only one image can be selected at once
- fetches post media when loading posts
- adds placeholders for improved ui
- to be able to add image media to posts on creation & load
- run UI and attempt to post media
> feat(posts): implement and wire up ability to post image media

- src/apps/feed/lib/usePostMedia.ts
We're enhancing the usePostMedia hook's caching strategy by implementing longer cache durations, smarter refetching rules, and optimized URL refresh intervals.
To significantly reduce network requests and improve performance by reusing cached media data for up to 2 hours and preventing unnecessary refetches, which will result in fewer loading states and a smoother user experience.
Run UI and check network requests when re-rendering post media
> refactor(use-post-media): optimize post media caching with React Query to reduce network requests

- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix-client.vitest.ts
- src/lib/chat/session-storage.test.ts
- src/lib/chat/session-storage.ts
- src/store/chat/bus.ts
- src/store/matrix/index.ts
- src/store/matrix/saga.ts
Updates how we handle tokens in matrix and introduces refresh tokens.
The access token has been removed from local storage and is now fetched every time the user comes to the app. When the token expires, a new token will be fetched using the refresh token. If that operation fails, the user will be logged out.
User matrix access tokens are expiring due to us saving the token to local storage and never updating it unless the user either clears local storage manually, or logs out. When this happens, we don't have a way to respond to the 401s properly.
The matrix-js-sdk swallows the 401 errors and just returns null values, so we respond to those values and display invalid states to users in the UI.
The only way I've found to properly handle this situation is to implement the refresh token. …
> Fix: Add refresh token to matrix

- src/lib/chat/chat.vitest.ts
- src/lib/chat/index.ts
- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/matrix-adapter.ts
- src/lib/chat/matrix/matrix-client-instance.ts
- src/lib/chat/matrix/utils.ts
- src/store/channels-list/event-type-handlers/handle-room-data-events.ts
- src/store/channels-list/saga.ts
- src/store/channels-list/utils.ts
- src/store/matrix/saga.ts
- src/store/users/saga.ts
Reworks the matrix client instance to support resetting the instance when the user logs out.
This only supported being created once, which didn't work well when users logged out then back in without refreshing.
Also, I took the opportunity to clean up the api a bit so that it's more cohesive.
Now the SDK methods are wrapped so that there is a single interface for interacting with Matrix
Logging out and then back in results in a broken matrix instance
> Fix: Matrix client instance reset

- src/apps/feed/components/post-input/index.tsx
- src/apps/feed/components/post-input/menu/index.tsx
- src/apps/feed/components/post-input/styles.scss
- src/apps/feed/components/post-media/index.tsx
- src/apps/feed/lib/useSubmitPost.ts
We're adding a Giphy picker to the post input component with a modal overlay UI that appears centered on screen.
To enable users to easily search and select GIFs from Giphy when creating posts, with a user-friendly interface that works consistently regardless of where the picker is opened from.
Run UI and add gif to post creation
> feat(post-media): enable giphy post media and add giphy picker to post input

- src/apps/feed/components/post-input/index.test.tsx
- src/apps/feed/components/post-input/index.tsx
- src/apps/feed/components/post-input/menu/index.tsx
- src/apps/feed/components/post-media/index.tsx
- src/apps/feed/components/post-media/styles.module.scss
- src/apps/feed/lib/usePostMedia.ts
- adds video support to post media uploads
- tweaks use post media stale / interval times to prevent media no longer being displayed after expiration from backend
- allow users to post video media
- run UI and attempt to upload a video in a post
> feat(post-media): add video support to post media uploads

- src/lib/chat/matrix/matrix-client-instance.ts
- src/lib/chat/session-storage.test.ts
- src/lib/chat/session-storage.ts
- src/store/channels-list/saga.ts
- src/store/chat/saga.ts
Ensures the integrity of the login/logout system even if we encounter errors.
There is an error that can cause the matrix client to get in a bad state. When this happens, the login/logout system breaks and the user can't get back into a working state without logging out and refreshing the page.
Login
Open local storage and change your device id
Refresh, you'll see a Matrix error
Log out
Log in
The app should be working correctly.
> Fix: Ensure login/logout cycle isn't broken due to errors

- src/apps/feed/components/post-input/index.test.tsx
- src/apps/feed/components/post-input/index.tsx
- src/apps/feed/components/post-input/menu/index.tsx
- src/apps/feed/components/post-input/utils.ts
- src/config.ts
We are updating the post media Dropzone components to use type-specific file size limits from environment-configured values.
This ensures the frontend enforces the same media size restrictions as the backend, preventing user confusion and upload errors.
Run UI and select a range of file types and sizes
> feat(post-media): enforce correct file size limits for post images, GIFs, and videos using config and shared utility

- src/apps/feed/components/post-media/index.tsx
We are updating the PostMedia component to only open the lightbox for non-video media types.
This maintains consistent UX by ensuring videos play inline and are not shown in the lightbox, matching existing behavior.
Run UI and click video - check lightbox does not open
> refactor(post-media/lightbox): prevent lightbox from opening for video media in post media component and continue to play inline as intended

- src/lib/chat/matrix-client.ts
- src/lib/chat/matrix/errors.ts
- src/store/chat/saga.ts
Handles the Matrix initialization error that can occur if the user id or device id don't match what's in the local crypto db.
Users can get stuck in a loop where their device id doesn't match what's in the crypto store, so the app will never finalize. This ensures that if the matrix crypto can't be initialized, the client will unwind and the app will be reset.
Manually break your device id by altering it in local storage
Reload the app, you should see the error page
Click try again, the app should now load properly
> Fix: Handle matrix error and reset the app

- src/apps/feed/components/post-input/index.test.tsx
- src/apps/feed/components/post-input/index.tsx
- src/apps/feed/components/post-input/menu/index.tsx
- src/apps/feed/components/post-input/utils.ts
- src/config.ts
- src/store/posts/utils.ts
We are updating the file size validation logic to correctly enforce type-specific limits for images and videos, and moving this logic into a shared utility.
Previously, images could bypass their size limit due to using the video max size as a global limit; this change ensures each media type is validated against its correct maximum and improves code maintainability.
Attempt to post media of different sizes
> refactor(post-input): update media file size validation to enforce correct limits for images and videos

- src/store/channels/index.ts
- src/store/channels/saga.ts
- src/store/messages/saga.ts
Adds null checking for optimistic message updating.
Also updates the receive channel type to specify that messages and users can be ids or the full objects
> Fix error in optimistic message update flow

- src/apps/feed/components/feed/index.tsx
- src/apps/feed/components/feed/lib/useFeed.ts
- src/apps/home/index.tsx
- src/components/layout/panel/index.tsx
- src/components/layout/panel/styles.module.scss
We’re adding a toggle to the HomeApp feed to let users filter between “All” posts and posts from users they follow, using a new shared PanelTitleToggle component.
To improve user experience by allowing users to easily view either all posts or just those from people they follow, and to lay the groundwork for more personalized feeds.
Run UI and visit HomeApp
> feat(feed): add All/Following feed filter toggle to HomeApp with shared panel toggle component

- src/apps/feed/components/post-view-container/index.tsx
- src/apps/feed/components/post-view-container/reply-list/index.tsx
We're adding the missing authorPrimaryZid and authorPublicAddress props to the Post components in both the PostView and Replies components.
To fix the issue where clicking on user profiles in post views and replies was resulting in /profile/undefined URLs instead of the correct profile paths.
run ui and attempt profile navigation from post view / replies
> fix(profile-navigation): add missing author identifiers to post components in PostView and Replies to prevent undefined profile links

- src/apps/feed/components/feed/index.tsx
- src/lib/last-feed-filter.ts
- src/store/authentication/saga.test.ts
- src/store/authentication/saga.ts
We're adding localStorage persistence for the feed's "All/Following" toggle state.
To maintain the user's selected feed filter (All/Following) when navigating between posts and profiles, improving UX by preserving their view preference.
Visit the home app, navigate away, and then back. Check the filter is set to what it was before you navigated away.
> feat(home-feed): persist feed filter state between navigation

- src/lib/chat/matrix/matrix-adapter.ts
Adding this back in as it was not properly migrated with the sliding sync update
> Adding back channel zid logic that was missing

- src/components/messenger/list/conversation-item/index.tsx
- src/components/messenger/list/conversation-item/index.vitest.tsx
- src/components/messenger/list/conversation-list-panel/index.tsx
- src/store/channels/index.ts
- src/store/channels/selectors.ts
Fixes the conversation-item typing that was covering up an issue with avatar url logic
> Fix conversation-item avatar url logic

- src/apps/feed/components/feed/index.tsx
- src/apps/feed/components/post/index.tsx
- src/apps/feed/lib/useGetReturnFromProfilePath.ts
- src/apps/feed/lib/useReturnFromProfileNavigation.ts
- src/apps/profile/index.tsx
- src/apps/profile/index.vitest.tsx
We're implementing a return navigation system that preserves scroll position when navigating back from a profile view to the feed.
To improve user experience by maintaining context when navigating between profile and feed views, ensuring users return to their exact previous position.
Run ui, visit a profile from one of the feeds, then navigate back and check you are in the same location as before
> feat(profile/feed/post): implement profile return navigation with scroll position preservation

- src/components/citizen-list-item/index.tsx
- src/components/messenger/group-management/container.tsx
- src/components/messenger/group-management/index.test.tsx
- src/components/messenger/group-management/index.tsx
- src/components/messenger/group-management/view-group-information-panel/index.test.tsx
- src/components/messenger/group-management/view-group-information-panel/index.tsx
- src/components/messenger/group-management/view-members-panel/index.test.tsx
- src/components/messenger/group-management/view-members-panel/index.tsx
- src/components/profile-link-navigation/index.tsx
We're replacing the clickable CitizenListItem behavior with a dedicated ProfileLinkNavigation component that only makes the avatar clickable for profile navigation.
To prevent accidental conversation starts/opens when users intend to navigate to profiles by clicking outside the avatar area.
Open the members panels and click avatar to navigate to profile
> refactor: update citizen list item to use dedicated ProfileLinkNavigation component

- src/components/message/index.tsx
- src/store/messages/index.ts
We're adding profile navigation functionality to avatars in group chat messages by wrapping the MatrixAvatar with ProfileLinkNavigation and updating the Sender interface to include wallet information.
To provide consistent user experience by allowing users to navigate to profiles by clicking avatars in group chats.
Navigate to a group conversation in messenger app and click a users avatar
> feat(message/group-avatars): add profile navigation to group chat avatars

- src/apps/feed/components/feed/index.tsx
- src/apps/feed/components/feed/lib/useFeed.ts
- src/apps/feed/components/feed/search-drawer/index.tsx
- src/apps/feed/components/feed/search-drawer/styles.module.scss
- src/components/layout/panel/styles.module.scss
We're adding a search drawer to the Feed header that allows users to search for and navigate to other users' profiles.
To improve user navigation and discovery by providing quick access to user profiles directly from the Feed.
Run UI and navigate to a app with feed. click search icon, search user and click user to navigate to profile
> feat(feed/header): add global user search drawer to feed header and wire up profile navigation

- src/apps/feed/components/feed/search-drawer/index.tsx
- replaces primary wallet address with users third web wallet address in order to user profile navigation correctly
> fix(feed/search-drawer): use users third web wallet instead of primary wallet address for profile navigation on search results

- src/apps/feed/components/feed/lib/useFeed.ts
- src/apps/feed/components/feed/search-drawer/index.tsx
- src/store/users/types.ts
Adding the thirdWebWalletAddress field to the /api/v2/users/searchInNetworksByName API response.
To enable proper profile navigation in the search drawer by providing access to users' ThirdWeb wallet addresses.
In feed user search, search for a user and check network tab for thirdweb wallet address
> feat(user-search): expose ThirdWeb wallet address in user search API response

- src/components/chat-view-container/chat-view-container.tsx
- src/components/chat-view-container/chat-view-container.vitest.tsx
- src/components/chat-view-container/chat-view.tsx
- src/components/chat-view-container/chat-view.vitest.tsx
- src/components/messenger/message-info/container.tsx
- src/store/group-management/selectors.ts
- src/store/message-info/index.ts
- src/store/message-info/saga.test.ts
- src/store/message-info/saga.ts
- src/store/messages/saga.ts
- src/store/panels/selectors.ts
Fixes the message info read by list not working
The action modifying the readby of the message wasn't wired up properly.
The toggle sidekick selector wasn't looking at the right state so it was always closing the panel if you had it open and selected message info on another message
Select message info on a message, see the read by users, select info on another message, panel should stay open.
> Fix: Message info panel readby

- src/components/messenger/autocomplete-members/index.tsx
- src/components/messenger/lib/types.ts
- src/components/messenger/list/conversation-list-panel/index.tsx
- src/components/messenger/list/index.tsx
- src/store/group-management/saga.ts
- src/store/users/types.ts
Correctly maps user selection to user objects for inviting to channel
We were pulling users directly from the redux store, but those users might not be in the store if you are not in any conversations with them. This caused the invite to fail since the users list would be empty.
Now, we use the standardized way of getting users that ensures they're loaded.
Search for a user that you don't have any conversations with and add them to a conversation
> Fix: Fix inviting users to channel

- src/components/messenger/list/conversation-list-panel/index.tsx
- src/components/messenger/list/conversation-list-panel/index.vitest.tsx
Filters out social channel notification counts in messenger tabs
Social channels shouldn't affect notification counts in messenger
> Filter social channels notifications from showing up in messenger

- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
Keeps the optimistic message `createdAt` timestamp
Messages could jump around if the timestamp from the server was far off from the optimistic timestamp. This could make the UI feel really off on slower connections
> Fix: Created at updating with optimistic messages.

- src/lib/feature-flags/production.ts
Adding 2 more users to oauth linking
> Add users to oauth linking

- src/components/invite-dialog/container.test.tsx
- src/components/invite-dialog/container.tsx
- src/components/invite-dialog/index.test.tsx
- src/components/invite-dialog/index.tsx
- src/components/invite-dialog/styles.scss
- src/store/create-invitation/index.ts
- src/store/create-invitation/saga.test.ts
- src/store/create-invitation/saga.ts
We're removing the invite count display and related state management from the frontend to support the new unlimited invites system.
We're making these changes because we're refactoring the invite system to use permanent, user-specific invite codes for Zero Pro subscriptions instead of limited invite counts.
> refactor(invites): remove invite count from frontend for unlimited invites

- src/apps/profile/lib/useProfile.ts
- src/apps/profile/panels/UserPanel/useUserPanel.ts
- src/components/messenger/user-profile/container.tsx
- src/components/messenger/user-profile/zero-pro-panel/index.tsx
- src/components/messenger/user-profile/zero-pro-panel/usePollZeroProActiveStatus.ts
- src/store/authentication/index.ts
- src/store/authentication/saga.ts
- src/store/authentication/types.ts
- src/store/channels/index.ts
refetches current user data when subscription is successful
to display correct elements in ui 
> fix: refetch and get correct subscription data when successfully subscribed

- src/components/messenger/list/conversation-item/conversation-item.scss
- src/components/messenger/list/conversation-item/index.tsx
- adds zero pro badge for one on one conversations
- refactors the styling a little
- display badge like so
> feat(conversation-item): add zero pro badge for one on one conversations

- src/components/messenger/user-profile/linked-accounts-panel/constants.ts
Removes telegram link from linking options as it's currently disabled, and isn't working
> fix: Remove telegram link

- src/components/messenger/user-profile/account-management-panel/container.test.tsx
- src/components/messenger/user-profile/account-management-panel/container.tsx
- src/components/messenger/user-profile/account-management-panel/index.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- src/components/messenger/user-profile/linked-accounts-panel/index.tsx
- src/components/messenger/user-profile/linked-accounts-panel/styles.scss
- src/store/account-management/index.ts
- src/store/account-management/selectors.ts
Moves linking email from "Manage wallets" to "Linked Accounts" section
We renamed some sections so it makes more sense to have email in the linked accounts panel
> feat: Move email link to linked-accounts panel

- src/components/message/index.tsx
- src/components/message/styles.scss
- src/store/messages/saga.test.ts
- src/store/messages/saga.ts
- Removes the border from the spinner. It looked silly having a spinning line attached to the spinner icon
- Hides empty space at the bottom of images with no body
- Fixes a race condition with images where they would sometimes not appear in the chat
> Fix: Cleanup misc

- src/components/zero-pro-badge/index.tsx
- only show zero pro badge hover card and text content when user is not a pro subscriber
- improved ux
> feat(zero-pro-badge): only show zero pro badge hover card and text content when user is not a pro subscriber

- src/apps/feed/components/create-channel/stages/creating-channel-stage/index.tsx
- src/apps/feed/components/create-channel/stages/creating-channel-stage/styles.module.scss
- src/apps/feed/components/join-channel/index.tsx
Create Channel Flow:
Replace automatic useEffect-driven channel creation with manual "Create Community" button
Remove useEffect that was causing infinite re-renders and multiple API calls
Add user-controlled navigation with "View Channel" button
Remove automatic navigation to prevent race conditions
Join Channel Flow:
Add joinChannelMutation.reset() to clear previous error state on retry
Add specific error handling for "Too Many Requests" rate limit errors
Show user-friendly messages instead of generic balance errors
Error Handling:
Improve error messages for rate limit scenarios
Prevent error flickering when users retry join attempts
Distinguish between network issues and insufficient token balance
Improve the flow and fix ux issues
1. How will this …
> fix(create-channel/tgc): fix create channel flow and minor ui flickering issues

- src/apps/feed/components/create-channel/stages/review-stage/index.tsx
- src/apps/feed/components/create-channel/stages/review-stage/styles.module.scss
- improves loading state when purchasing a zid via the create channel (tgc) flow
- improve ux/ui
> feat: add loading spinner to purchase zid button when creating token gated channel

- src/apps/feed/components/create-channel/stages/create-zid-stage/index.tsx
We're adding validation to disable the continue button when the joining fee is set to 0 in the create channel flow.
To ensure token-gated channels always have a meaningful joining fee requirement, preventing users from creating channels that don't actually gate access with token ownership.
> fix: prevent creating token-gated channels with zero joining fee

- src/apps/feed/components/sidekick/index.tsx
- removes zid prefix from channel name
- improve ui, as per designs
> feat(channels-app/sidekick): remove zid prefix from channel name

- src/apps/feed/components/join-channel/index.tsx
- updates error handling and join text content
- no longer required to only have self-custody wallet holdings
> feat(channels-app/join-channel): update error handling and join text content

- src/components/messenger/user-profile/account-management-panel/container.tsx
- src/components/messenger/user-profile/account-management-panel/index.test.tsx
- src/components/messenger/user-profile/account-management-panel/index.tsx
- src/components/messenger/user-profile/account-management-panel/styles.scss
- src/components/wallet-list-item/index.test.tsx
- src/components/wallet-list-item/index.tsx
- src/components/wallet-list-item/styles.scss
- src/store/account-management/api.ts
- src/store/account-management/index.ts
- src/store/account-management/saga.test.ts
- src/store/account-management/saga.ts
- src/store/authentication/types.ts
Adding multiple wallets
Removing wallets
Transferring wallets from another account
Give users more control over what wallets are attached to their account and which ones can be used to log in
> feat(account): Enhanced wallet management

- src/apps/profile/panels/UserPanel/styles.module.scss
> Remove dead space from the profile card in User Profile panel

- src/apps/leaderboard/components/table-header/index.tsx
- src/apps/leaderboard/components/table-header/styles.module.scss
- src/apps/leaderboard/components/table-row/user-display/index.tsx
- src/apps/leaderboard/components/table-row/user-display/styles.module.scss
- Rename 'MEOW' column to 'MEOW Earned'
- User name are hyperlinked now to their profiles (while recording idk why but the cursor pointer doesn't turn to a hand)
https://github.com/user-attachments/assets/67e1d758-a5c7-4d49-9ea3-3107ff9577fe
> Update Leaderboard app: Make users name linked to their profile

- src/apps/token/components/token-launcher/FormInputs.tsx
- src/apps/token/components/token-launcher/index.tsx
- src/apps/token/components/token-launcher/styles.module.scss
- src/apps/token/components/token-launcher/utils.ts
- src/apps/token/hooks/useTokenForm.ts
- src/apps/token/hooks/useTokenSubmission.ts
We're removing the Initial Buy Amount input field from the token launcher form and eliminating the ERC20 approval step from the token creation flow.
Since the initial buy amount is now hardcoded to "0" and users can't modify it, there's no need for the input field or the approval step since no MEOW tokens are being spent during token creation.
> refactor(token-app/token-launcher): remove initial buy amount input and approval step from token launcher

- src/apps/feed/lib/useSubmitPost.ts
- src/store/posts/saga.ts
- src/store/posts/utils.ts
We're removing frontend ZID fallback logic and sending undefined for the zid field when users don't have a ZID, allowing the backend to handle wallet address fallback.
To simplify the frontend architecture by letting the backend determine the author identifier (ZID or wallet address) instead of duplicating this logic in the frontend.
> refactor(posts): remove frontend zid fallback logic for post creation

- src/components/chat-view-container/chat-view.tsx
- src/lib/chat/matrix/chat-message.ts
- src/lib/date.ts
- src/store/messages/index.ts
- src/store/messages/saga.ts
- src/store/messages/utils.ts
**Problem**: If you send multiple messages in quick succession, sometimes (due to server load), they appear to be 'bouncing' on the UI (basically the timing becomes out of order). This can be more easily reproduced if you try to send multiple image messages at the same time: while they're all optimistically rendered initially at the same time, as soon as the first image upload is successful, the state is updated, and the `createdAt` changes from our optimistic message object to the actual matrix event. So, after that, when the UI sorts the messages, it can fall out of order (since the `optimisticMessage.createdAt` can be different from `canonicalMessage.createdAt`). 
Therefore, as the actual matrix events for the file upload keeps coming in, the order keeps getting changed (hence the …
> Fix: When sending messages in quick succession, the timing becomes out of order.
