zer0-os/zOS

src/Main.tsx
src/components/address-bar/container.test.tsx
src/components/address-bar/container.tsx
src/components/app-menu/container.test.tsx
src/components/app-menu/container.tsx

Resolved behavioural issues while testing in our development environment.

Addressing code review comments

---

src/components/address-bar/index.test.tsx
src/components/address-bar/index.tsx
src/components/address-bar/styles.scss
src/components/app-menu/container.tsx
src/lib/apps/index.ts

Address Bar UX updates

---

src/Main.tsx
src/_variables.scss
src/app-sandbox/styles.scss
src/components/address-bar/styles.scss
src/index.scss
src/index.tsx
src/main.scss

simplifies the layout, and pulls the main layout back out of the sandboxed react app
to keep the platform layout and logic in the platform, separated from the sandbox.
load the app. do stuff. 

Simplify layout

---

package.json
src/index.scss

bump zOS-feed, fix spacing on sandbox

---

src/components/address-bar/index.tsx
src/components/web3-connect/index.test.tsx

fixes the build which was failing due to lint errors
the build was failing

remove unused vars

---

src/index.tsx

fix root redirect

---

package.json

remove homepage

---

package.json

Bump zOS-feed

---

craco.config.js
package-lock.json
package.json

bump feed for cloudinary

---

package.json

bump zOS-feed 1.7.0

---

package-lock.json
package.json

bump @zer0-os/zos-component-library 0.6.0

---

.github/workflows/development-electron.yml
.github/workflows/development.yml
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx
src/config.ts
src/lib/web3/chains.ts
src/lib/web3/connectors.ts
src/lib/web3/index.ts
src/setupTests.ts
src/store/web3/index.test.ts
src/store/web3/index.ts

Add error message if network not supported

---

package.json

bump @zer0-os/zos-component-library 0.6.2

---

src/index.scss
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

Add style theme for connect button

---

package-lock.json
package.json

bump zos-zns to 1.1.3

---

src/index.scss

remove bounce effect

---

src/components/app-menu/styles.scss

Add mouse over to apps name

---

src/components/app-menu/styles.scss
src/main.scss

Align nav text with the logo

---

src/components/app-menu/styles.scss
src/main.scss

Align app name for left collapse

---

src/Main.tsx
src/components/logo/index.test.tsx
src/components/logo/index.tsx

Add link to logo

---

.github/workflows/development-electron.yml
.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/run-tests.yml
src/lib/web3/connectors.ts
src/lib/web3/web3-react.tsx

Add production deploy

---

package-lock.json
package.json

bump zos-feed 1.11.0

---

package-lock.json
package.json

bump feed version

---

craco.config.js
package-lock.json
package.json
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx

updates to the latest version of the feed, which simplifies routing, as well as updates the App interface.
to fix the feed routing.
load the feed. drill down into an item that has children. refresh. 

Fix feed routing

---

package-lock.json
package.json

bump zos-feed 1.15.0

---

src/components/autocomplete-dropdown/styles.scss

height of search

---

src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/components/web3-connect/index.test.tsx
src/main.scss
src/store/web3/index.test.ts

Logo position

---

src/components/address-bar/styles.scss
src/components/wallet-manager/styles.scss

Overlay size

---

src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx
src/lib/web3/connectors.ts
src/store/web3/index.ts

Change data if network changed in wallet

---

src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx

1 - We need await after we activate connector in test.

Reconnect connector on reload page

---

src/index.scss
src/main.scss

Fix width sandbox container

---

src/platform-apps/channels/styles.scss

add styling to channel list

---

src/platform-apps/channels/styles.scss

Channel message styling

---

src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/platform-apps/channels/styles.scss
src/store/web3/index.test.ts
src/store/web3/index.ts

add connectWallet to app props

---

src/config.ts
src/store/channels-list/api.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Get channels list from api zero

---

package.json
src/_variables.scss
src/index.scss
src/main.scss
src/platform-apps/channels/styles.scss

fix sandbox width

---

.github/workflows/development-electron.yml
.github/workflows/development.yml
.github/workflows/production.yml

Add zero_api var

---

src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

fetch channels

---

src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss
src/store/messages/index.ts

Add view video to message

---

src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/styles.scss
src/store/messages/index.ts

Style view images

---

package-lock.json
package.json
src/index.tsx
src/platform-apps/channels/styles.scss
src/zns-route-connect.test.tsx
src/zns-route-connect.tsx

adds a 0 to zna route urls.
to enable the handling of the root zna.
go to a zos url.
if the zna you provide does not have a leading 0, it will redirect to one with a 0 prefix.

Update url structure

---

package-lock.json
package.json
src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss
src/platform-apps/channels/utils.tsx
tsconfig.json

Add emojis

---

src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss

Add play audio to messages

---

package-lock.json
package.json
src/_variables.scss
src/app-sandbox/styles.scss
src/main.scss
src/platform-apps/channels/styles.scss

centers the address bar and the feed, taking the 'connect' button into consideration.
cuz we like to be pretty.
load the app. see the magic.

Fix feed layout

---

src/components/app-menu/styles.scss

Add spacing between apps

---

src/lib/apps/index.test.tsx
src/lib/apps/index.ts

remove channels feature flag

---

src/platform-apps/channels/channel-view.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss

- Left align messages (keep day dividers centered)
- Remove 00 in start of channel text (see image attached)

channel enhancement

---

src/store/channels-list/saga.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Remove prefix from Id url

---

src/Main.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/main.scss

moves the connect button into the header and removes the sidekick.
cuz it was getting in the way of the pointer, and has no purpose.
load the app. drag the scrollbar. 

Remove sidekick

---

src/store/messages/api.ts

send filter as json

---

src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss

add author avatar and name

---

package-lock.json
package.json
src/app-sandbox/styles.scss
src/platform-apps/channels/channel-list.test.tsx
src/platform-apps/channels/channel-list.tsx
src/platform-apps/channels/container.test.tsx
src/platform-apps/channels/container.tsx
src/platform-apps/channels/styles.scss

changes some styles and tweaks the layout
cuz we're awesome
click around.

Layout changes

---

src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss
src/platform-apps/channels/utils.tsx
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

enhancement channels styles

---

package.json
src/platform-apps/channels/channel-list.test.tsx
src/platform-apps/channels/channel-list.tsx
src/platform-apps/channels/styles.scss
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels/index.ts

Add categories to channels list

---

src/components/authentication/index.tsx

fix action authorize

---

src/store/authentication/api.ts

fix cookies

---

src/platform-apps/channels/styles.scss

Fix style for channel enhancements

---

src/platform-apps/channels/styles.scss

Fix bug/shrink messages style

---

src/platform-apps/channels/styles.scss

Fix bug/resolve merge

---

src/platform-apps/channels/channel-list.test.tsx
src/platform-apps/channels/channel-list.tsx
src/platform-apps/channels/styles.scss

Resolve category regression

---

package-lock.json
package.json
src/app-sandbox/styles.scss
src/components/wallet-manager/styles.scss
src/main.scss
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

makes the context panel collapsible
because
load the app. go to feed or channels.
click the 'filter' icon to the right of the app navigation.
the drawer should slide out.

Add collapsible context panel

---

package-lock.json
package.json
src/app-sandbox/styles.scss
src/main.scss
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

updates styling of context panel
cuz the styles were wrong.
open the app. marvel at the beauty of the context panel and navigation panels.

Context panel styles

---

src/platform-apps/channels/channel-list.test.tsx
src/platform-apps/channels/channel-list.tsx
src/platform-apps/channels/container.test.tsx
src/platform-apps/channels/container.tsx
src/platform-apps/channels/styles.scss
src/store/channels-list/index.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels/index.ts
src/store/messages/saga.ts
src/store/normalized/index.ts

Show unread messages badge on channels

---

src/platform-apps/channels/channel-view.tsx

fix eqeqeq

---

src/platform-apps/channels/channel-view-container.tsx
src/platform-apps/channels/channel-view.test.tsx
src/platform-apps/channels/channel-view.tsx

Bugfix: hide message input

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx

fix Autorisation 

---

src/store/channels-list/api.ts

Changed chatChannels/public to chatChannels

---

src/store/authentication/saga.ts
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

Send message instantly

---

package-lock.json
package.json
src/app-sandbox/index.tsx
src/lib/apps/index.test.tsx
src/lib/apps/index.ts

Adds zApp DAOs to the list of apps.
To get DAOs zApp in zOS for iteration.
- Click "DAOs" in the app selector.
- Check that the "DAOs" app renders.

feat: add zApp DAOs

---

package.json
src/Main.test.tsx
src/Main.tsx
src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/main.scss
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json
src/store/index.ts
src/store/layout/index.test.ts
src/store/layout/index.ts

tweaks the way that the platform and apps respond to layout changes
so that the search bar & other platform elements can respond to changes in the layout.
load the app. open/close the context panel. the address bar should adjust appropriately.

Layout tweaks

---

src/components/message-input/styles.scss
src/lib/apps/index.ts
src/platform-apps/channels/styles.scss

fix channels styling

---

package-lock.json
package.json
src/app-sandbox/styles.scss
src/main.scss
src/modules/_animation.scss
src/platform-apps/channels/styles.scss
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

Tweak context menu styles

---

src/components/link-preview/styles.scss
src/platform-apps/channels/styles.scss

fix styling

---

src/platform-apps/channels/styles.scss

fade in channel view

---

src/platform-apps/channels/styles.scss

fix divider

---

package-lock.json
package.json

Bumps zApp Staking version to latest.
Bring across the latest round of feedback.
-

chore: bump zapp staking

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/lib/api/rest.ts
src/platform-apps/channels/channel-view-container.test.tsx
src/platform-apps/channels/channel-view-container.tsx
src/store/authentication/api.ts
src/store/authentication/index.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts

Add disconnect button

---

src/components/indicator-message/styles.scss
src/platform-apps/channels/channel-view.test.tsx
src/platform-apps/channels/channel-view.tsx

Show indicator only if user is scrolled up

---

src/components/message-input/styles.scss
src/platform-apps/channels/channel-view-container.test.tsx
src/platform-apps/channels/channel-view-container.tsx

https://user-images.githubusercontent.com/27851097/198080402-368ed18b-ff7f-4a9c-9af3-fd6804191dca.mov

Fix mentions rendred & fetchUsers on channel

---

src/platform-apps/channels/styles.scss

Fix overlapping mentions

---

src/components/address-bar/container.test.tsx
src/components/address-bar/container.tsx
src/config.ts
src/store/apps/index.test.ts

Fix the searching outside of Feed

---

src/platform-apps/channels/styles.scss

Modify channel animation time

---

src/components/inverted-scroll/index.tsx

Fixing the channel scroll on first load - I've used the logic from zero-web

fix channel scroll

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/platform-apps/channels/channel-view-container.test.tsx
src/platform-apps/channels/channel-view-container.tsx
src/platform-apps/channels/channel-view.tsx

auto focus textarea input

---

src/components/theme-engine/index.test.tsx
src/components/theme-engine/index.tsx
src/store/saga.ts
src/store/theme/index.test.ts
src/store/theme/index.ts
src/store/theme/saga.test.ts
src/store/theme/saga.ts
src/zns-route-connect.test.tsx

Save the current viewMode in localStorage

---

.env.example
src/components/account/create.test.tsx
src/components/account/create.tsx
src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/config.ts
src/store/authentication/api.ts
src/store/authentication/index.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts
src/store/authentication/types.ts
src/zns-route-connect.tsx

Related API PR: https://github.com/m3m3n70/zero-api/pull/844
https://user-images.githubusercontent.com/31045/201802564-271fc1c8-f5f1-4a46-b9a2-08a366c0edfa.mov

Create user from web3

---

src/platform-apps/channels/channel-list.test.tsx
src/platform-apps/channels/channel-list.tsx
src/platform-apps/channels/container.test.tsx
src/platform-apps/channels/container.tsx
src/platform-apps/channels/styles.scss
src/store/channels-list/saga.ts
src/store/channels/index.ts

add private channel

---

src/store/channels/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

fix double message

---

src/store/messages/saga.ts

Fix double message behavior

---

.github/workflows/development.yml
.github/workflows/run-tests.yml

fix unit test

---

src/lib/chat/index.ts
src/platform-apps/channels/chat-connect/chat-connect.tsx
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

realtime delete message

---

src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx

Apps do not load.
Reproduce:
- Connect with Metamask
- Close your browser
- Reopen the zOS url (Note that Metamask prompts for the password)
- Note that the Apps do not load

Fixed an issue where Apps do not load

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/styles.scss
src/lib/api/rest.ts
src/platform-apps/channels/channel-view-container.test.tsx
src/platform-apps/channels/channel-view-container.tsx
src/platform-apps/channels/channel-view.tsx
src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/platform-apps/channels/messages-menu/edit-message-actions.tsx
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx
src/platform-apps/channels/messages-menu/styles.scss
src/platform-apps/channels/styles.scss
src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Add edit message button

---

package-lock.json
package.json
src/app-sandbox/styles.scss

Reverts zer0-os/zOS#267
The context panel expand target didn't load properly.

Revert "Fix channel list scrollbar"

---

src/app-sandbox/styles.scss

Revert "Scroll channel list when it's too long"

---

package-lock.json
package.json
src/app-sandbox/styles.scss

[zos-scrollbar.webm](https://user-images.githubusercontent.com/31045/208738605-95a86b17-ac1d-4b63-8215-9b4c43bc1011.webm)

Scroll channel list when it's too long

---

src/components/link-preview/styles.scss
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss
src/store/messages/api.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

Add send link preview

---

README.md
STYLE_GUIDE.md

Fixes a few typos in the documentation.
Cleanliness
N/A
1. Does this change any APIs? N/A

Fix some documentation typos

---

src/main.scss

add gradient to zns bar

---

public/index.html
src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx

add static background color

---

src/components/autocomplete-dropdown/autocomplete-dropdown.test.tsx

Improves the performance of the autocomplete-dropdown test by not fully rendering the complicated nested component.
Before:
After:
While having the fastest possible tests isn't an end goal in itself, it is a factor in the developer experience. This is a simple change that improves some of our slowest tests.
Run the automated tests.

Shallow render in autocomplete-dropdown tests

---

src/components/message-input/index.test.tsx

Missed removing some stuff when I changed the test to render shallow.
So the lint will pass!
Run the lint

Fix some lint errors in tests

---

.github/workflows/run-build.yml
.github/workflows/run-lint.yml
.github/workflows/run-typecheck.yml
src/components/message-input/index.tsx

Adds a CI action to run the project build, lint, and type checking on PRs
1. We have Lint rules to keep our code consistent
2. We use type checking to try to reduce certain classes of bugs
3. If it can't build then we don't want to merge it
All of these things are important parts of maintaining the project so we want to prevent errors from reaching the main branches.
Each step has been verified in this PR as failing when appropriate and will be successful prior to merging.

Add a CI action to run the build on PRs

---

.github/workflows/development.yml

Deploys `hotfix/**` branches to the development environment for testing hotfixes

Deploy to development on hotfix branches

---

package-lock.json
package.json

Bump the version to test releases and hotfixes

Minor version bump

---

package-lock.json
package.json
src/utils.ts

Adds a log message to test the hotfix process

Add a hotfix log message for testing

---

package-lock.json
package.json
src/utils.ts

Add a hotfix log message for testing (#331)

---

src/utils.ts

Removes test logging used to test hotfixes and releases

Remove test logging

---

src/platform-apps/channels/message.tsx
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx

Add reply permission

---

package-lock.json
package.json
src/_variables.scss
src/components/tooltip/index.test.tsx
src/components/tooltip/index.tsx
src/components/tooltip/styles.scss
src/platform-apps/channels/direct-message-members/index.test.tsx
src/platform-apps/channels/direct-message-members/index.tsx
src/platform-apps/channels/direct-message-members/styles.scss
src/store/direct-messages/direct-messages-fixture.json

- add tooltip on chat hover
- render name instead of members name

- add tooltip on chat hover

---

src/components/inverted-scroll/index.test.tsx
src/components/inverted-scroll/index.tsx
src/components/inverted-scroll/styles.scss
src/components/message-input/index.tsx
src/components/message-input/menu.tsx
src/components/message-input/styles.scss
src/platform-apps/channels/channel-view.tsx
src/platform-apps/channels/container.tsx
src/platform-apps/channels/direct-message-chat/styles.scss
src/platform-apps/channels/styles.scss

Starts styling the message input based on designs
Progress towards the final design
Send messages in both the chat-window and the Channel app.

Initial styling of message input

---

src/components/message-input/index.tsx
src/platform-apps/channels/image-cards/image-card.tsx
src/platform-apps/channels/image-cards/styles.scss

Adds styling to the image preview in the message input.

Style message input image preview

---

src/platform-apps/channels/styles.scss

Styles images, audio, and video in chat

Style multi-media in chat

---

src/components/message-input/styles.scss
src/components/reply-card/reply-card.tsx
src/components/reply-card/styles.scss
src/platform-apps/channels/message.tsx
src/platform-apps/channels/styles.scss

Style replies in chat

---

src/platform-apps/channels/direct-message-chat/index.test.tsx
src/platform-apps/channels/direct-message-chat/index.tsx
src/platform-apps/channels/direct-message-chat/styles.scss

Renders the proper information for one on one and one to many DM chats

Render chat window header for DMs

---

src/platform-apps/channels/message.test.tsx
src/platform-apps/channels/message.tsx
src/shared-components/theme-engine/_theme.scss
src/shared-components/theme-engine/theme.json

Updates the chat timestamp to match the design

Chat timestamp formatting

---

src/platform-apps/channels/direct-message-chat/styles.scss

Style the minimized Chat window to match design

Style minimized chat window

---

src/platform-apps/channels/message.tsx
src/platform-apps/channels/messages-menu/styles.scss
src/platform-apps/channels/styles.scss

Move the message context menu to a hover slide in per design.

Move message context menu to a slide in hover

---

src/platform-apps/channels/direct-message-chat/index.tsx
src/platform-apps/channels/direct-message-chat/styles.scss
src/platform-apps/channels/styles.scss

Don't display the author name when:
1. It's my own message
2. I'm in a one on one chat

Don't display the author name on messages when not necessary

---

src/components/sidekick/styles.scss
src/platform-apps/channels/direct-message-members/styles.scss

ZOS-94 : DM scroll

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/messenger/chat/index.tsx
src/platform-apps/channels/styles.scss

- add sender avatar only in messenger.

add sender avatar to messenger

---

src/platform-apps/channels/styles.scss

fix long direct message

---

package-lock.json
package.json
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

Note: hitting tab focuses on the first item in the channel list
[Before.webm](https://user-images.githubusercontent.com/31045/222263584-19891d91-1625-4b4c-ae66-ad5a0588a19e.webm)
Note: hitting tab focuses on the button, hitting the Enter key creates the conversation
[After.webm](https://user-images.githubusercontent.com/31045/222263621-baaeffa2-d2a0-4484-81c3-14b66f331364.webm)

New message touch up

---

src/components/notification/list/index.test.tsx
src/components/notification/list/index.tsx
src/components/notification/list/style.scss

Adds the empty notifications list design to the notifications popup

Empty Notifications design

---

.github/dependabot.yml

I think this is causing unneeded PRs

Removed dependency-type definition

---

src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/user-actions/styles.scss
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx

Adds the initial UserActions component which renders the user's Avatar.
Migrate towards the new design for the top nav bar.
Connect your wallet and observe!

Add top nav UserActions and user avatar

---

src/components/message/index.tsx

Fix mentions parsing

---

package.json
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/platform-apps/channels/styles.scss
src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Ability to remove link preview from message

---

src/components/notification/item/index.test.tsx
src/components/notification/item/index.tsx
src/components/notification/item/style.scss
src/components/notification/list/container.tsx
src/components/notification/list/index.tsx

- display unread notification state.
- <img width="1198" alt="Screenshot 2023-03-20 at 14 35 24" src="https://user-images.githubusercontent.com/102802882/226374237-f7c7e048-dd0b-4a17-9889-90c8ce995aa4.png">

unread notifications

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss
src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/sidekick/styles.scss

Styles the Conversation List title bar.
Match design

Style Conversation List title bar

---

src/components/messenger/list/index.tsx

Removes some unused props.
Cleanup

Remove unused props

---

src/components/chat-view-container/chat-view-container.tsx
src/components/message-input/container.tsx

Fix lost input focus

---

src/components/notification/popup/index.test.tsx
src/components/notification/popup/index.tsx
src/components/user-actions/index.tsx

- I will add the unit test shortly
- close notification popup when click outside
- we should close notification popup when click outside the popup

close notification when click outside

---

package-lock.json
package.json

release 0.14.0

---

src/components/chat-view-container/chat-view-container.tsx

Fix lost focus

---

package-lock.json
package.json

- use zUI version for all dependencies
we have a conflict in zUI which we cannot get the specified version in package.json

fix zui conflict

---

src/config.ts

This reverts commit ff9cf0492db85783c330391eda54549d3e957e30.

Revert "Debug mode for Sentry (#449)"

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/lib/web3/index.test.tsx
src/lib/web3/index.ts
src/store/authentication/saga.ts

https://user-images.githubusercontent.com/27851097/227242461-43eb4019-375b-44b8-a9a7-2025661caf91.mov

Fix change sessions if account metamask is changed

---

src/components/notification/list/container.test.tsx
src/components/notification/list/container.tsx
src/store/notifications/index.ts

Renders notifications for when someone replies to your message in a channel.

Render channel reply notification

---

src/components/notification/list/container.test.tsx
src/components/notification/list/container.tsx
src/store/notifications/index.ts

Render the notification for being mentioned in a conversation.

Render mentioned in a conversation notification

---

src/main.scss

Aligns the top of the User Actions with the Address bar
Design feedback

Align user actions with address bar

---

src/components/notification/popup/index.tsx
src/components/notification/popup/style.scss

Adds basic scroll functionality to the notifications popup. No design available for this state yet so these are just reasonable guesses for now.
Slightly nicer when you have a full list of notifications.

Add scrollbar to notification popup

---

src/components/notification/popup/index.tsx
src/components/user-actions/index.tsx

Fix closing notification popup

---

src/components/messenger/list/create-conversation-panel.tsx
src/components/messenger/list/styles.scss
src/lib/bem.ts

Cleans up from the structural refactoring. Renames the base block style name in the CreateConversationPanel.
Tidying up.
Ensure creating a one on one converssation still looks correct.

Tidy up some styling in the CreateConversationPanel

---

src/lib/chat/chat-message.ts

https://user-images.githubusercontent.com/33264364/229768828-2c1a020d-b1d8-4239-b5ae-e6e75db0f7ce.mov

[Bug] Parent Message disappears when you're replying to a message

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

Gets the conversation list a little closer to the design.
Note: I think we need to move the scrollbar outside the padding but since that padding is on the parent container it'll take a little be more work than I wanted to invest here.
Features/Design progress

Add some info and styling to the conversation list

---

src/components/messenger/list/conversation-item.tsx

Fixes the icon in the conversation list for groups.

Fix group conversation icon

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/create-conversation/index.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts

Some tidying up of the messenger list component from the recent refactorings.
Tidiness
Test the whole create conversation flow

Remove unused state and redundant calls

---

src/components/app-menu/container.test.tsx
src/components/image-upload/index.test.tsx

Cleans up some tests. It appears these were copy/pasted.

Clean up some tests

---

src/store/create-invitation/saga.test.ts

Temporary fix for test failure unrelated to this test.

Fix test: Add to config stub

---

src/authentication/accept-invite/container.test.tsx
src/authentication/accept-invite/container.tsx
src/authentication/accept-invite/index.test.tsx
src/authentication/accept-invite/index.tsx
src/authentication/accept-invite/styles.scss
src/invite.tsx
src/store/registration/api.ts
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

+ Added error states
+ Updated saga logic
+ Added unit tests
+ Hooked up API integration (PR: [https://github.com/m3m3n70/zero-api/pull/972](https://github.com/m3m3n70/zero-api/pull/972))

Zos 288: Invite Screen (Error states, api integration, unit tests)

---

src/login.tsx
src/store/login/api.ts
src/store/login/index.ts
src/store/login/saga.test.ts
src/store/login/saga.ts

Connects to the login api endpoint and redirects the user to the main page if successful.

Perform actual login on email login page

---

src/authentication/create-email-account/index.tsx
src/authentication/create-email-account/styles.scss
src/authentication/validate-invite/index.tsx

Adds the login links on the initial registration pages per the design

Add login links to existing registration pages

---

src/components/rewards-popup/styles.scss

Adds an animation to the rewards popup

Add fadein of rewards popup

---

src/components/reply-card/styles.scss
src/platform-apps/channels/styles.scss

Fixes the over flow when replying to a long message.

Fixed reply overflow

---

src/components/rewards-popup/styles.scss

Received a background image for the rewards popup. This adds it.

Change rewards popup background

---

src/Main.tsx
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/platform-apps/channels/styles.scss
src/store/layout/index.ts

Adds icons to move in/out of messenger full screen mode from the chat window.
Initial styling to make the chat fit the new messenger full screen layout.

Give chat window ability to render in full screen messenger layout

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/store/authentication/types.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts

Forces the app into full screen messenger mode if the user is not a member of worlds.

Force full screen messenger if not a member of worlds

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/sidekick/index.tsx

Removes the sidekick title bar if the user isn't a member of worlds

Hide titlebar on sidekick when in forced fullscreen

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

Hides the sidekick close button when in full screen mode

Don't render sidekick close icon when in full screen mode

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

Allows expanding to full screen messenger from the sidekick

Add expand button to sidekick

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

Render the current user's avatar in the rewards bar when fullscreen

Add avatar to rewards bar

---

src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss

Ensures the full screen messenger window is sized appropriately

Ensure full screen message window is sized properly

---

src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss

Moves the rewards popup based on the layout the user is in

Position rewards popup based on current layout

---

src/components/chat-view-container/chat-view.tsx
src/components/messenger/list/index.tsx
src/platform-apps/channels/styles.scss

Styles the full screen conversation based on the design with received on the left and sent on the right at various max width proportions based on window size.

Style the full screen conversation with messages split into right/left

---

src/store/channels-list/channels.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Opens the initial conversation for the user when they've first completed the registration process.
Register as a new user and verify that once they've completed the registration process (i.e., set their Name) the app opens and the very first conversation is open and ready.

Open the initial conversation when a user first logs in after registering

---

src/authentication/create-account-details/container.test.tsx
src/authentication/create-account-details/container.tsx
src/authentication/create-account-details/index.test.tsx
src/authentication/create-account-details/index.tsx
src/authentication/create-account-details/styles.scss
src/store/registration/api.ts
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Adds uploading of profile image to the profile creation screen

Add profile image to account details creation screen

---

src/components/rewards-faq-modal/constants.tsx

remove extra text in rewards-faq-modal

---

package-lock.json
package.json

Bumps zUI to the latest version.

Bump zui version

---

src/store/registration/saga.ts

Refactors the main registration saga by pulling out clearly named functions.
Much easier to follow the user's journey.
Register!

Refactor: clean up registration saga to make phases more clear

---

src/store/create-invitation/saga.ts

Noticed an error in the invite fetch saga. This fixes it. Just a typo.

Fix a saga error

---

package-lock.json
package.json
src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

[JIRA](https://wilderworld.atlassian.net/browse/ZOS-332)
- Adds enhancer to `Invite Friends` button
- Adds ability to Control+A invite text
- Pointer cursor on button
Design feedback.
Open the `Share Friends` dialog, test the above functionality works.

feat: design feedback on Create Invite modal

---

src/components/invite-dialog/container.test.tsx
src/components/invite-dialog/container.tsx
src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss
src/store/create-invitation/index.ts
src/store/create-invitation/saga.test.ts
src/store/create-invitation/saga.ts

Zos 289: Show remaining invites in `invite-dialog`

---

src/components/messenger/lib/utils.tsx
src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

[https://wilderworld.atlassian.net/browse/ZOS-439](https://wilderworld.atlassian.net/browse/ZOS-439)
Before:
After:

Zos 439 fix media preview display in conversation list sidebar

---

src/Main.test.tsx
src/Main.tsx
src/_layout.scss

[JIRA](https://wilderworld.atlassian.net/browse/ZOS-388?atlOrigin=eyJpIjoiMWYzNTBlMDA1NDA4NDI4Zjk0NWYyYWYxMjk4ZTgyNTEiLCJwIjoiaiJ9)
zOS
Messenger

Remove Network bar from zOS + messenger

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

Before
After (`ratik-new` is highligted as it is current conversation, same as hover state)

Zos 396 highlight current conversation in conversation list sidebar

---

src/components/messenger/chat/index.tsx
src/store/channels-list/api.ts
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts
src/store/login/saga.test.ts
src/store/login/saga.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

[JIRA](https://wilderworld.atlassian.net/browse/ZOS-387?atlOrigin=eyJpIjoiMjNjZWJiMjAzMTM5NDRkM2E2ZDUwNjMyNWVlZTA0MjIiLCJwIjoiaiJ9)
https://github.com/zer0-os/zOS/assets/33264364/c8666168-edd9-4729-a3f4-cdb33bc00983

Display most recent conversation in main container as default conversation on login

---

public/index.html

Update the favicon

---

src/store/channels-list/api.ts

I am seeing `undefined` error on prod (but shows correctly on my local). So added a `?? error` to log.

Update Error text while fetching channels, conversations

---

src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/store/create-invitation/saga.test.ts
src/store/create-invitation/saga.ts

Reloads the invite data each time you click on "invite friends" button.
Earlier this only fetched a single time.

Zos 485: Invite data reload when opening the dialog

---

src/pages/login/login-component.test.tsx
src/pages/login/login-container.test.tsx

Adds unit tests to `login-component` and `login-container`.
There were previously no tests.
Run `npm test pages/login`, or look at the CI test output.

test(login): add unit tests

---

src/components/settings-menu/index.tsx

https://github.com/zer0-os/zOS/assets/39112648/d90dee66-f2fe-47ab-9130-2f13577b4995
https://github.com/zer0-os/zOS/assets/39112648/ed17ac92-4859-4b66-81ad-7fca772d9acb
- run the app and click on the avatar in the top left corner of the messenger.

feat: set isActive state for avatar component used in settings dropdown menu

---

src/store/layout/saga.ts
src/store/rewards/saga.ts

Show rewards tooltip only in Messenger (full screen) mode

---

src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

no new conversation
no new member (in group chat)

Antiphonal search text fixes

---

src/components/messenger/list/index.tsx
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx

- only show the rewards tooltip if in fullscreen

Fix rewards tooltip

---

src/components/message-audio-recorder/index.tsx
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/menu.test.tsx
src/components/message-input/utils.ts
src/lib/api/attachment.ts
src/lib/chat/chat-message.ts
src/platform-apps/channels/attachment-cards/attachment-card.tsx
src/platform-apps/channels/attachment-cards/index.tsx
src/platform-apps/channels/attachment-cards/styles.scss
src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

[JIRA](https://wilderworld.atlassian.net/browse/ZOS-464?atlOrigin=eyJpIjoiZGNmNzQzM2IxZTRlNDUxYzhiMjJjODgwMjdkYTRhNmEiLCJwIjoiaiJ9)
Allows the user to attach pdf & text files. Includes some small refactorings as well.
https://github.com/zer0-os/zOS/assets/33264364/fc6fdd62-5830-4d37-912b-ce5d822ce9cc

Zos 513 UI allow users to send text pdf files

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/menu.tsx
src/components/message-input/styles.scss

Note: This component needs further updates to be in line with design. These can be made in another PR as this task specifically focuses on Icon size and positioning. Some refactoring was required. I'd quite like to dig in and tidy all of this up to be honest, it's a bit hard to navigate!
Before:
After:

fix: compose message icon sizes 

---

src/icon-mocks.ts

Updates the zUI component mocks as we've had some new ones lately

Update component mocks

---

src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx

A couple of copy changes:
- ZERO -> $ZERO
- Zero -> ZERO
Matching UI to Figma.
1. Open the rewards modal
2. Check the reward amount is in $ZERO
3. Check that any mention of ZERO is uppercase

feat(rewards-pop-up): copy updates

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.test.ts

Moves some saga tests to a separate file to make working with them easier.

Move send message tests to new file

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/menu.test.tsx
src/components/message-input/utils.ts

add support sending `.zip` files

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Improves the testing around sending a message:
* Tests more thoroughly with independent tests
* Simulates failures properly
Also fixes a couple of bugs that existed and were exposed while improving the testing.
New work will be happening in this area so this is to enable more confident modification.

Improve the testing around sending a message

---

src/components/message-input/index.tsx
src/components/message-input/styles.scss

- adds scroll to message input

feat: add scroll to message input

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts

Improves the test coverage for receiving a real time message. Includes very minor tweaks to the production code.
Future changes to how this works are incoming. This allows us to more confidently make those changes.

Improve the testing around receiving a new real-time message

---

src/store/channels/saga.test.ts
src/store/messages/saga.fetch.test.ts
src/store/messages/saga.receiveNewMessage.test.ts

Adds test coverage around marking messages as read refactor.

Add tests for updated `markMessagesAsRead` logic

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Changes the message send error handler to refetch the current message state when a message fails
If other things happened prior to the actual send failing then we'd lose all the new activity. This fixes that.

Reference current state when handling message send failure

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

When we're sending a message we get a response from the server but we were ignoring it. This now uses that result to replace the previously rendered optimistic message.
Note: It's still possible to get the real-time event sooner than the send message response so we leave the real time parsing in so that the soonest result replaces the message.
Currently this replacement happens when we get the real time event from sendbird for the message. But, we have the data right now so we might as well use it.
* Send a message
* After a couple of seconds try to edit it. If it is editable then we've correctly replaced the optimistic message

Replace optimistic message as soon as the send is successful

---

src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts

Improves the testing around the `uploadFileMessage` saga
To allow refactoring and enhancements

Improve the tests around uploading file messages

---

src/store/messages/api.ts
src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts

Some refactoring of the `uploadFileMessage` saga
Just some tidying up.

Minor refactoring of uploadFileMessage

---

src/store/page-load/saga.test.ts
src/store/page-load/saga.ts

A commit i had missed to push during the test review - [this](https://github.com/zer0-os/zOS/pull/759#discussion_r1258606800) one.

Update page-load test

---

src/components/content-highlighter/styles.scss
src/components/message/styles.scss

Un-nests some of the message styles
Easier to find/understand things. Preparation for making modifications.

Unnest message styles

---

src/components/message/index.tsx
src/components/message/styles.scss

Removed some styles that weren't impacting anything

Remove some unused styles

---

src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/utils.tsx

IF you enter `/` or `*`..etc it breaks the whole app. 
Before
https://github.com/zer0-os/zOS/assets/33264364/e37383b4-93dc-4b79-930a-c6bf82a8a1bb
After
https://github.com/zer0-os/zOS/assets/33264364/ba7a46b5-1e24-4808-a1e4-d903846f1524

Zos 564 entering a special character eg (`/`) in conversations search breaks the app

---

package-lock.json
package.json

- chore: bump zui version (`0.25.1`) -> (`0.25.2`)

chore: bump zui version (`0.25.1`) -> (`0.25.2`)

---

src/components/message/styles.scss
src/platform-apps/channels/messages-menu/styles.scss

Fix Padding/Margin issue with the message bubbles sent quickly

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

This ensures we don't clobber the most current lastMessage information when polling for conversations.
Now that we're optimistically rendering messages the regular conversation poll can get different information than what we have in memory.

When fetching the conversation list ensure we don't override optimistic information

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/platform-apps/channels/styles.scss
src/store/channels-list/saga.ts
src/store/channels/index.ts
src/store/messages/saga.ts

Messenger (full screen):
https://github.com/zer0-os/zOS/assets/33264364/e684c03c-dbd9-41a2-a554-0284ad40f368
Channel on zOS:
https://github.com/zer0-os/zOS/assets/33264364/4286c6d6-fa63-4da7-be67-5fdce761bf04
Messenger (normal):
https://github.com/zer0-os/zOS/assets/33264364/64a76adb-0b07-4c0a-89d7-ea2e302c705c

Zos 578: Show error when messenger gets stuck in perma skeleton loader state

---

src/components/edit-profile/container.tsx
src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss
src/components/image-upload/index.tsx
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/store/authentication/channels.ts
src/store/authentication/saga.ts
src/store/edit-profile/api.ts
src/store/edit-profile/index.ts
src/store/edit-profile/saga.ts
src/store/reducer.ts
src/store/saga.ts

Enables users to edit their profiles. 
SC:
Flow:
https://github.com/zer0-os/zOS/assets/33264364/0ae90a9c-770d-454c-956a-1ac703c7089b

Zos 600: Enable users to edit their profile

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts
src/store/saga.ts
src/store/users/index.ts
src/store/users/saga.test.ts
src/store/users/saga.ts

Stores the user search results into the data store so that we can use them when optimistically rendering a new conversation.
https://github.com/zer0-os/zOS/assets/43770/b4f7ec87-e93a-4117-a66d-5f85c5e6115b
https://github.com/zer0-os/zOS/assets/43770/771f4a73-0676-4af7-b7ac-68311295a1fd

Store user search results

---

src/components/dev-panel/container.tsx
src/components/dev-panel/conversations/index.tsx
src/components/dev-panel/conversations/styles.scss
src/components/dev-panel/index.tsx
src/components/dev-panel/messages/index.tsx
src/components/dev-panel/messages/styles.scss
src/components/dev-panel/styles.scss

Adds conversations to the dev panel
To enable quicker testing of various conversation creation states

Add Conversations to the dev panel

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss
src/components/dev-panel/conversations/index.tsx
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts
src/store/channels/index.ts

Renders an error if an optimistically rendered conversation fails to create
User feedback

Render error if the conversation fails to create

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx

Zos 469: Adjust preview text behavior in conversations list sidebar when files images are received

---

src/authentication/create-account-method/index.test.tsx
src/authentication/create-account-method/index.tsx
src/authentication/create-email-account/index.tsx
src/authentication/create-email-account/styles.scss
src/components/wallet-select/styles.scss
src/lib/password.test.ts
src/lib/password.ts
src/pages/login/login-component.test.tsx
src/pages/login/login-component.tsx
src/pages/login/login.scss
src/store/registration/saga.ts
src/store/web3/saga.test.ts
src/store/web3/saga.ts

- removes wallet icon backgrounds
- update toggle group logic (show when creating account via email)
- updates alert messages
- adds option to log in footer
- updates success variant for password validity
- some ui tweaks
- as per product QA feedback/figma designs.

fix: sign up and log in flow feedback 

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/styles.scss
src/components/messenger/list/utils.tsx

Zos 576 group chat icons not displaying in the conversation header

---

src/lib/chat/sendbird-client.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts

1. Renames the function
2. Renames the parameter

Refactor channel mapping function

---

src/components/message/index.tsx
src/components/message/styles.scss

Fixes the max-height of images in messages.

Fix max height of images in messages

---

src/components/messenger/list/conversation-item/index.tsx

Removes an unused method that was missed previously

Remove unused method

---

package-lock.json
package.json
src/components/edit-profile/styles.scss
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss
src/components/message-audio-recorder/index.tsx
src/components/message/index.tsx

- replaces `IconButton` with `zUI` `IconButton` and checks no distorted or broken icons.
- updated `IconButton` in latest `zUI` version.
- run the messenger and check icons displayed.

feat: update IconButton's (zUI component)

---

src/components/rewards-popup/styles.scss

Fixes a sass deprecation warning

Fix scss deprecation warning

---

src/components/messenger/list/conversation-list-panel/index.test.tsx
src/components/messenger/list/conversation-list-panel/index.tsx
src/components/scrollbar-container/index.test.tsx
src/components/scrollbar-container/index.tsx

Before:
https://github.com/zer0-os/zOS/assets/33264364/aa3df655-9ce3-4070-adee-4c2d3c9084e0
After
https://github.com/zer0-os/zOS/assets/33264364/3721fc00-a14c-4fef-be18-507fcaf706a5

Searching conversations list should reset scroll position

---

src/components/content-highlighter/content-highlight.test.tsx
src/components/content-highlighter/index.tsx
src/components/message/index.tsx

Removes a new unused Component property

Remove unused property

---

src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/utils.ts

Fixes the message model type to match what's actually happening

Fix the Message model type

---

src/components/message-input/menu/menu.test.tsx
src/components/message-input/menu/menu.tsx
src/components/message-input/menu/styles.scss
src/components/message-input/utils.ts

Pops up a toast notification if the file size exceeds the limit (currently 10MB)
https://github.com/zer0-os/zOS/assets/33264364/1d4dcc5b-3667-434b-9c80-68c821ac01cd

Zos 611: Send toast notification if the file a user is trying to attach exceeds the size limit

---

src/components/chat-view-container/chat-view.tsx
src/components/message-input/index.test.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/parent-message/index.test.tsx
src/components/message/parent-message/index.tsx
src/components/message/parent-message/styles.scss
src/components/message/styles.scss
src/lib/chat/chat-message.ts
src/lib/chat/types.ts
src/store/messages/index.ts
src/store/messages/utils.ts

Applies a restyling for reply messages in the conversation
Sender view
Receiver view

New style for replies in message list

---

src/components/message-input/container.tsx
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/styles.scss
src/components/messenger/chat/styles.scss
src/components/reply-card/reply-card.test.tsx
src/components/reply-card/reply-card.tsx
src/components/reply-card/styles.scss

Restyles the reply quote to be above the message input and have the new style

Restyle the reply card when replying

---

src/store/page-load/saga.ts

Extracts separate functions for the page load logic
Preperatory refactoring for adding more logic to the page load.
Load the page in various logged in/out states and verify things are redirected as before.

Refactor: Extract methods for page load handling

---

.env.example
src/authentication/android-download/index.test.tsx
src/authentication/android-download/index.tsx
src/authentication/android-download/styles.scss
src/config.ts
src/invite.tsx
src/lib/browser/index.ts
src/pages/login/login-container.tsx
src/store/page-load/index.ts
src/store/page-load/saga.test.ts
src/store/page-load/saga.ts

Adds a notice to download the Android app on the login and registration pages

Add Android App download suggestion

---

package-lock.json

Remove lodash.debounce

---

src/components/content-highlighter/styles.scss
src/components/message/styles.scss

Implement new design for @-mentions so they do not affect line spacing

---

.prettierrc.json
src/components/address-bar/container.tsx
src/store/messages/saga.fetch.test.ts

Refactors some tests:
* Uses the more correct StoreBuilder
* Removes some duplicated tests
* Formatting
Hopefully make the tests easier to scan

Refactor the message fetch saga tests

---

src/components/link-preview/index.test.tsx
src/components/link-preview/index.tsx
src/components/link-preview/styles.scss
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss

Applies new styling for the link previews in messages

Restyle link previews

---

package-lock.json
package.json

- chore: bump zui version (`0.26.4`) -> (`0.26.6`)

chore: bump zui version (`0.26.4`) -> (`0.26.6`)

---

.github/workflows/development.yml
.github/workflows/production.yml

Adds the new Matrix env var to the deploys

Add Matrix home server url to the deploys

---

src/components/edit-profile/container.test.tsx
src/components/edit-profile/container.tsx
src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/store/authentication/saga.ts
src/store/edit-profile/api.ts
src/store/edit-profile/saga.ts

Data for current user's matrix ID, token comes from the backend now.

Use { matrixId, accessToken } from `/current` user

---

src/components/messenger/list/conversation-item/index.tsx
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

Fixes the Matrix Room to Conversation mapping to detect one on ones correctly.

Identify one on one Matrix conversations

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

Sometimes the AccountData isn't updated immediately. This is an additional check that adds some reliability to whether the message is a Conversation or not.

Add extra check on Conversation filter

---

src/lib/chat/chat-message.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts

Moves matrix message mapping functions to `/matrix/chat-message.ts`.

Move `mapMatrixMessage` to `/lib/chat/matrix/chat-message.ts`

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

- updates room (conversations and channels) name changes in real time.
- so a room name change will be updated in real time for all users.
- make a room name change in element and check this is updated in real time in zos.
Demo:
https://github.com/zer0-os/zOS/assets/39112648/27becaa1-eb9b-49a6-a9f3-e607c243e047

feat: (matrix) publish and update room name change

---

src/lib/chat/matrix-client.ts

Changes the public facing functions of the Matrix client to always wait for the resolve connection promise and creates the promise as soon as the class is instantiated to ensure it's there to wait for.
Noticed we had some cases where we were calling into Matrix before the connection had even been attempted. This was causing failures upon rendering the app the first time.
Load the app and verify that it loads as it did previously

Wait for an active connection in all our public matrix functions

---

src/lib/chat/matrix-client.ts

- gets all messages for a room and adds these to the mapToGeneralChannel. 
- suggested refactor for obtaining lastMessage data.
- removes the need to set `lastMessage` property. Our existing logic handles last message data using the messages data.
- open messenger > in the conversation list if a conversation has existing message history you should see the preview for the last/latest message sent. In addition, the conversation list items should be sorted in order based on the conversation with the latest message event.

refactor: get all messages from room and remove last message mapping

---

src/lib/chat/matrix-client.ts

Rooms can become invalid if all the people who have joined the room end up leaving. This handles that scenario for those who receive the invite "late" and are trying to auto-join.
To ensure the app renders fully. The user will just never know they were invited to this, now defunct, room.
With person B logged out of zOS (i.e., no browser loaded) user person A to invite them to a conversation. In Element as person A, leave the conversation. Now load zOS as person B. You should find that the app still loads properly and doesn't "black screen" or anything.

Handle auto join failures by ignoring them

---

src/lib/chat/matrix-client.ts
src/store/channels-list/api.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts

Just changes the implementation a little - use a local map, and set the zero users after fetching them (from the matrixIds).

use map for zero users in `matrix-client.ts`

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts

Maps all the channel.messages & conversations.messages *sender's* to their ZERO profile.

Map channel/conversation message while loading channel + conversations in Matrix

---

src/store/messages/saga.ts

It's possible that while mapping the senders of a message in a channel, that the user is NOT found in our local cache (i.e `state.normalized.users`). In this case we need to grab it's matrix ID, and call the API to fetch it's profile (as it could be the case that the user is no longer a member of channel).

Handle case if member is not found in `state.normalized.users` while mapping senders

---

src/lib/chat/matrix-client.ts

Small refactoring to simplify a few of the room state getters

Refactor: Simplify current room state getters

---

src/store/messages/saga.ts

Revert "Remove `''` while selecting messages in `rawMessagesSelector`"

---

src/store/messages/saga.ts
src/store/messages/utils.matrix.test.ts
src/store/messages/utils.matrix.ts

Add tests for `mapMessageSenders` in `store/messages/utils.matrix.test.ts`

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

**NOTE** - still need to look into the weird state behaviour we're getting with the conversation list while creating a new conversation.
https://github.com/zer0-os/zOS/assets/33264364/0634195a-2887-44d4-b25d-ec925035756d

Fix issue where Matrix id displays in conversation and as conversation name when creating new conversation

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/lib/chat/matrix/types.ts
src/lib/chat/sendbird-client.ts
src/store/messages/api.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Introduces the capability to handle and process edited messages. Key changes include:
- Implementing functionality to determine if a message is an edit event.
- Refactoring message handling logic to account for edited messages and update the original message content accordingly.
- Introducing mechanisms to listen for edited message events and respond with the appropriate updates.
- Refactoring related functions for better clarity and reduced code repetition.
To ensure that our matrix client can effectively handle message edits.
Open the messenger > Send a message > Click the three dots message menu > Select `Edit` > Edit the message and submit > Check message has been edited.
NOTE: The …

feat: (matrix) edit message

---

src/components/message-input/index.tsx

Hides the image/attachment icons and disabless drag and drop

Hide image/file attachment options

---

src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-faq-modal/constants.tsx
src/components/rewards-popup/index.tsx

- updates copy `ZERO` to `MEOW` in the relevant places.
- token name change.

feat: zero ticker name to meow ticker name copy changes

---

src/components/message-input/index.tsx

Hides the microphone icon when in Matrix mode.

Don't show voice message icon in Matrix mode

---

src/components/message-input/index.tsx

Disables image paste in Matrix mode

Disable image clipboard paste in Matrix mode

---

src/Main.tsx
src/main.scss

Hide the zNS address bar in Matrix mode

Don't show the Address Bar in Matrix mode

---

src/components/user-actions/index.tsx

Hides the notificatio icon in Matrix mode since it's not usable

Hide Notification icon in Matrix mode

---

src/components/messenger/list/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx

refactor: (rewards-container) zero token name to meow

---

src/components/messenger/list/index.tsx
src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx

refactor: (rewards-popup) zero token name to meow

---

src/components/messenger/list/index.tsx
src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/store/rewards/index.ts
src/store/rewards/saga.test.ts
src/store/rewards/saga.ts

refactor: (rewards saga function names) zero token name to meow

---

src/components/messenger/list/index.tsx
src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/store/rewards/api.ts
src/store/rewards/index.ts
src/store/rewards/saga.test.ts
src/store/rewards/saga.ts

refactor: (rewards api function name) zero token name to meow

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss
src/store/rewards/api.ts
src/store/rewards/index.ts
src/store/rewards/saga.test.ts
src/store/rewards/saga.ts

refactor: (zero token class names and constants) zero token name to meow

---

src/components/secure-backup/container.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/components/secure-backup/styles.scss
src/lib/chat/matrix-client.ts
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Adds success and failure messaging to the Secure Backup flow

Add success and failure messaging

---

src/lib/chat/index.ts
src/store/matrix/index.ts

Add better typing to some of the Secure Backup stuff

---

src/Main.test.tsx
src/components/message-input/index.test.tsx
src/components/user-actions/index.test.tsx
src/lib/feature-flags.ts
src/store/messages/saga.fetch.test.ts

Changes the `enableMatrix` flag to default to `true`
To turn on Matrix for real.

Change the Matrix feature flag to default to true

---

src/lib/chat/sendbird-client.ts
src/store/channels-list/api.ts

- removes unused api request from channels-list store.
- removes unused api function and keeps the `api.ts` file up to date with what is used.

refactor: remove channels-list store create conversation api request

---

craco.config.js
package-lock.json
package.json
src/index.scss

This updates zUI to the latest version which includes an update to the underlying radix-ui dropdown menu
The very old 0.X version of the radix component has rendering performance problems that have been fixed in newer versions.
3 second performance profile before (no user activity).  Note how the browser is almost constantly active even with no user activity or app activity.
Zoomed in showing the radix function that is running so constantly:
3 second performance profile after (no user activity). Note how there's almost no activity when the nothing is actually happening.

Fix an issue with rendering performance

---

src/components/dev-panel/conversations/index.tsx
src/components/dev-panel/encryption/container.tsx
src/components/dev-panel/encryption/index.tsx
src/components/dev-panel/encryption/styles.scss
src/components/dev-panel/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Adds some Matrix debug info to the dev panel
To help us troubleshoot decryption issues
Enable the dev panel. Open it and view the Encryption tab.

Add Matrix debugging information to dev panel

---

src/components/dev-panel/encryption/container.tsx
src/components/dev-panel/encryption/index.tsx
src/components/dev-panel/encryption/styles.scss
src/components/messenger/list/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/matrix/index.ts
src/store/matrix/saga.ts

Adds some encryption related options for troubleshooting possible recovery mechanisms
Generating consistend decryption errors is proving difficult. Adding these to the dev panel so we can selectively try some in production.

Add some encryption related troubleshooting options in the dev panel

---

src/lib/chat/matrix-client.ts

Bug fix: await the various logout steps

Await logout

---

src/lib/chat/matrix-client.ts

- refactors lengthy process raw events to messages function in the matrix client.
- This refactoring aims to make `processRawEventsToMessages` more readable by delegating specific tasks to helper methods.
- Open messenger and ensure admin messages and messages render correctly, and editing a message functionality remains the same.

refactor: tidy up process raw events to messages function

---

src/components/messenger/list/group-management/container.test.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/test/store.ts

Wraps the GroupManagement component with a Container to isolate state management

Wrap the GroupManagment component with a Container

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/store/test/store.ts

Now that the component is extracted this tidies up some prop names, etc, to be more context appropriate.

Refactor: tidy up properties and imports from extract component refactoring

---

src/components/group-management-menu/index.test.tsx

Refactor: group management menu tests

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/messenger/chat/index.tsx

Move business logic for add members permission outside the menu

Refactor: Change AddMember permission check to happen outside menu

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx

Adds a stub component for editing the conversation details

Add EditConversationPanel stub

---

src/components/messenger/list/add-members-panel/index.test.tsx
src/components/messenger/list/add-members-panel/index.tsx
src/components/messenger/list/add-members-panel/styles.scss
src/components/messenger/list/group-management/container.test.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/group-management/index.ts
src/store/group-management/saga.test.ts
src/store/group-management/saga.ts

- submits the selected members and adds member/s to active conversation.
- to ensure state and client update with newly added members to room/conversation.
- Open messenger > window.FEATURE_FLAGS.enableGroupManagementMenu = true; > window.FEATURE_FLAGS.enableAddMemberToGroup = true; > Click three dot menu > Select Add Member > Add Member panel should be displayed in the sidekick (messenger list) > Add new member > Check conversation / room contains new member/s.
Add Members
https://github.com/zer0-os/zOS/assets/39112648/135c243f-6e97-4186-bb48-0c243817645c

feat: submit selected members and add to room

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx

Prevents editing a conversation if it is a one on one

Do not allow editing a conversation if it is a one on one

---

src/components/citizen-list-item/index.test.tsx
src/components/citizen-list-item/index.tsx
src/components/citizen-list-item/styles.scss
src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx
src/components/messenger/list/edit-conversation-panel/styles.scss
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx

Lists the users currently in the conversation on the Edit Conversation panel

Edit Conversation: List the users

---

src/components/citizen-list-item/index.test.tsx
src/components/citizen-list-item/index.tsx
src/components/citizen-list-item/styles.scss
src/components/messenger/list/edit-conversation-panel/index.tsx
src/components/messenger/list/edit-conversation-panel/styles.scss

1. Added remove icon to CitizenListItem
2. Added tag to CitizenListItem
3. Add scrollbar to the edit group panel

Add Remove icon to CitizenListItem

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/group-management/index.ts
src/store/group-management/saga.test.ts
src/store/group-management/saga.ts

Implements the remove member from room logic.
Note, still to come:
* Confirmation Dialog
* Ensuring the leave events are processed upon browser refresh (bug affecting most room events)
https://github.com/zer0-os/zOS/assets/43770/6c77ab17-fd6a-493d-b8c3-4ef52b5a652b

Remove member from room

---

templates/container/container.test.tsx.mustache
templates/container/container.tsx.mustache
templates/generate.js

Adds a basic template for component containers

Add a container generator template

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx
src/components/messenger/list/group-management/container.test.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/group-management/index.ts
src/store/group-management/saga.test.ts
src/store/group-management/saga.ts
src/store/group-management/types.ts

Adds the saga logic to actually make the API call to matrix to update the icon/url.
(normal case)
https://github.com/zer0-os/zOS/assets/33264364/0592151d-93b2-4c4f-88c0-0f4e95a64b66
(case when setting a name to "empty", and vice versa)
https://github.com/zer0-os/zOS/assets/33264364/b7335aa5-0a89-41e8-9ccb-2557d267c1eb

Edit Conversation (Name, Icon): Saga logic

---

package-lock.json
package.json

Updates zUI
The ModalConfirmation has had some functionality and style tweaks

Update zUI to 0.28.0

---

src/components/citizen-list-item/index.test.tsx
src/components/citizen-list-item/index.tsx

Minor refactor to use library function rather than component code

Use utility for display name

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message/index.tsx
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/lib/chat/index.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/saga.ts
src/store/messages/saga.fetch.test.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.test.ts
src/store/messages/utils.matrix.ts
src/store/rewards/saga.ts

Starts to remove usages of the `enableMatrix` feature flag so we can begin to remove the complexity of having multiple paths.

Remove numerous uses of the enableMatrix feature flag

---

src/Main.tsx
src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss
src/components/message-input/styles.scss
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/sidekick/styles.scss
src/index.scss
src/main.scss
src/platform-apps/channels/styles.scss

+ Updates conversation panel, conversation header, and message input to have 
- 16px padding all around
- 16px border radii
+ Adds the new background image
+ Adds gradient to the top of conversation header behind

[Matrix] REDESIGN 01: Structural UI Changes

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.test.ts
src/store/messages/utils.matrix.ts
src/store/registration/saga.ts

The getZEROUsers api call was recently updated to return a proper domain User object but some spots were still assuming the bad data structure. This fixes those spots.

Fix usages of getZEROUsers api call

---

src/store/channels-list/selectors.ts
src/store/layout/saga.test.ts
src/store/login/saga.test.ts
src/store/login/saga.ts

This fixes the selection of the most recent conversation after login

Select the most current conversation after login

---

src/components/user-actions/container.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/wallet-manager/index.tsx
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts
src/store/layout/types.ts

Removes functionality related to opening/closing sidekick, since it's always open now.

Remove code related to `updateSidekick`

---

src/Main.test.tsx
src/Main.tsx
src/app-sandbox/index.tsx
src/components/user-actions/container.test.tsx
src/components/user-actions/container.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/lib/chat/matrix-client.ts
src/store/authentication/saga.test.ts
src/store/layout/constants.ts
src/store/layout/index.test.ts
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts
src/store/layout/types.ts

removes code related to `isSideKickOpen`.

Remove `isSideKickOpen` global var

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx

- prevent add member when one on one conversation

fix: prevent add member when one on one conversation

---

src/components/messenger/list/styles.scss

refactor: remove unused messenger list header styles

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

- removes rewards from messenger list
Before
After

refactor: remove rewards from messenger list

---

src/store/registration/saga.test.ts
src/store/registration/saga.ts

We found a bug where the inviter id wasn't getting set properly on the custom "User joined zero" event. This fixes it.

Fix custom user event when user joins zero

---

src/_glass.scss
src/components/sidekick/styles.scss

Adds the border around glass panels

Add glass panel border

---

src/components/sidekick/styles.scss

Some dumb guy 👀  removed the background which removed the gradient on top of conversation list. Re-added.

Re-add background to `sidekick/styles.scss`

---

src/store/channels-list/api.ts

Fix return type

---

src/_glass.scss

Removes the glass border until a fix for the icon button can be made

Remove glass border

---

src/store/messages/saga.ts

Remove saga that was only used in publicZOS mode

---

src/components/link-preview/styles.scss

ZOS Redesign: Link previews

---

package-lock.json
package.json

- chore: bumps zui `(1.1.0)` -> `(1.2.0)`

chore: bump zui `(1.1.0)` -> `(1.2.0)`

---

README.md

Updates the README information

Update README for latest Matrix development

---

src/_glass.scss
src/components/messenger/list/conversation-item/conversation-item.scss

- removes unused mixin parameters.
- the params are not required and therefore should be removed for simplicity.

refactor: remove unused mixin parameters

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts

We're permanently in full screen mode for Messenger so this removes all the bits that were handling the moving in/out of fullscreen mode

Remove code that opens/closes full screen mode

---

src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss

- updates the invite dialog content.
- to align with figma designs as part of the redesign.
> open messenger > in the conversation panel, click the `Invite Friends` button > check invite dialog modal.

feat: update invite dialog

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message-input/container.tsx
src/components/message-input/giphy/giphy.test.tsx
src/components/message-input/giphy/giphy.tsx
src/components/message-input/index.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/rewards-button/index.test.tsx
src/components/rewards-button/index.tsx
src/components/rewards-container/index.test.tsx
src/components/rewards-container/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx

Removes references to `isMessengerFullScreen` in most of the components

Remove component references to isMessengerFullScreen

---

src/authentication/create-account-method/index.tsx
src/lib/feature-flags.ts
src/pages/login/login-component.tsx

Change feature flag to disable email registration and disable it by default.

Disable email registration

---

src/lib/feature-flags.ts
src/store/authentication/saga.ts
src/store/layout/saga.ts
src/store/page-load/saga.test.ts
src/store/page-load/saga.ts

Removes the state related to public ZOS view since we no longer have that mode

Remove public zos layout state

---

src/store/page-load/saga.test.ts

Refactors the page load saga tests to use some of our more current conventions

Refactor page load tests

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/feature-flags.ts

Adds a feature flag to quiet some of the extra Matrix logging

Add flag to disable the verbose Matrix logging

---

src/main.scss
src/shared-components/theme-engine/_theme.scss

Removes old css classes that are no longer used

Remove old css classes

---

package-lock.json
package.json
src/components/messenger/list/view-group-information-panel/index.test.tsx
src/setupTests.ts

Some refactoring of the tests to simplify and make a little more readable.

Refactor group information panel tests

---

src/components/messenger/list/edit-conversation-panel/index.tsx

-  updates admin tag (`admin`) -> (`Admin`)
- as per figma design

refactor(edit-conversation-panel): update admin tag (`admin`) -> (`Admin`)

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/utils/utils.test.ts
src/components/messenger/list/utils/utils.tsx

- simplifies the group management `sortMembers` function,
- improve code quality and readability.

refactor: simplify group management sort members function

---

src/components/messenger/chat/index.test.tsx

- refactors the messenger chat tests.
- improves code quality/tests.

refactor: tidy up messenger chat tests

---

src/components/messenger/chat/index.test.tsx
src/lib/chat/matrix-client.ts
src/store/channels-list/channels.ts
src/store/channels-list/saga.ts
src/store/chat/saga.ts

Refactor matrix events, publish custom event when current users joins channel

---

src/lib/web3/connectors.ts
src/lib/web3/index.ts

Adds the sepolia network to allow for testing on development.

Add sepolia network

---

src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss

Update Edit Profile Modal design (part of redesign changes)

---

.github/workflows/development.yml
.github/workflows/production.yml

- removes `REACT_APP` from the dev & prod `.yml`  config environment variable (`REACT_APP_ZNS_EXPLORER_URL`)
- to align with other env variables in these files.

feat: update development and production config zns explorer env variable

---

src/store/edit-profile/saga.test.ts

Fix failing test

---

.github/workflows/run-tests.yml

Runs tests on PRs explicitly (in addition to on branches)

Run tests explicitly on PRs

---

src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss
src/index.scss
src/store/edit-profile/api.ts

Add Dropdown to select primary_zid in `edit profile` screen

---

src/components/messenger/chat/conversation-header/index.tsx

Somehow some bad formatting got through the checks. This fixes it.

Fix formatting

---

src/lib/feature-flags.ts

- flips the allow join room feature flag

feat: set allowJoinRoom feature flag default to true

---

src/components/verify-id-dialog/index.test.tsx
src/components/verify-id-dialog/index.tsx
src/components/verify-id-dialog/styles.scss

- adds verify id dialog.
- to use as content for modals.

feat: add verify id dialog

---

src/store/messages/messages.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Publishes an event when a message is sent

Publish event when message is sent

---

src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Prompts the user to enter their backup key if they have a backup but it hasn't been restored on this device.

Prompt the user to restore their backup when they log in

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Removes references to the old "channels" in the channels-list sagas
We never set `isChannel: true` since the move to Matrix. They're all considered conversations.

Remove references to old channels in channel-list saga

---

src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

- handles secure backup flow by introducing the setting of stages.
- to handle the secure backup UI flow.
Note: A follow up PR introduces the stages to the UI. Please check `Pull Requests` for follow up.

feat: handle secure backup stages - matrix saga

---

src/components/secure-backup/index.tsx

- uses the already existing destructured props in place of `this.props....`
- code consistency in this part.

refactor(secure-backup): use destructured props

---

src/_glass.scss
src/components/group-management/leave-group-dialog/index.test.tsx
src/components/group-management/leave-group-dialog/index.tsx
src/components/group-management/leave-group-dialog/styles.scss
src/components/messenger/chat/index.tsx
src/components/modal/index.test.tsx
src/components/modal/index.tsx
src/components/modal/styles.scss

Adds a Modal component and uses it for the Leave Group Dialog.

Add Modal Component

---

src/store/channels-list/saga.ts

Not sure what this was used for previously but it's unused now so removed.

Remove unused delay function

---

src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts
src/store/test/store.ts

- implements and handles verify key phrase stage to secure backup.
- to display the `VerifyKeyPhrase` component in the UI.
- run tests as usual / run locally and follow steps in demo below with a user that has not yet backed up key.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/64c8787d-59cb-485a-9531-40c901ba99e0

feat: implements and handles verify phrase key stage to secure backup

---

src/components/logout-confirmation-modal/container.test.tsx
src/components/logout-confirmation-modal/container.tsx
src/components/logout-confirmation-modal/index.test.tsx
src/components/logout-confirmation-modal/index.tsx
src/store/test/store.ts

Uses the new specific state variables in the logout confirmation modal

Use the new specific state values in the logout confirmation modal

---

src/components/secure-backup/container.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx

Uses the new backup state values in the secure backup modal

Use new specific state values in secure-backup modal

---

src/components/messenger/chat/conversation-header/index.test.tsx
src/components/messenger/chat/conversation-header/index.tsx
src/components/messenger/chat/conversation-header/styles.scss
src/components/messenger/chat/styles.scss

- extracts styles to conversation header stylesheet.

refactor(conversation-header): extract and clean up styles from parent

---

src/store/messages/saga.ts

This moves the asynchronous part of processing a batch of new messages away from the part that saves the new message list
When we receive a batch of new messages we need to do various replacements on the list of messages in the channel to ensure we replace optimistic messages, don't duplicate messages, etc. In order for that to work properly we have to get the current list of messages and make modifications/additions to that list. However, if any of that process has an asynchronous component then the original list of messages can change by some other process (say process B). That means after all the batch manipulations, the list we save is based off the old data and not have the changes from "process B" which means we'd overwrite that and the user would not see those messages from …

Move async processing of batch messages away from actual saving

---

src/store/login/saga.test.ts
src/store/login/saga.ts
src/store/test/store.ts

Refactors the emailLogin saga and tests
Preperatory refactoring

Refactor emailLogin saga

---

src/components/secure-backup/index.tsx
src/lib/enum.ts
src/pages/login/login-component.test.tsx
src/pages/login/login-component.tsx
src/store/authentication/saga.ts
src/store/login/index.ts
src/store/login/saga.test.ts
src/store/login/saga.ts

Rather than redirect the user in the components this handles the login completion redirect in the sagas where the user flows should be handled.

Move the Done login stage handling into sagas

---

src/components/secure-backup/backup-faq/index.test.tsx
src/components/secure-backup/backup-faq/index.tsx
src/components/secure-backup/generate-prompt/index.test.tsx
src/components/secure-backup/index.tsx

- some proposed changes to backup faq implementation

refactor: backup faq 

---

src/components/settings-menu/index.tsx

- renames `Secure Backup` -> `Account Backup` menu item label

refactor(settings-menu): rename item label

---

src/components/secure-backup/index.tsx
src/components/secure-backup/recovered-backup/index.test.tsx
src/components/secure-backup/recovered-backup/index.tsx
src/components/secure-backup/restore-prompt/index.test.tsx
src/components/secure-backup/restore-prompt/index.tsx

Adds the FAQ link to the other variations of the backup prompt screen

Add Learn More link on the other backup screens

---

package-lock.json
package.json

Updates zUI to get the icon positioning fix

Update zUI to 1.9.0

---

.env.example
.github/workflows/development.yml
.github/workflows/production.yml
src/config.ts

- adds `ZOS_ROOT_URL` env var
- updates config

feat: add root url env variable and update config

---

src/components/group-management/leave-group-dialog/index.tsx
src/components/logout-confirmation-modal/index.tsx
src/components/modal/index.test.tsx
src/components/modal/index.tsx
src/components/modal/styles.scss

Adds config items for the button variations on the Modal

Add button variations for Modal

---

src/components/modal/index.test.tsx
src/components/modal/index.tsx

Adds properties to disable buttons on the Modal

Allow disabling of buttons on Modal

---

src/components/modal/styles.scss
src/components/secure-backup/generate-backup/index.test.tsx
src/components/secure-backup/generate-backup/index.tsx
src/components/secure-backup/generate-prompt/index.test.tsx
src/components/secure-backup/generate-prompt/index.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/components/secure-backup/recovered-backup/index.test.tsx
src/components/secure-backup/recovered-backup/index.tsx
src/components/secure-backup/restore-backup/index.test.tsx
src/components/secure-backup/restore-backup/index.tsx
src/components/secure-backup/restore-prompt/index.test.tsx
src/components/secure-backup/restore-prompt/index.tsx
src/components/secure-backup/styles.scss
src/components/secure-backup/success/index.test.tsx
src/components/secure-backup/success/index.tsx
src/components/secure-backup/verify-key-phrase/index.test.tsx
src/components/secure-backup/verify-key-phrase/index.tsx

Moves the button handling in the SecureBackup flow to the Modal for consistency with all Modals[

Move SecureBackup buttons to Modal

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts

This property wasn't being used anywhere so removed it.

Remove GroupChannelType from Channel

---

src/_glass.scss
src/components/settings-menu/index.tsx
src/components/settings-menu/rewards-item/container.test.tsx
src/components/settings-menu/rewards-item/container.tsx
src/components/settings-menu/rewards-item/index.test.tsx
src/components/settings-menu/rewards-item/index.tsx
src/components/settings-menu/rewards-item/styles.scss
src/lib/feature-flags.ts

Stubs in the rewards card in the settings menu when the feature flag is enabled

Initial component to render rewards in settings menu

---

src/components/rewards-popup/container.tsx
src/components/settings-menu/rewards-item/container.test.tsx
src/components/settings-menu/rewards-item/container.tsx
src/lib/number.test.ts
src/lib/number.ts
src/store/rewards/saga.ts

Fetches the rewards data on login and renders appropriately in the User Settings menu.

Fetch and render the true rewards data

---

src/store/rewards/index.ts
src/store/rewards/saga.ts

Removes some old rewards code that was opening the rewards popup on login

Remove rendering rewards popup automatically

---

src/components/rewards-modal/faq/index.test.tsx
src/components/rewards-modal/faq/index.tsx
src/components/rewards-modal/faq/styles.scss
src/components/rewards-modal/index.test.tsx
src/components/rewards-modal/index.tsx
src/components/rewards-modal/styles.scss

Adds the FAQ to the Rewards modal

Rewards FAQ

---

src/components/settings-menu/container.test.tsx
src/components/settings-menu/container.tsx
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/store/rewards/index.ts
src/store/rewards/saga.ts
src/store/test/store.ts

Renders the highlight ring on the profile settings menu Avatar if the user hasn't viewed their latest total rewards.

Highlight the user avatar if there are rewards that haven't been viewed

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.test.tsx
src/components/messenger/list/conversation-list-panel/index.tsx

Adds the empty state for the Favorite list

Add empty favorites state

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.test.tsx
src/components/messenger/list/conversation-list-panel/index.tsx

Adds the unread counts to the All and Favorite tabs

Add unread counts to conversation tabs

---

src/components/message-input/index.tsx

- formatting improvements
- housekeeping

refactor(message-input): tidy up formatting

---

src/Main.tsx
src/_glass.scss
src/components/app-bar/index.test.tsx
src/components/app-bar/index.tsx
src/components/app-bar/styles.scss
src/components/app-bar/world-panel-item/index.test.tsx
src/components/app-bar/world-panel-item/index.tsx
src/components/app-bar/world-panel-item/styles.scss
src/components/sidekick/styles.scss
src/lib/feature-flags.ts

Adds an AppBar (feature flagged) on the left of zOS for switching between Apps

Add initial AppBar

---

src/_glass.scss
src/components/app-bar/index.test.tsx
src/components/app-bar/index.tsx
src/components/app-bar/styles.scss
src/components/app-bar/world-panel-item/index.test.tsx
src/components/app-bar/world-panel-item/index.tsx
src/components/app-bar/world-panel-item/styles.scss

Adds the More Apps icon to the AppBar and styles it per the design.

Add More Apps and style to AppBar

---

src/index.scss

Change the background image

---

src/components/admin-message/index.tsx
src/components/admin-message/styles.scss
src/components/chat-view-container/styles.scss

Updates the styles of the datestamps and admin messages per design

Update admin message and date-stamp styles

---

src/lib/feature-flags.ts

Enable AppBar by default

---

src/components/joining-conversation-dialog/styles.scss

Styles the "Joining conversation..." message to be like the admin messages in conversations

Style the Joining Conversation message

---

src/components/message-input/styles.scss
src/components/messenger/chat/styles.scss

Some style tweaks for the Message Composer

Style tweaks for message composer

---

src/components/message/styles.scss

Minor updates to the message bubble styles to make them more compact

Update message bubble styles

---

src/components/messenger/list/conversation-list-panel/index.test.tsx
src/components/messenger/list/conversation-list-panel/index.tsx

Hides the unread count if the count is zero

Don't render unread counts if they are zero

---

src/components/message-input/index.tsx

- replaces `className` attributes to use bem class name 
- refactoring/tidy up

refactor(message-input): use bem for classNames

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.tsx

- updates copy.
- updates image path.

refactor: update favorites tab empty state

---

src/_glass.scss
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/rewards-tooltip/container.test.tsx
src/components/messenger/list/rewards-tooltip/container.tsx
src/components/messenger/list/rewards-tooltip/index.test.tsx
src/components/messenger/list/rewards-tooltip/index.tsx
src/components/messenger/list/user-header/index.test.tsx
src/components/messenger/list/user-header/index.tsx
src/components/tooltip-popup/styles.scss
src/components/tooltip-popup/tooltip-popup.tsx
src/store/rewards/index.ts
src/store/rewards/saga.test.ts
src/store/rewards/saga.ts
src/tooltip-head.svg

Displays a rewards tooltip, which shows the user that there are accumulated rewards since the **last day** which (s)he has not seen. 
**NOTE:** As per design, the tooltip disappears after 3s, and we record that the user has seen the rewards (i.e if the user reloads, then the tooltip is NOT displayed again)

Display rewards tooltip if user has accumulated new rewards (previous day) 

---

src/lib/chat/matrix-client.ts

- removes a random unused if statement from initializer
- unused code / clean up
- run as usual.

refactor(matrix-client): remove unused if statement from initializer

---

src/components/messenger/chat/conversation-header/styles.scss

- updates avatar status color in Conversation Header.
NOTE:: The conversation header should be refactored to use the Avatar component. Noted down as a task to follow up on.
- align with design and recent color changes.

refactor(conversation-header): update avatar status color

---

src/store/rewards/saga.ts

Remove comment in `rewards/saga.ts`

---

src/components/content-highlighter/styles.scss

- remove display setting.
- fixes truncation issue in message preview.

fix(content-highlighter): truncation in message preview

---

.github/workflows/development.yml

Adds new deployment configuration for deploying to the new development site which points to zos-api instead of zero-api

Add a deployment to the new zOS development site

---

src/components/messenger/chat/conversation-header/index.tsx
src/components/messenger/list/conversation-item/index.test.tsx
src/components/messenger/list/conversation-item/index.tsx
src/components/messenger/list/utils/utils.tsx

- remove unused sendbird custom icon util.
- no longer required.

refactor: remove sendbird custom icon util

---

.github/workflows/production.yml

Deploys to the new production site on release

Deploy to new production site

---

src/components/messenger/list/utils/utils.test.ts
src/components/messenger/list/utils/utils.tsx

- updates last seen helper output
- adds test coverage
- to align with latest design

refactor: update last seen helper function output

---

src/components/image-upload/index.tsx
src/components/image-upload/styles.scss

- updates edit icon background color

feat(image-upload): update edit icon background color

---

src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

-  update footer-mask copy and size

feat(messenger-list): update footer-mask copy and size

---

package-lock.json
package.json

- chore: bump ZUI version (`1.9.7`) -> (`1.9.9`)

chore: bump ZUI version (`1.9.7`) -> (`1.9.9`)

---

package-lock.json
package.json

chore: bump ZUI version (`1.9.9`) -> (`1.10.0`)

chore: bump ZUI version (`1.9.9`) -> (`1.10.0`)

---

package-lock.json
package.json

chore: bump ZUI version (`1.10.0`) -> (`1.10.1`)

chore: bump ZUI version (`1.10.0`) -> (`1.10.1`)

---

package-lock.json
package.json

chore: bump ZUI version (`1.10.1`) -> (`1.10.2`)

chore: bump ZUI version (`1.10.1`) -> (`1.10.2`)

---

package-lock.json
package.json

- chore: bump ZUI version (`1.10.2`) -> (`1.10.3`)

chore: bump ZUI version (`1.10.2`) -> (`1.10.3`)

---

package-lock.json
package.json

- chore: bump ZUI version (`1.10.3`) -> (`1.10.5`)

chore: bump ZUI version (`1.10.3`) -> (`1.10.5`)

---

src/components/message-input/emoji-picker/emoji-picker.tsx
src/components/message-input/emoji-picker/styles.scss

developer env 
1. How will this affect security? **noops**
1. How will this affect performance? **yeah more fast**
1. Does this change any APIs? **no**

feat(emoji): change style to panel emoji

---

src/components/message-input/emoji-picker/emoji-picker.tsx
src/components/message-input/emoji-picker/styles.scss

- adds glass styles (gradient border, background, backdrop etc).
- tidies up some of the css using our mixins.
- removes styles that are not required.
- polishes up some of the styling.
- improved ui.
- run the UI and check emoji picker.

refactor(emoji-picker): polish up styles and tidy up

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.tsx

* add fade-in effect on favorites
* change active tab border color to highlight

feat(conversation-panel): Fade In Favorites Section

---

src/pages/login/login.scss

* add fad in transaction on login page 
* fix show background image on login page 
localy

feat(loginPage): add Fade In Login

---

src/platform-apps/channels/messages-menu/index.tsx

* enable right clicking on message box
* using click position to open tool box
improves the UX of user activities in chat
1. How will this affect security? noops
1. How will this affect performance? more fast 
1. Does this change any APIs? noops

chore(messages-menu): enable right click to editing message

---

src/platform-apps/channels/messages-menu/index.tsx

Revert "chore(messages-menu): enable right click to editing message"

---

src/components/message/index.test.tsx
src/components/message/index.tsx

chore(message): add right click on message box

---

src/components/message/index.test.tsx
src/components/message/index.tsx

Revert "chore(message): add right click on message box"

---

package-lock.json
package.json

chore: bump ZUI version (`1.10.5`) -> (`1.10.7`)

chore: bump ZUI version (`1.10.5`) -> (`1.10.7`)

---

package-lock.json
package.json

chore: bump ZUI version (`1.10.7`) - (`1.10.8`)

chore: bump ZUI version (`1.10.7`) - (`1.10.8`)

---

src/components/body-class-manager/index.tsx
src/index.scss
src/index.tsx

add new component to manager background image

feat(body): add new component BodyClassManager

---

package-lock.json
package.json
src/components/citizen-list-item/index.tsx
src/components/message-input/mentions/index.tsx
src/components/message/index.tsx
src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/conversation-item/index.tsx
src/components/messenger/list/selected-user-tag/index.tsx
src/components/messenger/list/user-search-results/index.tsx
src/components/settings-menu/index.tsx

- chore: bump ZUI version (`1.10.8`) -> (`1.10.9`)

chore: bump ZUI version (`1.10.8`) -> (`1.10.9`)

---

src/components/message/index.tsx
src/platform-apps/channels/messages-menu/index.tsx

* right click on message box, fix design rules
https://www.youtube.com/watch?v=FHqsaFCh7dY

chore(message): fix design rules on right click action

---

src/components/messenger/chat/conversation-header/index.test.tsx
src/components/messenger/chat/conversation-header/index.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/sidekick/index.tsx
src/store/group-management/saga.ts

- moves group management panels to the right side kick
- run ui and run through the group management flows

refactor: add group management to right side kick

---

src/components/message/index.tsx

https://github.com/zer0-os/zOS/assets/57037080/6f7e256b-4f3f-4c2f-a042-7010fee9e41f
Try using right click on bubble msg
1. How will this affect security? no
1. How will this affect performance? no
1. Does this change any APIs? no

chore(message): fix right click issues

---

src/components/message/index.test.tsx
src/components/message/index.tsx

Allows to reply to a reply.
https://github.com/zer0-os/zOS/assets/33264364/e317f2e4-17f0-45e6-b4cb-dd6cce407dbd

Allow `Reply to a reply`

---

src/components/messenger/user-profile/styles.scss

feat(user-profile): fade in profile image

---

src/components/message-input/giphy/giphy.tsx
src/components/message-input/giphy/styles.scss

- changes attempting to update styling of gif picker to fit our theme a little closer.
- as per request/design.
- open gif picker.

feat(giphy): style updates 

---

src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/components/messenger/lib/utils.tsx

Update typing indicators UI display (in direct message chat)

---

src/components/messenger/chat/styles.scss

https://github.com/zer0-os/zOS/assets/33264364/d82b98c5-1b20-45af-9b7b-c1e76dd0af77

Add animation for displaying typing indicators

---

src/_background.scss
src/invite.scss
src/main.scss
src/pages/login/login.scss
src/reset-password.scss

- add main and root background mixins to background scss file.
- imports and include these mixins to relevant pages.
- add fade animations.
- as per design/request.
- run UI and check background behaviours as per demo below.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/d187ccdb-f4aa-48ec-a658-0bb8fee6cc62

feat(backgrounds): add root and main background mixins and import to pages

---

package-lock.json
package.json

- chore: bump ZUI version (`1.10.9`) -> (`1.11.0`)

chore: bump ZUI version (`1.10.9`) -> (`1.11.0`)

---

src/authentication/create-account-details/index.tsx
src/authentication/create-account-details/styles.scss

- create account details redesign.
- run UI and go through the create account flow, check UI of account details stage.

feat(create-account-details): redesign

---

src/authentication/request-password-reset/index.tsx
src/authentication/request-password-reset/styles.scss

- request password page redesign.
- run UI and check the reset password flow (visit /reset-password).

feat(request-password-reset): redesign

---

src/_glass.scss

fix: desktop css mask

---

src/lib/browser/index.ts

fix: windows desktop notifications

---

src/components/group-management/member-management-dialog/container.test.tsx
src/components/group-management/member-management-dialog/container.tsx
src/components/messenger/group-management/member-management-menu/container.test.tsx
src/components/messenger/group-management/member-management-menu/container.tsx
src/components/messenger/group-management/member-management-menu/index.test.tsx
src/components/messenger/group-management/member-management-menu/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/group-management/index.ts
src/store/group-management/saga.test.ts
src/store/group-management/saga.ts

https://github.com/zer0-os/zOS/assets/33264364/616627cb-ed7c-44a2-a66e-280815350a99

Add the ability to remove a user as moderator (by admin)

---

src/components/messenger/group-management/member-management-menu/index.tsx

update member management menu texts for: `remove member`, `remove mod`

---

package-lock.json
package.json

- chore: bump ZUI version (`1.11.1`) -> (`1.11.2`)

chore: bump ZUI version (`1.11.0`) -> (`1.11.2`)

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

Note :: I will move the invite dialog to the dialog manager when I'm feeling better & more time.
- re-adds invite button to messenger list.

feat: re-add invite button to messenger list

---

src/Main.tsx
src/_background.scss
src/main.scss

- updates background (animation)
- run ui and check background.

feat(main-background): update main background (animation)

---

src/Main.tsx
src/_background.scss
src/main.scss

Production deploys are blocked since this is into `main`. This PR reverts this.

Revert "feat(main-background): update main background (animation)"

---

src/components/messenger/group-management/edit-conversation-panel/index.test.tsx
src/components/messenger/group-management/edit-conversation-panel/index.tsx
src/components/messenger/group-management/index.tsx

Before:
https://github.com/zer0-os/zOS/assets/33264364/bf0ce6ef-e561-42d2-9cda-9ac43beb415c
After:
https://github.com/zer0-os/zOS/assets/33264364/5cedaf16-cefa-4b41-aae8-24e4d3cca1ff

Remove ability to left click on a member in edit group panel

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

- adds buffer space to conversation list item.
- adds gradient to button container.
- run ui and check (as per screenshot below).
https://github.com/zer0-os/zOS/assets/39112648/84fe09cf-3a1e-41fe-9d14-76d0de9602cb

feat(messenger-list): invite button background gradient and buffer

---

src/components/messenger/user-profile/settings-panel/index.test.tsx
src/components/messenger/user-profile/settings-panel/index.tsx
src/components/messenger/user-profile/settings-panel/styles.scss

- adds settings panel 
- panel to handle user settings
- not yet wired up to the ui to test.

feat(user-settings): add settings panel

---

package-lock.json
package.json

- chore: bump ZUI version (`1.11.2`) -> (`1.11.3`)

chore: bump ZUI version (`1.11.2`) -> (`1.11.3`)

---

src/components/messenger/user-profile/settings-panel/styles.scss

- adds gap to reduce label and input spacing

feat(select-background-input): add gap to reduce label and input spacing

---

src/lib/feature-flags.ts

- flips enable user background feature flag

feat(feature-flags): flip enable user background feature flag

---

package-lock.json
package.json

- chore: bump ZUI version (`1.11.3`) -> (`1.11.4`)

chore: bump ZUI version (`1.11.3`) -> (`1.11.4`)

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message/index.tsx
src/components/message/styles.scss
src/components/messenger/message-info/container.tsx
src/store/message-info/index.ts
src/store/message-info/saga.test.ts
src/store/message-info/saga.ts
src/store/messages/saga.ts

Revert "feat(chat-view): implement message bubble read receipts"

---

src/platform-apps/channels/messages-menu/index.tsx

- re-orders the message-menu menu items.

refactor(message-menu): re-order menu items

---

src/components/messenger/user-profile/container.tsx
src/components/messenger/user-profile/index.test.tsx
src/components/messenger/user-profile/index.tsx
src/components/messenger/user-profile/overview-panel/index.test.tsx
src/components/messenger/user-profile/overview-panel/index.tsx
src/components/messenger/user-profile/wallets-panel/container.tsx
src/components/messenger/user-profile/wallets-panel/index.test.tsx
src/components/messenger/user-profile/wallets-panel/index.tsx
src/components/messenger/user-profile/wallets-panel/styles.scss
src/lib/feature-flags.ts
src/store/user-profile/index.ts
src/store/user-profile/saga.test.ts
src/store/user-profile/saga.ts

Add new "wallets" section in user profile (feature flagged)

---

src/components/messenger/user-profile/wallets-panel/container.test.tsx
src/components/messenger/user-profile/wallets-panel/container.tsx
src/components/messenger/user-profile/wallets-panel/index.test.tsx
src/components/messenger/user-profile/wallets-panel/index.tsx
src/components/messenger/user-profile/wallets-panel/styles.scss
src/store/reducer.ts
src/store/saga.ts
src/store/wallets/index.ts
src/store/wallets/saga.test.ts
src/store/wallets/saga.ts

Images:
Error state:
Video:
https://github.com/zer0-os/zOS/assets/33264364/5e5fe881-bd63-418d-8227-a759e456da25

Add `+ Add new wallet` button, `WalletSelect` Modal flow in "wallets" section

---

vite.config.ts

Changes output directory to `build` for Netlify

build: `build` output directory

---

src/authentication/create-email-account/container.test.tsx
src/authentication/create-email-account/container.tsx
src/components/messenger/user-profile/account-management-panel/container.test.tsx
src/components/messenger/user-profile/account-management-panel/container.tsx
src/components/messenger/user-profile/account-management-panel/index.test.tsx
src/components/messenger/user-profile/account-management-panel/index.tsx
src/components/messenger/user-profile/account-management-panel/styles.scss
src/store/account-management/index.ts
src/store/account-management/saga.test.ts
src/store/account-management/saga.ts

https://github.com/zer0-os/zOS/assets/33264364/8a9b86ab-d9aa-45ef-93fe-9b62c1110748

Add "Add Email Account" modal on `Manage Accounts` section

---

src/index.tsx

- fixes the issue shown below.
- improve UI/UX
- run UI and render page.
BEFORE:
https://github.com/zer0-os/zOS/assets/39112648/18a8d31e-a446-4295-967d-3f4778066749
AFTER:
https://github.com/zer0-os/zOS/assets/39112648/d533f6f6-ccf0-4736-9667-47c64b0a1247

fix(background): flickering page on data fetch

---

src/index.tsx

Revert "fix(background): flickering page on data fetch"

---

src/components/messenger/user-profile/account-management-panel/container.test.tsx
src/components/messenger/user-profile/account-management-panel/container.tsx
src/components/messenger/user-profile/account-management-panel/index.test.tsx
src/components/messenger/user-profile/account-management-panel/index.tsx
src/components/messenger/user-profile/account-management-panel/styles.scss
src/store/account-management/index.ts
src/store/account-management/saga.test.ts
src/store/account-management/saga.ts
src/store/registration/api.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts
src/store/test/store.ts
src/store/user-profile/saga.test.ts
src/store/user-profile/saga.ts

Complete flow here - [https://www.loom.com/share/03f5ed11a95a4dcb8fe68db78dbfae91?sid=ce273305-cdfc-4837-a7a2-1b89625e2fc5](https://www.loom.com/share/03f5ed11a95a4dcb8fe68db78dbfae91?sid=ce273305-cdfc-4837-a7a2-1b89625e2fc5)

Complete UI + API integration for adding an email account for a "web3 only" account

---

src/authentication/validate-invite/index.tsx

Update Invite Code max length from 14 to 6

---

index.html

- updates meta tag content with messenger app id (replacing old zero id)
- direct users to correct app via smart app banner
- shall be able to test in dev env.

feat(root-html): update meta tag content with messenger app id

---

package-lock.json
package.json

- chore: bump version (`1.107.0`) -> (`1.108.0`)

chore: bump version (`1.107.0`) -> (`1.108.0`)

---

package-lock.json
package.json

- chore: bump version (`1.108.0`) -> (`1.109.0`)

chore: bump version (`1.108.0`) -> (`1.109.0`)

---

src/components/message/parent-message/styles.scss
src/components/reply-card/styles.scss

- apply media container fixed width to prevent changing of element size
- fixes incorrectly named class name in scss file
- jolting image elements

fix(parent-message/reply-card): apply media container fixed width to prevent changing of element size

---

package-lock.json
package.json

bump version (`1.110.0` -> `1.111.0`)

---

package-lock.json
package.json

- chore: bump version (`1.111.0`) -> (`1.112.0`)

chore: bump version (`1.111.0`) -> (`1.112.0`)

---

src/components/citizen-list-item/index.tsx

- removes unused user status getter
- remove unused code - tidy up

refactror(citizen-list-item): remove unused user status getter

---

src/components/messenger/list/conversation-item/index.tsx

- removes unused user status getter
- remove unused code - tidy up

refacrtor(conversation-item): remove unused user status getter

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts
src/store/users/saga.ts

- removes unused user presence functions from client and sagas
- house keeping / tidy up removing unused code

refactor(matrix-client): remove unused user presence functions from client and sagas

---

src/config.ts
src/lib/chat/matrix-client.ts

- temporary change to test event logging in specific environment
- temporary change for testing performance

feat(matrix-client): update event logging to be environment specific

---

package-lock.json
package.json

- chore: bump version (`1.113.0`) -> (`1.114.0`)

chore: bump version (`1.113.0`) -> (`1.114.0`)

---

src/config.ts
src/lib/chat/matrix-client.ts

Revert "feat(matrix-client): update event logging to be environment specific"

---

src/components/chat-view-container/chat-view.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx

Revert "refactor(chat-view): temporarily disable message bubble read receipts processing"

---

package-lock.json
package.json

- chore: bump version (`1.118.0`) -> (`1.119.0`)

chore: bump version (`1.118.0`) -> (`1.119.0`)

---

src/lib/chat/matrix-client.ts
src/lib/feature-flags.ts
src/store/channels-list/saga.ts

- adds timer logs
- adds feature flag
- to analyse timings

feat: add timer logs (feature-flagged)

---

package-lock.json
package.json

- chore: bump version (`1.121.0`) -> (`1.122.0`)

chore: bump version (`1.121.0`) -> (`1.122.0`)

---

src/store/channels-list/saga.ts

-  remove comments
Recorded elsewhere

refactor: remove comments

---

src/lib/chat/matrix-client.ts

- updating the mapConversations function to fetch only the latest user message using the new `getUpToLatestUserMessageFromRoom` method, instead of retrieving all messages from a room.
- Avoiding Unnecessary Processing: By fetching only the latest user message, we avoid downloading and decrypting potentially large image files and other media that are not immediately needed. This can significantly reduce the processing load during initial load.
- Improved Initial Load Times: This targeted approach ensures that only the most relevant message is processed initially, which speeds up the loading time.
- Reduced Data Transfer: Fewer data are transferred over the network, which reduces latency and bandwidth usage.
- run the UI and check initial load time performance.
1. How …

refactor(matrix-client): optimize map conversations to fetch only the latest user message to avoid unnecessary image processing on initial load

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss
src/lib/chat/matrix/chat-message.ts
src/lib/chat/matrix/media.ts
src/store/messages/index.ts
src/store/messages/saga.ts

Revert "feat: download and decrypt images only when conversation is active"

---

.env.example
.github/workflows/development.yml
.github/workflows/production.yml
src/config.ts

- adds web app download path environment variable
- to access the path using env variables

feat(env-and-config): add web app download path environment variable

---

src/index.tsx
src/lib/feature-flags.ts
src/maintenance.scss
src/maintenance.tsx

- feat: add maintenance page w/feature-flag
This is a quick implementation to put the app into a maintenance type mode (basically just showing a different page and redirecting)

feat: add maintenance page w/feature-flag

---

src/index.tsx
src/lib/feature-flags.ts

- feat: restore app routes (remove maintenance route)
Restore usual routes.

feat: restore app routes (remove maintenance route)

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/message-info/saga.test.ts
src/store/message-info/saga.ts
src/store/messages/saga.ts

Revert "refactor(read-receipts): remove calls for read receipts"

---

src/App.tsx
src/App.vitest.tsx
src/Main.test.tsx
src/Main.tsx
src/apps/app-router.tsx
src/apps/app-router.vitest.tsx
src/components/app-bar/index.tsx
src/index.tsx
src/lib/feature-flags.ts
src/messenger-main.test.tsx
src/messenger-main.tsx

This was previously reverted. This PR just rebases the initial changes onto `main`

feat: add app switcher

---

src/components/message/index.tsx

refactor: remove console logs

---

package-lock.json
package.json

-chore: bump version (`1.142.0`) -> (`1.143.0`)

chore: bump version (`1.142.0`) -> (`1.143.0`)

---

src/components/messenger/list/group-details-panel/group-type-menu/index.test.tsx
src/components/messenger/list/group-details-panel/group-type-menu/index.tsx
src/components/messenger/list/group-details-panel/group-type-menu/styles.scss
src/components/messenger/list/group-details-panel/group-type-menu/types.ts

- adds group type select input component

feat: add group type select input component

---

src/components/messenger/list/group-details-panel/group-type-dialog/index.test.tsx
src/components/messenger/list/group-details-panel/group-type-dialog/index.tsx
src/components/messenger/list/group-details-panel/group-type-dialog/styles.scss

- adds group type modal dialog
- to display group typing information

feat: add group type modal dialog

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts

- gets group type and sets isSocialChannel property on each room
- improvement to Channel props

refactor: add isSocialChannel property to Channel structure for each room and set flag using groupType from event data

---

package-lock.json
package.json
src/components/messenger/feed/components/create-post/index.tsx
src/components/messenger/feed/components/create-post/styles.module.scss
src/components/messenger/feed/components/post/index.tsx
src/components/messenger/feed/components/post/styles.module.scss
src/components/messenger/feed/components/posts/index.tsx
src/components/messenger/feed/components/posts/styles.module.scss
src/components/messenger/feed/index.tsx
src/components/messenger/feed/lib/types.ts
src/components/messenger/feed/mock.ts
src/components/messenger/feed/styles.scss
src/components/sidekick/styles.scss

note: this feature is still feature flagged, and it's using mock data!

feat: basic feed UI

---

package-lock.json
package.json

- chore: bump version (`1.148.0`) -> (`1.149.0`)

chore: bump version (`1.148.0`) -> (`1.149.0`)

---

src/components/messenger/feed/components/create-post/index.tsx

Currently, they don't do anything

feat: hide post media buttons

---

src/components/messenger/feed/components/create-post/index.tsx
src/components/messenger/feed/components/post/index.tsx

Correctly format mult-line post data
Also some small refactoring - apologies for not separating PRs

feat: multi-line posts

---

src/lib/chat/matrix-client.ts

This change optimizes the retrieval of chat and post messages by reducing redundant calls to the liveTimeline. The events are now retrieved once and passed down, improving the overall performance of the message fetching process.
We are making this change to enhance the performance of the application by minimizing unnecessary calls to the liveTimeline, which can be resource-intensive. This optimization reduces the load on the system and improves the efficiency of message handling.

refactor(matrix-client): optimize event handling in message retrieval by reducing redundant liveTimeline calls

---

package-lock.json
package.json

- chore: bump version (`1.149.0`) -> (`1.150.0`)

chore: bump version (`1.149.0`) -> (`1.150.0`)

---

src/lib/chat/matrix/chat-message.ts

- updates map event to post message sender data to include display sub handle field
- to get sender data to display the users zid or wallet address in posts ui

feat(matrix-client): update map event to post message sender data to include display sub handle field

---

src/components/messenger/feed/components/post/index.tsx
src/components/messenger/feed/components/post/styles.module.scss

- updates name, sub handle, date and body text design

feat(post-component): update name, sub handle, date and body text design

---

package-lock.json
package.json

- chore: bump version (`1.150.0`) -> (`1.151.0`)

chore: bump version (`1.150.0`) -> (`1.151.0`)

---

src/apps/messenger/Main.module.scss
src/apps/messenger/Main.tsx
src/components/messenger/feed/components/posts/styles.module.scss
src/components/messenger/feed/index.tsx

https://linear.app/zero-tech/issue/ZOS-221/removed-post-separator-instead-of-page-divider

feat: add post divider, remove vertical divider

---

package-lock.json
package.json

- chore: bump version (`1.151.0`) -> (`1.152.0`)

chore: bump version (`1.151.0`) -> (`1.152.0`)

---

package-lock.json
package.json

Revert "chore: bump version (`1.151.0`) -> (`1.152.0`)"

---

package-lock.json
package.json

chore: bump version (`1.152.0`) -> (`1.153.0`)

chore: bump version (`1.152.0`) -> (`1.153.0`)

---

package-lock.json
package.json

- chore: bump version (`1.153.0`) -> (`1.154.0`)

chore: bump version (`1.153.0`) -> (`1.154.0`)

---

src/App.tsx
src/components/inverted-scroll/styles.scss
src/components/messenger/feed/styles.scss
src/main.scss

- Sets max width for app container (`1700px`)
- Sets max width for feed container (`504px`)
- Chat scrollbar only visible on hover

feat: app max width, feed max width

---

src/lib/feature-flags.ts

-  flip social channel related feature flags

feat(feature-flags): flip social channel related feature flags

---

package-lock.json
package.json

- chore: bump version (`1.154.0`) -> (`1.155.0`)

chore: bump version (`1.154.0`) -> (`1.155.0`)

---

src/store/authentication/saga.test.ts
src/store/authentication/saga.ts

Before:
https://github.com/user-attachments/assets/a8d05665-f3eb-4bf5-b472-642e5a498722
After:
https://github.com/user-attachments/assets/c47d3a2c-5069-40c3-92f6-dac592d2266d

[Fix] `Sign In` button disappears immediately after logout even when the wallet is connected 

---

src/apps/messenger/Main.module.scss
src/apps/messenger/Main.tsx
src/components/header/index.module.scss
src/components/messenger/chat/index.tsx

- refactors positioning and styles of messenger chat header
- run UI as usual

refactor(redesign-chat-header): update positioning and styles of messenger chat header

---

src/components/messenger/group-management/view-group-information-panel/styles.scss
src/components/messenger/group-management/view-members-panel/styles.scss
src/components/sidekick/styles.scss

- fixes right sidekick sizing
- as requests / bug
- check right sidekick aligns with styles of left side kick i.e. width / position

fix(sidekick): right sidekick sizing

---

src/components/message-input/index.tsx
src/components/message-input/menu/menu.tsx
src/components/message-input/styles.scss
src/components/messenger/feed/components/post-input/index.tsx
src/components/messenger/feed/components/post-input/styles.scss

- resizes action icons for message input and post input
- per design

feat(post-input/message-input): resize action icons

---

src/components/messenger/feed/components/post-input/styles.scss

- post input and avatar alignment

refactor(post-input): post input and avatar alignment

---

src/components/messenger/feed/components/post-input/index.tsx

- update placeholder for post input

refactor(post-input): update placeholder

---

src/components/messenger/feed/components/post-input/styles.scss
src/components/messenger/feed/styles.scss

- fixes scrollbar border gap mis-alignment

fix(posts): scrollbar border gap mis-alignment

---

src/components/group-management-menu/index.tsx

-  replace group icon with three dot icon (conversation actions)

refactor(conversation-actions): replace group icon with three dot icon

---

src/components/messenger/feed/components/posts/styles.module.scss

feat(posts): add border inline for posts

---

src/components/sidekick/styles.scss

- closed to open transition positioning
- improve ux

fix(right-sidekick): closed to open transition positioning

---

src/apps/messenger/Main.module.scss
src/components/messenger/conversation-actions/styles.scss

-  improve/align component position and sizing (conversation actions)
- UX/UI improvements

refactor(conversation-actions): improve/align component position/sizing & remove duplicated styles

---

src/components/messenger/feed/components/post/index.tsx

- resolve missing dependency console warning

fix(post): resolve missing dependency console warning

---

src/apps/messenger/Main.module.scss
src/components/messenger/feed/styles.scss

- updates split pane gap for positioning and spacing

refactor(app-layout): update split pane gap for positioning and spacing

---

package-lock.json
package.json

- chore: bump version (`1.162.0`) -> (`1.163.0`)

chore: bump version (`1.162.0`) -> (`1.163.0`)

---

package-lock.json
package.json

- chore: bump version (`1.163.0`) -> (`1.164.0`)

chore: bump version (`1.163.0`) -> (`1.164.0`)

---

package-lock.json
package.json

chore: bump version (`1.164.0`) -> (`1.165.0`)

chore: bump version (`1.164.0`) -> (`1.165.0`)

---

package-lock.json
package.json

Revert "chore: bump version (`1.164.0`) -> (`1.165.0`)"

---

package-lock.json
package.json

- chore: bump version (`1.164.0`) -> (`1.165.1`)

chore: bump version (`1.164.0`) -> (`1.165.1`)

---

src/store/messages/saga.ts
src/store/posts/saga.ts

- add and put error logs if message or post fetching fails

refactor: add and put error logs if message or post fetching fails

---

package-lock.json
package.json

- chore: bump version (`1.167.0`) -> (`1.168.0`)

chore: bump version (`1.167.0`) -> (`1.168.0`)

---

src/apps/messenger/Main.tsx
src/components/messenger/group-management/view-group-information-panel/styles.scss
src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/group-management/saga.ts

- improves footer positioning for leave group button
- improved UI

fix(view-group-info-panel): improve footer positioning for leave group button

---

src/lib/chat/matrix-client.ts

- reduce paginate limit for chat messages
- as requested for performance optimizations

refactor(matrix-client): reduce paginate limit for chat messages

---

src/components/message/styles.scss

- removes animated background on image placeholders, replaces with static background
- performance optz

refactor(message): remove animated background on image placeholder

---

package-lock.json
package.json

-chore: bump version (`1.173.0`) -> (`1.174.0`)

chore: bump version (`1.173.0`) -> (`1.174.0`)

---

src/components/messenger/list/create-conversation-panel/create-conversation-panel.scss

- adjusts submit button container positioning by updating margin
- improve ui

refactor(create-conversation-panel): ui improvement - adjust submit button container positioning

---

src/components/secure-backup/container.tsx
src/lib/chat/matrix-client.ts
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

This PR updates the secure backup flow by addressing issues with the secret storage bootstrap's expected key format, ensuring proper use of the key during cryptographic operations.
We encountered format-related errors due to 'potential' changes in how secret storage keys are processed - we are not totally sure. This update fixes those errors.
Test by generating a secure backup, saving it, and restoring it, ensuring the flow works smoothly. Validate that both encoded and private keys are correctly used and removed from state when appropriate

fix(secure-backup): bootstrap secret storage expected key format issue

---

package-lock.json
package.json

- chore: bump version (`1.180.0`) -> (`1.181.0`)

chore: bump version (`1.180.0`) -> (`1.181.0`)

---

src/lib/chat/matrix-client.ts

- prevents processing and publishing real time user avatar or name updates
- improve UI / UX

refactor(matrix-client): prevent processing and publishing real time user avatar or name updates

---

package-lock.json
package.json

- chore: bump version (`1.181.0`) -> (`1.182.0`)

chore: bump version (`1.181.0`) -> (`1.182.0`)

---

src/lib/chat/matrix-client.ts

This update optimizes the message fetching logic to only retrieve new messages when fetching more, preventing redundant data loads and ensuring efficiency in pagination.
To improve the performance of the message fetching process by reducing unnecessary API calls and avoiding duplicate messages. This change enhances user experience by minimizing loading times and preventing UI flickering caused by re-fetching already loaded messages.
- run ui and 'fetchMore' messages

fix(matrix-client): optimize Chat Message fetching to only retrieve new messages when fetching more, reducing redundant data loads

---

src/lib/chat/matrix-client.ts

This update optimizes the Post Message fetching logic to only retrieve new messages when fetching more, preventing redundant data loads and ensuring efficiency in pagination.
To improve the performance of the Post Message fetching process by reducing unnecessary API calls and avoiding duplicate Post Messages. This change enhances user experience by minimizing loading times and preventing UI flickering caused by re-fetching already loaded Post Messages.
- run ui

fix(matrix-client): optimize Post Message fetching to only retrieve new messages when fetching more, reducing redundant data loads

---

package-lock.json
package.json

- chore: bump (`1.186.0`) -> (`1.187.0`)

chore: bump (`1.186.0`) -> (`1.187.0`)

---

package-lock.json
package.json

-  install blurhash package for blurhash generation

chore(package.json): install blurhash package

---

src/components/joining-conversation-dialog/styles.scss

- center aligns joining conversation dialog
- improved ui / ux

fix(main): center align joining conversation dialog

---

package-lock.json
package.json

- chore: bump version (`1.190.0`) -> (`1.191.0`)

chore: bump version (`1.190.0`) -> (`1.191.0`)

---

package-lock.json
package.json

- chore: bump version (`1.191.0`) -> (`1.192.0`)

chore: bump version (`1.191.0`) -> (`1.192.0`)

---

package-lock.json
package.json

- chore: bump version (`1.192.0`) -> (`1.193.0`)

chore: bump version (`1.192.0`) -> (`1.193.0`)

---

package-lock.json
package.json

- chore: bump version (`1.193.0`) -> (`1.194.0`)

chore: bump version (`1.193.0`) -> (`1.194.0`)

---

src/store/messages/saga.fetch.test.ts
src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Revert "fix(map-reactions/message-saga): improve mapping of reactions to messages in by handling in mapMessagesAndPreview"

---

package-lock.json
package.json

- chore: bump version (`1.194.0`) -> (`1.195.0`)

chore: bump version (`1.194.0`) -> (`1.195.0`)

---

package-lock.json
package.json

- chore: bump version (`1.195.0`) -> (`1.196.0`)

chore: bump version (`1.195.0`) -> (`1.196.0`)

---

package-lock.json
package.json

- chore: bump version (`1.196.0`) -> (`1.197.0`)

chore: bump version (`1.196.0`) -> (`1.197.0`)

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

- remove sending of join event on account creation
- removes admin message for the above
- does not decrypt in time, so a quick fix until we can improve

refactor(matrix-client): remove sending join event and generating admin message on account creation

---

package-lock.json
package.json

- chore: bump version (`1.198.0`) -> (`1.199.0`)

chore: bump version (`1.198.0`) -> (`1.199.0`)

---

src/lib/feature-flags.ts

- flip enableTokenGatedChat feature flag

refactor(feature-flags): flip enableTokenGatedChat feature flag

---

package-lock.json
package.json

- chore: bump version (`1.201.0`) -> (`1.202.0`)

chore: bump version (`1.201.0`) -> (`1.202.0`)

---

src/lib/feature-flags.ts

- adds enableNotificationsApp feature flag

feat(feature-flags): add enableNotificationsApp ff

---

src/components/notifications-feed/notification-item/index.tsx
src/components/notifications-feed/notification-item/styles.module.scss
src/lib/feature-flags.ts

- adds notifications feed item component

feat(notification-feed): add notificiations feed item component

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/store/messages/utils.matrix.test.ts
src/store/messages/utils.matrix.ts
src/store/notifications/index.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts
src/store/reducer.ts
src/store/saga.ts

- implements initial fetch, process and store notifications functionality
- adding notifications app feature
- not yet wired up to UI

feat(notifications-saga/matrix-client): initial fetch, process and store notifications functionality

---

package-lock.json
package.json

- chore: bump version (`1.202.0`) -> (`1.203.0`)

chore: bump version (`1.202.0`) -> (`1.203.0`)

---

src/components/messenger/feed/components/post-input/index.tsx
src/components/messenger/feed/components/post/index.tsx
src/components/messenger/feed/feed-view-container/feed-view-container.tsx
src/components/messenger/feed/index.tsx
src/lib/feature-flags.ts
src/store/posts/constants.ts
src/store/posts/index.ts
src/store/posts/saga.ts
src/store/posts/utils.ts

Use the `enableIrysPosting` flag to allow viewing and creating social channel posts via Irys.

feat: irys posting

---

src/components/messenger/feed/components/post-input/container.tsx
src/components/messenger/feed/components/post-input/index.tsx
src/components/messenger/feed/components/post-input/styles.scss
src/components/messenger/feed/index.test.tsx
src/components/messenger/feed/index.tsx
src/store/posts/index.ts
src/store/posts/saga.ts

feat: progress & error states

---

src/components/messenger/feed/components/post/actions/meow/meow-action.module.scss
src/components/messenger/feed/components/post/actions/meow/meow-action.tsx
src/components/messenger/feed/components/post/index.tsx
src/components/messenger/feed/components/posts/index.tsx
src/components/messenger/feed/feed-view-container/feed-view-container.tsx
src/components/messenger/feed/feed-view-container/feed-view.test.tsx
src/components/messenger/feed/feed-view-container/feed-view.tsx
src/store/posts/index.ts
src/store/posts/saga.ts
src/store/posts/utils.ts

- Adds ability to MEOW on Irys posts
- Handles case where user has already MEOW'd a post

feat: MEOW on posts

---

src/store/posts/saga.ts
src/store/posts/utils.ts

More useful error messages when a post fails to submit.

feat: post error messaging

---

src/apps/notifications/notifications-container.module.scss
src/apps/notifications/notifications-container.tsx

- adds the sidekick container with conversation 
- as requested for design - i.e. ui / ux improvements (navigation).
- run UI, enable feature flag for notifications app and check sidekick renders as expected

feat(notifications-app): add sidekick and conversation list to notifications app

---

package-lock.json
package.json

- chore: bump version (`1.203.0`) -> (`1.204.0`)

chore: bump version (`1.203.0`) -> (`1.204.0`)

---

src/lib/feature-flags.ts

- flips notifications app feature flag

refactor(feature-flags): flip notifications app feature flag

---

package-lock.json
package.json

- chore: bump version (`1.204.0`) -> (`1.205.0`)

chore: bump version (`1.204.0`) -> (`1.205.0`)

---

src/lib/feature-flags.ts

flip notification read status feature flag

feat(feature-flags): flip notification read status feature flag

---

src/lib/feature-flags.ts

Revert "feat(feature-flags): flip notification read status feature flag"

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/notifications/index.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts

Revert "refactor(fetch-and-get-notifications): optimize notification fetching and processing"

---

package-lock.json
package.json

- chore: bump version (`1.207.0`) -> (`1.208.0`)

chore: bump version (`1.207.0`) -> (`1.208.0`)

---

src/components/notifications-feed/index.test.tsx
src/components/notifications-feed/index.tsx
src/components/notifications-feed/notification-item/index.tsx
src/components/notifications-feed/notification-item/styles.module.scss
src/components/notifications-feed/styles.module.scss
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/lib/feature-flags.ts
src/store/notifications/index.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts

Revert "feat(matrix-client/notifications-saga): track read and unread notifications and attempt to enhance performance"

---

package-lock.json
package.json

- chore: bump version (`1.208.0`) -> (`1.209.0`)

chore: bump version (`1.208.0`) -> (`1.209.0`)

---

package-lock.json
package.json

chore: bump version (`1.212.0`) -> (`1.213.0`)

chore: bump version (`1.212.0`) -> (`1.213.0`)

---

package-lock.json
package.json

- chore: bump ZUI version (`1.14.0`) -> (`1.16.0`)

chore: bump ZUI version (`1.14.0`) -> (`1.16.0`)

---

src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx

- replaces zos component library lightbox with zui lightbox
- updated component 
- run ui and click on image

feat(lightbox): replace zos component library lightbox with zui lightbox

---

src/components/message/index.tsx

- add copy image fallback handling for non-supported clipboard media types
- to support copying images for non supported media types
- attempt to copy image on messages using the message menu

refactor(message-menus): add copy image fallback handling for non-supported clipboard media types

---

src/components/messenger/feed/components/load-more/index.module.scss
src/components/messenger/feed/components/load-more/index.tsx
src/components/messenger/feed/components/load-more/useLoadMore.ts
src/components/messenger/feed/feed-view-container/feed-view-container.tsx
src/components/messenger/feed/feed-view-container/feed-view.tsx
src/lib/feature-flags.ts
src/store/posts/index.ts
src/store/posts/saga.ts
src/store/posts/utils.ts

- Lets users refresh the posts in their feed without refreshing the whole app.

feat: load more posts button

---

src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts

- updates optimistic conversation structure to include highlight unread count

refactor(channels-list-saga): update optimistic conversation structure to include highlight unread count

---

src/store/posts/saga.ts

- prevents message reset when opening conversation

fix(posts): prevent message reset when opening conversation

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/dialog-manager/container.test.tsx
src/components/dialog-manager/container.tsx
src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/messenger/conversation-actions/container.test.tsx
src/components/messenger/conversation-actions/container.tsx
src/components/messenger/conversation-actions/index.tsx
src/components/messenger/conversation-actions/index.vitest.tsx
src/components/report-user-dialog/container.test.tsx
src/components/report-user-dialog/container.tsx
src/components/report-user-dialog/index.test.tsx
src/components/report-user-dialog/index.tsx
src/components/report-user-dialog/styles.scss
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx
src/store/reducer.ts
src/store/report-user/api.ts
src/store/report-user/index.ts
src/store/report-user/saga.test.ts
src/store/report-user/saga.ts
src/store/saga.ts
src/store/test/store.ts

Add ability to report a user (via conversation actions)

---

public/electron.js

feat(electron): update config

---

src/components/chat-view-container/chat-view-container.tsx
src/components/reaction-menu/index.tsx

- add error logging and improve state updates
- reports of reactions being unresponsive.

refactor(reaction-menu): add error logging and improve state updates

---

src/components/chat-view-container/chat-view.test.tsx
src/pages/login/login-component.tsx

- removes reset password page feature flag

refactor(login-page): remove reset password page feature flag

---

src/components/lightbox/index.tsx
src/components/lightbox/styles.module.scss

-  improve ux and apply key event features such as arrow navigation, esc to close etc
- ux / ui requests
- adds missing features

feat(lightbox): improve ux and apply key event features

---

src/components/app-bar/index.tsx

- re-orders app icons
- run UI and check app bar

refactor(app-bar): re-order app icons

---

src/components/chat-view-container/chat-view.test.tsx

- resolves out of date test assertion

fix(chat-view-tests): resolve out of date test assertion

---

docs/ZOS_AUTHENTICATION_AND_MATRIX_CONNECTION_GUIDE.md

- adds zos & matrix connection guide draft
- useful documentation for devs

chore(docs): add zos & matrix connection guide draft

---

src/components/sidekick/styles.scss

Remove Sidekick border

---

src/components/message/styles.scss

- update colour of owners message bubble
- run ui and send a message

refactor(message-bubble): update colour of owners message bubble

---

package-lock.json
package.json

- chore: bump version (`1.242.0`) -> (1.243.0`)

chore: bump version (`1.242.0`) -> (1.243.0`)

---

src/components/app-bar/more-apps-modal/index.tsx

- updates external url
- direct user to correct wilder world marketplace site
- run ui, click more apps in app bar, select marketplace

fix(app-bar): update more apps marketplace url to direct user to wilder world marketplace

---

src/lib/chat/matrix/chat-message.test.ts
src/lib/chat/matrix/chat-message.ts

- enables matrix audio file messaging
- to send and receive audio files (including voice notes)
- not yet wired up to UI

feat(matrix-client): enable matrix audio file messaging

---

src/components/message/styles.scss
src/platform-apps/channels/audio-cards/styles.scss

- remove audio controls enclosure border

refactor(audio-controls): remove audio controls enclosure border

---

src/components/app-bar/styles.scss
src/components/messenger/list/conversation-item/conversation-item.scss
src/components/notifications-feed/notification-item/styles.module.scss

- updates highlight notification colour

refactor(highlight-notifications): update highlight notification colour

---

.env.example
.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/staging.yml
src/config.ts

- add matrix home server name env vars and update config

feat(config): add matrix home server name env vars and update config

---

src/apps/feed/components/feed-chat/index.test.tsx
src/apps/feed/components/feed-chat/index.tsx
src/apps/feed/components/feed/index.tsx
src/apps/feed/components/feed/styles.module.scss
src/lib/feature-flags.ts
src/store/chat/index.ts
src/store/chat/saga.test.ts
src/store/chat/saga.ts

- creates and adds feed chat container to feed app
- to enable chat window next to feeds
- run ui and go to feeds 

feat: create and add feed chat container to feed app

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

- filter social channels from conversation list

feat(messenger/list): filter social channels from conversation list

---

src/lib/feature-flags.ts

feat(feature-flags): flip feed chat flag

---

package-lock.json
package.json

chore: bump version (`1.270.0`) -> (`1.271.0`)

---

src/apps/feed/components/feed-chat/index.test.tsx
src/apps/feed/components/feed-chat/index.tsx
src/apps/feed/components/feed-chat/styles.module.scss
src/apps/feed/components/feed/index.tsx
src/components/layout/panel/index.tsx
src/components/messenger/group-management/container.test.tsx
src/components/messenger/group-management/container.tsx
src/components/sidekick/variants/members-sidekick.tsx

- adds sidekick to feed chat
- disables group management if social channel
- refactors feed chat ui
- refactors code 
- improvements

feat: add sidekick to feed chat

---

package-lock.json
package.json

- chore: bump version (`1.278.0`) -> (`1.279.0`)

chore: bump version (`1.278.0`) -> (`1.279.0`)

---

src/apps/feed/components/sidekick/index.tsx
src/apps/feed/components/sidekick/lib/selectors.ts
src/apps/feed/components/sidekick/lib/useSidekick.ts
src/apps/feed/components/sidekick/styles.module.scss
src/lib/chat/matrix-client.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts

- adds unread count to feed list items
- improved ux
- run ui as usual, check feed list for feeds that contain unread feed chats

feat: add unread count to feed list items

---

src/components/messenger/user-profile/overview-panel/styles.scss

- fix scrollable container of user profile overview panel
- UX improvements (bug fix)
- run ui and test scroll of user profile overview

fix(user-profile/overview-panel): fix scrollable container

---

src/components/messenger/user-profile/overview-panel/styles.scss

- fixes scroll on user profile overview panel when on channels app
- improve UX
- run ui and test scroll of user profile overview panel when on Channels app

fix(user-profile/overview-panel): scrollable container on user profile overview panel when on channels app

---

src/components/messenger/user-profile/account-management-panel/styles.scss

- fixes scrollable container when on messenger app
- improved UX
- run ui and test scrollable container when on the messenger app

fix(account-management-panel): scrollable container when on Messenger App

---

src/apps/feed/components/feed-chat/index.tsx
src/apps/feed/components/feed-chat/styles.module.scss
src/components/layout/panel/index.tsx

- adds conversation actions to channel chat
- ability to mute rooms and open group info
- run ui > open social channel > click three dot menu

feat: add conversation actions to channel chat

---

src/components/notifications-feed/index.test.tsx
src/components/notifications-feed/index.tsx
src/components/notifications-feed/index.vitest.tsx

Revert "refactor(notifications-app): remove muted tab from notifications app"

---

src/lib/chat/matrix-client.ts

Revert "fix(matrix-client): push empty rule actions array when muting"

---

src/apps/feed/components/sidekick/index.tsx
src/apps/feed/components/sidekick/lib/selectors.ts
src/apps/feed/components/sidekick/lib/useSidekick.ts
src/apps/feed/components/sidekick/styles.module.scss

- wires up the existing muting system to the channels app chats
- ability to mute chats in channels app

feat(channels-app): wire up existing muting system to channels app chat rooms

---

src/apps/feed/components/feed-chat/index.tsx
src/apps/messenger/Main.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/group-management/member-management-dialog/container.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/conversation-actions/container.tsx
src/components/messenger/conversation-header/container.tsx
src/components/messenger/feed/index.tsx
src/components/messenger/group-management/member-management-menu/container.tsx
src/components/messenger/message-info/container.tsx
src/store/channels/selectors.ts

- Implementing memoized selectors for channel data to prevent unnecessary recalculations.
- To improve UI responsiveness by reducing redundant data processing.

refactor(components): implement memoized selectors for denormalized channel

---

src/apps/feed/components/feed-chat/index.tsx
src/apps/messenger/Main.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/group-management/member-management-dialog/container.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/conversation-actions/container.tsx
src/components/messenger/conversation-header/container.tsx
src/components/messenger/feed/index.tsx
src/components/messenger/group-management/member-management-menu/container.tsx
src/components/messenger/message-info/container.tsx
src/store/channels/selectors.ts

Revert "refactor(components): implement memoized selectors for denormalized channel"

---

src/store/chat/saga.test.ts
src/store/chat/saga.ts

- move mark room as read on perform validation

refactor(chat-saga): move mark room as read on perform validation

---

src/components/messenger/conversation-header/index.tsx

- removes unused avatar component from conversation header
- code quality

refactor(conversation-header): remove unused avatar component from conversation header

---

src/_glass.scss
src/components/avatar/constants.ts
src/components/avatar/index.test.tsx
src/components/avatar/index.tsx
src/components/avatar/status/index.test.tsx
src/components/avatar/status/index.tsx
src/components/avatar/status/styles.module.scss
src/components/avatar/styles.module.scss

- add custom avatar component 
We're implementing a custom Avatar component directly in the ZOS codebase instead of relying on the ZUI library's Avatar component. This gives us more flexibility to modify and extend the Avatar functionality as needed for ZOS-specific requirements without having to update the ZUI library.
- run tests as usual. this is not yet wired up to the ui

feat(avatar): add custom avatar component 

---

src/store/chat/saga.ts

- replaces debounce with take latest
- take latest is an improvement on using debounce

refactor(chat-saga): replace debounce with take latest

---

src/apps/feed/components/sidekick/index.tsx
src/apps/feed/components/sidekick/styles.module.scss

-  removes font weight from unread feed item
- improved ux

refactor(feed-item): remove font weight from unread feed item

---

src/components/messenger/group-management/view-group-information-panel/index.tsx
src/components/messenger/group-management/view-group-information-panel/styles.scss

- fixes ability to close panel with 'x' icon
- user unable to close panels

fix(panel-actions): unblock close panel 'x' icon

---

src/apps/app-router.tsx
src/apps/aura/auraIcon.tsx
src/apps/aura/index.tsx
src/apps/aura/manifest.ts
src/apps/external-app/constants/whitelistedApps.ts
src/components/app-bar/index.tsx
src/lib/feature-flags.ts
src/lib/feature-flags/development.ts
src/lib/feature-flags/flags.ts
src/lib/feature-flags/production.ts
src/store/active-zapp/selectors.ts

Adds the Aura zApp to zOS for internal testing

Add Aura zApp

---

src/lib/feature-flags/production.ts

Add another user to aura

---

src/lib/feature-flags/production.ts

Add user to aura

---

src/apps/app-router.tsx
src/apps/iframe/styles.scss

- fill full height for fullscreen zapps

refactor(iframe): fill full height for fullscreen iframe zapps

---

src/components/messenger/list/index.tsx

- Adding debounce to the user search functionality in the messenger list component to prevent multiple API calls when typing search terms.
- To improve performance by reducing unnecessary network requests when users are typing search queries.
- run UI > search users in messenger list and check network tab

feat(messenger-list): debounce user search in messenger list to reduce api calls

---

src/lib/chat/matrix-client.ts

Moves matrix logging behind the verbose logs feature switch to save memory in production

Move matrix logging behind feature switch

---

src/store/authentication/saga.ts
src/utils.ts

This allows us to better track issues reported by specific users

Add user id to sentry logging

---

src/components/chat-view-container/chat-view.tsx
src/components/message/index.tsx
src/lib/chat/matrix/chat-message.ts
src/store/messages/index.ts

Fixes the pop-in when posting media.
Adds support for media captions that come from mobile
Before:
After:

Fix media pop-in when posting. Add mobile captions

---

src/apps/feed/components/post/styles.module.scss

- removes unnecessary top margin on date
- this was added during development but not removed, no longer required

refactor(post): remove unnecessary top margin on date

---

src/apps/feed/components/feed/index.tsx
src/apps/feed/components/feed/lib/useFeed.ts
src/apps/feed/components/post/index.tsx
src/apps/feed/components/post/styles.module.scss
src/apps/profile/lib/useProfile.ts
src/apps/profile/panels/Switcher/index.tsx
src/store/posts/utils.ts

Revert "feat: navigate to user profile by clicking avatar in feed"

---

src/components/app-bar/index.tsx

refactor(app-bar)

---

src/components/message/index.tsx

Fixes the message menu re-rendering a bunch when it shouldn't

Fixes the message menu constantly re-rendering

---

src/apps/feed/components/feed/index.tsx
src/apps/feed/components/feed/lib/useFeed.ts
src/apps/feed/components/post/index.tsx
src/apps/feed/components/post/styles.module.scss
src/apps/profile/lib/useProfile.ts
src/apps/profile/lib/useProfileApp.ts
src/apps/profile/panels/Switcher/index.tsx
src/store/posts/utils.ts

#2953 was reverted, so we're adding the changes back!

feat: navigate to user profile

---

.eslintrc.json
src/apps/feed/components/post-view-container/usePostView.ts
src/authentication/create-account-details/container.tsx
src/components/chat-view-container/chat-view.tsx
src/components/edit-profile/index.test.tsx
src/components/message-input/container.tsx
src/components/message/menu/messageMenu.tsx
src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/message-info/container.tsx
src/components/messenger/user-profile/account-management-panel/index.tsx
src/components/messenger/user-profile/linked-accounts-panel/container.tsx
src/components/report-user-dialog/container.tsx
src/lib/chat/index.ts
src/lib/chat/matrix/event-type-handlers/handleRoomDataEvents.ts
src/lib/chat/matrix/matrix-adapter.ts
src/platform-apps/channels/image-cards/image-card.tsx
src/platform-apps/channels/image-cards/index.tsx
src/store/authentication/saga.test.ts
src/store/channels-list/saga.ts
src/store/login/saga.test.ts
src/store/messages/saga.ts
src/store/posts/saga.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Adding no duplicate imports rule to clean up our imports

Add no duplicate imports rule

---

src/lib/chat/chat.vitest.ts
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/matrix-adapter.ts
src/lib/chat/sliding-sync.ts
src/store/channels-list/event-type-handlers/group-type.ts
src/store/channels-list/event-type-handlers/handle-room-data-events.ts
src/store/channels-list/event-type-handlers/room-member.ts
src/store/channels-list/event-type-handlers/room-message.ts
src/store/channels-list/saga.ts
src/store/channels/saga.ts
src/store/chat/bus.ts

Addresses feedback on the Sliding Sync PR. I'll add comments on each item

Feedback from sliding sync pr

---

src/lib/feature-flags/production.ts

- flips enable post media flag for production

refactor(feature-flags): flip enable post media flag for production

---

src/App.tsx
src/components/message-input/index.tsx
src/components/message/edit-message-actions/edit-message-actions.tsx

Cleans up comments for zos-115 as it's been fixed

Clean up comments from zos-115

---

src/store/authentication/saga.ts
src/store/matrix/index.ts
src/store/matrix/saga.ts

Fixes the matrix token error calling the wrong logout method.
I also moved the event handler to the authentication saga instead of the matrix saga

Fix: Fixes matrix token error logout

---

src/apps/profile/lib/types.ts
src/apps/profile/lib/useFollow.ts
src/apps/profile/lib/useProfile.ts
src/components/follow-button/index.tsx
src/components/follow-button/index.vitest.tsx
src/components/follow-button/styles.module.scss
src/store/reducer.ts
src/store/saga.ts
src/store/user-follows/api.ts
src/store/user-follows/index.ts
src/store/user-follows/saga.ts

We're implementing a complete follow system with Redux state management, API integration, and proper type definitions for follow counts.
To provide a robust follow system that handles follow/unfollow actions, maintains real-time follow counts, and integrates with the backend API while ensuring type safety.

feat(follow): implement follow system with Redux and API integration

---

src/components/messenger/list/index.tsx

Reverts zer0-os/zOS#3045
The core issue is resolved in https://github.com/zer0-os/zOS/pull/3046

Revert "feat(messenger-list): filter out users with existing conversations from search results"

---

src/components/messenger/chat/index.tsx

Fixes message input not gaining auto focus when a user selects reply on a message

Fix: Message input auto focus on reply

---

src/apps/profile/panels/UserPanel/index.tsx
src/apps/profile/panels/UserPanel/styles.module.scss

- repositions the message button on user panel (profile)

refactor(user-panel): re-position message button

---

src/apps/profile/panels/UserPanel/index.tsx
src/lib/feature-flags.ts
src/lib/feature-flags/development.ts
src/lib/feature-flags/flags.ts
src/lib/feature-flags/production.ts

feature flag direct message button on profile (production)

feat: feature flag direct message button on profile

---

package-lock.json
package.json

Bumping ZUI version to get new avatar change

Chore: Bump zui version 1.27.1

---

src/authentication/validate-invite/index.test.tsx
src/authentication/validate-invite/index.tsx

remove max invite character length from input

refactor(get-access): remove max invite character length from input

---

src/lib/feature-flags/production.ts

Add user to oauth linking

---

package-lock.json
package.json
src/apps/profile/panels/UserPanel/styles.module.scss
src/components/matrix-avatar/index.tsx
src/components/matrix-avatar/matrix-avatar.module.css

Fixes the avatar flicker by updating the avatar zui version.
Fixes the sizing on profile page due to component change
Hides the avatar if the mxc url is loading

fix: Avatar flicker on app change

---

src/components/messenger/user-profile/linked-accounts-panel/index.tsx
src/components/messenger/user-profile/overview-panel/index.tsx
src/lib/feature-flags.ts
src/lib/feature-flags/development.ts
src/lib/feature-flags/flags.ts
src/lib/feature-flags/production.ts

Changes `Manage accounts` -> `Manage wallets`
Moves `Linked Accounts` section
Removes oAuth linking feature switch
Removes linked accounts feature switch

Update profile panel options

---

src/components/profile-card/index.tsx
src/components/profile-card/index.vitest.tsx
src/components/profile-card/lib/useProfileCard.ts
src/components/profile-card/styles.module.scss

- feat(profile-card): add zero pro badge to profile card
-

feat(profile-card): add zero pro badge to profile card

---

src/apps/feed/components/feed/index.tsx
src/apps/feed/components/post-view-container/index.tsx
src/apps/feed/components/post-view-container/reply-list/index.tsx
src/apps/feed/components/post/index.tsx
src/apps/feed/components/posts/index.tsx
src/apps/profile/lib/types.ts
src/apps/profile/lib/useProfile.ts
src/apps/profile/panels/UserPanel/index.tsx
src/apps/profile/panels/UserPanel/index.vitest.tsx
src/apps/profile/panels/UserPanel/useUserPanel.ts
src/components/profile-card/index.tsx
src/components/profile-card/index.vitest.tsx
src/components/profile-card/lib/useProfileCard.ts
src/store/posts/utils.ts

- feat(feed/posts): wire up zero pro sub status to post data

feat(feed/posts): wire up zero pro sub status to Feed and Post data

---

src/components/messenger/user-profile/container.tsx
src/components/messenger/user-profile/index.tsx
src/components/messenger/user-profile/overview-panel/index.tsx
src/components/messenger/user-profile/overview-panel/styles.scss
src/components/messenger/user-profile/zero-pro-panel/index.tsx
src/components/messenger/user-profile/zero-pro-panel/stages/Main.tsx
src/store/authentication/types.ts
src/store/channels/index.ts

- replace status network request for zero pro status data and use current user data instead
- update overview panel to display pro status badge

refactor: replace status network request for zero pro status with current user data

---

src/lib/feature-flags/production.ts

feat(feature-flag): flip zero pro flag - production

feat(feature-flag): flip zero pro flag - production

---

src/lib/feature-flags/production.ts

revert: feature flag flip - zero pro

---

src/lib/feature-flags/production.ts

feat(feature-flag): flip zero pro feature flag

feat(feature-flag): flip zero pro feature flag

---

src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/autocomplete-members/styles.scss
src/components/messenger/lib/types.ts
src/components/messenger/lib/utils.tsx
src/components/messenger/list/selected-user-tag/index.tsx
src/components/messenger/list/selected-user-tag/selected-user-tag.scss
src/components/messenger/list/user-search-results/index.tsx
src/components/messenger/list/user-search-results/user-search-results.scss
src/store/users/types.ts

adds badge to selected user tag

feat(select-user-tag): add zero pro subscription badge to selected user tags

---

src/apps/feed/components/feed/search-drawer/index.tsx
src/apps/feed/components/feed/search-drawer/styles.module.scss

- adds zero pro sub badge to search drawer results

feat(search-drawer): add zero pro sub badge to search drawer results

---

.env.example
.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/staging.yml
src/config.ts

- adds multiple infura urls to env vars and config
- to be able to select network and search tokens for create channel flow

feat(config/env-vars): add multiple infura urls to env vars and config

---

src/apps/wallet/home/components/receive-dialog.tsx
src/apps/wallet/send/components/token-number-input.tsx
src/apps/wallet/send/components/token-swap-module.tsx
src/apps/wallet/send/search/wallet-user-search.tsx
src/apps/wallet/send/success/wallet-transfer-success.module.scss
src/apps/wallet/send/success/wallet-transfer-success.tsx
src/apps/wallet/send/transfer-amount/wallet-transfer-amount.tsx
src/apps/wallet/transactions/transaction.module.scss
src/apps/wallet/transactions/transaction.tsx
src/apps/wallet/types.ts
src/lib/feature-flags/production.ts

Minor feedback items on the wallet UI
Add z chain warning to receive dialog
Enables feature switch in prod

Release wallet

---

src/apps/wallet/components/token-icon/token-icon.module.scss

Fixes the image size of token icons

Fix token icon image size

---

src/components/claim-rewards-button/index.tsx

refactor: remove logs

---

src/components/messenger/user-profile/overview-panel/rewards-item/index.tsx

refactor(hover-card/claim): update text

refactor(hover-card/claim): update text

---

src/lib/feature-flags/production.ts

feat(feature-flags): flip enableClaimRewards

feat(feature-flags): flip enableClaimRewards

---

src/apps/wallet/components/formatted-number/formatted-number.tsx
src/apps/wallet/queries/useBalancesQuery.ts
src/apps/wallet/tokens/token-skeleton.module.scss
src/apps/wallet/tokens/token-skeleton.tsx
src/apps/wallet/tokens/tokens-list.tsx
src/apps/wallet/transactions/transaction-skeleton.module.scss
src/apps/wallet/transactions/transaction-skeleton.tsx
src/apps/wallet/transactions/transactions-list.tsx
src/apps/wallet/utils/format-numbers.ts

Better token skeleton
Better transaction skeleton
Better decimal handling for dollar values
Preloading token images to prevent pop in

wallet: Small cleanup items in tokens list

---

src/components/zero-pro-badge/index.tsx

- improves display hover card logic
- does not render hover elements if user is zero pro subscriber, just the icon
- improve code quality

refactor(zero-pro-badge): improve display hover card logic

---

src/apps/feed/components/create-channel/stages/find-token-stage/index.tsx
src/apps/feed/components/create-channel/stages/find-token-stage/styles.module.scss

- disables select network options that are not yet available
- improve ux 

refactor(create-channel/find-token-stage): disable select network options that are not yet available

---

src/apps/feed/components/post/styles.module.scss

- fix post scrollbar that appears on meow click

fix(post): post scrollbar appears on meow click

---

src/apps/feed/components/create-channel/stages/creating-channel-stage/index.tsx

fix: create channel stage error handling

fix: create channel stage error handling

---

src/apps/feed/components/join-channel/index.tsx

- updates join text on join requirements for new token gated channels

feat(join-channel): update join text on join requirements for new token gated channels

---

package-lock.json
package.json
src/index.tsx
src/lib/browser/index.ts
src/pages/index.ts
src/pages/oauth-consent/index.ts
src/pages/oauth-consent/oauth-consent.module.scss
src/pages/oauth-consent/oauth-consent.tsx
src/pages/oauth-consent/scopes.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts
src/store/login/index.ts
src/store/login/saga.ts
src/store/login/selectors.ts

Adds support for redirecting on login (for OAuth)
Adds OAuth consent page
Adds support for Zero as an OAuth login provider
Test with new Z Wallet coming soon

Add support for redirect on login, and oauth consent page

---

src/apps/feed/components/create-channel/stages/review-stage/index.tsx

add wallet validation for token-gated channel creation
ensure the user purchases zid with their associated self custody wallet to avoid any unexpected behaviours such as failed validation

feat(create-channel-tgc/review-stage): add wallet validation for token-gated channel creation

---

src/apps/feed/components/create-channel/stages/review-stage/index.tsx

We're updating the signer creation in the channel purchase review stage to use wagmi's getWalletClient instead of MetaMask-specific window.ethereum, and adding user-friendly error handling for signer creation failures.
To support all wallet types that RainbowKit supports (WalletConnect, Coinbase Wallet, etc.) instead of being limited to MetaMask, and to provide clear error messages to users when wallet integration issues occur instead of silent console errors.

feat(create-channel-tgc/review-stage): support all RainbowKit wallet types for zid purchase flow

---

src/lib/feature-flags/production.ts

- flip enableCreateTGCChannel flag

feat(feature-flags/production): flip enableCreateTGCChannel flag

---

src/apps/feed/components/create-channel/stages/create-zid-stage/index.tsx

fix(create-channel/zid-stage): hardcode meow ticker

---

src/apps/staking/features/stake-in-pool/hooks/useStakeData.ts

Fixes formatting issue when using "Max"
parseFloat rounds up the number, which is more than the user has

fix(staking): Fix max issue

---

src/components/message/index.test.tsx
src/components/message/media/messageMedia.tsx
src/components/message/styles.scss
src/components/message/utils.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Removes the complexity of optimistic rendering
Optimistic rendering has had some issues with content not showing up properly, so this removes the complexity and relies on syncing messages instead for 100% reliability

Clean up message rendering bugs

---

src/apps/staking/lib/useClaimRewards.ts

Fixes the chainId being on params instead of the body

Fix chain id with claim staking rewards

---

src/apps/staking/features/view-staking-pools/index.tsx
src/lib/feature-flags.ts
src/lib/feature-flags/development.ts
src/lib/feature-flags/flags.ts
src/lib/feature-flags/production.ts

Adds the AVAX MEOW staking pool to the UI

feat(staking): Release AVAX MEOW staking pool

---

src/apps/wallet/components/zero-card/zero-card.tsx
src/apps/wallet/home/wallet-home.module.scss
src/apps/wallet/hooks/useWalletBalance.ts
src/apps/wallet/hooks/userZeroBalance.ts

Totals all token prices instead of only Z Chain MEOW

Update wallet balance to take into account multi-chain assets

---

src/apps/feed/components/create-channel/lib/hooks/useZidAvailability.ts
src/apps/feed/components/create-channel/stages/review-stage/hooks/useGetParentDomainHash.ts

- update use of graph endpoints (zchain)
- use zchain

feat(zns): update graph endpoint (zchain)

---

src/apps/token/components/table-empty-state/index.tsx
src/apps/token/components/table-header/index.tsx
src/apps/token/components/table-header/styles.module.scss
src/apps/token/components/table-row/index.tsx
src/apps/token/components/table-row/styles.module.scss
src/apps/token/components/utils.ts

- adds trade column to dex table and rows
- to display trade button as per design

feat(token-app/dex-table): add trade column to dex table and rows

---

src/apps/staking/features/view-pool/index.tsx
src/apps/staking/features/view-pool/styles.module.scss
src/apps/staking/lib/useClaimRewards.ts
src/lib/api/rest.ts

Adds error handle for claim rewards and shows insufficient gas balance error properly

Add error message for gas balance

---

src/restricted.scss
src/restricted.tsx

refactor(restricted-screen): redesign

---

src/apps/token/components/token-launcher/FormInputs.tsx
src/apps/token/components/token-launcher/index.tsx
src/apps/token/components/token-launcher/styles.module.scss
src/apps/token/components/token-launcher/utils.ts
src/apps/token/hooks/useTokenForm.ts
src/apps/token/hooks/useTokenSubmission.ts

Revert "refactor(token-app/token-launcher): remove initial buy amount input and approval step from token launcher"

---

src/components/app-bar/index.tsx
src/components/app-bar/index.vitest.tsx

feat(app-bar): update layout

---

.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/staging.yml

fix: pin netlify-cli to v23.7.1 to resolve deployment failures

fix: pin netlify-cli to v23.7.1 to resolve deployment failures
