zer0-os/zOS

src/components/feature-flag/index.test.tsx
src/components/feature-flag/index.tsx
src/lib/feature-flags.ts

adds the ability to set feature flags, and use them from within components.
so that we can hide functionality behind feature flags
add a feature flag and see if it works.

add feature flag lib and supporting component

---

src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx
src/components/address-bar/container.test.tsx
src/components/address-bar/container.tsx
src/components/address-bar/index.test.tsx
src/components/address-bar/index.tsx
src/components/app-menu/container.test.tsx
src/components/app-menu/container.tsx
src/lib/apps/index.ts
src/store/apps/index.test.ts
src/store/apps/index.ts
src/store/apps/saga.test.ts
src/store/apps/saga.ts
src/store/zns/index.ts
src/zns-route-connect.tsx

small refactor to apps types and structure across the platform.
adds app object to state rather than just the type.
to make things a bit more explicit, so it's easier to add new apps, and easier to access data about the current app.
load the app. click around. observe.

Refactor apps

---

package-lock.json
package.json

updates the feed version to fix paging.
the feed paging was resetting whenever the metadata was loaded for the items. it is now smarter, and also dumber. we will reset whenever the item collection updates, but not when individual item data is changed.
load the feed. scroll. watch the magic. (there should not be duplicate metadata requests)

bump feed patch version

---

src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx
src/store/web3/index.test.ts
src/store/web3/index.ts

adds address & chainId to app interface.
to provide contextual data to the current app
if the app loads, it's good. unless you're building an app. then you can make sure you've got the current chain and address when they update.

Add to app interface

---

package-lock.json
package.json

fixes the feed scrolling.
adding a fixed height to the app container caused the feed to stop scrolling. each app should be responsible for a) managing its own scrolling, or b) using its height to trigger scrolling on the parent/sandbox container.
go to the feed. see it scroll.

bump feed version to fix scrolling

---

src/platform-apps/channels/channel-view-container.test.tsx
src/platform-apps/channels/channel-view-container.tsx
src/store/messages/api.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

fixes a bug where new messages were always appended to the message list.
because duplicate messages are no fun.
go to a channel.
go to another channel.
go back to the first channel.
you should only see messages that you should see.

Fix messages bug

---

src/lib/api/rest.ts
src/store/channels-list/api.ts

The `join` method from path was removing a slash. Resulting in: `makePath https:/zero-network-development.herokuapp.com`

Changed API URL joining (the 'join' method was stripping slashes)

---

package.json

Increments `@zero-tech/zapp-staking` version number.
There have been a number of changes pushed to the Staking zApp.
Unsure if we ironed out this process - let me know!

feat: bump zapp-staking version

---

package-lock.json
package.json
src/app-sandbox/index.tsx
src/lib/apps/index.test.tsx
src/lib/apps/index.ts

- Adds a new external package: [`@zero-tech/zapp-nfts`](https://www.npmjs.com/package/@zero-tech/zapp-nfts) - this is the nfts zApp.
- Adds the App.NFTS enum value to the list of active apps in lib/apps/index.ts.
- Renders NFTS zApp when selectedApp === App.NFTS.
Short answer: it adds zApp NFTS to the list of apps.
- To break ground on the relationship between zApps and zOS - this PR will act as validation of our process.
- Click "NFTS" in the app selector.
- Check that the "NFTS" app renders.

feat: add zApp NFTS to app container

---

src/components/zns-dropdown/index.tsx
src/main.scss

Modifies the spacing and alignment of the top left Connect wrapper and changes the copy in the Search.

UX: changed Search copy, modified top Connect wrapper.

---

src/Main.test.tsx
src/Main.tsx
src/_layout.scss
src/_variables.scss
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/app-sandbox/styles.scss
src/components/app-menu/styles.scss
src/main.scss

fixes the animation of the search bar when the platform menu collapses/expands
because the animation is off, which looks bad.
open the app. expand the browser so that the app menu is expanded. shirnk the browser so that it collapses. all of the layout elements, including the search bar, should animate at the same speed.

Fix collapse animation

---

.env.test

The tests expect the default app to be NFTS. This creates a `.env.text` to ensure consistent setup of the test environment.
Tests should pass out of the box without extra setup.
* Run the full test suite. All tests should pass now.
* Manually verified that `npm start` still respects the `.env` file values and ignores `.env.test`.
* Also verified that vars that are already set in the environment are not overridden by the `.env.test` file.
1. How will this affect security? No
1. Does this change any APIs? No

Set the default app to NFTS during tests

---

.eslintrc.json
src/components/indicator-message/index.test.tsx
src/components/message-input/index.test.tsx
src/components/message-input/menu.test.tsx
src/components/message-input/utils.test.ts
src/platform-apps/channels/channel-view.test.tsx
src/platform-apps/channels/message.test.tsx
src/store/theme/index.test.ts

This turns no-unused-vars in typescript files to be a lint error rather than a warning and fixes up the current errors.
Code cleanliness
Run the lint
1. Does this change any APIs? N/A

Lint: Make unused variables in typescript an error

---

src/_layout.scss
src/app-sandbox/styles.scss
src/platform-apps/channels/channel-view.tsx
src/platform-apps/channels/styles.scss

1. Adds left padding (64px) to the AppContent component
2. Adds a css variable for apps to use to add right padding as necessary
3. Updates the Channels app to use the right hand padding
Note: PR to add the right padding to the Feed app to follow.
https://www.notion.so/zerotech/9a4ed77a5ea14501a3e6ef7a33f5a546?v=21e3add7413040bfb3eaf77e8c689cec&p=a2badc2a9c354fee800342544f121f8c&pm=s
We decided that, due to apps potentially having scrollbars, we'd enforce the 64px padding on the left side of the AppContent node but provide a simple mechanism for the apps to define where in their structure the 64px right padding should go. While not ideal, it's a simple compromise between flexibiity and consistency. Otherwise, the scrollbars would be seen 64px inside the right edge of the browser and …

Add padding to AppContent components

---

package-lock.json
package.json

Updates the feed app version to the latest version which implements the new padding requirements.
To ensure consistency of app spacing. [Task](https://www.notion.so/zerotech/9a4ed77a5ea14501a3e6ef7a33f5a546?v=21e3add7413040bfb3eaf77e8c689cec&p=a2badc2a9c354fee800342544f121f8c&pm=s)
Load zOS and verify that there is 64px of spacing between the right side of the browser/scrollbar and the content.
1. Does this change any APIs? No

Update feed app

---

src/components/autocomplete-dropdown/index.tsx

Changes the deprecated componentWillReceiveProps hook to the UNSAFE version.
>      Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
>
>      * Move data fetching code or side effects to componentDidUpdate.
>      * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
>      * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod …

Mark componentWillReceiveProps as unsafe

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx

1. When authenticating, if we receive an error from web3 then we shouldn't expect that there's a valid response object to reference.
1. Removes a console.log statement as we shouldn't log raw errors
1. Removes try/catch
Bug fix.
Authenticate
1. Does this change any APIs? N/A

Fixes a bug in authentication where we are referencing a result even in the case of an error

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/utils.ts

Improves the performance of the message-input test by not fully rendering the complicated nested component. While they have all improved the significant differences are:
* adds placeholder
* submit message when click on textarea
Before:
After:
While having the fastest possible tests isn't an end goal in itself, it is a factor in the developer experience. This is a simple change that improves some of our slowest tests.
Run the automated tests.
1. How will this affect performance? Faster testing
1. Does this change any APIs? No

Improve performance of message-input tests

---

src/components/message-input/index.tsx

Fix an error where we were returning a function rather than calling the function.
Because Dale is a fool.
Paste an image into the message input.

Fix error when using the global clipboard

---

src/components/autocomplete-dropdown/autocomplete-dropdown.test.tsx

Refactoring of the autocomplete-dropdown tests.
I found the tests difficult to follow while I was working on the performance. This makes a few things a little easier to undestand, IMO.
Run the automated tests.

Refactor: autocomplete-dropdown tests"

---

src/components/autocomplete-dropdown/autocomplete-dropdown.test.tsx
src/components/autocomplete-dropdown/index.tsx

Fixes the "escape" test for the autocomplete-dropdown
While refactoring the tests I noticed that the test for pressing the escape key did not, in fact, press the escape key.
* Run the tests
* Open zOS and start typing in the network search. Press Escape. Verify that the autocomplete component disappears.

Fix autocomplete escape key test

---

src/app-sandbox/container.test.tsx
src/app-sandbox/index.test.tsx

This change mocks the importing of large external project during some tests. This saves a significant amount of time.
Before:
After:
Importing these libraries is quite expensive and we don't directly render them during the tests so we don't need the full projects to be loaded.
Run the automated tests

Tests: Mock imports that are loading large sets of code

---

src/Main.test.tsx
src/app-sandbox/container.test.tsx
src/components/autocomplete-dropdown/autocomplete-dropdown.test.tsx
src/components/autocomplete-dropdown/index.tsx
src/components/error-boundary/index.test.tsx
src/components/theme-engine/index.test.tsx
src/components/web3-connect/index.test.tsx
src/components/zns-dropdown/index.test.tsx
src/setupTests.ts
src/store/theme/saga.test.ts

This fixes existing type errors in the tests.
Since the build only includes production files these typescript errors were never really noticed. Now that we're going to run the type check on the whole src folder we need to have correct types in the tests. This is, of course, also just the desired thing.
Run the type check: `npx tsc`

Fix type errors in tests

---

.github/workflows/development.yml
.github/workflows/production.yml

Note: Do not merge until #305 has been merged as that will ensure the current branches pass the checks.
This adds the lint and typecheck to the set of pre-checks prior to doing a build on `development` or `main`.
Added verification to detect when merge issues occur.
Merge to development or main.

Run lint and quick type check before deploying to development/production

---

src/components/autocomplete-dropdown/autocomplete-dropdown.test.tsx
src/components/autocomplete-dropdown/index.tsx
src/components/zns-dropdown/index.test.tsx
src/components/zns-dropdown/index.tsx

Note: I tried to refactor in steps and commit at appropriate increments in case the progression is easier to follow than just the end result.
Renames an event that was published by the autocomplete-dropdown component and updates the component to be a little more clear about what the intent is.
I found it difficult to understand what the dropdown was meant to be doing. For example, what does "close bar" even mean from the context of a generic autocomplete dropdown?
Generally speaking, components should use events that indicate what happened vs how something should react. We want to tell the parent component that the user cancelled their search/selection but it's up to the parent to decide that means they want to "close" the whole thing.
Perform some zns searches. Use esc to cancel, select …

Refactor: Rename event published by autocomplete-dropdown

---

.github/workflows/development.yml
.github/workflows/production.yml

This changes the production deployment action to only run when a release is published rather than on merge to main. After this step we'll have to manually create the release after merging the release branch into `main` until the rest of the process becomes more automated.
This is the first step in moving towards development on the `main` branch and using tags/releases for deployment.
Create a release and verify that it runs the deploy as expected.

Deploy to production when a release is published

---

bin/create-release

Updates the `create-release` script to create a tag instead of a release branch.
We're moving toward using tags and github releases for deployment.
Run `./bin/create-release -d`. This should perform a dry-run and tell you which version you're about to publish.
You may need to comment out the `checkout_main` call and then change your `package.json` version to something new to get past the sanity checks. Be sure to delete the newly created tag if you need to with `git tag -d vX.Y.Z`

Update create-release script to create a git tag instead of a branch

---

.github/workflows/create-release.yml

Adds a github action that will, hopefully, create a new Release when a tag is pushed.
This is untested at the moment and includes the ability to manually trigger it. Unfortunately, in order to do that it must first exist on the default branch.
To automate the step of creating the Release on github.
To be tested once merged to main

Draft release when tag created

---

.github/workflows/development.yml

Removes the development branch from the deploy action
No longer using the development branch and we don't want conflicting deploys.

No longer deploy to development when the development branch is updated

---

.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/run-build.yml
.github/workflows/run-lint.yml
.github/workflows/run-tests.yml
.github/workflows/run-typecheck.yml

Adds concurrency protection to github actions to ensure only one run is happening at a time.
When merging PRs to developemnt, for example, we don't want to have competing deploys as they may collide and the timing would be indeterminate.

Add concurrency protection to github actions

---

.github/workflows/create-release.yml

Changes the release creation action to use the version as the release name and not a concatenated string.

Use just the version for the release name

---

bin/create-release

Updates the instructions at the end of create-release to just publish the newly created release.
This is the new process now that we have a github action to automatically create a release when a tag is created.

Update instructions at the end of create-release

---

bin/create-hotfix

Adds a script to set up for hotfix development.
In the rare case when we need to make an emergency fix and don't want to deploy the latest `main`, we want to be able to quickly set up to deploy a hotfix.

Script to set up hotfix development

---

.github/create-tag
.github/workflows/create-tag.yml

Adds a github action to create a new tag based on the package.json version whenever the file is changed. If the tag already exists this silently passes as it is an indication that the package.json file changed in an unrelated way.
To reduce the manual work to create new releases

Create tag via github action when the package.json version changes

---

src/utils.ts

This adds a temporary extra log message to the release output to simulate a change that has been made on main when we want to do a hotfix that does not include the change.

Add a log statement to the release output to test hotfix deploys

---

.github/workflows/run-tests.yml

Since we run the tests on every branch push vs on PRs we need the concurrency matcher to use the github ref vs the PR ref.

Fix the concurrency matcher in run-tests

---

src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/sidekick/styles.scss
src/platform-apps/channels/direct-message-members/index.test.tsx
src/platform-apps/channels/direct-message-members/index.tsx
src/platform-apps/channels/direct-message-members/styles.scss

render unread messages :
- in front of each chat
- total on all unread messages in tab head

show unread count

---

src/lib/api/attachment.ts
src/lib/api/rest.ts

ZERO-API PR: [https://github.com/m3m3n70/zero-api/pull/874](https://github.com/m3m3n70/zero-api/pull/874)
Pass an X-header (`X-APP-PLATFORM`) while making any request to zero-api.
Screenshot on zero-api PR is added

Support cookie renaming via client headers

---

src/platform-apps/channels/styles.scss

Fixes bug where chats with very few messages weren't rendering the proper height.

Fix non-full height chat window with few messages

---

src/platform-apps/channels/styles.scss

Center the date heading in chat to match design

Center align the chat date

---

src/components/icon-button/index.test.tsx
src/components/icon-button/index.tsx
src/components/icon-button/styles.scss
src/components/message-input/menu.tsx
src/platform-apps/channels/direct-message-chat/index.test.tsx
src/platform-apps/channels/direct-message-chat/index.tsx
src/platform-apps/channels/direct-message-chat/styles.scss
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx
src/platform-apps/channels/messages-menu/styles.scss
src/platform-apps/channels/styles.scss

Creates an IconButton component to have common styling for all clickable icons.
Note: In a future PR this will be pulled into the zUI repository.
To make it easier to adhere to the standard design for clickable icons.

Extract an IconButton component and update the chat window

---

src/platform-apps/channels/direct-message-chat/index.tsx
src/platform-apps/channels/direct-message-members/index.tsx
src/platform-apps/channels/util/index.test.ts
src/platform-apps/channels/util/index.ts

Removes spaces in the list of names in the Direct Message member list.

Fixed spaces in the names of the Direct Message member list

---

src/platform-apps/channels/direct-message-chat/styles.scss

Moved DM title ellipsis to tooltip (title is now a tooltip)

---

src/components/message-input/index.tsx
src/components/message-input/styles.scss

The mentions popup was being cut off as it renders outside the message input. Allow overflow so that it's visible.

Allow mentions menu to render in portal

---

src/platform-apps/channels/messages-menu/portal-menu.test.tsx
src/platform-apps/channels/messages-menu/portal-menu.tsx
src/platform-apps/channels/messages-menu/styles.scss

This makes the PortalMenu actually use a Portal so it can popup over top of everything.

PortalMenu now uses a portal

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message-input/index.tsx

Fix lost focus for chat input

---

src/components/chat-connect/chat-connect.tsx
src/lib/chat/index.ts

Disconnects a user when their Chat Access Token is revoked.
https://user-images.githubusercontent.com/31045/219496463-cf2b08d8-aa9c-4ae2-ad2d-cf453052ed06.mov

Disconnect a user when their Sendbird token is revoked

---

src/Main.tsx
src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/sidekick/styles.scss
src/components/sidekick/types.ts
src/lib/storage/index.test.ts
src/lib/storage/index.ts
src/setupTests.ts
src/store/layout/constants.ts
src/store/layout/index.test.ts
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts
src/store/layout/types.ts
src/store/layout/utils.test.ts
src/store/layout/utils.ts
src/store/saga.ts

- store the state of sidekick if it's open or closed.
- in case no value in the storage, we open the sidekick and we store the value.

make sidekick opening interactive with storage

---

src/store/messages/saga.test.ts
src/store/messages/saga.ts

When we fetch the next set of messages (i.e., scrolling) this adds the new messages to the start of the message list since we receive everything in chronological order.
Bug fix
Scroll up in a conversation and ensure the second page of messages correcly renders at the top of the chat and not the bottom.
1. Does this change any APIs? N/A

Put the messages in the right order when fetching more

---

.github/dependabot.yml

adds dependabot config file
to keep zapp packages up to date.
you just sit and watch the magic.

adds dependabot.yml

---

src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/sidekick/types.ts
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/user-actions/styles.scss
src/store/layout/utils.test.ts

Moves the notification popup from the sidekick to the UserActions.
Note: This does not yet position the popup relative to the button. That will be completed after moving the Conversations panel button to the UserActions.
Matching design

Move notification popup to UserActions

---

src/components/messenger/list/index.test.tsx
src/platform-apps/channels/container.test.tsx

Adds some tests around some of the channel/conversation filtering logic
We're about to refactor this area and fix the bug where the boolean is inverted.
Run the automated tests

Write tests for some channel filtering logic

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/platform-apps/channels/container.test.tsx
src/platform-apps/channels/container.tsx
src/store/channels-list/index.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts

This fixes the polarity of the `isChannel` flag in redux.
We had accidentally inverted the `isChannel` flag.
Load zOS and verify that the user's Conversations load correctly. Go to the Channels app and verify the list of Channels loads correctly.

Fix the polarity of the isChannel flag in redux

---

src/components/user-actions/container.test.tsx
src/components/user-actions/container.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/user-actions/styles.scss
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx

Adds the unread message count to the Conversation icon
Design implementation
Open the app and send a message to the user from another login. Verify the unread count updates.
Note: at the moment we have a bug where you have to open a chat window first to connect to sendbird to get real time updates.

Add unread count to the UserActions Conversation icon

---

src/components/user-actions/container.test.tsx
src/components/user-actions/container.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/user-actions/styles.scss
src/components/user-actions/user-menu-popup.test.tsx
src/components/user-actions/user-menu-popup.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx

Moves the wallet disconnect functionality into a popup triggered by the user avatar.
Design work
Note: Designs for the popup itself are still pending. This is sufficient to move the wallet address out of the header and still allow the functionality of disconnecting.
Connect a wallet. Click the user Avatar. Click Disconnect. Verify you are disconnected as before.
https://user-images.githubusercontent.com/43770/226710870-013e6ceb-8dbb-41d8-b15e-2839e0b79125.mp4

Move wallet disconnect to a user menu

---

src/components/notification/popup/index.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/components/user-actions/styles.scss
src/components/user-actions/user-menu-popup.tsx

Fixes the Notification popup and UserMenu popup to render relative to the activation nodes
Match design better
Click the Notification icon with the conversations open and closed. Verify the popup is relative to the notification icon.
Click the User Avatar with the Conversations open and closed. Verify again.
Notifications w/ conversation open:
Notifications w/ conversations closed:
User Menu w/ conversations open:
User Menu w/ conversations closed:

Render UserAction popups relative to the right nodes

---

src/components/notification/list/container.tsx
src/components/user-actions/container.test.tsx
src/components/user-actions/container.tsx
src/components/user-actions/index.test.tsx
src/components/user-actions/index.tsx
src/store/notifications/index.ts

Adds the count to the notification icon in the UserActions.
Note: This will only update when you open the notification list at the moment. Live updating to come in a future PR.
So the user can see how many unread notifications they have.
Create a `chat_channel_mention` notification. Open the Notification list. Confirm the unread count shows up by the icon.

Render notification count in UserActions

---

src/components/notification/popup/style.scss

Uses a proper theme based color for the Notifications heading in the popup
So we can see the title in light mode!
Open the notifications popup, switch themes, verify the title changes color appropriately.

Fix the Notifcation popup title color

---

src/components/account/create.test.tsx
src/components/account/create.tsx

- show the error only in case an image is uploaded
- not calling updateImage when no image is uploaded

fix image upload

---

src/store/channels-list/saga.test.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts

Allows public channels to load for anonymous users.
When public channels are fetched from our API they don't have an `isChannel` property, but we use the `isChannel` property within zOS to delineate between Messenger Conversations and Channels. This resulted in our Public Channels being treated as Messenger Conversations.
View zOS as a Disconnected Anonymous user, force a cache refresh, verify that the public channels are loaded.

Resolved an issue where the public channels did not load for anonymous users

---

src/platform-apps/channels/styles.scss

Reduces the size of the link preview so that the 'X' icon is visible in a DM with link preview. Previously it was being overlapped.
Before:
After:

Reduce the size of link preview 

---

package-lock.json
package.json
src/components/sidekick/index.test.tsx
src/components/sidekick/index.tsx
src/components/wallet-manager/index.tsx
src/lib/storage/index.test.ts
src/lib/storage/index.ts
src/store/authentication/index.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts
src/store/layout/index.ts
src/store/layout/saga.test.ts
src/store/layout/saga.ts

Moves the code that was initializing the remembered user sidekick state into an initialize saga.
This felt a little cleaner to set the global state rather than having components try to initialize themselves directly.
Log in as a user, open the sidekick. Log out. Log in as the same user again and verify the sidekick opens.

Create user based initialization saga

---

src/app-sandbox/container.test.tsx
src/app-sandbox/container.tsx

Removes console warning: 'Warning: Setting defaultProps as an instance property on Container is not supported and will be ignored. Instead, define defaultProps as a static property on Container.'

Resolve: 'Warning: Setting defaultProps...' warning

---

src/components/account/create.test.tsx
src/components/account/create.tsx

Pre populates the display name with the short address (this is what was happening behind the scenes). Makes the button keyboard friendly.
[create-account.webm](https://user-images.githubusercontent.com/31045/228037535-b198a82b-e17d-458a-b59e-35cd7dc09aa2.webm)

Create account updates

---

src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/autocomplete-members/styles.scss
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/create-conversation-panel.test.tsx
src/components/messenger/list/create-conversation-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/panel-header.test.tsx
src/components/messenger/list/panel-header.tsx
src/components/messenger/list/start-group-panel.test.tsx
src/components/messenger/list/start-group-panel.tsx
src/components/messenger/list/styles.scss
src/components/sidekick/styles.scss

This re-implements the Create Group Chat functionality. This will create a new group chat as it was previously.
To follow up afterwards with the new group chat screen (i.e., name and image).
To get the app back to the previous state but matching the designs.
Go through all the variations of creating conversations.

Implement Create Group Chat functionality

---

package-lock.json
package.json
src/Main.test.tsx
src/components/messenger/autocomplete-members/__mocks__/index.tsx
src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/autocomplete-members/styles.scss
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/create-conversation-panel.test.tsx
src/components/messenger/list/create-conversation-panel.tsx
src/components/messenger/list/direct-messages-fixture.json
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/panel-header.test.tsx
src/components/messenger/list/panel-header.tsx
src/components/messenger/list/start-group-panel.test.tsx
src/components/messenger/list/start-group-panel.tsx
src/components/messenger/list/styles.scss
src/components/sidekick/styles.scss
src/jest.d.ts
src/setupTests.ts

Refactors the messenger list into separate panels so we can separate the flow logic from each step of the flow.
While adding the group conversation functionality this seemed like a good step to make adding the next screens simpler.
Verify the messenger list still works as expected with the exception of the existing bugs.

Refactor: Split message list into separate components

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/index.test.tsx

Refactor: Extract a component for rendering the conversation item in the conversation list.
Tidying up. More focused tests and simpler components.
* Automated tests
* Open the conversation list and view it. Verify it appears and behaves as expected

Extract ConversationItem component and push tests downward

---

src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/search-conversations/index.test.tsx
src/components/messenger/search-conversations/index.tsx

Changes the conversation search to determine the filtered results during render rather than as static state.
There are numerous bugs related to the user's conversation list changing via external events (eg: real time message received) and the conversation list not updating. An example is the bug where the unread count isn't updating when a new message is received.
* Open the conversation list
* Send a message from another user to this user
* Verify that the unread count updates
https://user-images.githubusercontent.com/43770/229908343-0b107c7c-47a0-435d-bce7-7d7dee722732.mp4

Determine the filtered conversations at render time

---

package-lock.json
package.json
src/components/messenger/list/group-details-panel.test.tsx
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/selected-user-tag.test.tsx
src/components/messenger/list/selected-user-tag.tsx
src/components/messenger/list/start-group-panel.test.tsx
src/components/messenger/list/start-group-panel.tsx
src/components/messenger/list/styles.scss
src/setupTests.ts
src/store/channels-list/api.ts
src/store/channels-list/index.ts
src/store/channels-list/saga.ts
src/store/channels-list/types.ts

Adds the Group Details panel into the group conversation flow.
Note: For now, this just interjects the second panel in the flow always. Once the endpoint is built to search for pre-existing conversations with the same users we can skip the second step if possible.
A step towards allowing users to set the name and image for a group conversation.
Create group conversations
https://user-images.githubusercontent.com/43770/230182486-c19cebb8-1bbb-49c6-950f-bbe3e69db189.mp4

Add Group Details panel to Conversation pane

---

src/store/channels-list/api.ts

Removes the stub response and hits the real api when looking for existing group conversations.
Continuation of the group conversation feature.
Start a group conversation with people whom which you already have a group conversation with (exact member list). When you click Continue it should open your existing conversation.
Start a group conversation with people you don't already have one with. Clicking continue should take you to the Group Details panel.

Hit actual api to check for group conversations

---

src/components/messenger/list/group-details-panel.test.tsx
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss
src/store/channels-list/api.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/types.ts

Adds the Name field to group conversation creation.
So we can name group convos!
Create a group conversation. Set a name. Verify it shows up in the conversation list with the name and the name renders in the chat window.

Add name field to group creation

---

src/components/messenger/list/group-details-panel.test.tsx
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/create-conversation/index.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts
src/store/index.ts
src/store/saga.ts

Puts the Create Group button into loading state while the group is being created.
Note: This also prepares a createConversation saga which will evolve into managing the whole user flow as a saga. It includes some temporary hacks to ensure the flow still continues to work in both modes for now. These will disappear over the next few PRs.
User experience
Create a group conversation and see the loading indicator. Adding an image will make it slower which may help.

Add loading state when creating group conversation

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/create-conversation/index.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts
src/store/create-conversation/types.ts

Moves selecting of group chat members into saga
Continuation of moving Create Conversation user flow into saga.
Verify all functionality of creating a new conversation.

Push selecting members for group chat into saga

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/create-conversation/index.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts

Pushes the management of the entire user journey of creating a new conversation into a saga.
Attempting a new pattern for managing a user journey.
Test the entire flow of creating various types of conversations.

Move management of full create conversation flow into saga

---

src/store/authentication/saga.ts
src/store/create-conversation/saga.ts

Adds an auth channel to announce login/logout events and listens to that channel to cancel in-progress conversation creation.
Tightening up the flow of creating a conversation.
Before: Note that the conversation flow is still in progress when logging back in.
https://user-images.githubusercontent.com/43770/231522934-e6cbf62d-794c-45eb-80fb-9073fcb5474f.mp4
After: Note that the conversation flow has been cancelled
https://user-images.githubusercontent.com/43770/231523000-482eb317-58e3-4d57-8463-599cb55ea9fc.mp4

Cancel a create conversation saga when user logs out

---

src/components/messenger/autocomplete-members/styles.scss
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/styles.scss

Moves the conversation panel padding down the stack to allow for better scrollbar location.
Before:
After:

Move conversation padding to internal components to allow for better scrollbar positioning

---

src/store/create-conversation/saga.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts

Changes some direct references to the store in sagas to use the proper saga effect instead.
Cleanliness
* Start creating a conversation and then logout/login. Verify you're not still creating a conversation in the sidekick.
* Verify realtime notifications are being received while logged in then log out and confirm the connection is no longer listening.

Use saga effects rather than dispatching to the store directly

---

src/store/create-invitation/api.ts
src/store/create-invitation/saga.test.ts
src/store/create-invitation/saga.ts

1. Fetches real invite codes from the actual endpoint
2. Handles errors somewhat cleanly when fetching the invite code (no user feedback)

Fetch a real invite code

---

src/components/user-actions/user-menu-popup.test.tsx
src/components/user-actions/user-menu-popup.tsx

The logout popup was referencing the wallet `address`. This adds detection to prevent failure in the case the address does not exist.
Given the new login flows of creating accounts without a wallet, we need to ensure the app can still render if a user logs in this way.

Fix error when logged in without a wallet address

---

src/components/messenger/list/conversation-list-panel.tsx

Rather than control the mounting/unmounting of the Modal just use the `open` property.
For some reason, unmounting the Modal while it's open causes the app to consume the cpu. There must be some kind of loop in the underlying radix-ui component that goes haywire.
Before: Open the chrome task manager and sort by cpu. Open the Invite dialog and click the X to close it. Watch the cpu for that tab spike forever.
After: Repeat. Note the cpu usage drops back down to a normal usage.

Fix cpu hogging issue: Use Modal open state instead of unmounting

---

src/component-mocks.ts

Updates the zui test mocks
Forgot to do this when updating the zui package.

Update zui mocks

---

src/components/content-highlighter/index.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/platform-apps/channels/styles.scss

Messages with links have the same font as messages without links. They're clickable as well now.

Zos 307: Fix font issue with messages with links, make links clickable

---

src/index.tsx

Changes the onboarding flow to `/get-access`
Match the url provided in the invitation text.

Change the url for entering the onboarding flow

---

src/components/chat-view-container/chat-view.tsx
src/components/link-preview/index.tsx
src/components/message/index.tsx
src/components/messenger/chat/index.tsx
src/lib/browser/index.ts
src/lib/cloudinary/provider.tsx
src/store/create-invitation/saga.test.ts

This hides the singleton cloudinary provider behind a getter function.
Previously, this object was instantiated as soon as the file was loaded. This is a side-effect we'd like to avoid.
Run the tests
Smoke test the app where we have images displayed

Hide cloudinary provider creation behind a function

---

src/components/messenger/list/conversation-item.test.tsx

One test was failing on my local due to timezone issue

Remove hardcoded timestamp from test, use `moment()`

---

src/authentication/email-login/container.test.tsx
src/authentication/email-login/container.tsx
src/authentication/email-login/index.test.tsx
src/authentication/email-login/index.tsx
src/authentication/email-login/styles.scss
src/index.tsx
src/login.scss
src/login.tsx
src/store/login/api.ts
src/store/login/index.ts
src/store/login/saga.test.ts
src/store/login/saga.ts
src/store/reducer.ts
src/store/saga.ts

Implements an initial login by email screen at `/login`
Note: this currently does not let you log in as we don't have an endpoint yet. But, it does implement the basic validation handling and simulates a request.

Login by email screen

---

package-lock.json
package.json
templates/component/index.test.tsx.mustache
templates/component/index.tsx.mustache
templates/generate.js
templates/saga/api.ts.mustache
templates/saga/index.ts.mustache
templates/saga/saga.test.ts.mustache
templates/saga/saga.ts.mustache

Adds a script so you can run `node ./templates/generate.js component src/components/funny-button` and `node ./templates/generate.js saga src/store/interesting-saga`
I find I always create the same few files with a boilerplate starting point. This makes that slightly quicker.

Add a simple template script to generate components and store/saga files

---

src/components/messenger/list/conversation-item.test.tsx

Turns out the test didn't match what we were actually doing.

Fix bad test

---

src/authentication/create-account-details/index.test.tsx
src/authentication/create-account-details/index.tsx
src/authentication/create-email-account/index.test.tsx
src/authentication/create-email-account/index.tsx
src/authentication/email-login/index.test.tsx
src/authentication/email-login/index.tsx
src/authentication/validate-invite/index.test.tsx
src/authentication/validate-invite/index.tsx
src/test/utils.ts

Converts the recent registration and login pages to use forms. This allows a user to hit enter when in the form and it'll do what you'd expect.
UX
On any of the pages, enter information into one of the input boxes and, while still there, hit Enter. Verify the correct behaviour occurs.

Convert the registration/login pages to use forms

---

src/store/registration/api.ts
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Switches the last call of the registration page to `finalize` the account creation.
Rather than raw update profile data we call the business endpoint to finalize the account. This allows us to perform other operations on the back end when a user account is fully created.
Perform the registration flow.

Last page of registration flow now calls finalize endpoint

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

Maps the last message to a messagePreview attribute when rendering the conversation list.
Preperatory refactoring for adding in more detailed mapping of the message preview for admin messages, etc.
Open the app. Verify that the conversation list still shows the last message in the preview.

Refactor: Move the last message text to messagePreview attribute

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message-input/container.tsx
src/components/message-input/utils.ts
src/components/message/index.tsx
src/components/messenger/chat/index.test.tsx
src/platform-apps/channels/util/api.test.ts
src/platform-apps/channels/util/api.ts
src/store/channels-list/types.ts
src/store/channels/api.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts
src/store/channels/saga.ts

This removes code that is no longer necessary that was fetching the channel users every time we rendered a channel/conversation.
This is no longer required as the mentions search endpoint now filters by channel (and not network).
In addition, the normalization of these users was unconventional and we already have the `otherMembers` list on the channel so it was duplicate information.
Verify that you can still mention the appropriate people in channels/conversations.

Remove fetching of useres when channels are opened

---

src/components/admin-message/container.test.tsx
src/components/admin-message/container.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/lib/chat/chat-message.test.tsx
src/lib/chat/chat-message.ts

Adds preprocessing to format admin messages when rendered in the conversation list.
Accuracy/consistency of the messaging.
Invite a user and have them create an account to cause creation of the welcome conversation. Verify that the conversation list now shows the same message as the chat does.

Render the correct admin message in the conversation list

---

src/store/authentication/api.ts
src/store/registration/api.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Looks up a nonce then passes it into the Create Account endpoint.
- Open your developer tools
- Create a new user
- Verify that nonce is being called
- Verify that the nonce is passed in the header of the createAndAuthorize endpoint
https://github.com/zer0-os/zOS/assets/31045/0a83a90a-7d98-41ef-9208-db13e08c9657

Retrieve and pass nonce to Create Account endpoint

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Opens the rewards popup when you login immediately on first sign up.
To show the user the idea of rewards as soon as they enter Messenger.
Sign up as a new user and verify the popup is rendered without having to click the button. Refresh and confirm you no longer see the popup immediately.

Open the rewards popup immediately on first time sign up

---

src/Main.test.tsx
src/Main.tsx
src/app-sandbox/index.test.tsx
src/app-sandbox/index.tsx
src/lib/feature-flags.ts
src/main.scss
src/store/layout/index.test.ts
src/store/layout/index.ts
src/store/layout/saga.ts
src/store/layout/types.ts

Adds a feature flag (`fullScreenMessenger`) to render the app in full screen messenger mode
First step towards networkless Messenger users and full screen mode in zOS. This allows UI to be built in full screen mode while the rest of the full screen styling is completed.
Set the feature flag to true and refresh the page: `window.FEATURE_FLAGS.fullScreenMessenger = true`

Add a full screen messenger mode via feature flag

---

src/lib/feature-flags.ts
src/store/authentication/saga.test.ts
src/store/layout/saga.ts

Public zOS view was broken when logged out because it was forcing you into full screen mode but we don't yet have redirection to the login page. This removes the full screen feature flag and resets the Full Screen mode if a user logs out.

Fix public zOS view

---

src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

Based on design feedback, adds margin to the Invite Friends button in the conversations panel (sidekick)

Add margin on invite button

---

src/components/chat-view-container/chat-view.tsx

Fixes a bug where a brand new user conversation with the admin "welcome" message crashed the first time you open it.

Consider an admin message to be always from a different user in the conversation list

---

src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/components/wallet-select/error-network/index.test.tsx
src/components/wallet-select/error-network/index.tsx
src/components/wallet-select/error-network/styles.scss
src/components/wallet-select/index.test.tsx
src/components/wallet-select/index.tsx
src/components/wallet-select/modal.test.tsx
src/components/wallet-select/modal.tsx
src/components/wallet-select/styles.scss
src/components/wallet-select/wallets.ts

Copies the wallet-select component in from the zos-component-library and styles it to match current designs
Since we're moving towards zUI we're deprecating the zos-component-library. In this case I figured we'd really only be using this component in zOS core so I pulled it into zOS rather than zUI.
https://github.com/zer0-os/zOS/assets/43770/f325f6a2-d940-4c80-b60b-9b5fcaf8f03c

Pull wallet select component in from zos-component-library

---

src/components/messenger/list/panel-header.tsx
src/components/messenger/list/styles.scss

[Design feedback Jira task](https://wilderworld.atlassian.net/jira/software/c/projects/ZOS/boards/33?modal=detail&selectedIssue=ZOS-316)
[Jira Subtask](https://wilderworld.atlassian.net/jira/software/c/projects/ZOS/boards/33?modal=detail&selectedIssue=ZOS-354)
**What I’ve changed**:
- The messenger panel title with back arrow (.messenger-panel__header) needs the padding adjusted slightly to match the designs. Should be 16px vertical and horizontal. 
- Set svg container size so margin-right can be removed for gap between arrow and text. No margin required with correct container size and svg alignment.
- add isFilled prop to Icon to be aligned with design
- add background colour on hover of back button
*On Hover*

fix: messenger-panel header back arrow (conversation flow)

---

package-lock.json
package.json

- chore: bump zui version (`0.22.2`)
This bump includes the updated `children` type for the `Button` component. This means an Icon and a string can be used for the button, as per the image below.
- `children: ReactNode | string;`

chore: bump zui version (`0.22.2`)

---

src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx

Fixes the Connect Wallet bug which neo keeps having. 
If it happens, then localStorage key is cleared, page is reloaded & we show the popup to connect wallet.

Zos 363 fix connect wallet issue

---

src/component-mocks.ts
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

Pushes the timing logic of when to render the invite toast up to the existing user registration saga.
Simplification of state management in the component and concentrates the user flow logic in a single place
Register a new user and verify that the invite toast is shown 10 seconds after the rewards popup is closed for the first time.

Refactor: Move invite toast management to user registration saga

---

src/authentication/create-wallet-account/container.test.tsx
src/authentication/create-wallet-account/container.tsx
src/authentication/validate-invite/index.tsx
src/components/web3-connect/index.test.tsx
src/components/web3-connect/index.tsx
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts
src/store/web3/channels.ts
src/store/web3/index.test.ts
src/store/web3/index.ts
src/store/web3/saga.test.ts
src/store/web3/saga.ts

This refactors the web3 registration logic into a saga. This includes pushing some web3 connection activities into sagas as well to allow for reacting to changes without having to listen to component property updates.
We use web3-react to connect to the web3 external pieces. This means we're reliant upon component property changes to tell us when something in that library has changed. By making that layer as thin as possible (aka, just publishing the changes up to redux) we can then build our event system outside of components. This should make it much easier for us to build and test our user flows and provide a more consistent experience from a development perspective.
Register a new account via web3 through the new invite flow.

Refactor web3 registration to saga

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/store/authentication/saga.ts
src/store/login/index.ts
src/store/login/saga.ts

Refactor to move the web3 login control flow to a saga.
Similar to #618, we're trying to localize the flow control in sagas so components can just deal with rendering rather than performing logic based on property changes.
Enable public zOS and test creating new accounts by wallet in various ways.

Move web3 login logic to saga

---

src/authentication/create-account-details/index.tsx
src/components/account/create.tsx
src/components/image-upload/index.tsx
src/components/image-upload/styles.scss
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/styles.scss

After an image has been uploaded, there is now an option to choose another. This functionality is triggered by an edit icon. The drag and drop functionality also works for replacing an image.
Adds error state to `ImageUpload`.
This PR also fixes the aspect ratio issue on uploaded images.
So a user is able to change the image they have selected. This may be for a number of reasons, i.e. selected the wrong image in the media picker.
Navigate to one of the flows that contains the ImageUpload component. Upload an image and select the IconButton to open the media picker and replace the image, or drag and drop an image file over the ImageUpload component.
https://github.com/zer0-os/zOS/assets/39112648/9399e660-7e09-4443-9585-5e06a2cc200d
Error State:

feat: Implement image replacement functionality

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/components/wallet-manager/index.test.tsx
src/components/wallet-manager/index.tsx
src/store/authentication/index.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts
src/store/web3/saga.ts

Moves the logout handling to a saga rather than within the components reacting to property updates.

Push logout functionality from components to sagas

---

src/store/authentication/channels.ts
src/store/authentication/saga.ts
src/store/create-conversation/saga.ts
src/store/create-invitation/saga.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts

Adds a `type` attribute to the multicast user events.
Allows listeners to filter on the event type that they care about.
Login and logout in various configurations. Verify that the create conversation state is cleared, notifications are re-registered, inivites are fetched for the new user, etc.

Add an action type to the user login/logout events

---

src/components/authentication/index.test.tsx
src/components/authentication/index.tsx
src/store/authentication/channels.ts
src/store/login/index.ts
src/store/login/saga.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts
src/store/web3/channels.ts
src/store/web3/saga.test.ts
src/store/web3/saga.ts

Moves the web3 account change handling logic from component prop updates to sagas
A continuation of the previous refactorings. Relying on a component to keep up with your application state to transition to new states is hard to manage. Having them in the sagas makes this simpler.
Log into the app via web3 in various states. Try changing the web3 account and verify that you are re-logged in as the new account or prompted to finish registering a new account.

Move web3 account change handling into sagas

---

src/authentication/create-wallet-account/container.tsx
src/authentication/web3-login/container.tsx
src/index.tsx
src/zns-route-connect.test.tsx
src/zns-route-connect.tsx

This moves the Web3Connect component render up the tree so that we only render it once when the app loads up.
Moving between parts of the app and having that component wire up from scratch multiple times causes extra, invalid, system level events. This resolves that by making sure it only renders once.
* Login via web3. It should log you in.
Note: There is still an issue where your conversations may not load properly. This is a separate issue that will be resolved independently.

Move Web3Connect component render up the tree

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx

Mentions don't render properly in the conversation list

---

src/components/chat-connect/chat-connect.tsx
src/lib/chat/index.ts
src/store/channels-list/index.ts

Forces a channels + conversations refresh after reconnection with the sendbird client. 
Realtime message doesn't seem as realtime as they should be.

Zos 353: Realtime messages arent consistent

---

src/components/messenger/lib/utils.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/styles.scss

Adds bold font-weight to name and message in conversation item when there is an unread message for that current conversation.  Also changed the colour as per design.
Also some refactoring.
As per design.
Receive a message and check in the conversation list panel whether the name and message is now bold in font weight.

feat: highlight conversation item if unread message

---

src/components/messenger/lib/utils.test.ts
src/components/messenger/lib/utils.tsx

Adds a null/undefined/empty check to the highlightFilter function.
Bug fix: if a profile doesn't have a name this would crash.

Null check on the conversation search highlighting

---

src/components/messenger/list/styles.scss

Fixes the placement of the unread icon.
Unread Icon wasn't being placed at the end of the container.
As per figma design.
Check the conversation list panel for a *short* unread message and check the placement of the unread icon. It should sit at the end of the container as per design.
Berfore
After

fix: unread icon position

---

src/components/messenger/list/styles.scss

Fixes message height issue when there is a link in a message.
Bug in production causing chats to overlap/overflow.
Check conversation panel and conversation items are not overlapping.
Before:
After:

fix: handle word break and ellipsis when there is a link in a messaage

---

src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

When searching and there are no results for current conversations that match what the user has entered,  an empty state will be displayed to inform the user and this will also ensure the vertical padding looks correct. 
As per design to ensure the gap between search bar and conversation list looks correct.
Enter into the search input a name you don't have a current conversation with but there are user results.
Before 
After

feat: add empty current conversation search results state and adjust positioning

---

src/components/message-input/index.tsx

Fixes this issue:
https://github.com/zer0-os/zOS/assets/33264364/e041acfc-c483-42e4-99ad-e379aef1abf1

[Bug] Pasting an image in messenger chat will also paste it in "channels" chat

---

src/components/messenger/list/styles.scss

If there is a link present in the unread message content, the text is not displaying as bold, like the name of the user. This is because there is an additional child div tag when a link is added to the message, so the style is not applied. This PR gives the unread message the correct style when a link is present.
One other small change added - font-weight on unread message number/count.
As per design.
Create an unread message to your user from another test user, and ensure to include a link in the message. When opening the messenger the user with the unread message should have their name in bold and the message in bold.
Before
After

fix: unread message content to bold if link present in message

---

src/store/channels-list/utils.ts

Fixes the channel mapping to use a field that is actually returned from the api.
Because this currently doesn't work.

Translate the correct lastMessageAt field

---

src/_scrollbar.scss
src/app-sandbox/styles.scss
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss
src/components/scrollbar-container/index.test.tsx
src/components/scrollbar-container/index.tsx
src/components/scrollbar-container/styles.scss
src/index.scss
src/platform-apps/channels/container.tsx

- adds `scrollbar()` mixin (rather than use from zos-component-library)
- adds a new `ScrollbarContainer` that handles the style and behaviour of the scrollbar.
- adds a faded panel to to the `ScrollbarContainer` and its behaviour.
- adds the `ScrollbarContainer` to the conversation list panel message items.
- adds the `Scrollbar` container to the channel list content.
- adds `scrollbar()` mixin styles for the invert scroll on the main container.
- adds tests.
As per designs.
Open the app and start scrolling on the channel list, the main channel message container and the conversations panel 🙂 
https://github.com/zer0-os/zOS/assets/39112648/64fd399a-7862-4cc5-8215-38d792c5b6ac

feat: implement scrollbar containers and styles

---

src/store/authentication/channels.ts
src/store/authentication/saga.ts
src/store/create-conversation/saga.ts
src/store/create-invitation/saga.ts
src/store/notifications/saga.test.ts
src/store/notifications/saga.ts

Previously added a new accessor (rename basically) for the auth channel. This follows through on changing all the existing usages to the new name.

Refactor: use the newly renamed getAuthChannel

---

src/store/channels-list/saga.ts

Adds condition so we only fetch channels if we know the domain id.

Only fetch channels if we have a proper domain

---

src/components/scrollbar-container/index.test.tsx
src/components/scrollbar-container/index.tsx

- adds a prop to display or hide the scrollbar panel when the variant is `on-hover`
- design requested to remove this for now. By making this feature optional, we can use at a later date.
- search `<ScrollbarContainer />` in the code and add or remove `hasProp` to the attributes (explicitly). When running locally, if `hasProp` has been added to the attributes and the variant is `on-hover`, you will see the faded panel is rendered.

refactor: add `hasPanel` prop to hide or display scrollbar faded panel

---

src/components/messenger/list/styles.scss

- when a url/link is present in the message preview in the conversation item and the user clicks this with the intention of opening the chat, this will also trigger a new tab to open to the url.
- this is not desired behaviour. If there is a url/link visible in the message preview and it is clicked, only the chat should open, not the link itself.
- click a conversation item in the conversation list panel that shows a url in the message preview (aim to click this specific part of the conversation item) and a new tab to that page should not open.
Before:
https://github.com/zer0-os/zOS/assets/39112648/dedc5b34-0163-4ed1-b6ab-d42e075b1f0c
After: …

fix: prevent clicking on a link in the message preview of the conversation item component

---

src/index.scss

Sets overflow to hidden on the HTML node
To prevent scrollbars from showing up on the overall page when things are rendering.
Open the sidekick with lots of conversations. Scroll rapidly. You should _not_ see a second scrollbar appear.

Don't create scrollbars on the HTML node

---

src/components/messenger/list/styles.scss

- prevents horizontal scroll when empty state search results message is longer than the sidekick/conversation panel container.
- improve the ux when empty state is displayed.
- type a long string into the search input and check whether the word breaks when filling the sidekick/conversation panel container.
BEFORE:
AFTER:

fix: prevent horizontal scroll in empty state search results

---

src/components/sidekick/styles.scss

- adds inherited width to sidekick tab content container to fix jolting width when searching users.
The width of the sidekick container should remain at `270px`.
- to improve the UX of the sidekick container re the width jolting.
- in the sidekick panel, start typing 'to' for example, and determine whether or not the width of the sidekick panels remains the same throughout.
Before:
https://github.com/zer0-os/zOS/assets/39112648/be2e165c-b1d6-413b-bfff-2530dd443da7
After:
https://github.com/zer0-os/zOS/assets/39112648/19350588-73d6-4baf-b5bb-db52ffe7f090

fix: improve ux of sidekick tab content container width (fullscreen-messenger)

---

src/lib/chat/index.ts

Clears our 'keep-alive' interval in the sendbird class and adds a little null safety.
So things don't explode when you logout
Login...then logout and confirm the page doesn't explode with an error.

Clear the interval when disconnecting sendbird

---

src/lib/chat/index.ts
src/store/chat/bus.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Updates chat messages in real time when they've been edited from another session. Not yet implemented: link previews, attachments.
For a smooth experience
1. Open a conversation with another account
2. Edit a message from the other account
3. Verify that the original screen updates in "real time"

Listen to real time message edit events

---

src/store/messages/saga.test.ts
src/store/messages/saga.ts

Adds the url link preview to a message if it was updated to include/remove a url.

Handle link previews when receiving message updates

---

src/lib/chat/index.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

If we receive a user invite to a channel we reload the conversation list right away rather than wait for the intermittent poll. We do this because we don't yet have an endpoint to load a single converation's details.
For better real time behaviour.
Open two session. In one session start a new conversation including the person from the other session. Verify that the new conversation is visible to the other session fairly quickly.

Reload the conversation list when we've been invited to a channel

---

src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx

Dont show rewards tooltip if rewards are '0'

---

src/components/tooltip-popup/styles.scss

Before (tooltip is active but it was hidden)
After

Show rewards tooltip on "top" of conversation

---

src/components/messenger/autocomplete-members/styles.scss
src/components/messenger/list/styles.scss

Adjust preview text in Conversation List sidebar to be entirely non-interactive (e.g., cannot even select or highlight it)
Even if you can’t interact with links in the sidebar in the testing environment, you can still interact with text, including selecting / highlighting. All text in the sidebar should be un-interactable-with. 
Login and navigate to conversation list panel. Attempt to highlight text. Click conversation item to open conversation.

fix: all text to be entirely non-interactive in conversation list panel

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-bar/styles.scss
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/components/settings-menu/styles.scss
src/index.scss

Triggers a drop down menu per the below-provided specs when a user clicks on their pfp in the upper left corner of the conversation list sidebar.
Populate a drop down menu with two items:
- a header with the user’s pfp, display name, and wallet / zID (as applicable, see design)
- logout option
* when clicking to logout the user should be redirected to login page.
Visibility for user to see which account they are logged into and ability to logout/disconnect.
Open messenger. Click profile icon (avatar in top left corner in the sidekick. Dropdown menu should appear with the two items detailed above. Check logout functionality by clicking logout. Should redirect you to the login page. …

feat: add settings menu

---

src/platform-apps/channels/styles.scss

Fixes the date separator in chat views to not float beside messages.
Before:
After:

Fix date separator in chat views

---

src/components/chat-view-container/chat-view-container.tsx
src/platform-apps/channels/styles.scss

This removes the chat view load animations when we're fetching the messages. This allows the user to receive an interactive view immediately.
To provide a snappier feel to the conversation window. Still to come are loading skeletons so that it's clear that message data may still be loading when you open a conversation for the first time.
Before:
https://github.com/zer0-os/zOS/assets/43770/ab5f84d3-47e7-4121-a995-1fd18fb73f87
After:
https://github.com/zer0-os/zOS/assets/43770/a896a233-054c-417c-8ce2-b0951ab26385

Render conversation contents as soon as the chat view is opened

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/platform-apps/channels/attachment-cards/attachment-card.tsx
src/platform-apps/channels/attachment-cards/index.tsx

Allows users to send video files as well. I have kept similar design to attachment card, since we're going to change it anyway. 
preview:
sent:

add video support

---

package-lock.json
package.json

- bumps zui version (`0.24.2`) -> (`0.24.3`)
- to pull in latest changes/additions from zui, including avatar component updates.

chore: bump zui version (`0.24.2`) -> (`0.24.3`)

---

src/platform-apps/channels/styles.scss

Increase size of group conversation participant avatars next to message bubble in conversation window

---

src/components/settings-menu/index.tsx

- Transform `containsAtSymbol` and `userHandle` into methods that get evaluated each time they are called, which would reflect changes in props. 
- When we initialize class fields like in `settings-menu` they get their values once at the time of class instantiation and won't get updated when props change. As a result, it would be better to transform `containsAtSymbol` and `userHandle` into methods.

refactor: refactor userHandle check to a function (settings-menu)

---

src/platform-apps/channels/styles.scss

[ZOS-421](https://wilderworld.atlassian.net/browse/ZOS-421)
[ZOS-421](https://wilderworld.atlassian.net/browse/ZOS-421)
1. Open messenger
2. Send a very long message
3. Adjust viewport size to check scaling
[ZOS-421]: https://wilderworld.atlassian.net/browse/ZOS-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ZOS-421]: https://wilderworld.atlassian.net/browse/ZOS-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(message): bubble width

---

src/components/tooltip-popup/styles.scss
src/components/tooltip-popup/tooltip-popup.tsx

Before:
After:
- hover x icon
As per Figma design:
https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?type=design&node-id=9680-494052&mode=design&t=bry2DJnD3v3oNeLq-0

fix: rewards tooltip ui styling

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

+ removes top title for network users in full screen mode as well
+ add collapse icon in view control header
Note: `IconExpand1` will be replaced by `IconCollapse1` after adding it in zUI.

Revamp view control header display

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx

Uses
instead of the expand icon

Update `IconExpand1` to latest zUI `IconCollapse1`

---

src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss

fix: collapse icon ui fixes

---

src/components/chat-view-container/chat-skeleton.test.tsx
src/components/chat-view-container/chat-skeleton.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss
src/store/channels/index.ts
src/store/messages/saga.fetch.test.ts
src/store/messages/saga.ts

Adds skeleton loading templates to display while messages are being loaded for a conversation for the first time.
To reduce the feel of the loading time.
https://github.com/zer0-os/zOS/assets/43770/d08717ff-1e15-49af-9371-f181788063b0

Render skeleton when loading chat messages

---

src/components/messenger/list/conversation-list-panel.tsx

Prevents re-rendering of conversation search results every time you type a character.
Smooth feel
Type searches in the conversation search and confirm that the lower set of results doesn't flash as you type.

Don't change the search results until we receive the results

---

src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

This removes buggy code that was never being hit. It was intended to show an empty state if you didn't have any conversations.
1. It didn't even work. It would never render because the conditional was bad.
2. In the new Messenger you should always have at least one conversation anyway as we create one when you sign up.
3. Even if you do have an empty conversation list, it looks fine just leaving it empty.

Remove unused code that was pretending to render an empty state

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Sets the hasLoadedMessages flag when creating a new conversation. Since it's new, we have the messages already :)
When we create a new conversation we don't want to show the skeleton loader.
NOTE: Simpler to review with whitespace ignored. I nested some tests.

Assume all messages are loaded after creating a conversation

---

src/platform-apps/channels/styles.scss

Fades in the messages once they're fetched to ease the feel a bit.
Based on feedback from the design team we decided this smooths out the transition between chats and between the loading state to completed state.

Fade in the messages once fetched

---

src/platform-apps/channels/styles.scss

Fixes an issue where messages just prior to the date stamp in a conversation wouldn't react to mouse events thus preventing the 'more' menu from showing up.
Before:
After:

Fixes issue when the 'more' menu doesn't show up on messages prior to a date stamp

---

src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/platform-apps/channels/styles.scss

- repositions sender avatar. This was required for the three dot menu positional changes. The three dot menu will now appear on the inside of the senders message, i.e. if sender is owner then the three dots appear to the left of the message, if the sender is not the owner, the three dots will appear to the right of the message.
- you can run the branch and open up a group chat to see the position of the avatars. They should be as per the `after` screenshot below.
Before:
After:

feat: reposition sender avatar

---

src/store/messages/saga.send.test.ts
src/test/saga.ts

Tried to clean up the send message saga tests a bit.
Note: this is just cleaning what's there whether it's correct or not. Next step will be making these tests more thorough and refactoring the send message a bit to allow us modify it more easily.
They were unnecessarily long and included data unrelated to the thing being tested, etc.

Clean up the send message saga tests a bit

---

src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss

`Close` button
- Correct button size
- Correct button color
Match UI to Figma
- Open Rewards popup
- [Compare `Close` button to Figma](https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?type=design&node-id=7019%3A313888&mode=design&t=iBCZXrRXxzczRa8n-1)

feat(rewards-popup): match close button to Figma

---

src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss

Adds the arrow to the rewards popup [per Figma](https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?type=design&node-id=9680%3A494052&mode=design&t=iBCZXrRXxzczRa8n-1).
Matching UI to Figma.
1. Open messenger
2. Hit "Rewards"
3. In full screen, check that the arrow is on the top left edge of the popup
4. In side panel, check that the arrow is on the top right edge of the popup

feat(rewards-popup): add arrow

---

src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/conversation-list-panel.tsx

Update "Search For Contacts .." placeholder text

---

package-lock.json
package.json

- bumps zUI to latest version (0.24.4) -> (0.25.0)
- pull in latest changes to `DropdownMenu` component.

chore: bump zui version (`0.24.4`) -> (`0.25.0`)

---

package-lock.json
package.json

- bump zui version (`0.25.0`) -> (`0.25.1`)

chore: bump version (`0.25.0`) -> (`0.25.1`)

---

package-lock.json
package.json

- pins radix popper version to resolve arrow/pointer bug
- radix dropdown menu arrow when shown was causing the app to crash

chore: pin radix popper version

---

src/platform-apps/channels/messages-menu/index.tsx

- adds `showArrow` prop to dropdown menu on messages menu
- to display the arrow that points to the dropdown menu trigger
Open chat and click three dots menu. Should see arrow.

feat: add show arrow dropdown menu prop on messages menu

---

src/components/messenger/list/index.tsx
src/components/settings-menu/index.tsx
src/store/authentication/types.ts

- fixes the secondary user information in profile settings menu
- currently displaying incorrect data (using wrong type).
- sign in and click profile avatar. Check out secondary user information. This should be wallet address if available, or email address if no wallet address.
Before:
After:

fix: display correct address for user handle

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Refactors the message send saga into a "flow management" style.
This allows us to test the "phases" of sending a message independently so we can test the intermediate state changes more easily.
Verify that sending messages still works.

Refactor: message send saga split to main chunks

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

When sending a message we now render optimistically and then fetch any link previews in the background while sending the message.
More responsive feeling for the user
Before with 5s delay added to the link preview fetch:
https://github.com/zer0-os/zOS/assets/43770/22d65dc6-6493-4f54-94f2-352017da9173
After with 5s delay added:
https://github.com/zer0-os/zOS/assets/43770/fb245caa-5431-4b1d-b279-0166c4a8d92e
After with normal operation (only standard network delays, etc)
https://github.com/zer0-os/zOS/assets/43770/c67f7578-1c3a-4094-bb2d-db4713853261

Fetch the link preview after rendering the optimisitic message

---

src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/styles.scss

Based on Eth & Kelly's feedback, updated the top padding for the "no results" text to be consistent across both cases.

Add padding to the "no results view"

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.test.ts

Moves the tests for receiveNewMessage into a separate file to make them easier to work with.

Move some tests to a separate file

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts

Fixes a couple of scenarios where receiving a realtime message would do things that we probably don't want.
Easier to understand exceptional scenarios and fixing bugs.

Fix some questionable logic in the realtime message receive

---

package-lock.json
package.json
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/lib/number.test.ts
src/lib/number.ts

Formats the reward amount in the rewards modal as described in [Jira](https://wilderworld.atlassian.net/browse/ZOS-430?atlOrigin=eyJpIjoiMTlkZTM0OTMxNWM5NDA3YzkwZmE1MTNkODY3Yzc3ZTkiLCJwIjoiaiJ9).
The rewards amount did not match Figma.
- Open the rewards modal
- Check that the number is formatting as per the description in Jira.

feat(rewards-popup): number formatting

---

src/platform-apps/channels/styles.scss

- fixes the margin for the compose a message input.
- this change is to fix the margin to what is currently in production. This was not an intended design change, therefore the fix is required.
- open the app (not in full screen) and check the message input has equal margins as per screenshots below.
Before:
After:

fix: update class name to fix message input margin

---

src/components/content-highlighter/content-highlight.test.tsx
src/components/content-highlighter/index.tsx
src/components/content-highlighter/styles.scss
src/components/messenger/list/conversation-item.tsx

- adds a `negative` variant to the content highlighter so mentions are displayed in plain text if variant is set to `negative`.
- adds tests for content-highlighter
- as per figma desings.
- open app, navigate to a conversation and tag a user when composing a message. Send message and check UI in conversation item in sidekick.
Before:
After:

feat: conversation item preview mentions as plaintext

---

package-lock.json
package.json
src/lib/chat/chat-message.test.tsx
src/lib/chat/chat-message.ts
src/store/channels/index.ts
src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

Uses an optimisticId when sending text based messages to correlate received events for optimistically rendered data.
The existing cached array is fragile and buggy at the moment. This allows us to be more accurate.
Send messages and then try to edit them after a couple of seconds. If you can edit them successfully that means the data store was updated correctly.

Use optimisticId to manage rendering of optimistic text based messages

---

src/components/message-input/giphy/styles.scss

- increase z-index of giphy container so when replying to a message the text is no longer layered above.
- UI error.
- open a chat and select a message to reply to. Open the giphy container next to the message input. Check that the text of the reply message is layered behind the giphy container.
Before:
After:

fix: increase zindex of giphy container

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx

- fixes the following bug and adds tests:
https://github.com/zer0-os/zOS/assets/39112648/02cb88d1-2e30-4d45-bc29-48437013b802
- for the intended behaviour (to send a message on click)
- open chat, type message, click send icon.
After:
https://github.com/zer0-os/zOS/assets/39112648/140e88c8-825a-409d-9574-3f9d75983271

fix: send message when clicking send icon

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx

Fixes a bug where we couldn't submit the message when there were only files and no message text.

Send file based messages even with no text

---

src/store/messages/saga.test.ts
src/store/messages/saga.uploadFileMessage.test.ts

Moves the saga tests for `uploadFileMessage` to a separate file.
The saga is buggy and we need to fix it. The main saga test file is too large to deal with.

Move saga tests to separate file

---

src/store/messages/saga.ts

Adds newly uploaded file based messages to the channel message list as of the time of completion.
There was a bug previously where if you uploaded a file based message and new messages came in while those files were uploading the converstion messages would get overwritten with the old state when the image uploads finally finished.
Send file based messages and verify that things still work

Fix bug where sending an image message would break messages received during upload

---

src/store/messages/saga.ts

This ensures we don't add image messages to the channel if they've already been added (usually because of a real time event happening in between).
Bug fix

Fix issue where multiple image uploads would render an image twice

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/store/messages/index.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Moves the sending of file based messages into the general message send saga
Move towards rendering image based messages with text as a single bubble. This pushes the sending logic into the same place so we can control what gets tied together.
Send an image (or other file) message with some messgae text. Ensure all the messages send as usual.

Move file message sending into the send saga

---

src/store/channels/saga.test.ts
src/store/channels/saga.ts

This fires off a fetch for messages when we receive an event that the unread count for a channel changed.
To help the app feel a little snappier. Generally, when you receive a message, you're likely to try to open in so this helps alleviate some of the delay when you do that.
* In one account open an unrelated conversation. Refresh to ensure you don't have anything in memory.
* In another account, send a message to the first account.
* Note the first one will have a message fetch in the network tab and opening the conversation will render the existing messages quickly without the loading skeletons.

Preload channel/conversation messages when the unread count changes

---

src/lib/chat/chat-message.ts
src/store/messages/api.ts
src/store/messages/index.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts

Sets the rootMessageId on the first media file when a message with both text and media files is sent.
Note: This does not yet render the messages as a single bubble.
This will allow us to later render the two messages as a single bubble.
Send a message with both text and an image. Verify the network request sends the rootMessageId on the first image message sent.

Set the rootMessageId on the first media file in message list

---

src/components/messenger/list/conversation-list-panel.tsx

Remove tooltip from hover on '+' New Conversation button 

---

src/zns-route-connect.tsx

Removes this message
NOTE: I haven't removed the actual component, just it's usage (since we may need it later)

Remove `ChatConnect` (Connection Lost message)

---

src/components/message-input/styles.scss

- fixes bug raised by product where some multiline text can be hidden when typing into the message input. 
- removes some hidden borders
- correctly sets font size and line height of text in input
- ui and ux enhancement
- bug fix
- type a range of long and short strings into the message input and check the correct behaviour is occurring. No text should ever be hidden unless scroll is triggered at max height of 200px.
Before: 
https://github.com/zer0-os/zOS/assets/39112648/dd9df5d4-5fd6-4acc-8b4d-625e5b360016
After:
https://github.com/zer0-os/zOS/assets/39112648/d9477d6c-0a5e-4866-b3ae-c73f2cfab370

fix: message input hidden text when multiline

---

src/components/message-input/mentions-config.ts
src/components/message-input/styles.scss

- after some investigating and trial and error, these changes are likely the best we can do at this time with highlighting mentions whilst composing a message due to the restrictions of react-mentions and the figma design.
Demo shows latest changes and what it looked like before:
https://github.com/zer0-os/zOS/assets/39112648/72373924-8e8a-40e1-941b-fd2e56a7bba5

feat: basic changes to composing a message mention highlights

---

src/components/message/index.tsx
src/components/message/styles.scss

Fixes the issue where group conversation messages were filling the max width available rather than being limited to the size of the content.
Before:
After:

Group conversation messages shouldn't fill the max width

---

src/components/message/index.tsx

Removes the usage of a css class `block-body` as it was also used above and this caused confusion (and risk).
Tested rendering of the message and editing a message and it seems to have no impact.

Remove the extra block-body css class usage

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/message/styles.scss

Renders a media message that has a root message as a single message bubble.
Side effects include:
1. Deleting the message only deletes the text message. This means that mobile would still show the image.
2. Until mobile makes changes, these would still show as separate messages on mobile.
3. Cannot edit the text (because we don't allow editing with media)
4. The "last message" preview still shows "You: sent an image"
Better experience
Attach an image (or movie) to a message and type some text. When rendered it should appear as a single message bubble.

Render image message with text

---

src/store/messages/saga.deleteMessage.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts
src/store/messages/test/helpers.ts

When you delete a message this will find all the associated child messages and delete them too.
So the user doesn't know that there are multiple messages behind the scenes and can clean up appropriately.
Create a media message with text and then delete it. Verify that 2 network calls are made to delete both the text message and the media message.

Delete multi-part messages fully

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx

Previously we were hiding child messages if the parent didn't exist because it probably happened due to a deletion. But now we properly delete the messages as a group so this should work as expected for the user on the web interface. However, since mobile does not yet treat these as a single message it is possible to delete the parent and not the child. In this case, we'd want to still see the child in the web to be consistent with the view the user sees in mobile.

Render child messages if the parent is not found

---

src/components/message/styles.scss

Changes the "tall" image rendering to just show it with a max height of 640px

Don't mangle tall images

---

src/components/messenger/autocomplete-members/index.tsx

Highlight search text in results for "Start Group Chat"

---

src/components/message/styles.scss

Position of some message bubbles isn't correct when rendering messages in group chat
Before
After

Fix rendering of messages in "Group Chat"

---

src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx

Before (search results does not show groups)
After

Implement ability to search groups via group name in the conversation list sidebar

---

src/store/messages/api.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts

Refactors the `uploadFileMessage` saga into specific handler classes.
Tidying up in preparation for optimistic rendering of file uploads. This condences the outer controlling logic and allows the differences to be more easily viewed/adjusted.
Upload various combinations of things

Refactor: Extract uploadable file class

---

src/store/messages/api.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts
src/store/messages/uploadable.test.ts
src/store/messages/uploadable.ts

Moves some of the upload logic to a separate file and pulls the mapping up the call stack
To allow adding optimistic rendering more easily

Move some upload logic around

---

src/components/content-highlighter/index.tsx
src/components/messenger/list/conversation-item.tsx
src/components/messenger/list/styles.scss

- The `Avatar` is no longer in the tabbing order.
- `ContentHighlighter` can now be passed a tabIndex to control tab ordering. This will prevent any links in the message preview from being focused.
- The behaviour from TAB-ing to select a conversation or search result is for the entire conversation / user preview itself is now highlighted, without any green ring around the avatar.
- Able to select a conversation using the `Enter` Key.
- Right now, when TAB-bing through search results and conversation list results, only the avatar of the selected result is highlighted (a green ring around the avatar).
- Open up the messenger and start keying down the `tab` key. The behaviour should be aligned with the `after` demo below.
1. How will this affect …

feat: conversation item tab accessibility 

---

src/components/tooltip/index.test.tsx
src/components/tooltip/index.tsx

- prevents the tooltip overlay from displaying if overlay content is empty.
- to prevent an empty overlay displaying when hovering over elements that use the tooltip but have no content to display.
- open messenger and hover over conversations in the conversations list panel. As per demos below.
Before:
https://github.com/zer0-os/zOS/assets/39112648/c691a1fe-3826-4e8a-888f-9c6cc82c7d9b
After:
https://github.com/zer0-os/zOS/assets/39112648/aea5086e-d525-4cf9-9aed-d2f84592943f

feat: update tooltip to only render overlay if there is content

---

src/store/users/api.ts

Uses the new route for searching users in network. 
**NOTE**: Should only be merged after [https://github.com/m3m3n70/zero-api/pull/1048](https://github.com/m3m3n70/zero-api/pull/1048)

Use V2 route for searching users in network

---

src/components/message-input/utils.ts
src/store/messages/api.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/saga.uploadFileMessage.test.ts
src/store/messages/uploadable.test.ts
src/store/messages/uploadable.ts
src/store/messages/utils.ts

Renders the image messages optimistically.
Note, scenarios not yet handled perfectly but coming:
* Sending an image with text still waits until the text message is sent before rendering the files (but they render all optimistically once that happens)
* When the final message result arrives from the server there's some rendering blips as the ids change
Provide immediate feedback to the user and have a more natural feeling of performance.
Send messages with files/images and notice they render immediately
https://github.com/zer0-os/zOS/assets/43770/32dbb0aa-a589-40a2-97f8-0130bf5f6029

Render file messages optimistically

---

src/components/chat-view-container/chat-view.tsx

Uses the `optimisticId` as the first preference for the rendering key when rendering Messages.
To prevent full re-rendering (and thus flashing) of messages when optimistic data becomes true data.
https://github.com/zer0-os/zOS/assets/43770/2cc5c7d6-7983-4c62-a042-b4e46e29b0ff
https://github.com/zer0-os/zOS/assets/43770/adf62dc4-5487-4214-8b9b-2ce88df6e2df

Use optimisticId for first rendering key

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

When we send a file message with text it will now render both pieces of the message optimistically before sending any api requests
Smooth experience

Render the full text with image message optimistically

---

src/store/chat/saga.ts

Clears the state for the active conversation id and active channel id when a user logout event occurs.
Future logins can fail if these values are set to channels that are unavailable to the newlyy logged in user. It's also not good to leave active state layin' around.
* Login as a user and wait for the first conversation to load
* Logout
* Login as a different user who wasn't involved in the conversation above
* Verify the app loads up and loads the first conversation for the new user

Clear active conversation and channel on logout

---

src/store/create-invitation/saga.ts

Clears the invitation state when user logs out
Cleanliness, security

Clear invite data on logout

---

src/components/messenger/list/styles.scss
src/components/messenger/list/user-search-results.test.tsx
src/components/messenger/list/user-search-results.tsx

- The Avatar is no longer in the tabbing order - given tabIndex -1.
- The behaviour from TAB-ing to create a conversation from a user search result is for the entire user preview itself is now highlighted, without any green ring around the avatar.
- Able to create a conversation using the Enter Key.
- accessibility and as per design
- search for user in the conversation list panel. When there are user search results, key down tab to navigate through the results.
Before: 
https://github.com/zer0-os/zOS/assets/39112648/c4030685-6431-4a66-a0a0-aeea389c1a17
After: 
https://github.com/zer0-os/zOS/assets/39112648/8aa37d97-bd56-4c74-abbc-7122fc7d0849

feat: tab accessibility for start conversation user results search

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-popup/container.test.tsx
src/components/rewards-popup/container.tsx
src/components/rewards-popup/index.test.tsx
src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss
src/lib/number.test.ts
src/lib/number.ts
src/store/rewards/api.ts
src/store/rewards/index.ts
src/store/rewards/saga.ts

Design Changes
Before
After:
EMPTY STATE

Zos 539: Display zero as large number and usd value as subtext in rewards modal

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss
src/lib/chat/chat-message.ts
src/platform-apps/channels/styles.scss
src/store/messages/index.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

Adds an error state for when messages fail to send.
This is the first step which sets the state and renders a failure note on messages.
Since we optimistically render we need a way to notify the user if a message fails to send.

Error state for message send failures

---

src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/autocomplete-members/styles.scss

Following conversation panel screens (start conversation via '+' icon and start group conversation)
- The Avatar is no longer in the tabbing order - given tabIndex -1.
- The behaviour from TAB-ing to start a conversation from a user search result is for the entire user preview itself is now highlighted, without any green ring around the avatar.
- Able to create a conversation using the Enter Key.
- accessibility and as per design
- Press the '+' icon in the conversation list panel. Enter a name to render search results, key down tab to navigate through the results.
Before:
https://github.com/zer0-os/zOS/assets/39112648/3b0fe063-5a23-4b4c-a1ed-305cefaea64c
After: …

feat: add tab accessibility to autocomplete member search

---

src/Main.tsx
src/components/dev-panel/container.tsx
src/components/dev-panel/index.tsx
src/components/dev-panel/styles.scss
src/lib/feature-flags.ts

Adds a dev panel to test the various message states. As you can see, very little effort was spent styling :)
It's frequently difficult to get into the various states a message can be in when it comes to the sending flow. This adds a hidden dev panel that allows a user to toggle the various states so we can quickly see how it impacts the view.
Enable via `window.FEATURE_FLAGS.enableDevPanel = true` and refresh
https://github.com/zer0-os/zOS/assets/43770/bf313fbf-96da-40d6-a514-dce8b2e2f392

Add a dev panel for message status testing

---

src/lib/chat/index.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

- clears the state when a user has left a conversation meaning a user will no longer be able to interact with a group that they had left or been removed from.
- Previously in Web, users can continue to interact with groups they have left. There was no way to leave groups in Web, but if I leave a group in iOS, a user can continue to interact with that group from the web client.
- using mobile and web, log in as the same user on each device. Create a group on web. Leave group on mobile then check that web reflects this change.
Result of leave group -
https://github.com/zer0-os/zOS/assets/39112648/9f686e41-4f62-40e9-949f-4d726cf70ed9

feat: remove ability for users that have left a group to continue interacting with that group

---

src/components/messenger/list/conversation-item.test.tsx
src/components/messenger/list/conversation-item.tsx

Renders the last message preview with a failed message if the most recent send failed

Render failed message in conversation list

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts

Handle scenario when sending a message with multiple files and the text (root) message send fails
https://github.com/zer0-os/zOS/assets/43770/7602bb8a-6b57-40d2-8a7e-162fa7a13235

Handle text message failure with multiple files

---

src/components/message/index.test.tsx
src/components/message/index.tsx

When a message is in progress we no longer render the message menu
To prevent people from trying to perform operations on an object that doesn't truly exist yet.
Use the dev panel to set messages into the 'In progress' state and verify there's no menu available.

Disable message menu when message is in progress

---

src/store/messages/saga.deleteMessage.test.ts
src/store/messages/saga.ts

Allows deleting of optimistic messages (i.e., failed to send messages)
To allow a user to clear their screen in the case of a message failure.

Deleting optimistic message

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx

Updates the message menu to only allow deletion of failed messages
Since there's no real message you can't reply or edit.

Only allow deletion of failed messages

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss

Forces the menu trigger for failed messages to always be visible
To draw the user's attention to the options available to them.
https://github.com/zer0-os/zOS/assets/43770/342a1896-5145-43c3-9650-e21813b49eaf

Force the menu trigger to be visible for failed messages

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss

- updates the message footer to align with figma design.
- ensures failure message position does not change.
- edited flag in line with time.
- as per figma design.
- open messenger and edit a message to see changes as per screenshot below.
Before: 
After:
*failure position check*
*messages in quick succession*

feat: update message footer

---

src/components/message-input/container.tsx
src/components/message-input/index.tsx
src/components/message-input/styles.scss
src/components/message/index.tsx
src/components/message/styles.scss
src/platform-apps/channels/styles.scss

- first iteration of edit message display changes
- open messenger and navigate to the edit message flow.
*no footer spacing when time is not displayed*
*footer with time when displayed*
*long message and icon position*

feat: edit message display iteration one

---

src/components/message-input/index.tsx
src/components/message/edit-message-actions/edit-message-actions.tsx
src/components/message/edit-message-actions/styles.scss
src/components/message/index.tsx
src/components/message/styles.scss

- second iteration of edit message display changes.
- includes border change on editing message bubble.
- includes re-order of edit action icons.
- includes hiding time updated if editing.
- includes hiding error message (the whole footer) when editing.
- as per figma designs (recently changed)
- open messenger and navigate to the edit message flow.
*updated design*

feat: edit message display iteration two 

---

src/components/message-input/index.tsx

- hides emoji icon / picker when editing a message.
- hiding the emoji icon / picker when editing due to broken layout of the emoji picker container and parent containers. The dev time at the moment is not worth the value of making these changes that will potentially cause a number of bugs. As discussed with team, we shall remove this for now when editing.
- follow the edit flow and check that the emoji picker icon is not present when editing.
https://github.com/zer0-os/zOS/assets/39112648/42432efd-1d9d-4837-b2d1-2b629445280a

feat: hide emoji icon and emoji picker if editing message

---

src/components/message/edit-message-actions/edit-message-actions.test.tsx
src/components/message/edit-message-actions/edit-message-actions.tsx
src/components/message/edit-message-actions/styles.scss
src/components/message/index.tsx

- handles save edit disabled state.
- adds test coverage for edit message actions sub-component.
- as per design/product discussion.
- when editing a message, delete the message content and check the save (check icon) is disabled and the tooltip is not displayed.
*Disabled State*
https://github.com/zer0-os/zOS/assets/39112648/4da03c19-ecb0-48e4-8acd-9fc999695c94

feat: handle save edit disabled state and add test coverage

---

src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/conversation-list-panel.tsx
src/components/messenger/list/styles.scss

- removes antiphonal text as shown in the demo below.
- requested from product/n3o.
- enter characters into one of the search inputs in the sidekick until no users are returned. Check that there is nothing rendered when this happens.
Before:
https://github.com/zer0-os/zOS/assets/39112648/891d901d-e2ab-4bc9-a3ea-d59fa468f806
After: 
https://github.com/zer0-os/zOS/assets/39112648/04b16d7f-b68d-4e9d-b6c9-6722be8f8f54

feat: remove antiphonal text from searches returning no results

---

src/components/rewards-popup/styles.scss

- fixes gap between sidebar and rewards modal & arrow placement.
- fixes position of rewards pop up arrow.
- open messenger in full screen and click the rewards button to open the rewards pop up modal. Check positions as per design: https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?node-id=7019%3A313890&mode=dev
Before:
After:

fix: gap between sidebar and rewards modal & arrow placement

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss

Tries to get the message bubble closer to the designs. In particular, this PR is related to some basic structural changes and rendering media to the borders of the message bubble.
Design enhancements
Send various messages of all kinds of types both in succession and not.

Style media messages full width

---

src/components/inverted-scroll/styles.scss

- populates messages (where the container uses `InvertedScroll` from the bottom up.
- as per figma designs / product request.
- open messenger fullscreen or collapsed direct message and check that messages are populated from the bottom up - as per screenshots below.
Before: 
After:

feat: populate messages from the bottom up

---

src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-bar/styles.scss

- Update the space between the word “Rewards” and the Rewards icon to be 4 px
- Update the hover text to no longer be bold on hover
- Update the text to no longer be bold when active
- Update the hover state to match the specification in the above Figma file
- Orange badge should hide as soon as rewards modal is opened
- Update rewards bar buttons as per design
- Updates rewards button icon status design
- Adds test coverage
- as per design (https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?type=design&node-id=6797-369406&mode=dev)
- open full messenger and check rewards bar/rewards button. Compare with design linked above.
*Updated design* …

fix: rewards icon button in the sidebar

---

src/platform-apps/channels/container.tsx

- moves `ZUIProvider` higher up to resolve the app-context-panel slide in/slide out issue.
- due to a bug that was introduced when `ZUIProvider` was added recently.
- open the app (not in fullscreen) and click the channels panel icon button to open/close. Demo below.
Before:
https://github.com/zer0-os/zOS/assets/39112648/212e4840-bb48-420c-9cbd-a1bfae2922dc
After:
https://github.com/zer0-os/zOS/assets/39112648/75829e79-dc47-48f6-b7e3-d4864ec9e955

fix: resolve app context panel transition/animation issue

---

src/authentication/_styles.scss
src/authentication/validate-invite/index.test.tsx
src/authentication/validate-invite/index.tsx

- improves/fixes the handling of errors on the invite screen.
- alert remains visible when there has been an error.
- adds the error state of the input when rendering alert.
- disables button when invite code has not been edited as per design.
- to improve the UI/UX of the invite screen.
- navigate to /get-access. enter invalid code. then enter valid code.
OUTCOME:
https://github.com/zer0-os/zOS/assets/39112648/07620972-5ca8-47a6-a4c2-4917fa73c8ac

fix: invite screen error handling

---

src/store/channels-list/index.ts
src/store/channels-list/saga.ts
src/store/create-conversation/saga.ts

Removes an extra event listener that already existed
We had 2 listeners to the same event under the same conditions which was causing us to send 2 api calls for the same thing.
Create new conversations in the various ways (particularly one on ones)

Remove redundant event listener for creating conversations

---

src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx

When using the quick search in the conversation list, clear the filter state when a conversation is selected.
It's very confusing for the search results to remain there as if nothing has happened.

Clear the search state when a conversation is selected

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx

Translates typed colon based emojis to unicode (eg, :tada:)
This is so other front ends can render the emoji properly without having to add parsing. We don't allow custom emojis so we should just let the standard unicode characters behave properly.
Type a message with `:tada:` in zOS and then view the message on mobile. It should appear as a proper emoji.

Translate typed emojis to unicode

---

src/authentication/_styles.scss
src/authentication/create-account-details/index.tsx
src/authentication/create-account-details/styles.scss
src/authentication/create-email-account/index.tsx
src/authentication/create-email-account/styles.scss
src/authentication/create-wallet-account/index.tsx
src/authentication/create-wallet-account/styles.scss
src/authentication/email-login/index.tsx
src/authentication/email-login/styles.scss
src/authentication/footer/footer.tsx
src/authentication/footer/styles.scss
src/authentication/select-method/index.tsx
src/authentication/select-method/styles.scss
src/authentication/validate-invite/styles.scss
src/invite.scss
src/invite.tsx

- fixes the layout to a reasonable standard while developing in sign up / log in flows.
- ensure the pages are still usable and easy to develop on top of.
- open the application and run through the sign up / log in flows.

fix: sign up and log in layout

---

src/authentication/create-account-method/container.test.tsx
src/authentication/create-account-method/container.tsx
src/authentication/create-account-method/index.test.tsx
src/authentication/create-account-method/index.tsx
src/authentication/footer/styles.scss
src/authentication/validate-invite/styles.scss
src/invite.tsx

- refactors the create account method container to follow the container / presentation-component structure that we are using in the authentication folder.
- adds test coverage for the container and component.
- refactors other areas of the code for a tidy up.
- to follow existing practices/conventions.
- to improve the code quality.
- to add test coverage to the container and component.
- to ensure registration state can be accessed for the ToggleGroup component (i.e. is loading - display elements / hide elements).
- ensure all tests are passing and functionality for the sign-up flow is working as expected by visiting the `/get-access` page.

refactor: create account method container/presentation-component structure

---

src/authentication/create-wallet-account/styles.scss
src/components/wallet-select/index.test.tsx
src/components/wallet-select/index.tsx
src/components/wallet-select/styles.scss

- updates the wallet select component for the creating wallet stage.
- navigate to `/get-access` page and select a wallet to connect with.
BEFORE:
https://github.com/zer0-os/zOS/assets/39112648/fd35629d-9932-4dd2-abb6-c5a4f332261b
AFTER:
https://github.com/zer0-os/zOS/assets/39112648/02daed18-0ca7-4bc3-a0fe-705cd398a7fe

feat: update wallet select for creating wallet account

---

src/authentication/create-wallet-account/styles.scss
src/authentication/web3-login/styles.scss
src/components/wallet-manager/index.tsx
src/components/wallet-select/index.test.tsx
src/components/wallet-select/index.tsx
src/components/wallet-select/modal.tsx
src/components/wallet-select/styles.scss

- some minor updates to the update wallet select component
- as per figma design
- run through the sign-up/log-in flow.
BEFORE:
AFTER
The Wallet Select Modal when in app (not messenger) will remain the same due to adding the `walletSelectTitle` prop:

feat: update wallet select for sign-up / log-in flow 

---

src/authentication/create-account-method/index.tsx
src/authentication/create-account-method/styles.scss
src/authentication/create-wallet-account/container.test.tsx
src/authentication/create-wallet-account/container.tsx
src/authentication/create-wallet-account/index.tsx
src/authentication/create-wallet-account/styles.scss

- adjusts the position of the create account method container when connecting wallet via the create wallet account method (as shown in the demo video below) - this position should only change for create wallet account method flow, not the create email account, hence the condition added.
- updates the style and content of the error states on the create wallet account method as per figma designs.
- navigate to `/get-access` page and run through the create wallet account flow. Check against the [figma](https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?type=design&node-id=10746-374167&mode=dev) designs
ERROR STATE UPDATE: 
POSITION UPDATE WHEN …

feat: create wallet account error state and connecting state updates 

---

src/components/image-upload/index.tsx

- updates image upload text content to be optional. 
- as per figma designs. The reason for this is in the create account 'name and avatar' screen designs, there is no text content (placeholder text) in the image upload component, but there is for other use cases of the image upload component.
- navigate to one of the image upload components in the app and add the attribute `uploadText` to view text content.
With `uploadText`:
Without `uploadText`:

feat: update image upload text content to be optional

---

.eslintrc.json
src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message-input/container.tsx
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/styles.scss

This shows a warning message to the user if they try to send a messaage in an optimistically rendered conversation.
When we optimistically render we have to account for users trying to do things before data is real.

Disable sending messages while conversation is being created

---

src/invite.scss
src/pages/login/login.scss

- updates zero logo
- as per figma design
BEFORE:
AFTER:

feat: update zero logo

---

src/authentication/email-login/styles.scss

- minor fixes as shown below.
- to align with figma designs.
- visit `/login` page and trigger alert states.
BEFORE:
AFTER:

fix: minor log in with email alert ui fixes

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Ensure we don't remove optimistic conversations from the list when the automatic poll happens
To make sure the UI doesn't rip an "in progress" conversation out of the UI for the user
Force a conversation creation to take a long time (longer than 1 minute). Verify that when the background poll happens the conversation does not disappear.

Don't replace optimistic messages when conversation poll happens

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/store/channels-list/saga.ts
src/store/channels/index.ts

Uses an `optmisticId` as the default rendering key
To prevent replacing of the message input when the real conversation arrives.
Create a new conversation and start typing a message. Verify that when the real result is complete the new message is not cleared.

Ensure the rendering of the conversation message input remains when optimistic conversation is replaced

---

src/store/channels-list/saga.ts

Fixes the data type of the optimistic conversation id fields
They were the wrong type which was causing the automatic input focus to not work
Create a new conversation and verify the message input is immediately focused.

Fix the type of optimistic fields

---

src/components/dev-panel/conversations/index.tsx

Adds a quick null check in the dev-panel in case a conversation has no other users.

Add null check in dev-panel

---

src/components/invite-dialog/container.test.tsx
src/components/invite-dialog/container.tsx
src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss
src/store/create-invitation/index.ts
src/store/create-invitation/saga.test.ts
src/store/create-invitation/saga.ts

- checks if data is loading to render elements at the same time. Prior to this the elements were rendering at different times making the elements fade-in at different times.
- fades in the elements as per figma.
- this also reverts the colour of the invites left logic
- as per figma design. This is to soften the rendering of the the elements
- once logged in click the invite button to bring up the invite module.
BEFORE:
https://github.com/zer0-os/zOS/assets/39112648/52a78d85-8c64-4efe-afa2-e3039ad7ae15
AFTER:
https://github.com/zer0-os/zOS/assets/39112648/8a7cad06-fefc-488f-85ae-f56d2b5a62fa

feat: add fade-in animation to invite code module

---

src/components/messenger/list/conversation-list-panel.test.tsx
src/components/messenger/list/conversation-list-panel.tsx

Now after searching:
(returns both direct + group match)
(direct matches are prioritized first, and then group conversation matches by otherMember names)

Fix: search results no longer returning all group conversations containing members matching search input

---

src/components/messenger/list/styles.scss

Spacing between search input and '+' icon should be 8 px

---

src/components/messenger/list/group-details-panel.test.tsx
src/components/messenger/list/group-details-panel.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/create-conversation/saga.ts

Closes the group details panel immediately when creating a conversation
We previously had a loading state on the button while the conversation is created but since we now have optimistic rendering we can close this immediately.

Close the group panel right away when creating a group

---

src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts

Adds tests around the existing behaviour for `toLocalChannel`

Add tests around toLocalChannel

---

src/components/messenger/list/conversation-item/index.test.tsx
src/components/messenger/list/conversation-item/index.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/lib/chat/chat-message.test.ts
src/lib/chat/chat-message.ts

Pulls the calculation of the message preview date for the conversation list up a couple of levels
To allow greater control of which date to use

Elevate calculation of converstion preview date

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

Uses the message list as the first option when rendering the message preview in the conversation list.
The lastMessage property on a conversation is really meant to be a shortcut for rendering previews without fetching a conversation's messages. However, in cases where we actually have the message data, using the most recent message in the list makes more sense and saves a lot of juggling of trying to manage the lastMessage property.
https://github.com/zer0-os/zOS/assets/43770/75f73777-f1f1-4136-b021-9bd30cec2230
https://github.com/zer0-os/zOS/assets/43770/d2af8cba-d0b5-4056-8c36-83969d693f10

Use message list for preview rendering in conversation list

---

src/components/messenger/list/create-conversation-panel/index.tsx
src/components/messenger/list/panel-header/index.tsx

Wraps some callbacks connected to click events to prevent serialization of the event to redux
Turns out these warnings actually cost quite a bit of time. I started noticing it when navigating the conversation panels as shown in the videos.
https://github.com/zer0-os/zOS/assets/43770/a95a90a1-5e1b-42ba-9aa1-ff2da0335a9f
https://github.com/zer0-os/zOS/assets/43770/3d50e631-d0b3-4b9e-a88b-f81c2064441d

Wrap callbacks to hide event information

---

package-lock.json
package.json

- bumps zUI version from (`0.25.3`) to (`0.26.1`). 
- this includes fixes to the zUI IconButton component
- to pull in the latest changes from zUI, with the aim of improving the use of IconButton component in zOS and deprecate other versions/duplicates of IconButton.
- check node modules for correct zUI version.
- risk - unlikely, but some icons could be distorted due to creating a pr to bump version and pull in zUI changes prior to adjusting existing uses.

chore: bump zui (`0.25.3`) -> (`0.26.1`)

---

src/components/content-highlighter/index.tsx
src/components/message/styles.scss

- fixes a current issue where elements displayed in the message block body are forced onto new lines when links are included in the message. 
- small change that inherits the display, resulting in a correct lay out of elements in the message block body.
- bug found in production. messages are not being displayed as expected. See screenshots below.
- open messenger and compose messages with a number of elements including highlight and tagging, and urls etc.
BEFORE:
- channels
- collapsed chat
- full screen
AFTER:
- channels
- collapsed chat
- full screen

fix: elements displayed in block body

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts
src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.send.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Removes the management of the `lastMessage` and `lastMessageCreatedAt` properties of a channel
In #926 we removed the reliance on the shortcut property `lastMessage`. That means we no longer need to juggle that field every time messages arrive/change. It is only used on first load of conversatiosn to render the preview if we haven't loaded messages yet.
Use the Messenger in various ways and verify that the preview and sorting in the conversation list maintains correctness.

Remove management of lastMessage on channels

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx

Removes some code that's doing duplicate work.
We're already managing the active channel id in the top level component that reads the channel id from the url.

Remove duplicate setting of the active channel id

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts
src/store/channels/index.ts
src/store/channels/saga.ts
src/store/chat/selectors.ts
src/store/messages/index.ts
src/store/messages/saga.fetch.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

Simplifies the logic for polling for new messages in public ZOS mode by just always running a poll. If there's no user and we have an active channel then they must be viewing it in public mode.
Simplifies the code as we don't have to react to all the various state changes
When in public ZOS mode verify that new messages that are sent from someone else show up within the poll interval

Simplify the channel message polling when in public ZOS mode

---

package-lock.json
package.json

- bumps zui version number
-  to pull in latest version of zui that contain toast notification updates
- import ToastNotification and ensure the new attribute `viewportClassName` is available to use.

chore: bump zui version (`0.26.2`) -> (`0.26.3`)

---

package-lock.json
package.json

- bumping zUI version 
- pulls in latest version of zUI which contains some ToastNotification updates.
- search toast notification > check that attribute `duration` is available.

chore: bump zui version (`0.26.3`) -> (`0.26.4`)

---

src/components/content-highlighter/index.tsx
src/components/message/index.tsx

This removes a couple of references to mentioned users' profile id.
It seems like at one point in time there may have been a profileId associated with a mentioned user but based on the api at the moment that is never set.

Remove unused profileId for mentions

---

src/components/message/index.tsx
src/store/messages/index.ts

Removes a property (`mentionedUserIds`) from the Edit Message payload that we're not using and was always send as undefined. It is passed as an independent parameter already.

Remove unused property from edit message data

---

src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-popup/styles.scss

- repositions rewards pop up and arrow.
- adds condition to show rewards pop up when conversations have loaded (on first time login).
- updates toast secondary message text.
- adds 20s duration to invite toast notification.
- updates conditions for rewards button styles.
- repositions invite toast notification.
- as per onboarding flow designs.
- create a new account and run through the onboarding flow. compare with designs - [figma](https://www.figma.com/file/aETpyuG2AKjNcQtCjldcX0/ZERO-Messenger-%2F-Web?node-id=9680%3A494047&mode=dev)
https://github.com/zer0-os/zOS/assets/39112648/125a54f2-cebf-4279-ad72-24152b520830

feat: improve onboarding sequence and timings

---

src/components/content-highlighter/index.tsx
src/components/content-highlighter/styles.scss
src/components/message/parent-message/styles.scss

Truncates long messages that were replied to.

Truncate replied to messages in conversation thread

---

src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx

- when a message is sent the chat view container will scroll to the bottom to the most recently sent message.
- so when replying to a message, the chat view container will scroll to the bottom to the most recently sent message.
- open a chat, scroll to a higher message, reply to that message and press send.
https://github.com/zer0-os/zOS/assets/39112648/fe44d015-ca14-4089-8b39-4dafe9bc1b07

feat: implement scroll to bottom on message send

---

src/components/messenger/autocomplete-members/styles.scss

Implements the css fixes when displaying new users in search results.
Before:
After:

Implement height and spacing fixes for search result list during new conversation creation flow

---

src/authentication/footer/footer.tsx
src/authentication/request-password-reset/index.tsx
src/index.tsx
src/pages/login/login-component.tsx
src/reset-password.scss
src/reset-password.tsx
src/store/login/index.ts
src/store/page-load/saga.test.ts
src/store/page-load/saga.ts
src/store/request-password-reset/saga.test.ts
src/store/request-password-reset/saga.ts

- adds `/reset-password` route/page.
- updates authentication footer to be used in request password reset ui
- redirects authenticated user away from `/reset-password`.
- updates tests
- resets request password reset when enter request password reset page
- to handle reset-password flow on its own route/page.
- run the app. go to login page. select email. select `reset` in footer. you will be directed to the `/reset-password` page.
`/reset-password`
https://github.com/zer0-os/zOS/assets/39112648/35e53ec2-b7f2-47cb-ad2c-199bb5b83e86

feat: add reset-password route

---

src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/message/styles.scss

- replaces div with background img with zUI Avatar component.
- should be using the re-usable Avatar component available.
- open a group chat and check the sender Avatars 

feat: update messages to use sender avatar

---

src/components/message-input/index.tsx
src/platform-apps/channels/messages-menu/index.test.tsx
src/platform-apps/channels/messages-menu/index.tsx

- focuses on the message input when reply prop exists
- so the user can starting typing immediately without an additional mouse event.
- select reply to a message from the message menu and check if the message input is focussed.
https://github.com/zer0-os/zOS/assets/39112648/22149e15-2b94-4c7d-af58-54cb706f1822

feat: set cursor if replying to a message

---

src/components/message/styles.scss

- removes `100%` width set on `block-audio`. By doing this the audio controls width will be set to its default of 300px (for chrome browser).
I decided to set the width to `300px` so its consistent across all browsers.
This also fixes the hidden audio messages sent in succession as shown in the recording below.
- users are unable to play the audio due to the width of the controls.
After removing the `width: 100%` and replacing with `300px`.
Blank audio messages:
https://github.com/zer0-os/zOS/assets/39112648/80a04239-bac3-4155-a132-05015bdf6abe
https://github.com/zer0-os/zOS/assets/39112648/1af12dc9-8861-4635-80db-defb119d80f6

fix: width of audio control interface

---

src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/autocomplete-members/index.tsx
src/components/messenger/list/start-group-panel/index.tsx

If you have selected a user to "start a group chat", then it won't be displayed in the search results.
Before (user is selected & also displayed in the search results):
After (selectedUser is NOT displayed in the results):

Remove users from search results after they've been added to a pending group chat

---

package.json
src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss
src/components/inverted-scroll/index.test.tsx
src/components/inverted-scroll/index.tsx
src/components/inverted-scroll/styles.scss

This removes a lot of the manual scroll position management that was happening in the InvertedScroll component and replaces it with mechanisms more built into the browsers.
Notes:
* There's still an edge case when infinite scrolling up. To be handled in another story.
* Pinning to the bottom may not quite work correctly in Safari as the overflow-anchor doesn't appear to be supported.
We've been having issues with the chat window randomly scrolling to the bottom of the history. Smooth out the user experience.
Exercise various scroll states and events in a conversation:
* When opening the converstation it shoudl be scrolled to the bottom
* When scrolled to the bottom the conversation should stay pinned there. New messages "push the conversation up".
* Scroll up a bit and then receive a new …

Fix scroll to bottom issues

---

src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss

Moves the infinite scroll waypoint down by 700px to start the message fetch earlier
Infinite scroll tuning

Begin new page fetch earlier

---

src/components/chat-view-container/chat-skeleton.test.tsx
src/components/chat-view-container/chat-skeleton.tsx
src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss

Renders a loading skeleton when scrolling up in a conversation causes a fetch for more messages.
To give the user information that more data is loading.
Open a conversation with a lot of messages. Scroll up to trigger a load of the next page. Verify the skeleton is shown while loading.

Render loading skeleton during infinite scroll load

---

src/components/chat-view-container/chat-view.tsx
src/components/chat-view-container/styles.scss
src/components/chat-view-container/utils.test.ts
src/components/chat-view-container/utils.ts
src/platform-apps/channels/styles.scss

Removes the message group wrapper node in the conversation view. This was previously used to style the messages based on their position in the group. Replaced it with specific classes on the nodes.
Having larger wrapping nodes gets in the way of the browser maintaining scroll position when content changes.
Scroll up on a long conversation and note that most situations load new data without the view "jumping"

Remove message group wrapper node

---

src/components/chat-view-container/chat-view.tsx

Hide the waypoint when we fetch more messages for a conversation.
When fetching new messages a user may scroll around which triggers more leave/enter events on the waypoint but we don't really want to trigger more fetches.

Remove Waypoint while fetching messages

---

src/components/chat-view-container/chat-view.tsx
src/platform-apps/channels/styles.scss

Removes the `messages` wrapper node in the conversation view. It's unclear why this existed in the first place but it seems to not be required.
Having larger wrapping nodes gets in the way of the browser maintaining scroll position when content changes.
Scroll up on a long conversation and note that most situations load new data without the view "jumping"

Remove messages wrapper node

---

src/components/chat-view-container/chat-view.tsx
src/store/channels/index.ts
src/store/messages/saga.ts

Adds a separate progress state for loading more messages in a conversation/channel.
Having them connected causes the fetch more skeleton to render at inappropriate times.
Open a conversation and scroll up to trigger loading more messages. Verify the small skeleton renders appropriately.

Add a status when fetching more messages for a conversation

---

.prettierrc.json
src/components/address-bar/container.tsx

Update the prettier config to allow single line arrays up to 3 elements.
Forcing arrays to multiple lines makes a lot of code very hard to scan due to the extended vertical height.
Before:
After:

Change array wrap to more than 3 elements in prettier config

---

src/store/messages/saga.fetch.test.ts
src/test/saga.ts

This creates a wrapper around `expectSaga` to allow calling `provide` multiple times.
This allows use to set up default responses in tests and then override them when required which helps each test be more focused on the setup that actually impacts the results.

Allow providing default responses in saga tests

---

src/store/messages/saga.fetch.test.ts
src/store/messages/saga.ts

This ensures we maintain the message cache that we already have when fetching messages upon opening a conversation.
Previously if you scrolled up and loaded a few pages of a conversation then switched away, when you came back we would fetch the first page again but then wipe out the later pages that hade been loaded. This ensures we don't wipe out all that data we've already gathered.

Maintain existing cached messages when loading the first page of a conversation

---

src/components/chat-view-container/styles.scss
src/components/message/parent-message/styles.scss

Fixes rendering of replies to shorter messages. Previous fix for long messages didn't take this into account.
Before:
After:

Fix reply rendering

---

src/components/chat-view-container/chat-view-container.tsx

Sorts messages by created time prior to rendering rather than relying on the data store to be exactly correct all the time.
To ensure we render in the correct order

Sort messages by created timestamp

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss
src/components/rewards-bar/index.test.tsx
src/components/rewards-bar/index.tsx
src/components/rewards-bar/styles.scss
src/lib/feature-flags.ts

- refactors the rewards feature
- extracts settings menu from rewards
- tidies up the styles for rewards and settings menu
NOTE : Feature flag to be added in a separate PR.
- In order to easily feature flag rewards.

refactor: extract settings menu and refactor rewards bar

---

src/components/message/index.test.tsx
src/components/message/index.tsx

Only want to render the link preview if it's a purely text message and not a reply.

Do not render link preview if message has some other components

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss

- removes `includesRewardsAvatar` prop.
- replaces conditions using `includesRewardsAvatar` prop with `isMessengerFullScreen`.
- `includesRewardsAvatar` is used in the same way `isMessengerFullScreen`. Made sense to me to remove and replace.
```
includeRewardsAvatar: layout?.value?.isMessengerFullScreen,
isMessengerFullScreen: layout?.value?.isMessengerFullScreen,
```

refactor: remove includesRewardsAvatar (duplicate prop)

---

src/store/messages/saga.send.test.ts
src/store/messages/saga.ts
src/store/messages/utils.ts

Sets a thin link preview on the optimistic message so it's rendered immediately
More feedback for the user
Send a message with a url. You'll see the link preview briefly while the true preview is being fetched.

Set truly optimistic link preview

---

src/components/image-upload/index.tsx
src/components/image-upload/styles.scss
src/platform-apps/channels/attachment-cards/attachment-card.tsx

- fixes attachment card close icon button size
- fixes image upload icon button size / over riding styles.
- since the latest zUI version bump, some icon buttons required tweaking due to the changes
Examples of fixes from bumping latest zUI version. The attachment card and the image upload required some manual tweaks to their sizes.
BEFORE
AFTER

fix: icon button ui breaks with latest zui version bump 

---

src/components/message/edit-message-actions/edit-message-actions.tsx
src/components/message/edit-message-actions/styles.scss

- fixes edit action icon sizes 
- broken ui since latest zUI version bump
Figma
BEFORE
AFTER

fix: edit action icon sizes and padding

---

src/components/message-input/index.tsx
src/components/message-input/menu/menu.tsx
src/components/message-input/menu/styles.scss
src/components/message-input/styles.scss

- replaces local icon button component with zUI icon button component for message input

refactor: (message input) replace local icon button component 

---

src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss

- replaces local icon button component with zUI icon button component for messenger chat
----
Lol ignore the title for one of my bookmarks there
FIGMA (providing screenshot because of size change)

refactor: (messagenger/chat) replace local icon button component 

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.tsx

- replaces local icon button component with zUI icon button component for conversation list new icon
How it looks after LOCAL change (not sure why screenshot is blurry but it looks fine in browser)

refactor: (conversation list/new icon) replace local icon button component

---

src/components/rewards-faq-modal/index.test.tsx
src/components/rewards-faq-modal/index.tsx
src/components/rewards-faq-modal/styles.scss

- replaces local icon button component with zUI icon button component for rewards faq modal
FIGMA (providing screenshot because of size change)

refactor: (rewards faq modal close icon) replace local icon button component

---

src/components/rewards-popup/index.tsx
src/components/rewards-popup/styles.scss

- replaces local icon button component with zUI icon button component for rewards pop up close icon
FIGMA (providing screenshot because of size change)

refactor: (rewards popup close icon) replace local icon button component

---

src/components/tooltip-popup/styles.scss
src/components/tooltip-popup/tooltip-popup.tsx

- replaces local icon button component with zUI icon button component for tooltip pop up close icon

refactor: (tooltip popup) replace local icon button component

---

src/platform-apps/channels/audio-cards/audio-card.tsx

- replaces local icon button component with zUI icon button component for audio card delete icon
How it looks in PROD (this is from design as audio is currently broken - refer to image card delete icon for the same icon)

refactor: (audio card delete icon) replace local icon button component

---

src/platform-apps/channels/messages-menu/index.tsx
src/platform-apps/channels/messages-menu/styles.scss

- replaces local icon button component with zUI icon button component for delete message modal close icon

refactor: (delete message modal) replace local icon button component

---

package-lock.json
package.json

- chore: bump version (`0.62.0`) -> (`0.63.0`)

chore: bump version (`0.62.0`) -> (`0.63.0`)

---

src/store/messages/saga.send.test.ts

Fixes a test that was missed when allowing message sending via Matrix

Fix a test

---

.env.example
src/config.ts
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/authentication/saga.ts
src/store/authentication/types.ts
src/store/chat/saga.ts
src/store/edit-profile/saga.ts

Adds an env var for the default home server and saves the user credentials in local storage
* To allow defining the default home server per environment (currently just development or local)
* To allow testers to quickly set up a user to test with

Configure zOS to a home server and save user creds in local storage

---

src/lib/chat/chat-message.ts

Removes the updatedAt timestamp from the original matrix message mapping. We use that to determine if we've edited the message and since we don't do that yet we might as well have it cleared

Remove updatedAt timestamp from Matrix message mapping

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/channels-list/api.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

- Updates the Matrix Client to differentiate between 1-on-1 and group conversations.
- Updates the Channels List saga to call client.
- Updates the Sendbird Client.
- Adds test coverage / fixes failing tests.
- to differentiate between 1-on-1 and group conversations.
- to ensure Sendbird Client also still fetches conversations.
- run Matrix/Element and check one on one conversations appear in the conversation list, and channels appear in the channel list.
Screenshot of 1-on-1 & channels lists

feat: (matrix) differentiate between 1-on-1 and group conversations

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

- handles when a user has no conversations or channels yet.
- adds test coverage.
- Fixes the following console error: TypeError: Cannot convert undefined or null to object 
- create a new account on Element and go through the steps to add this user in zOS with the matrix id and token. Open the console and check if the error is thrown.
Before
After

fix: handle when a user has no conversations or channels

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/lib/chat/types.ts
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts

Since the clients require different ids we need to pass the relevant bits of the user record into the chat client when creating a conversation.

Pass the full user record when creating conversations

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/utils.ts
src/lib/chat/types.ts
src/store/channels-list/saga.ts
src/store/users/saga.ts

Adds the Matrix specific functionality to create a Conversation (in Matrix this is a room that "is_direct" and is in the user's account list of `m.direct` events)
Notes:
* This functionality works for group Conversations too but the process of creating a group conversation has other checks that need to be switched to Matrix first.
* Currently the receiving user still has to manually accept the invitation in Element. Future work will do this automatically on behalf of the user.
In zOS search for a user that has a matrix id set and start a conversation with them. You will see the conversation created and can send a message. Verify the other user received the invite by going to Element.

Create conversation via Matrix

---

src/store/channels-list/saga.test.ts

- enhancements to channels-list saga tests.
- as per previous feedback on channels-list saga work. The aim tidy up the test suite because the tests were cluttered with the default response of the mock client.
- run the command: `npm run test src/store/channels-list/saga.test.ts` and ensure all tests are passing.

refactor: improved readability and maintainability enhancements to channels-list saga tests

---

src/components/messenger/chat/index.tsx

Missed a spot where we're assuming an "other member" exists but for Matrix convos we don't have that mapped yet.

Fix opening a one on one from matrix

---

src/lib/chat/matrix-client.ts

Auto accepts invites when we receive an invite event for the current user
So the user sees the conversation/channel immediately upon creation.
Create a conversation with someone. In that other user's browser, verify that the conversation appears and you can see/send messages

Auto accept invites to rooms

---

src/store/channels-list/saga.ts

Removes the conversation/channel polling in Matrix mode
We don't want to rely on constantly polling for all the data. Disabling now allows us to discover areas we've missed

Do not poll for Conversations and Channels when in Matrix mode

---

src/lib/chat/chat-message.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

- Implements "reply to text messages" using the matrix API.
**NOTE**: this creates a reply to a message, and NOT a thread. 
Also, we're having `undefined` as the user's `firstName` & `lastName` (aka the `message sender`). This is because the matrix message does NOT return the sender metadata. It just returns it's user_id. Will discuss more about this.

Zos 708 matrix reply to text only message

---

src/lib/chat/matrix-client.ts

Adds debugging output for the various enum'ed events that the Matrix SDK provides
To make it easier to find which events we need to listen to during development

Add extra debugging for Matrix events

---

src/lib/chat/matrix-client.ts

Refactor channel/conversation mapping to extract a common function
To make the differences between Conversations and Channels more visible

Generalize Channel mapping in Matrix client

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

- sets the user status using the presence data provided from getUser.
- to be able to see if a user is online or offline.
- open the messenger and check the user status. You can console.log the user data and check is user.presence is equal to online.

feat: set status badge using matrix presence

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels/selectors.ts
src/store/chat/bus.ts
src/store/test/store.ts
src/store/users/saga.ts
src/store/users/selectors.ts

Adds event listeners for when users are added to / removed from rooms and fixes up the initial determination of room members.
Handle membership based on events so that we can replay the events and get into the correct state as well as handle the real time updates.

Handle membership events to ensure correct room members

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

For initial render of Rooms we return the explicitly set room name if exists.
To perform the initial render correctly

Return the explicit room name when rendering conversations

---

src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/utils.test.ts
src/lib/chat/matrix/utils.ts
src/platform-apps/channels/util/api.ts

Implements user mentions using matrix
*NOTE*:
+ This implements a simple approach - we use channel.otherMembers as cache, and then filter the results based on the search string. 
**Follow ups**:
- map the `otherMembers` in the channelInfo to the zOS users.
- update the sendbird implementation for "conversations" to use otherMembers as cache as well.

[Matrix] Implement user mentions

---

src/components/messenger/list/index.tsx
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts

- enhances the mapMatrixMessage to include sender details
- to have defined sender details data in the message preview (conversation list item)
- open messenger > click on a user in the conversation list that has message history > when conversation renders to top of the list you should see the senders name or 'you'. If the senders name is visible and they sent the last message, this means the sender data is being fetched correctly.
BEFORE
AFTER
DEMO - SORT ORDER
https://github.com/zer0-os/zOS/assets/39112648/279f913e-f2c5-495d-ac71-7855c357e17a

feat: show last message in conversation list and preview details

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/channels-list/index.ts
src/store/channels-list/saga.ts

This removes the component triggered conversation list fetch.
When we load the app we are already loading the conversations in the background. There's no need to use the component to trigger it and it was just causing duplicate requests.
Open the app and verify that conversations load on render.

Don't fetch conversations when the list is rendered

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/channels-list/api.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts
src/store/test/store.ts

Adds the search for existing converations during the group conversation creation flow.
This allows group conversation to work!
Create a group conversation. It should create successfully. Then try to create a group conversation with a matching set of users to an existing group and verify that it opens the existing one.

Matrix: Create group conversation

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

Sets the Matrix room name if provided when creating a conversation

Set the conversation name if provided

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

Uploads the group conversation cover image

Upload group conversation image

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Fixes a bug where the receiving users of a new conversation were seeing the conversation in the list twice.
Because of the evented nature of the data changes the room is first noted as a Channel and then eventually gets found to be a Conversation. When we were refetching the whole conversation list this would cause the room id to be in the channel (room) list twice which caused the double rendering.

Remove existing channels from list When fetching full conversation list

---

src/lib/chat/matrix-client.ts
src/lib/chat/matrix/utils.test.ts
src/lib/chat/matrix/utils.ts

Fetches and maps ZERO users <-> matrix users, when we fetch all channels + conversations. This also fixes the user mention display (if the matrix account is linked with ZERO).
Follow Up
- check on realtime events (messages, join/leave a room etc)

Map ZERO users to matrix users

---

package-lock.json
package.json

chore: bump version (`0.63.0`) -> (`0.64.0`)

chore: bump version (`0.63.0`) -> (`0.64.0`)

---

src/lib/chat/matrix-client.ts

Only sends the name field when creating a conversation if it is set.
Matrix rejects fields with `null` based on some type checking (i.e., it is not a string) so just don't send it.
Ensure creating 1 on 1 conversations and group conversations without a name work.

CreateConversation: Only send the name field if it is not null

---

src/store/messages/saga.ts

Maps the message senders to ZERO users when we load messages for a channel/conversation. Messages are being rendered more properly now.
Also, the names on the conversation list are also of ZERO users:

Map message senders in matrix mode

---

src/lib/chat/matrix-client.ts

- removes timestamp set for `updatedAt` in `mapMatrixEventToMessage`.
- to remove the edited flag on unedited messages.
- send a message and ensure the edited flag does not appear on the message footer.
BEFORE
AFTER

fix: remove edited flag on unedited messages

---

src/lib/chat/matrix-client.ts

Gets the actual room created timestamp when fetching Matrix rooms.
We use createdAt as a fallback ordering in the Conversation list

Set the createdAt on rooms

---

src/store/messages/saga.ts
src/store/messages/utils.matrix.ts

Moves a matrix related functionality to `utils.matrix.ts`. Since we use `mapMessageSenders` only in the case if matrix is enabled.

Move `mapMessageSenders` from `messages/saga.ts` -> `messages/utils.matrix.ts`

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.ts

Fetches/maps the parentMessage data correctly while parsing all messages fetched after loading a channels/conversation. 
- We first try to fetch the parent message from the list of "already loaded messages"
- if message is not found (i.e it could be an older message), in that case we call the matrix API to fetch the message.
Before:
After:
**NOTE**: This does not currently work for when replying to messages in real-time.

Matrix: set `parentMessage` while mapping messages which are replies

---

src/lib/chat/index.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.ts

- Handles the parentMessage mapping, when sending a message in real time. In this case we should always have the "parentMessage" in our local redux state. 
- Also added a new function for mapping message.sender for a single new message, since we don't need to create a whole new map in this case.
https://github.com/zer0-os/zOS/assets/33264364/38fbe58f-a92f-4251-b97e-aad4be47b03e

Matrix: Handle real time replies, update mapping for `receiveNewMessage`

---

src/store/messages/saga.ts

Reverts [this](https://github.com/zer0-os/zOS/pull/1074/files#diff-e407e648c98001ae7df5920d97c03f7c4d30f5ca8ddc6ee3c553cd244aa331d3R87) change. This is causing the messages to not render the parent message.
Before:
After reverting:

Remove `''` while selecting messages in `rawMessagesSelector`

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

- removes unused `getUser`. 
- noticed we are not actually using this `getUser` method. Instead we use `this.matrix.getUser`, this is likely due to `getUser` being async.

refactor: remove unused get user method

---

src/store/messages/saga.fetch.test.ts
src/store/messages/saga.ts

Saves any new message fetched, OR if a an existing message has an updated property (eg. `parentMessage`) to the redux state.

Fix: Save new messages to state during `fetch`

---

src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/store/messages/utils.matrix.ts

We don't need to fetch the parent message data during `mapMatrixMessage`, since we already do that while loading new messages.

Refactor: remove `await` from `mapMatrixMessage`

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Adds saga tests for `mapToZeroUsers` function, which tests for mapping channels otherMembers + channel messages.

add tests for `mapToZeroUsers`

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/session-storage.test.ts
src/lib/chat/session-storage.ts

adds end to end encryption
because we want to be secure
create a new conversation
send some messages
inspect them and make sure they're encrypted
and that they are visible by the other participant(s)

E2e encryption

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/messages/api.ts
src/store/messages/saga.deleteMessage.test.ts
src/store/messages/saga.ts

This PR introduces an update to the chat functionality of our application to support the deletion of messages across two different chat clients: Matrix and Sendbird. It achieves the following:
- updated IChatClient interface by abstracting out the deletion method so that irrespective of the underlying chat client, the application can delete messages in a consistent manner.
- implemented the deleteMessageByRoomId method for the Matrix client, utilizing the redactEvent method from the Matrix JS SDK.
- direct implementation within the Sendbird client of the deleteMessage api. This approach ensures that the deletion logic is encapsulated within the chat client itself.
- updated messages/saga.ts function deleteMessage to fetch the active chat client and delegate the delete operation to it.
- …

feat: [matrix] delete a message 

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

- replaces how we're currently setting the users `isOnline` status by fetching the correct data using matrixs `getPresence` method.
- currently using `getUser`, to set the users online status, this accidentally works as the user will be defaulted to `offline`. Using `getPresence` asynchronously will return the users correct online status. Similar to how we are getting the last seen at data.
- open messenger and check users online status in the conversation list.

feat: fetch the users presence asynchronously (isOnline)

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

Adds a forced decryption on rooms when loading the channels and conversations to ensure messages are all decrypted before we process the data
There was a timing issue when loading channels the first time which caused messages to not get loaded.
Open the app with some Channels and verify that the messages load

Force decrypt the events before we start processing the rooms

---

src/store/messages/utils.matrix.ts

We're making the assumption that the parent message of a reply is already in state but that's not always the case. This provides null handling

Fix scenario when rendering a reply for a message that hasn't been loaded yet

---

src/components/edit-profile/container.test.tsx
src/components/edit-profile/container.tsx
src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/store/edit-profile/index.ts
src/store/edit-profile/saga.ts

Removes the temporary scaffolding for manually setting the Matrix credentials.
No longer needed as this is all hidden from the user now.
Open the Edit Profile modal and verify you can still edit things but the Matrix related fields are no longer visible.

Remove editing of Matrix credentials from Edit Profile modal

---

src/lib/chat/matrix/utils.test.ts
src/lib/chat/matrix/utils.ts

Fixes the issue with user mentions, where the display names do not pop up as soon as you start typing the full name. 
https://github.com/zer0-os/zOS/assets/33264364/d655c3be-9b1b-4989-a53d-2a682b650187

Fix user mentions issue 

---

src/components/message/index.tsx

Removes the icon to remove the link preview in messages in Matrix mode
Not yet implemented for Matrix

Disable URL preview removal button

---

src/lib/chat/matrix-client.ts

- Error handling in `getUserPresence` to silently handle errors without logging them to the console.
- To reduce console noise and ensure graceful degradation in scenarios where user presence data is unavailable or erroneous.
Before:

refactor: silence user presence retrieval errors

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/messages/saga.ts

When sending a new Matrix message we were not returning the proper Message data. This fixes the send and also changes the `replaceOptimisticMessage` to not overwrite the entire object and only the fields that were provided.
Depending on the order of events arriving this was causing the optimistic message to be overwritten with mostly empty data.
Send messages. Disable the new message event handler and send messages again. Verify that, without the event handler, sending still works as expected.

Only overwrite changed data when sending a new message

---

src/store/channels-list/saga.ts
src/store/messages/utils.matrix.ts
src/store/users/saga.ts
src/store/users/selectors.ts

Updates the `userByMatrixId` function to fetch the ZERO user using the API, if it doesn't exist in store locally. This is particularly helpful on the other end of the "create conversation" (i.e the user who the conversation was started with).

Update `userByMatrixId` to fetch user from API, if it doesn't exist in redux store

---

src/lib/chat/matrix-client.ts

- returns the created conversation data "after" creating the conversation
- this also sets the default conversation as the newly created one. 
https://github.com/zer0-os/zOS/assets/33264364/bddeff28-87ad-402c-835b-399b22baef0c

Set the active conversation as the newly created one

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/messages/saga.ts

- only returns changed data when editing or receiving an updated message
- maps to zero user when receiving an updated message.
- we only need to return the message data that has changed when editing a message, i.e. message and updatedAt.
- to prevent the UI inconsistency as shown in the before demo below.
- to correctly map the sender data to ensure the UI renders correctly.
BEFORE:
https://github.com/zer0-os/zOS/assets/39112648/de69cda6-bc81-4e60-9a4e-d957225964e5
AFTER:
https://github.com/zer0-os/zOS/assets/39112648/0f70ea29-bcca-4fae-9f6a-87ccac96f298

fix: only return changed data when editing a message

---

src/lib/chat/matrix-client.ts

The AccountData is only one way in which a room is identified as a conversations. The other is that the room has a DMInviter.

Filter conversation list properly when account data event is received

---

src/store/rewards/api.ts
src/store/rewards/saga.test.ts
src/store/rewards/saga.ts

- updates rewards route `/zero` to `/meow`
- updates response properties: `zero` -> `meow` & `zeroPreviousDay` -> `meowPreviousDay`
- token name change.

feat: update rewards route and response properties from zero to meow

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts

Batches the saga processing of new message events
When loading messages from Matrix we get them as individual "decrypted" events. This means we publish the "new message" event multiple times. If you load a room with 100s of messages this causes multiple invocations of the saga which was causing lots of rerenders.
Batching the processing allows for fewer rerenders. Simplified timing results when loading and rendering a conversation with around 130 messages:
Before - 9 to 10 seconds
After - 800ms
Ensure you can load messages in a conversation/channel and verify that receiving real time messges still works.

Batch the processing of new message received events

---

package-lock.json
package.json

- bumps matrix-js-sdk `^26.2.0` -> `^29.1.0`
- fixes notifications count property value

chore: bump matrix-js-sdk version

---

src/components/secure-backup/container.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/components/secure-backup/styles.scss
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/components/settings-menu/styles.scss
src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts
src/store/reducer.ts
src/store/saga.ts

Modal for managing the Matrix key backup
Note: Success messaging and error messaging to be handled in follow ups.
To allow users to login to a completely different session and decrypt old messages.

Adds modal for creating and restoring a key backup

---

.github/actions/common/action.yml
.github/workflows/create-tag.yml
.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/run-build.yml
.github/workflows/run-lint.yml
.github/workflows/run-tests.yml
.github/workflows/run-typecheck.yml

Updates some github action dependencies (checkout@v4 and setup-node@v3)
It may resolve some github action warnings about deprecations.

Update some github action dependency versions

---

src/components/edit-profile/container.test.tsx
src/components/edit-profile/container.tsx
src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss
src/components/secure-backup/index.test.tsx
src/lib/feature-flags.ts
src/store/edit-profile/api.ts
src/store/edit-profile/index.ts
src/store/edit-profile/saga.ts
src/test/utils.ts

Adds "secret" buttons to allow internal users to leave/join the global network. Pretty basic. It doesn't even know if you are or are not in the global network. Just presents both buttons no matter what and assumes you know what you're doing.
Intended to allow internal Zero employees to leave the global network so they don't show up in search results for random people

Allow internal users to join and leave the global network

---

package-lock.json
package.json
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/menu/menu.test.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/lib/chat/matrix/media.ts

Adds the ability to send an image message while matrix is enabled.
https://github.com/zer0-os/zOS/assets/33264364/9cf060c5-e83a-449c-80b6-0094109d34b8

Send an image message via Matrix

---

src/lib/chat/matrix-client.ts

Fixes the bug we're having while creating a new conversation with Matrix. It was related to not `awaiting` the promise returned by `mapMatrixMessage`

Fix create conversation in Matrix

---

src/lib/chat/matrix/chat-message.ts
src/store/messages/saga.ts

Fetches the link preview for each message after `fetch` 
Before:
After

[FIX] Render Link Previews in Message Bubbles

---

src/components/messenger/chat/index.tsx
src/store/authentication/saga.test.ts
src/store/layout/saga.ts

Forces all users regardless of network status into the full screen Messenger. I.E., there will no longer be Networks and Channels.
Starting from the raw Messenger for all users for now.

Force zOS into full screen Messenger mode

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

This removes the distinction between Channels and Rooms from Matrix. All rooms are now considered a Conversation.
We no longer have a distinction in zOS between channels and conversations so no need to filter any more.

All rooms are now considered Conversations

---

src/components/invite-dialog/container.test.tsx
src/components/invite-dialog/container.tsx
src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss

Removes the message about inviting a user to a network since we're no longer considering networks for the time being.

Remove the 'network' message on the InviteDialog

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/sendbird-client.ts
src/store/channels/api.ts
src/store/channels/saga.test.ts
src/store/channels/saga.ts

- This PR implements functionality to track and update unread message counts in the application using the Matrix client. It refactors the existing event handling logic to streamline the process of receiving new messages and updates the unread count accordingly. 
- To ensure conversations are highlighted when there are unread messages, and the unread count is updated and reflected in the UI. 
- Send messages to a zOS user you are logged in with and check the conversation list item is highlighted, and, the unread counter in the conversation list item increments for every unread message. Once the conversation has been `read` the conversation list item should no longer be highlighted and a send receipt will be sent to the server which should set the unread count back to 0, in turn the UI …

feat: implement unread message count functionality with matrix client

---

src/store/channels-list/saga.ts

- when a user creates a room and the channel is added, the members will be mapped to zero users & user presence will be updated.
- fixes the app crashing when adding channels due to a users presence data not being available, and ensures the correct user data (such as name) is rendered correctly.
- create a conversation with another user > check the correct user data is rendered.
BEFORE: 
https://github.com/zer0-os/zOS/assets/39112648/c609f619-1f2e-4c64-8283-68c99c3cdd72
AFTER:
https://github.com/zer0-os/zOS/assets/39112648/7b37762e-5d24-4a9d-a8d0-bf4750c01aa8

fix: map zero users and update presence when user adds room

---

src/store/channels-list/api.ts

This adds a mapping from the server side user response to the format the app expects
In the app a user record has the primary key of `userId` not `id`. Adding this to the api fetch so all callers will get the right data.

Map to a proper user object after api call

---

src/lib/chat/matrix-client.ts

While sending an image, we should also record that a message was sent (for rewards calculation)

Record an event that an image message was sent

---

package-lock.json
package.json

chore: bump zOS version (`0.79.0`) -> (`0.80.0`)

chore: bump zOS version (`0.79.0`) -> (`0.80.0`)

---

src/lib/chat/matrix/chat-message.ts

[Matrix] Compose and Send IMAGE + TEXT Message

---

src/lib/chat/matrix-client.ts

We're seeing an error in production where the edit event does not contain content. Adding null check and debugging information.

Temporary fix for empty edit events

---

src/store/channels-list/saga.ts

- fixes a type error in the channel list saga.
- fixing the type error in the channel list saga prevents the saga failing and therefore the names of the user are correctly rendered in the conversation list items. 
- this fix also appears to prevent users from creating more than one conversation with another user.
- create a conversation between two users > check name in conversation list item is rendered as expected > check that you can not create another conversation with the same user as they should not appear in the search results.
BEFORE DEMOS:
UserId in place of User Name when creating a conversation & creating more than 1 conversation with user. …

fix: channel list saga type error failure

---

src/store/channels-list/saga.ts
src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts
src/store/utils.ts

When batch processing incoming messages ensure only 1 copy of the message is used.
Sometimes we receive multiple events for the same message in quick succession and they end up being processed in the same batch. This uniqifies the message in the list before saving to the store.

Uniqify messages before saving them in batch processing

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts
src/store/utils.test.ts
src/store/utils.ts

When filtering duplicate events, favor the most recent

Favor the latest event when processing batch messages

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/chat/bus.ts

Adds code to more fully cleanup Matrix data when a user logs out
Turns out we weren't cleaning up enough of the Matrix sdk cached data when logging a user out. This causes strange behaviour when a user logs in again as themselves or someone else.

Fully log out of Matrix and chat when logging out

---

src/store/channels-list/saga.ts

This fixes a re-login issue we were seeing
Previously if you had logged out and then tried to log in again right away without refreshing the page we wouldn't fetch the conversation list because we were returning out of the listener after 1 successful run.
Logout and login again. You should see your conversation list.

Fix re-login without refresh

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

Uses the more complete `logout` message rather than just `stopClient`
I believe the logout method will actually "remove" the device from the room list since we'll never connect as that device again. This keeps things trim.

Switch to Matrix SDK logout rather than stopClient

---

src/invite.scss
src/pages/login/login.scss
src/reset-password.scss

- This change adds the CSS property `mix-blend-mode: screen` to the styling of our logo container. This property ensures that the logo's black background is rendered as transparent across different browsers.
- We are implementing this change to address the issue of inconsistent logo background rendering across various browsers.
- load zOS login, invite, create account screens and check logo background.
**Examples**
Firefox Before:
Firefox After:
Safari After:
Edge After:

fix: blend zero logo for cross-browser background consistency

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/group-management-menu/styles.scss
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/lib/feature-flags.ts

- adds the group management menu to the conversation header
- adds feature flag for the group management dropdown menu in the conversation header
- adds test coverage
- to be able to manage groups i.e. leave group, add members.
- Open messenger > Enable menu by entering `window.FEATURE_FLAGS.enableGroupManagementMenu = true;` in the console > Check three dot menu in conversation header.
Menu in conversation header:

feat: add group management menu to conversation header

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/types.ts

Sets the appropriate `power_level` for each user while creating a conversation. The creator is set as `100` (i.e admin), and everyone else as "viewer" (`0`).
Previously everyone's power level was set to "100", which means everyone had admin functionality. This is not desirable. 
Log the `PowerLevels` events using the eventTimeline, and check for the power_levels for each user in a room.

Set `power_levels` for each user while creating a conversation

---

src/lib/browser/index.ts
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/lib/chat/matrix/types.ts
src/store/chat/bus.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts

First iteration of adding browser notifications. If the approach is in line with how we expect to handle browser notifications, it should be straight forward enough to add additional logic of when to send browser notifications.
Changes were made in reference to how Element handles browser notifications.
- handles Notification Permissions when initialising the client.
- listens for timeline room events.
- processes room timeline events and maps the event to a browser notification message.
- once timeline event is processed we action real time chat event `receiveLiveRoomEvent`.
- messages saga actions sending the browser notifications.
- to handle and add browser notifications to zOS.
- pull branch > login to zOS > enable notifications on initialisation >  send your current user a message …

feat: add browser notifications

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/lib/feature-flags.ts

- Adds ‘Add Member’ as an option list to the triple dot menu, such that ONLY ROOM ADMINS can see it.
- So room admins are able to start the add member flow by selecting `Add Member` from the group management dropdown menu.
- `enableGroupManagementMenu` > `enableAddMemberToGroup` >  Create a room > Click three dot menu > Check if `Add Member` menu item renders > Click `Add Member` > Check console log for `group management: starting add group member`.
Add Group Member Menu Item Exclusively For Room Admin:
https://github.com/zer0-os/zOS/assets/39112648/d421a6e5-e93a-452a-90f3-493b5c998c1b

feat: enable add member menu option exclusively for room admins

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts

This changes the message event handler to favor newer updates to messages.
Due to various event timing we sometimes have a message in the list that shows "could not decrypt" message but a later event comes in with the properly decrypted version. Previously, since the message was already in the list, we were ignoring the new event. This is particularly obvious during a key backup restore as all messages are undecryptable and performing the restore wouldn't immediately update the view.

Update messages immediately when a backup restore occurs

---

src/components/secure-backup/container.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/lib/chat/index.ts
src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

This changes the key backup to use cross-signing and secure storage.
The cross-signing allows us to 'verify' the new device properly so that all future messages are also available upon subsequent key backup restores.
Create a backup, send some messaages, logout, restore the backup, send more messages, logout again and restore again. You should be able to decrypt all the messaages from both before the restore and after.

Modify key backups to use cross-signing

---

package-lock.json
package.json

- bump zos version (`0.86.0`) -> (`0.87.0`)

chore: bump version (`0.86.0`) -> (`0.87.0`)

---

src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx

Refactoring to pull the GroupManagement panel stuff into its own component so the messenger list doesn't have to manage as much.

Refactor: extract GroupManagement sub-component

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx

If there are no menu options available then don't render the menu at all

Don't render the group management menu if no options are available

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/lib/feature-flags.ts

Adds the Edit menu option to the room management menu if the user is an admin of the room (feature flagged)

Adds Edit Group menu item to room management menu

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/lib/feature-flags.ts

The conversation management features are all independently as necessary now

Remove the global enableGroupManagementMenu feature flag

---

src/components/messenger/autocomplete-members/index.test.tsx
src/components/messenger/autocomplete-members/index.tsx

- where `AutoCompleteMembers` is being used, i.e. `New Conversation` (create conversation), `Select Member` (create group), `Add Members` (group management), when selecting a member, the input will be cleared, and the search results will be reset.
- behaviour requested (n3o).
- open messenger and go through one of the flows mentioned above that use the `AutoCompleteMembers` component. When selecting a member, the input should clear and the search results should also clear. 
To note: A follow up PR should probably be to ensure the input is focussed once cleared.
Before:
https://github.com/zer0-os/zOS/assets/39112648/7ca7b0bf-379a-49b5-a827-c2d5f41e3bb5
After: …

feat(autocomplete-members): clear input and search results

---

templates/component/index.test.tsx.mustache

Removes the quotes in the `describe` block of the test template.

Remove quotes in test template

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx

Removes "Name cannot be empty" error, since it can be.

Remove "name" error while editing a group

---

src/lib/chat/matrix-client.ts
src/lib/chat/matrix/types.ts

When fetching the rooms for a user we need to filter out any rooms where their membership is "Leave"
It turns out that Matrix still returns rooms that you were kicked out of in the user's list of rooms. Technically, you can still see the history of those rooms if you'd like but for our purposes we just don't want them to show up for the user.

Filter out rooms that the user has left

---

src/components/messenger/list/edit-conversation-panel/index.test.tsx
src/components/messenger/list/edit-conversation-panel/index.tsx

To prevent "empty" conversations we don't allow you to remove members of a room to fewer than 2 for now.

Don't allow removing members if there are only 2 left

---

src/store/channels-list/api.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts

Changes the getZEROUsers api call to map the result to a local domain User object.
This allows our business logic to deal with users as it would expect them to be shaped.

Return a true user object from the getZEROUsers api call

---

src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.test.ts
src/store/test/store.ts

The StoreBuilder was saving user state in an invalid format. This....fixes that.

Update StoreBuilder to properly store user records

---

src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.test.ts
src/store/messages/utils.matrix.ts

We had multiple places where we mapped raw message event data to include senders, previews, parentMessage, etc. This consolidates.

refactor: reduce duplication of mapping message events with fully loaded data

---

src/store/channels-list/channels.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/login/saga.ts

Refactos the conversation bus to publish events with a `type` which makes consuming the events more standard.

Refactor the conversationBus to be more standard

---

src/components/messenger/chat/styles.scss

I wasn't able to see the gradient on the top messages going behind the header. Works after increasing the gradient by 1. (possibly because of z-index: 1 being default of browser)
Before:
After:

zOS Redesign: Increase z-index by 1 for the header gradient

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

This removes the body of the `fetchChannels` since we no longer consider channels in Messenger. This allows us to ignore the old code when making changes.
Future: Remove all the calls to fetchChannels

Remove functionality of fetchChannels

---

src/store/chat/bus.test.ts
src/store/chat/bus.ts
src/store/chat/saga.ts

This adds functionality to the chat client/saga event boundary (the Chat Bus) which delays chat events from being published until the system indicates that it's prepared to receive them.
There's currently race condition bugs related to the Matrix "snapshot" being loaded and various "catch up events" being consumed. Eg:
1 We load the conversation list and are processin it but, since it's async, other things are being processed
2 While that is happening, an event such as "User Joined Room" happens and publishes to the sagas. The saga tries to find the room but since the room list is still empty due to #1 being in progress it does nothing.
3 Subsequently, #1 finishes and we have all the room data loaded into state that is the snapshot version which does not yet include the user who joined. …

Delay event publishing until all conversations have been loaded once

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

- updates `updateUserPresence` to accept users directly and dispatch actions (users presence in state).
- streamline/enhance fetching users presence.

refactor: updateUserPresence to accept users directly and dispatch actions

---

src/lib/chat/chat-message.test.ts
src/lib/chat/chat-message.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts
src/store/chat/saga.ts
src/store/messages/index.ts
src/store/messages/saga.fetch.test.ts
src/store/messages/saga.test.ts
src/store/messages/saga.ts
src/store/messages/utils.matrix.ts

- admin message for when a member leaves a room
- to highlight to other users that a member has left the room
- with two test users on different browser profiles, initiate the leave room flow and leave the room with one of your test users. once you have left the room, check on the other test users conversation that the admin message clearly states which user has left.
DEMO
https://github.com/zer0-os/zOS/assets/39112648/cb20bd68-cbfb-468e-995b-bfa0eaf97af7

feat: add member left admin message when member leaves room

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Prevents fetching user presence for the same users many times, particularly when first loading the conversations.

Unique the list we use when batch fetching the user presence

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/styles.scss
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx

- add users online status to profile avatar
NOTE: this is updating the settings menu dropdown trigger attributes to include the online status of the user (the avatar) for now. At  some point the settings menu will be removed. When this happens the dev working on this will just need to pull out the avatar component from the dropdown in settings menu.
Before:
After:

feat: add users online status to profile avatar

---

src/components/group-management-menu/index.tsx

- replaces group management three dot icon with the `IconButton` component that contains the three dot icon. This component 
- the styles of the icon button align with figma, i.e. correct padding and size.
- the icon button will have a hover.

refactor: replace three dot icon with icon button

---

src/_glass.scss
src/components/messenger/list/styles.scss
src/components/sidekick/index.tsx
src/components/sidekick/styles.scss

Applies "glass" styles (stroke, fill, box-shadow, and blur), to the conversation list panel.
Before:
After:

ZOS Redesign (glass style): Conversations Panel

---

src/_glass.scss
src/components/messenger/chat/styles.scss

ZOS Redesign: Apply flat/thick style to conversation header

---

src/_glass.scss
src/components/chat-view-container/styles.scss
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/menu/menu.tsx
src/components/message-input/styles.scss

+ Adds flat/thick style to message input container
+ updates the "send icon" to be filled if there is a typed message
+ replace paper clip icon with "+" icon
+ update text input style to "inset glass style"
+ Update `fontSize` to 16, `font-height` to 23.
Before:
After:

ZOS Redesign: Update Message Input styles

---

package-lock.json
package.json

- bump zui version `(0.28.0)` -> `(0.30.0)`

chore: bump zui version `(0.28.0)` -> `(0.30.0)`

---

package-lock.json
package.json
src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss
src/components/messenger/list/conversation-list-panel/index.tsx
src/components/messenger/list/user-header/styles.scss

- updates the padding of the header and list
- align with figma designs
Subtle differences.
Before:
After:

feat: update conversation list panel header and list padding

---

src/_glass.scss
src/components/messenger/list/conversation-item/conversation-item.scss

- updates styles for the conversation item - text and colours (including for states)
- align with figma redesign
NOTE: Removing the users name from the message preview if its a one on one conversation is likely to be included in another task. This task simply updates the styles.
FIGMA:
DONE:

feat: conversation item redesign updates

---

src/_glass.scss

Adds the glass border back and prevents it from stealing pointer events

Add glass border back with pointer events disabled

---

src/_glass.scss
src/components/messenger/list/conversation-item/conversation-item.scss

- updates the group avatar appearance in the conversation list.
- align with figma designs.
Appearance confirmed with design team.
Before:
After:

feat: (conversation-list) group avatar appearance redesign

---

src/platform-apps/channels/styles.scss

Adds padding to the top of the conversation so you can see the start of the conversation below the header

Add padding to top of the conversation

---

src/_glass.scss
src/components/message-input/styles.scss

Previously there was only a single state for message input background. The new design adds 2 - one for default, and another for active (i.e focused)
Default
Active (when typing something)

Add default and active states for message input (composer)

---

src/_glass.scss
src/components/message/styles.scss

Updates the message bubble as per the new design
Messages Sent (flat/thin)
Messages Received (flat/thick)

ZOS Redesign: Message Bubbles

---

src/_glass.scss
src/components/message-input/styles.scss
src/components/message/parent-message/styles.scss
src/components/reply-card/styles.scss

Updates the styles for replies (inside message-input, and the parent message rendered)
Message Input
Parent Message:

ZOS Redesign: Replies

---

src/components/messenger/list/conversation-item/index.tsx
src/components/messenger/list/styles.scss

- updates the handling of which Avatar Icons to display.
- to display the correct Avatars in the conversation list.

feat: update conversation list avatar logic

---

src/_glass.scss
src/components/messenger/list/conversation-item/conversation-item.scss

- implements the redesign for the unread message count
- as per figma designs

feat: unread count redesign

---

src/components/messenger/list/conversation-item/index.tsx

- applies `isRaised` property to `Avatar`'s used in the `ConversationList`.
- as per figma designs (re-design)

feat: apply raised styles to conversation list avatars

---

src/components/settings-menu/index.tsx
src/components/settings-menu/styles.scss

- applies the `spacious` sizing to the settings menu dropdown menu items.
- as per figma designs (re-design)
Before:
After:

feat: apply spacious sizing to settings menu dropdown menu

---

src/components/group-management-menu/index.tsx
src/components/group-management-menu/styles.scss
src/components/settings-menu/styles.scss

- updates group management dropdown menu items
- align with figma designs (re-design)
Before:
After:

feat: update group management dropdown menu items for re-design

---

package-lock.json
package.json

-  bumps zui version `(1.3.0)` -> `(1.4.0)`

chore: bump zui version `(1.3.0)` -> `(1.4.0)`

---

src/platform-apps/channels/messages-menu/index.tsx
src/platform-apps/channels/messages-menu/styles.scss

- updates the three dot message dropdown menu items.
- as per figma designs (re-design)
Before:
After:

feat: update message dropdown menu items for redesign

---

src/lib/chat/chat-message.test.ts
src/lib/chat/chat-message.ts

- replaces `group` with `conversation` (admin messages)
- for a one on one conversation the word `group` doesn't make too much sense `xyz was added to the group`.

feat: replace `group` with `conversation` (admin messages)

---

package-lock.json
package.json

- chore: bump zOS version `(1.0.0)` -> `(1.1.0)`

chore: bump version `(1.0.0)` -> `(1.1.0)`

---

src/components/messenger/list/index.tsx

Could be a conversation on my list where the "otherMember" had not accepted the invite. I was getting this on my local & development accounts.

Fix creating a new conversation

---

src/store/channels/saga.ts

The issue was with the race condition during create conversation's `startEvent` saga. It sets up a few race conditions, but if we "don't create a conversation", & just open an already existing one, the race condition isn't resolved and hence the `+` icon does not respond afterwards.
Before:
https://github.com/zer0-os/zOS/assets/33264364/5823c8e7-1233-40bd-aeb7-b4c59e039bd5
After:
https://github.com/zer0-os/zOS/assets/33264364/07580419-aa02-4d75-958d-e3913457d0fc

(Bug)  `+` icon not responding after you open a conversation with someone already on your list

---

src/_glass.scss
src/components/chat-view-container/chat-view.test.tsx
src/index.scss
src/lib/chat/chat-message.test.ts
src/lib/chat/chat-message.ts

- changes the "fill" as per Ethan (change the opacity to 50%)
- change the background image

Update zOS background image, change fill opacity

---

src/components/chat-view-container/styles.scss
src/components/messenger/chat/styles.scss
src/platform-apps/channels/styles.scss

We had some styles that were still included in the higher Channels app that applied to the lower components. This is just a consequence of extracting subcomponents and not getting all the styles moved down. This PR moves the ones that appear to impact Messenger.
To allow future deletion of the Channels app

Move some channel styles closer to the appropriate sub-components

---

src/components/group-management-menu/index.tsx
src/components/group-management-menu/styles.scss

- removes the use of `IconButton`.
- adds `IconDotsHorizontal` in place of the button.
- makes use of the `className` attribute on the dropdown. This is the className for the trigger.
- added trigger styles to stylesheet.
- prevent the console error.

fix: resolve group management menu nested button console error

---

src/components/group-management-menu/styles.scss

- applies height and width to group management trigger.
- as per figma, adds the width and height to the trigger to ensure correct hover radius.
Before:
After:

feat: apply height and width to group management trigger

---

src/lib/feature-flags.ts

Adds a feature flag for toggling email registration/login

Add feature flag for email login defaulted to enabled

---

src/authentication/create-account-method/index.tsx
src/pages/login/login-component.tsx

Hides the registration/login by email options based on the feature flag.
Registration enabled:
Registration disabled:
Login enabled:
Login disabled:

Hide the registration/login method toggle if email is disabled

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/channels/saga.ts
src/store/create-conversation/saga.ts

When in the create conversation flow we want to prevent creating duplicate 1 on 1s with the same user. This moves that protection logic out of the component and up to the appropriate saga

Move check for existing conversation into saga

---

package-lock.json
package.json

chore: bump zui version (`1.4.0`) -> (`1.5.0`)

chore: bump zui version (`1.4.0`) -> (`1.5.0`)

---

package-lock.json
package.json

- chore: bump zui version (`1.5.0`) -> (`1.6.0`)
(removes min width from modal)

chore: bump zui version (`1.5.0`) -> (`1.6.0`)

---

src/components/invite-dialog/container.test.tsx
src/components/invite-dialog/container.tsx
src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx
src/components/invite-dialog/styles.scss
src/store/create-invitation/index.ts
src/store/create-invitation/saga.ts

- dispatch a `clearInvite` saga action to clear the invite when the invite dialog is closed.
Issue:
The InviteDialog component's button flickers between disabled and enabled states on subsequent openings. Initially, on first opening, the inviteCode is not present, so the button is correctly disabled. However, on closing and reopening the dialog, the button quickly toggles from enabled (as inviteCode is initially present) to disabled (as inviteCode is momentarily cleared due to a reset() in the fetch saga) and back to enabled (after inviteCode is refetched and set).
Root Cause:
The fetchInvite saga always resets the inviteCode state on each call, causing the inviteCode to be temporarily undefined even if it was previously fetched. This reset, followed by a refetch, leads to flickering …

feat: clear invite when closing invite dialog

---

src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.ts
src/store/channels/saga.ts
src/store/create-conversation/saga.ts
src/store/login/saga.test.ts
src/store/login/saga.ts

Refactors sagas to call `openConversation` when that's what they mean rather than old direct data setting `setactiveConversationId`. This helps readability as the sagas now show the intention better but also allows us to modify what it means to open a conversation more easily.

Call openConversation rather than just setting state

---

package-lock.json
package.json

chore: bump version (`1.3.0`) -> (`1.4.0`)

chore: bump zOS version (`1.3.0`) -> (`1.4.0`)

---

src/components/dev-panel/container.tsx
src/index.tsx
src/messenger-main.test.tsx
src/messenger-main.tsx
src/store/channels/saga.ts
src/store/chat/index.ts
src/store/chat/saga.ts
src/store/chat/selectors.ts
src/store/login/saga.ts

1. Adds route parsing for conversations
1. When loading the url, parses the id and opens it rather than the top conversation
Eg: http://example.com/conversation/!URmXfWMRTpYQZBXEzV:zero-synapse-development.zer0.io
Still to come:
* Change the url when opening a conversation

Make conversations routable

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/message-input/container.test.tsx
src/components/message-input/container.tsx
src/components/message-input/index.tsx
src/components/message/index.test.tsx
src/components/message/index.tsx
src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/components/sidekick/styles.scss
src/store/channels/index.ts
src/store/channels/saga.ts
src/store/redux-container.ts

- refactored `<MessageInput>` component, moved it from `<ChatView>` (lower level) to `<MessengerChat>` (higher level in DOM).
- moved `reply` local state from container to global state in redux.
- added bottom gradient. 
- added background blur on composer
- messages can now be scrolled to the bottom of the composer.

Refactor `<MessageInput /> component, update styles (bottom gradient, scrollbar)

---

src/messenger-main.test.tsx
src/messenger-main.tsx
src/store/channels-list/saga.createConversation.test.ts
src/store/channels-list/saga.test.ts
src/store/channels/saga.ts
src/store/chat/saga.ts
src/store/create-conversation/saga.test.ts

This manages the open conversation via the URL.
Makes routable conversations a more complete user experience. The user can now use the back/forward button, bookmark pages, link to conversations (the key piece for token-gated access)

Manage the open conversation via the URL

---

src/pages/login/login-component.tsx
src/store/page-load/index.ts
src/store/page-load/saga.test.ts
src/store/page-load/saga.ts

If a user opens the app to a specific path but is not logged in the app will redirect back to that page once login is completed successfully.
Hit a known url within the app such as /conversation/<id> when the user is logged out. Log in. Verify that the correct conversation is open when the login completes and the app is fully loaded.

Redirect to the initial entry path when user logs in or creates new account

---

package-lock.json
package.json

- chore: bump zui version (`1.6.0`) -> (`1.7.0`)
Updates `IconInfoCircle` icon stroke width

chore: bump zui version (`1.6.0`) -> (`1.7.0`)

---

src/components/chat-view-container/chat-view-container.test.tsx
src/store/channels/saga.test.ts
src/store/channels/saga.ts
src/store/chat/index.ts
src/store/chat/types.ts
src/store/messages/saga.receiveNewMessage.test.ts
src/store/messages/saga.ts
src/store/test/store.ts
templates/container/container.test.tsx.mustache

Removes the `activeChannelId` from state as we no longer have "Channels"

Remove activeChannelId from state

---

src/lib/chat/index.ts
src/store/create-conversation/saga.test.ts
src/store/create-conversation/saga.ts

Hides the chatClient abstraction from the sagas. This makes the tests a little tidier as it's simpler to mock a chat call.

Hide the chatClient abstraction from the sagas

---

src/components/messenger/chat/styles.scss

Removes `overflow: hidden` prop which was hiding the emoji picker.
Before:
After:

Fix emoji picker not appearing on click

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/components/messenger/chat/index.tsx
src/lib/feature-flags.ts

- adds group info menu item to dropdown menu (group management)
- to have a menu item to open the group information panel (when implemented)
- In the console enter `window.FEATURE_FLAGS.enableGroupInformation = true;` > refresh > In a group conversation click the three dot group management menu > check group info menu item is displayed > click and check console logs.

feat(group-management): add group info menu item

---

src/components/messenger/list/group-management/container.tsx

- gets current users online presence.
- to have an accurate users status/presence in the group management panels
- open a group management panel that contains members avatars and check current users presence status (should be green/online, not grey/offline)

feat(group-management): get current users online presence

---

src/components/group-management-menu/index.tsx

- re-orders group management menu items as shown below.
- so `Leave Group` item is displayed last.
- open group management menu and check item order
Before:
After:

refactor: re-order group management menu items

---

src/components/group-management-menu/index.test.tsx
src/components/group-management-menu/index.tsx
src/lib/feature-flags.ts

- removes group info feature flag
- to enable view group information flow.
- open a group conversation and check if the `Group Info` menu item is displayed and initiates the flow.

feat: remove group information feature flag

---

package-lock.json
package.json

- chore: bump version (`1.6.0`) -> (`1.7.0`)

chore: bump version (`1.6.0`) -> (`1.7.0`)

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/view-group-information-panel/index.test.tsx
src/components/messenger/list/view-group-information-panel/index.tsx

- correctly assigns the `Admin` tag to the conversation admin.
- `Admin` tag was being assigned to current user for each group conversation.
- open group information panel and check the admin tag is next to the correct conversation admin user.
Note: this image contains changes to the Admin tag styles, which will be pushed in a follow up PR

fix(view-group-information): admin tag should be assigned to conversation admin

---

src/components/citizen-list-item/styles.scss

- updates styles of citizen list item tag
- as per figma design
- open edit group or group info panel to see the Admin tag.
Before:
After:

feat: update citizen list item tag styles

---

package-lock.json
package.json

chore: bump version (`1.7.0`) -> (`1.8.0`)

chore: bump version (`1.7.0`) -> (`1.8.0`)

---

src/components/messenger/list/utils/utils.test.ts
src/components/messenger/list/utils/utils.tsx

- adds helper functions (utils) to sort members for view group info panel and edit group info panel.
In the `sortMembers` function, the order is:
1. The current user is sorted to the top.
2. Admins are sorted next.
3. Users are then sorted based on their online status, with online users appearing before offline users.
4. Lastly, users are sorted alphabetically by their first name.

feat: add sort members and is user admin util functions to messenger/list/utils

---

src/components/citizen-list-item/index.tsx
src/components/citizen-list-item/styles.scss

- updates citizen list item avatar size and hover colour
Before:
After:

feat(citizen-list-item): update avatar size and hover color

---

src/components/group-management-menu/index.tsx

- fixes a non-serializable value detected console error.
- fixes the error shown below caused when clicking the `Edit Group` menu item.
- Click `Edit Group` menu item and check console for errors.
Error:

fix(grp-mgmt-menu): non-serializable value detected console error

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/view-group-information-panel/index.test.tsx
src/components/messenger/list/view-group-information-panel/index.tsx
src/components/messenger/list/view-group-information-panel/styles.scss

- adds edit button to view group information panel to navigate to the edit group panel.
- as per design - so the user can access the edit group panel from the view group information panel.
- if you are admin of a group, navigate to the group information panel > click `Edit` button > check edit group panel is displayed.
Navigate to Edit Group Panel from View Group Information Panel.
Note :: we may choose to improve/adjust back navigation at a later date.
https://github.com/zer0-os/zOS/assets/39112648/8337f1c9-c9a9-4d97-bb1e-c056a2aa300e

feat: navigate to edit group flow from view group information panel

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/view-group-information-panel/index.test.tsx
src/components/messenger/list/view-group-information-panel/index.tsx
src/components/messenger/list/view-group-information-panel/styles.scss

- starts the add member flow from group info panel when clicking the '+' icon.
- as per designs.
- open the group info panel on a group you are the admin of > click the '+' icon > check the add member flow is displayed.
Note : Back navigation will likely be improved at a future date in a separate task.
https://github.com/zer0-os/zOS/assets/39112648/c5a82c6f-7039-48df-aee6-1d01667f8778

feat: start add member flow from group info panel

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/group-management/index.test.tsx
src/components/messenger/list/group-management/index.tsx
src/components/messenger/list/view-group-information-panel/index.test.tsx
src/components/messenger/list/view-group-information-panel/index.tsx
src/components/messenger/list/view-group-information-panel/styles.scss

- opens leave group dialog from view group information panel if current user is not admin.
- as per designs.
- 
- navigate to a group conversation you are not an admin of > click group management three dot dropdown menu > select group info menu item > click Leave Group buttons.
Note: the leave group button is not exact to figma designs as we will be updating the button component in the near future.
https://github.com/zer0-os/zOS/assets/39112648/59e40da2-9e11-482d-a486-f2b75ce1a9aa

feat: open leave group dialog from view group information panel

---

src/lib/chat/index.ts
src/store/channels-list/index.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts
src/store/chat/index.ts
src/store/chat/saga.ts
src/store/chat/types.ts

We used to poll for channel information in the case of public zOS. That's no longer a thing so this removes it.

Remove old polling for channels

---

src/lib/feature-flags.ts

Add `allowJoinRoom`, if set `true` then user can be a part of a room that doesn't exist, or he hasn't joined yet.

Add allowJoinRoom feature flag

---

src/store/channels-list/saga.ts
src/store/channels-list/selectors.ts

Adds state tracking when we're loading the room list for the user so we can check it later on.

Track the channel list loading state

---

package-lock.json
package.json

- chore: bump version (`1.8.0`) -> (`1.9.0`)

chore: bump version (`1.8.0`) -> (`1.9.0`)

---

src/messenger-main.test.tsx
src/messenger-main.tsx

As per review feedback, we need to validate the active conversation when the user changes a url within the app as well.

Call `setActiveConversationId` on `componentDidMount` in `messenger-main.tsx`

---

src/messenger-main.test.tsx
src/messenger-main.tsx

This reverts commit 2fce711ec070f4f19d2607482d393509f59762d3. 
PR - [https://github.com/zer0-os/zOS/pull/1412](https://github.com/zer0-os/zOS/pull/1412)
This was causing issues with the initial load after logging in. Looking into it, but meanwhile reverting this change.

Revert "Call setActiveConversationId on componentDidUpdate in messenger-main.tsx (#1412)"

---

src/messenger-main.test.tsx
src/messenger-main.tsx
src/store/chat/saga.ts

As per review feedback, we need to validate the active conversation when the user changes a url within the app as well (working now)

Remove `rawSetActiveConversationId` from messenger-main.tsx

---

src/messenger-main.test.tsx
src/messenger-main.tsx
src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/login/saga.ts

Since we're validating the active conversation each time the components mounts/updates (after channels load), we can remove a previous function which was opening the first conversation after loading the channels. We can just open the first conversation in `performValidateActiveConversation` only.
Earlier this was causing an issue since two events were fired at the same time: `openFirstConversation` (by `openFirstConversationAfterChannelsLoaded` saga event), and the `validateActiveConversation` saga event.

Remove `openFirstConversationAfterChannelsLoaded` from `store/login/saga.ts`

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss

- correctly handles the conversation header avatar for group conversations, one on one conversations and whether there is a custom icon or not.
- to fix how the avatar is displayed in the conversation header depending on the conditions mentioned above.
- open messenger and check the avatar of the different types of conversations and set icons.
Before: 
After:

fix: handle conversation header avatar

---

src/store/channels/saga.ts

Infinite loop fix. If you don't have any conversations then this used to redirect to the empty conversation url which then tries to "open first conversation" again....

Set the raw data to null if we can't find a conversation rather than redirecting

---

src/components/error-dialog/index.test.tsx
src/components/error-dialog/index.tsx
src/components/error-dialog/styles.scss

- adds optional link and logic to the error dialog component.
- these changes have been made so the user can navigate to an external url (e.g. zns explorer) from the error dialog, and, also handle when a link is not required.
- pass in the optional props to where the `ErrorDialog` is being used and test that the link is displayed and navigates you to an external path in a new tab, and vice versa, e.g. only render the button if a link path & link text is not provided.
Style/Design as per Figma ['here'](https://www.figma.com/file/btwltL4Os8hAy3eS3pxaa6/ZERO-Messenger-Web-%7C-Glass?type=design&node-id=12825-41059&mode=design&t=dlAwjivfKOymGjtB-0) 
When `linkPath` and `linkText` are provided:
When `linkPath` or `linkText` are NOT provided:

feat(error-dialog): add optional link and logic

---

src/index.scss

- aligns messenger background image as shown in below demo.
- when screen size decreases/increases the background image should be aligned to the centre of the browser window.
- open messenger and decrease/increase screen size > check background is centre aligned 
Before:
https://github.com/zer0-os/zOS/assets/39112648/c9475817-ee4e-4468-82b3-ea8f8d5e1066
After:
https://github.com/zer0-os/zOS/assets/39112648/b9fda520-7df4-40df-b71b-9bfd70320504

feat: centre align messenger background image

---

src/components/messenger/chat/index.test.tsx
src/lib/chat/matrix-client.ts
src/store/authentication/types.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts

- returns primaryZID when fetching user data.
- to use/display the users primaryZID in the UI, i.e. display users primaryZID with user details/search by primaryZID.
- run api locally, set primaryZID in database table and check data is returned when fetching user data by logging the primaryZID.

feat: return primaryZID when fetching user data

---

src/store/chat/saga.test.ts
src/store/chat/saga.ts

After calling the API (`/matrix/room/join`), we should wait for the "real time" event from Matrix before setting the conversation Id. 
Previously we were setting the conversationId before even receiving the event, which was causing the UI to not behave properly (eg. messages fetch failed, UI crashing for some users etc).

Wait for `UserJoinedRoom` Event before setting the `rawActiveConversationId`

---

src/components/messenger/list/utils/utils.test.ts
src/components/messenger/list/utils/utils.tsx

- exposes first 6 characters of users wallet address (for user handle) rather than the first 4.
- log in using a wallet > check user handle in conversation list header (user-header) as shown below.

feat: adjust user handle wallet address truncation

---

src/components/messenger/chat/index.test.tsx
src/components/messenger/chat/index.tsx
src/components/messenger/chat/styles.scss
src/lib/chat/matrix/chat-message.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts
src/store/messages/index.ts
src/store/messages/utils.ts

Renders primary ZID OR wallet_address (or empty string if none exist) in conversation header.
Before:
After:
NOTE: For group conversations we still show online/offline status

Render primary ZID in conversation header

---

.env.example
src/components/messenger/list/user-header/index.tsx
src/config.ts
src/store/chat/utils.test.ts
src/store/chat/utils.ts

- replaces the use of the zns explorer url with the environment variable, through the config.
- we should use the zns explorer urls set by environment variables.
- add env variable (in env.example), `npm i`, `npm run start`, click one of the links used to navigate user to the explorer.

feat: use zns explorer url environment variable

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/channels-list/saga.ts
src/store/chat/bus.ts

We can remove this event (triggerred via `MemberShip.Invite`), since we're handling `currentUserAddedToChannel` via `MemberShip.Join` event

Remove `onUserReceivedInvitation` event

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

- Updates `createConversation` flow to first create a room, and then invite the appropriate users. 
- Sets the default power levels for all users (including new users which add to room)
Earlier, if you add a new member to room, then that member can still add other users to the group (this is disabled via UI, but you can still call the API directly and it will add new members). This is fixed now.
If you try to add a new member now, and you're not an admin, you'll get this error:
Similar code has been added on the API side as well.

[Fix] Non Admin member (non-creator) should NOT be able to add new users to group

---

src/components/message-input/index.test.tsx
src/components/message-input/index.tsx
src/components/message-input/styles.scss
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/utils.ts

Renders primary ZID of user while mentioning users in a chat.
NOTE: I didn't update the UI much, as there is a task dedicated to mentions redesign in the backlog.

Render Primary ZID while mentioning users

---

src/lib/chat/matrix-client.ts

It's been a few release cycles, and the function `matrixClient.setPowerLevels` can be removed now.

Remove `setPowerLevel` fn from `matrix-client.ts`

---

src/messenger-main.test.tsx
src/messenger-main.tsx
src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/chat/utils.ts

Removes having to use `%23` in the conversation url (which was needed to parse the alias before). Now, you don't need to use any encoded char before the alias string. 
The logic is update to check if the id starts with `!`, then it's a valid (unique) ID, otherwise it's an alias.
Before you'll hit this url:
`http://localhost:3002/conversation/%23hite:zos-dev.zer0.io`
Now the url updates to:
`http://localhost:3002/conversation/hite:zos-dev.zer0.io`
Screenshot

Removing `decodeURIComponent` (to decode `%23` from the conversation URL if the `conversationId` is an alias)

---

src/components/edit-profile/container.test.tsx
src/components/edit-profile/container.tsx
src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/lib/feature-flags.ts
src/store/edit-profile/index.ts
src/store/edit-profile/saga.ts

Edit the primary ZID of the user (this is just the ui part for now, so this is feature flagged)
Upcoming: API work, and integration

Allow user to edit the primary zid (UI)

---

src/store/edit-profile/api.ts

We've renamed `/api/v2/users/edit-profile` to `/api/v2/users/profile`, since it's a `PUT`.

Use updated route for editing a user's profile

---

src/components/messenger/list/conversation-list-panel/index.test.tsx
src/components/messenger/list/conversation-list-panel/index.tsx
src/components/messenger/list/conversation-list-panel/utils.ts
src/store/users/index.ts
src/store/users/saga.test.ts
src/store/users/saga.ts
src/store/users/types.ts

- handles primary zid when searching and filtering conversations.
- to ensure a users `primaryZID` is considered when searching and filtering in the conversation list.
- you will need to have test users that have a `primaryZID` which will allow you to search using a ZID in the search input and render results.

feat: handle search result filtering to include primary zid direct and indirect matches

---

src/store/chat/index.ts
src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/chat/types.ts

- adds loading state when validating joining a conversation.
- to communicate to the user the following : there will be a delay between loading the conversation list and displaying the conversation a user has been linked to. During this delay, the app is checking whether the URL is valid (does conversation exist) and if the user is a member (whether you are already added to the group or, if it is a TGC, whether you have the required token). 
- pass state to component level and log the boolean | alternatively add a basic ui component - then navigate to a conversation url.
When passed to component level:
https://github.com/zer0-os/zOS/assets/39112648/e8f5face-b3c4-43c3-a43e-6b2536f6e6d0

feat: add joining conversation loading state to chat saga

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts

This adds a check before reusing matrix credentials to ensure we want to reconnect as the same user. If ids don't match then we force a new login.
Should help solve the cases where a user with 2 accounts is getting them crossed up by being logged into zOS as one user but actually interacting with Matrix as previous user.

Only reuse credentials if the user id matches

---

.github/workflows/development.yml
.github/workflows/production.yml

- updates zns explorer url environment variable naming to match that on github env variables.
- should fix issue where the environment variable is not being set (due to mismatch of naming).
- on development or production we expect the use of this variable to direct you to the explorer url. this will need to be deployed to test.

fix: workflow environment variable naming to match with github (zns explorer url)

---

src/components/joining-conversation-dialog/index.tsx
src/components/joining-conversation-dialog/styles.scss

- adds a joining conversation dialog component.
- to import and use the component in `MessengerChat`.
- this is simply adding a component to the code base. no manual testing required here.

feat: add joining conversation dialog component

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts
src/store/chat/bus.test.ts
src/store/chat/bus.ts
src/store/chat/index.ts
src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/chat/types.ts

This adds some more consistent processing of Matrix events upon first load.
When connecting for the first time we queue up all matrix "catch up" events and then process all of them prior to allowing other events to process. This also publishes a new event that indicates that we've caught up with publishing the "catch up" events. It's not necessarily an indication that all business logic is complete but it's at least an indicator that our connection is in full working mode.

Add new event for when all matrix queued events are processed

---

src/store/chat/saga.test.ts
src/store/chat/saga.ts
src/store/chat/utils.test.ts
src/store/chat/utils.ts

- appends the extracted domain to the explorer url if activeConversationId is an alias.
- this ensures the user will be directed to the explorer - to a specific world.
- attempt to visit a room url (alias not id) > click 'Buy A Domain' link in error dialog > check explorer url (as shown below)
DEMO:
https://github.com/zer0-os/zOS/assets/39112648/e7bd9480-6d76-45ba-805e-6877f93b8975

fix: handle token gated join room error navigation

---

src/components/citizen-list-item/index.test.tsx
src/components/citizen-list-item/index.tsx
src/components/citizen-list-item/styles.scss

- fixes styles of the `CitizenListItem` that appear to have broken/been changed at some point recently.
- some refactoring to tests.
- as per figma designs. before and after below.
- check group info panel or edit group panel.
Before:
After:

fix(citizen-list-item): details, tag and remove icon positioning

---

.github/actions/common/action.yml
.github/workflows/production.yml

* Removes a redundant step in the common setup action. You have to checkout the code in the original action in order for the common action to be available.
* Use common setup during production github action

refactor: github actions common setup usage

---

.github/workflows/create-tag.yml

Removes the node setup step from the create-tag github action

Remove unused steps in create-tag action

---

src/components/messenger/lib/utils.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/index.tsx
src/components/messenger/list/utils/utils.test.ts
src/components/messenger/list/utils/utils.tsx
src/store/channels-list/utils.ts

- moves method higher up to libs folder in messenger 
- we'll be using this util outside of the `list` folder, therefore moving higher up in the `messenger` tree.

refactor: move get user handle to messenger lib utils folder

---

src/components/messenger/chat/conversation-header/index.tsx
src/components/messenger/chat/index.tsx

- moves permissions calcs out of conversation header
- flattens direct message props passed in
- renames events and variables
- adds condition to render header if direct message

refactor(conversation-header): improve props and naming

---

src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/index.tsx
src/store/authentication/types.ts

- exposes and uses `primaryWalletAddress` for current user - specifically for passing this value to `getUserHandle`.
- to use the actual default public wallet address as the primary wallet address rather than using the first wallet from wallets list.
- check redux auth>user state for primaryWalletAddress.
- check user handle is truncated address (user details -- if no zid)

feat: expose and use current user primary wallet address for user handle

---

src/components/messenger/chat/index.tsx

Temporary fix for when we have conversation data with a null/undefined otherMembers attribute. Will find the spot creating this data and fix the default to be an empty array as a follow up.

Account for possibly null otherMembers list

---

package-lock.json
package.json

chore: bump version (`1.10.0`) -> (`1.11.0`)

chore: bump version (`1.10.0`) -> (`1.11.0`)

---

src/lib/chat/index.ts
src/lib/chat/matrix-client.ts
src/store/chat/saga.test.ts
src/store/chat/saga.ts

Sometimes while verifying if a user is part of a conversation the whole convo list isn't loaded yet. I.E., on refresh when we haven't yet fully processed all the "catchup events". This adds a secondary check that gets the information straight from the matrix client. It's slightly slower but also should only ever happen in very rare cases as we use the initial state as the first check.
This helps alleviate a race condition that was occurring when refreshing the page just after joining a conversation.
Note: There are more changes to come as we're also now trying to load the messages while the app isn't quite in a full state. There are more data race conditions to resolve.

Add call to chat client to verify if user is a member of a room

---

src/components/messenger/chat/conversation-header/index.tsx
src/components/messenger/list/conversation-item/index.tsx

This gives priority to the "custom icon" set in the conversation data received from matrix. 
For eg. if there's a `oneOnOne` conversation with a `"icon"` value set, then we'll display that icon instead of the `profileImage` of the "other member".
This was required to display the conversationImage in a token-gated-chat, when there's only you & admin in the room. Instead of displaying the admin's profileImage, we want to display the conversationImage set in the "conversation" by the backend.

Render customIcon first as the conversationImage header (if set)

---

src/components/dev-panel/container.tsx
src/store/channels-list/saga.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts
src/store/channels/saga.ts
src/store/messages/saga.ts

Adds a saga to take a partial channel and set up all the default fields if the channel isn't in state yet.
Sometimes we'll get race conditions with events coming in prior to channels actually being in the state list. In these cases we want to ensure valid defaults are set in the data.
Create a conversation with someone. Refresh the browser once that's completed. Previously you'll notice that things frequently get trippeed up (eg: the skeleton renders and never disappears). That should no longer happen.

Receive partial channels and provide defaults if channel doesn't already have them

---

src/components/edit-profile/container.test.tsx
src/components/edit-profile/container.tsx
src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss
src/store/edit-profile/index.ts
src/store/edit-profile/saga.test.ts
src/store/edit-profile/saga.ts

https://github.com/zer0-os/zOS/assets/33264364/80c819c3-d2e0-454f-9223-819a41253a6a

Display loading indicator while fetching owned_zid's of user (during edit profile)

---

src/components/messenger/autocomplete-members/styles.scss

- truncates the user details in the search results in `AutocompleteMembers`.
- design.
Examples - 
Create Conversation Panel (Autocomplete Members)
Add Members Panel (Autocomplete Members)

fix(autocomplete-members): truncate search results user details

---

src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx

- allows the user to set primary_zid as "none"
https://github.com/zer0-os/zOS/assets/33264364/cd2df87a-6fc1-4e32-a564-0c56adee118a

Render `NONE (wallet address)` in dropdown while editing primary zid

---

src/components/messenger/list/user-header/styles.scss

- correctly truncates 'really long' user details in the user header.
- as per design & prevents ui issues shown below.
- update your user to have a really long name and check user header as shown below.
Before
After

fix(user-header-conversation-list): truncate user details

---

src/components/settings-menu/styles.scss

- correctly truncates 'really long' user details in the settings menu.
- as per design & prevents ui issues shown below.
- update your user to have a really long name and check settings menu as shown below.
Before:
After:

fix(settings-menu): truncate user details

---

package-lock.json
package.json

chore: bump version (`01.11.0`) -> (`1.12.0`)

chore: bump version (`01.11.0`) -> (`1.12.0`)

---

package-lock.json
package.json

- chore: bump version (`1.12.0`) -> (`1.13.0`)

chore: bump version (`1.12.0`) -> (`1.13.0`)

---

src/components/messenger/lib/utils.test.ts
src/components/messenger/lib/utils.tsx
src/components/messenger/list/group-management/container.tsx
src/components/messenger/list/index.tsx
src/lib/user.test.ts
src/lib/user.ts
src/store/channels-list/utils.ts
src/store/users/saga.ts

- renames `getUserHandle` -> `getUserSubHandle`
- moves `getUserSubHandle` to `lib/users`.
- redux stores shouldn't reference component code - this should be in a more general lib folder.
- run tests as usual - manually check ui where primary zid/user wallet address is displayed.

refactor: rename and move `getUserHandle` - (`getUserSubHandle`)

---

src/components/edit-profile/index.test.tsx
src/components/edit-profile/index.tsx
src/components/edit-profile/styles.scss

Update edit-profile modal design for success & error alerts

---

src/store/channels-list/saga.test.ts
src/store/channels-list/saga.ts

Removes some logic that was related to delayed discovery of whether a room was a channel or conversation.
We treat all rooms as conversations now so this is no longer a situation that can be reached.

Remove logic that converts channel to conversation in state

---

package-lock.json
package.json

- chore: bump version (`1.13.0`) -> (`1.14.0`)

chore: bump version (`1.13.0`) -> (`1.14.0`)

---

package-lock.json
package.json

- chore: bump version (`1.14.0`) -> (`1.15.0`)

chore: bump version (`1.14.0`) -> (`1.15.0`)

---

src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Performs a check for the current backup state when a user first sends a message
To convince users to create a backup!

Perform backup check when first message is sent

---

src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Refactors some chat client access to simplify the abstraction

Refactor getBackup to use abstracted function rather than client object

---

src/store/channels-list/saga.ts
src/store/channels-list/selectors.ts
src/store/channels-list/types.ts
src/store/channels-list/utils.ts
src/store/chat/saga.ts

Removes the selector that was filtering channels based on the isChannel flag as we don't use that any more

refactor: simplify old conversation selector

---

src/components/messenger/list/index.tsx
src/store/authentication/index.ts
src/store/authentication/saga.test.ts
src/store/authentication/saga.ts
src/store/authentication/types.ts
src/store/login/saga.ts
src/store/test/store.ts

Adds an intermediate logout saga which sets the (to be developed) logout confirmation modal to open and adds a forceLogout.
The app still currently uses the forceLogout until the modal is complete.

Add state for rendering the logout confirmation modal

---

src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/content-highlighter/content-highlight.test.tsx
src/components/content-highlighter/index.tsx
src/components/content-highlighter/styles.scss
src/components/message/index.tsx
src/lib/chat/matrix/chat-message.ts
src/store/matrix/index.ts
src/store/matrix/saga.ts
src/store/messages/saga.ts

Before:
After:
When you click on "help" icon:
https://github.com/zer0-os/zOS/assets/33264364/12a063e8-aff9-479e-94b0-bd32e1ac1e2d

Change `unable to decrypt message` text & design

---

src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

- error handling for generate backup call - sets stage, sets error message.
- error message to display in UI.
- handle stage.
- run tests / throw error in `generateBackup` saga function and open secure backup with a user who has not yet backed up. 

feat: add error handling - generate backup saga

---

src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx

- displays either `Account Backup` or `Verify Login` header.
- as per figma design. As shown [here](https://www.figma.com/file/btwltL4Os8hAy3eS3pxaa6/ZERO-Messenger-%2F-Web?type=design&node-id=12598-86331&mode=dev)

feat: handle stage specific secure backup dialog header

---

package-lock.json
package.json

- chore: bump version (`1.16.0`) -> (`1.17.0`)

chore: bump version (`1.16.0`) -> (`1.17.0`)

---

src/Main.test.tsx
src/Main.tsx
src/components/logout-confirmation-modal/container.test.tsx
src/components/logout-confirmation-modal/container.tsx
src/components/logout-confirmation-modal/index.test.tsx
src/components/logout-confirmation-modal/index.tsx
src/components/logout-confirmation-modal/styles.scss
src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/authentication/index.ts
src/store/authentication/saga.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts
src/store/test/store.ts

Adds a new modal to warn users of the consequences of logging out given the state of their backup.
To try to keep users from logging themselves out, or at least doing so with an understanding of what will happen.

Add logout confirmation modal

---

src/components/modal/index.tsx

There are known issues with radix-ui where various versions of "dialog-like" things cause the lib to get into a state where it forces pointer events off on the body. This is the hack solution that the community has come up with. :(
The bug can be reproduced by removing this code then log into the app. Once logged in then do a Logout. After logging out you'll be at the login page and none of the buttons will work. This is because the `pointer-events: none` is set on the body element.

Add hack to account for zUI badness with pointer events on the body

---

src/components/messenger/list/index.test.tsx
src/components/messenger/list/index.tsx
src/store/registration/index.ts
src/store/registration/saga.test.ts
src/store/registration/saga.ts

We used to encourage new users to invite more people when they registered but since we've decided not to any more.
This removes that Toast notification.

Remove the unused welcome toaster

---

src/store/test/store.ts

- removes test store `layout` state.
- test errors/warnings.
- following yesterdays removal of `layout` state the test store state should also be removed.

refactor: remove test store layout state

---

src/lib/chat/matrix-client.ts
src/store/messages/utils.matrix.ts

Display `Message Hidden` text if edit message cannot be decrypted

---

package-lock.json
package.json

- chore: bump version (`1.18.0`) -> (`1.19.0`)

chore: bump version (`1.18.0`) -> (`1.19.0`)

---

src/components/messenger/list/user-header/index.test.tsx
src/components/messenger/list/user-header/index.tsx
src/components/settings-menu/container.test.tsx
src/components/settings-menu/container.tsx
src/components/settings-menu/index.test.tsx
src/components/settings-menu/index.tsx
src/test/utils.ts

Since we now render the SecureBackup dialog more globally via state this removes the custom rendering from the SettingsMenu and just uses the saga to open the dialog

Remove rendering of Backup modal from SettingsMenu

---

src/components/secure-backup/generate-prompt/index.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx
src/components/secure-backup/restore-prompt/index.tsx
src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Splits up the early backup dialog phases into separate User initiated and System initiated phases
Makes the component easier to read and pushes the state logic up into the sagas
Do all the secure backup things!

Split backup phases to user/system initiated ones

---

src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts

Adds state fields which more explicitly describe the state of the user's key backup
To remove the internal data format knowledge in various components and sagas

Add metadata calculated state for components/sagas to access

---

src/lib/chat/matrix-client.ts

This updates the check for existing cross signing to the latest sdk version (non-deprecated).
Turns out the deprecated one doesn't report accurately if used immediately while the crypto is still being set up. This impacts the backup flows when logging into a new device/session.

Use the modern way to check for cross-signing

---

src/store/matrix/index.ts
src/store/matrix/saga.test.ts
src/store/matrix/saga.ts
src/store/test/store.ts

Removes `trustInfo` from the state as that's an internal Matrix format and nothing should reference it aside from the initial parsing saga.

Remove trustInfo from state

---

craco.config.js

zUI is built with conflicting versions of react/react-dom/react-router/etc. Previously we forced our version upon it via the webpack `alias` configuration but the recent upgrade to create-react-app added a plugin that restricts imports from outside the `src` folder. This caused our aliases to break.
This PR restores the aliases we previously had and adds a customization to the webpack configuration to remove the `ModuleScopePlugin` that create-react-app has added.

Add aliases to override zUI versions

---

src/store/authentication/saga.ts

Sets the LoginStage to the default Web3 when logging out.
There was a bug where if you start on the login page and login via email...then logout... instead of redirecting to the login page you'd remain at the root url. This happened because the completion of email logout sets the stage to Login.Done. So, the login page itself thought it was done and would redirect to the root url but the root url would detect is was not authenticated and thus not render anything.

Reset the login stage during logout

---

src/store/utils.ts

Fixes the syntax in the `race` call in `performUnlessLogout` helper.
Fixes bug where logging in as a user without a backup and then logging out wouldn't cancel the tasks that were pending so new logins would then not handle the backup flow properly.
This bug could be seen by doing the following:
1. Log in as a user who does not have a backup (this means it will wait until the first message is sent)
2. Logout
3. Log in as a user who DOES have a backup created.
Under normal circumstances this new user should see the backup dialog open prompting them to enter their recovery key. However, it was not. After the fix this should occur correctly.

Fix race syntax in performUnlessLogout

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss

- fixes conversation list panel padding - takes scrollbar width (4px) into account - equal padding each side.
Before:
After:

fix: conversation list panel padding

---

src/components/secure-backup/restore-backup/index.test.tsx
src/components/secure-backup/restore-backup/index.tsx

- makes use of input border error state fix in latest zui version.
- replaces styles set for input error state border and uses the built in error styles
- removes outdated test

refactor(restore-backup): use built in input error state for border

---

package-lock.json
package.json

- Includes the removal of "slide up" animation, which is failing in zOS due to possibly radix related issues.

chore: bump version (1.8.3) -> (1.8.4)

---

package-lock.json
package.json

- chore: bump version (`1.20.0`) -> (`1.21.0`)

chore: bump version (`1.20.0`) -> (`1.21.0`)

---

package-lock.json
package.json

- chore: bump version (`1.21.0`) -> (`1.22.0`)

chore: bump version (`1.21.0`) -> (`1.22.0`)

---

src/components/modal/styles.scss

Adds a max height (and min-height) to the Modal component to restrict the content size and forces a scrollbar on tall content.
Note: Red background added to provide contrast for screenshots
Before:
After:

Add a max height and content scroll to Modal component

---

src/components/messenger/list/index.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx

This converts the SecureBackup to the new Modal component so we can get all the modal goodies that we shouldn't have to re-implement every time.
Note: There will be some UI inconsistency until it gets fully converted. Ex: the buttons are still managed by each independent screen at the moment instead of the modal. Follow ups to come.
Example of how the scroll bar looks at the moment with the button managed by the screens. This is a temporary tradeoff.

Convert SecureBackup to an actual Modal

---

src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx

- updates the clipboard text when copying invite code
- as per requirements/design
- this gives more context/info to the person who receives the invite code that a current user has copied and sent.
- checkout branch > run UI > copy invite code > paste and check string has the same structure as below screenshot.

feat: update invite clipboard text

---

src/components/invite-dialog/index.test.tsx
src/components/invite-dialog/index.tsx

- replaces `config.zosRootUrl` with `config.inviteUrl`
- duplicated env variables not required.

refactor: use invite url config path in place of zos root url

---

src/components/secure-backup/container.tsx
src/components/secure-backup/index.test.tsx
src/components/secure-backup/index.tsx

Moves the loading indicator into the SecureBackup modal

Fix loading state on SecureBackup

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/components/messenger/chat/index.tsx

Removes a property that was only used to render old Channels and was currently hard coded to true.

Remove unused property

---

src/components/chat-view-container/chat-view-container.test.tsx
src/components/chat-view-container/chat-view-container.tsx
src/components/chat-view-container/chat-view.test.tsx
src/components/chat-view-container/chat-view.tsx
src/store/channels/api.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts
src/store/channels/saga.ts
src/store/channels/types.ts

Since we no longer have truly public channels that you can view and then try to join, this button is no longer useful. Remove it and the underlying sagas, etc.

Remove joinChannel button

---

src/lib/chat/matrix-client.ts
src/store/channels-list/saga.test.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts
src/store/channels/saga.test.ts

Removes the `hasJoined` property from Channel.

Remove hasJoined property from Channel

---

src/lib/chat/matrix-client.ts
src/store/channels-list/utils.test.ts
src/store/channels-list/utils.ts
src/store/channels/index.ts

Removes a property that wasn't used anywhere

Remove category from Channel

---

src/components/rewards-modal/styles.scss

Fix the green blob background on the rewards dialog

Fix rewards popup blob background

---

src/components/messenger/list/conversation-list-panel/conversation-list-panel.scss

Adds a default border so that the Favorite/All tabs don't bounce when changing

Fix the Favorite tabs from changing size when changing from active

---

src/lib/chat/matrix-client.test.ts
src/lib/chat/matrix-client.ts
src/lib/chat/matrix/chat-message.ts
src/lib/chat/matrix/utils.test.ts
src/lib/chat/matrix/utils.ts

- implements the construction of fallback content for message replies, automatically generating a quoted format of the parent message that precedes the reply content.
- adds util to parse the content body body to filter out fallback content. 
- to align with Mobile (android/ios) content body expectations.
- ensures that the displayed messages contain only the original content added by the user.
- run tests > send replies between android and web devices.
Constructing the fallback
Before:
After:

feat: fallback content construction for message replies and handle parsing of plain body

---

src/components/message-input/container.tsx
src/components/message-input/index.test.tsx
src/components/message-input/index.tsx

- removes unused `classname` prop from message input container / component.
- house keeping / no longer used.

refactor(message-input): remove `classname` prop
